# Habakkuk

The tables below show the Hebrew and Greek texts aligned vertically. When a Hebrew verse number does not match the Greek counterpart, the editors added a note with the corresponding verse number between square brackets.

## Chapter 1

### Verse 1

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| המשא             | το λημμα     |
| אשר              | ο            |
| חזה              | ειδεν        |
| חבקוק            | αμβακουμ     |
| הנביא            | ο προφητης   |
: Habakkuk chapter 1, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| עד               | εως          |
| אנה              | τινος        |
| יהוה             | κυριε        |
| שועתי            | κεκραξομαι   |
| ולא              | και ου μη    |
| תשמע             | εισακουσης   |
| אזעק             | βοησομαι     |
| אליך             | προς σε      |
| חמס              | αδικουμενος  |
| ולא              | και ου       |
| תושיע            | σωσεις       |
: Habakkuk chapter 1, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                 | Tov's retroversion                                                             | Septuagint                            |
|:-------------------------------|:-------------------------------------------------------------------------------|:--------------------------------------|
| למה                            |                                                                                | ινα τι                                |
| תראני                          |                                                                                | μοι εδειξας                           |
| און                            |                                                                                | κοπους                                |
| ועמל                           |                                                                                | και πονους                            |
| תביט                           |                                                                                | επιβλεπειν                            |
| ושד                            |                                                                                | ταλαιπωριαν                           |
| וחמס                           |                                                                                | και ασεβειαν                          |
| לנגדי                          |                                                                                | εξ εναντιας μου                       |
| ויהי                           |                                                                                | γεγονεν                               |
| ריב                            |                                                                                | κρισις                                |
| [ומדון]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] ומדין .wy]{.potential-difference} | [και ο κριτης]{.potential-difference} |
| ישא                            |                                                                                | λαμβανει                              |
: Habakkuk chapter 1, verse 3 { .hover tbl-colwidths="[35,30,35]"}

### Verse 4

| Masoretic text                      | Septuagint     |
|:------------------------------------|:---------------|
| על כן                               | δια τουτο      |
| תפוג •^[Etymological exegesis.] פרר | διεσκεδασται   |
| תורה                                | νομος          |
| ולא                                 | και ου         |
| יצא                                 | διεξαγεται     |
| לנצח                                | εις τελος      |
| משפט                                | κριμα          |
| כי                                  | οτι            |
| רשע                                 | ο ασεβης       |
| מכתיר                               | καταδυναστευει |
| את הצדיק                            | τον δικαιον    |
| על כן                               | ενεκεν τουτου  |
| יצא                                 | εξελευσεται    |
| משפט                                | το κριμα       |
| מעקל                                | διεστραμμενον  |
: Habakkuk chapter 1, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                               | Tov's retroversion                       | Septuagint                                                                                           |
|:-----------------------------------------------------------------------------|:-----------------------------------------|:-----------------------------------------------------------------------------------------------------|
| ראו                                                                          |                                          | ιδετε                                                                                                |
| [בגוים]{.potential-difference}                                               | [בגדים .wd <2.5>]{.potential-difference} | [οι καταφρονηται]{.potential-difference}                                                             |
| והביטו                                                                       |                                          | και επιβλεψατε                                                                                       |
| והתמהו                                                                       |                                          | και θαυμασατε                                                                                        |
| תמהו                                                                         |                                          | θαυμασια •^[Reference to doublet (occurring between the two elements of the doublet.] και αφανισθητε |
| כי                                                                           |                                          | διοτι                                                                                                |
| פעל                                                                          |                                          | εργον                                                                                                |
| פעל                                                                          |                                          | εγω εργαζομαι                                                                                        |
| בימיכם                                                                       |                                          | εν ταις ημεραις υμων                                                                                 |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                          | [ο]{.potential-difference}                                                                           |
| לא                                                                           |                                          | ου μη                                                                                                |
| תאמינו                                                                       |                                          | πιστευσητε                                                                                           |
| כי                                                                           |                                          | εαν                                                                                                  |
| יספר •^[Change from passive to active form in verbs.]                        |                                          | τις εκδιηγηται                                                                                       |
: Habakkuk chapter 1, verse 5 { .hover tbl-colwidths="[35,30,35]"}

### Verse 6

| Masoretic text                                                               | Septuagint                            |
|:-----------------------------------------------------------------------------|:--------------------------------------|
| כי                                                                           | διοτι                                 |
| הנני                                                                         | ιδου εγω                              |
| מקים                                                                         | εξεγειρω                              |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [εφ' υμας]{.potential-difference}     |
| את הכשדים                                                                    | τους χαλδαιους                        |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [τους μαχητας]{.potential-difference} |
| הגוי                                                                         | το εθνος                              |
| המר                                                                          | το πικρον                             |
| והנמהר                                                                       | και το ταχινον                        |
| ההולך                                                                        | το πορευομενον                        |
| למרחבי                                                                       | επι τα πλατη                          |
| ארץ                                                                          | της γης                               |
| לרשת                                                                         | του κατακληρονομησαι                  |
| משכנות                                                                       | σκηνωματα                             |
| לא                                                                           | ουκ                                   |
| לו                                                                           | αυτου                                 |
: Habakkuk chapter 1, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                                                               | Septuagint                        |
|:-----------------------------------------------------------------------------|:----------------------------------|
| אים                                                                          | φοβερος                           |
| ונורא                                                                        | και επιφανης                      |
| הוא                                                                          | εστιν                             |
| ממנו                                                                         | εξ αυτου                          |
| משפטו                                                                        | το κριμα αυτου                    |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [εσται]{.potential-difference}    |
| ושאתו •^[Etymological exegesis.]                                             | και το λημμα αυτου                |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [εξ αυτου]{.potential-difference} |
| יצא                                                                          | εξελευσεται                       |
: Habakkuk chapter 1, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                                                                               | Tov's retroversion             | Septuagint                                                                             |
|:-------------------------------------------------------------------------------------------------------------|:-------------------------------|:---------------------------------------------------------------------------------------|
| וקלו                                                                                                         |                                | και εξαλουνται                                                                         |
| מנמרים                                                                                                       |                                | υπερ παρδαλεις                                                                         |
| סוסיו                                                                                                        |                                | οι ιπποι αυτου                                                                         |
| וחדו                                                                                                         |                                | και οξυτεροι                                                                           |
| מזאבי                                                                                                        |                                | υπερ τους λυκους                                                                       |
| ערב •^[Difference in vocalization (reading).]                                                                |                                | της αραβιας                                                                            |
| [ופשו]{.potential-difference}                                                                                | [ופרשו]{.potential-difference} | [και εξιππασονται]{.potential-difference}                                              |
| פרשיו                                                                                                        |                                | οι ιππεις αυτου                                                                        |
| [ופרשיו •^[Reference to doublet (occurring between the two elements of the doublet.]]{.potential-difference} |                                | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [מרחוק]{.potential-difference}                                                                               | [יבאו]{.potential-difference}  | [και ορμησουσιν]{.potential-difference}                                                |
| [יבאו]{.potential-difference}                                                                                | [מרחוק]{.potential-difference} | [μακροθεν]{.potential-difference}                                                      |
| יעפו                                                                                                         |                                | και πετασθησονται                                                                      |
| כנשר                                                                                                         |                                | ως αετος                                                                               |
| חש                                                                                                           |                                | προθυμος                                                                               |
| לאכול                                                                                                        |                                | εις το φαγειν                                                                          |
: Habakkuk chapter 1, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text               | Tov's retroversion                                                                                | Septuagint                         |
|:-----------------------------|:--------------------------------------------------------------------------------------------------|:-----------------------------------|
| [כלה]{.potential-difference} | [כלה •^[Difference in vocalization (reading).] •^[Etymological exegesis.]]{.potential-difference} | [συντελεια]{.potential-difference} |
| לחמס                         |                                                                                                   | εις ασεβεις                        |
| יבוא                         |                                                                                                   | ηξει                               |
| מגמת                         |                                                                                                   | ανθεστηκοτας                       |
| פניהם                        |                                                                                                   | προσωποις αυτων                    |
| קדימה                        |                                                                                                   | εξ εναντιας                        |
| ויאסף                        |                                                                                                   | και συναξει                        |
| כחול                         |                                                                                                   | ως αμμον                           |
| שבי                          |                                                                                                   | αιχμαλωσιαν                        |
: Habakkuk chapter 1, verse 9 { .hover tbl-colwidths="[35,30,35]"}

### Verse 10

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| והוא             | και αυτος          |
| במלכים           | εν βασιλευσιν      |
| יתקלס            | εντρυφησει         |
| ורזנים           | και τυραννοι       |
| משחק             | παιγνια            |
| לו               | αυτου              |
| הוא              | και αυτος          |
| לכל              | εις παν            |
| מבצר             | οχυρωμα            |
| ישחק             | εμπαιξεται         |
| ויצבר            | και βαλει          |
| עפר              | χωμα               |
| וילכדה           | και κρατησει αυτου |
: Habakkuk chapter 1, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| אז               | τοτε            |
| חלף              | μεταβαλει       |
| רוח              | το πνευμα       |
| ויעבר            | και διελευσεται |
| ואשם             | και εξιλασεται  |
| זו               | αυτη            |
| כחו              | η ισχυς         |
| לאלהו            | τω θεω μου      |
: Habakkuk chapter 1, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                       | Septuagint     |
|:-------------------------------------|:---------------|
| הלוא                                 | ουχι           |
| אתה                                  | συ             |
| מקדם                                 | απ' αρχης      |
| יהוה                                 | κυριε          |
| אלהי                                 | ο θεος         |
| קדשי                                 | ο αγιος μου    |
| לא                                   | και ου μη      |
| נמות                                 | αποθανωμεν     |
| יהוה                                 | κυριε          |
| למשפט                                | εις κριμα      |
| שמתו                                 | τεταχας αυτον  |
| וצור •^[Etymological exegesis.] יצר  | και επλασεν με |
| להוכיח                               | του ελεγχειν   |
| יסדתו •^[Etymological exegesis.] יסר | παιδειαν αυτου |
: Habakkuk chapter 1, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                                                   | Septuagint                                                                                                                         |
|:---------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------|
| טהור                                                                             | καθαρος                                                                                                                            |
| עינים                                                                            | οφθαλμος                                                                                                                           |
| מראות                                                                            | του μη οραν                                                                                                                        |
| רע                                                                               | πονηρα                                                                                                                             |
| והביט                                                                            | και επιβλεπειν                                                                                                                     |
| אל                                                                               | επι                                                                                                                                |
| עמל                                                                              | πονους                                                                                                                             |
| לא                                                                               | ου                                                                                                                                 |
| תוכל                                                                             | δυνηση                                                                                                                             |
| למה                                                                              | ινα τι                                                                                                                             |
| תביט                                                                             | επιβλεπεις                                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | επι                                                                                                                                |
| בוגדים                                                                           | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι καταφρονουντας    |
| תחריש                                                                            | παρασιωπηση                                                                                                                        |
| בבלע                                                                             | εν τω καταπινειν                                                                                                                   |
| רשע                                                                              | ασεβη                                                                                                                              |
| צדיק {... •^[Questionable notation, equivalent, etc.] ממנו}                      | τον δικαιον                                                                                                                        |
| [ממנו]{.potential-difference}                                                    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} |
: Habakkuk chapter 1, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                                   | Septuagint                                                                                                          |
|:---------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------|
| ותעשה                                                                            | και ποιησεις                                                                                                        |
| אדם                                                                              | τους ανθρωπους                                                                                                      |
| כדגי                                                                             | ως τους ιχθυας                                                                                                      |
| הים                                                                              | της θαλασσης                                                                                                        |
| כרמש                                                                             | και ως τα ερπετα                                                                                                    |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | τα                                                                                                                  |
| לא                                                                               | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] τα ουκ |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εχοντα                                                                                                              |
| משל                                                                              | ηγουμενον                                                                                                           |
| בו                                                                               | {..εχοντα}                                                                                                          |
: Habakkuk chapter 1, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text                                                                                          | Septuagint                              |
|:--------------------------------------------------------------------------------------------------------|:----------------------------------------|
| כלה •^[Etymological exegesis.] כלה •^[Difference in vocalization (reading).] •^[Etymological exegesis.] | συντελειαν                              |
| בחכה                                                                                                    | εν αγκιστρω                             |
| העלה                                                                                                    | ανεσπασεν                               |
| יגרהו                                                                                                   | και ειλκυσεν αυτον                      |
| בחרמו                                                                                                   | εν αμφιβληστρω                          |
| ויאספהו                                                                                                 | και συνηγαγεν αυτον                     |
| במכמרתו                                                                                                 | εν ταις σαγηναις αυτου                  |
| על כן                                                                                                   | ενεκεν τουτου                           |
| ישמח                                                                                                    | ευφρανθησεται                           |
| ויגיל                                                                                                   | και χαρησεται                           |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                            | [η καρδια αυτου]{.potential-difference} |
: Habakkuk chapter 1, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text                                | Septuagint           |
|:----------------------------------------------|:---------------------|
| על כן                                         | ενεκεν τουτου        |
| יזבח                                          | θυσει                |
| לחרמו                                         | τη σαγηνη αυτου      |
| ויקטר                                         | και θυμιασει         |
| למכמרתו                                       | τω αμφιβληστρω αυτου |
| כי                                            | οτι                  |
| בהמה                                          | εν αυτοις            |
| שמן •^[Difference in vocalization (reading).] | ελιπανεν             |
| חלקו                                          | μεριδα αυτου         |
| ומאכלו                                        | και τα βρωματα αυτου |
| בראה •^[Etymological exegesis.] ברר           | εκλεκτα              |
: Habakkuk chapter 1, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text   | Septuagint            |
|:-----------------|:----------------------|
| העל כן           | δια τουτο             |
| יריק             | αμφιβαλει             |
| חרמו             | το αμφιβληστρον αυτου |
| ותמיד            | και δια παντος        |
| להרג             | αποκτεννειν           |
| גוים             | εθνη                  |
| לא               | ου                    |
| יחמול            | φεισεται              |
: Habakkuk chapter 1, verse 17 { .hover tbl-colwidths="[50,50]"}

## Chapter 2

### Verse 1

| Masoretic text                      | Septuagint      |
|:------------------------------------|:----------------|
| על                                  | επι             |
| משמרתי                              | της φυλακης μου |
| אעמדה                               | στησομαι        |
| ואתיצבה                             | και επιβησομαι  |
| על                                  | επι             |
| מצור •^[Etymological exegesis.] צור | πετραν          |
| ואצפה                               | και αποσκοπευσω |
| לראות                               | του ιδειν       |
| מה                                  | τι              |
| ידבר                                | λαλησει         |
| בי                                  | εν εμοι         |
| ומה                                 | και τι          |
| אשיב                                | αποκριθω        |
| על                                  | επι             |
| תוכחתי                              | τον ελεγχον μου |
: Habakkuk chapter 2, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                 | Septuagint           |
|:-----------------------------------------------|:---------------------|
| ויענני                                         | και απεκριθη προς με |
| יהוה                                           | κυριος               |
| ויאמר                                          | και ειπεν            |
| כתוב                                           | γραψον               |
| חזון                                           | ορασιν               |
| ובאר •^[Difference in vocalization (reading).] | και σαφως            |
| על                                             | επι                  |
| הלחות                                          | πυξιον               |
| למען                                           | οπως                 |
| ירוץ                                           | διωκη                |
| קורא                                           | ο αναγινωσκων        |
| בו                                             | αυτα                 |
: Habakkuk chapter 2, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                          | Tov's retroversion                                                        | Septuagint                         |
|:----------------------------------------|:--------------------------------------------------------------------------|:-----------------------------------|
| כי                                      |                                                                           | διοτι                              |
| עוד                                     |                                                                           | ετι                                |
| חזון                                    |                                                                           | ορασις                             |
| למועד                                   |                                                                           | εις καιρον                         |
| ויפח •^[Etymological exegesis.] יפע .xע |                                                                           | και ανατελει                       |
| לקץ                                     |                                                                           | εις περας                          |
| ולא                                     |                                                                           | και ουκ                            |
| [יכזב]{.potential-difference}           | [•^[Questionable notation, equivalent, etc.] לכזב]{.potential-difference} | [εις κενον]{.potential-difference} |
| אם                                      |                                                                           | εαν                                |
| יתמהמה                                  |                                                                           | υστερηση                           |
| חכה                                     |                                                                           | υπομεινον                          |
| לו                                      |                                                                           | αυτον                              |
| כי                                      |                                                                           | οτι                                |
| בא {!}pd                                |                                                                           | ερχομενος                          |
| יבא {!}pd                               |                                                                           | ηξει                               |
| לא                                      |                                                                           | και ου μη                          |
| יאחר                                    |                                                                           | χρονιση                            |
: Habakkuk chapter 2, verse 3 { .hover tbl-colwidths="[35,30,35]"}

### Verse 4

| Masoretic text                                                                                                                                                                        | Tov's retroversion          | Septuagint                   |
|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------|:-----------------------------|
| [הנה]{.potential-difference}                                                                                                                                                          | [הן]{.potential-difference} | [εαν]{.potential-difference} |
| עפלה •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] עלף •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)] |                             | υποστειληται                 |
| לא                                                                                                                                                                                    |                             | ουκ                          |
| ישרה                                                                                                                                                                                  |                             | ευδοκει                      |
| נפשו                                                                                                                                                                                  |                             | η ψυχη μου                   |
| בו                                                                                                                                                                                    |                             | εν αυτω                      |
| וצדיק                                                                                                                                                                                 |                             | ο δε δικαιος                 |
| באמונתו •^[Difference in preposition or particle.]                                                                                                                                    |                             | εκ πιστεως μου               |
| יחיה                                                                                                                                                                                  |                             | ζησεται                      |
: Habakkuk chapter 2, verse 4 { .hover tbl-colwidths="[35,30,35]"}

### Verse 5

| Masoretic text                                                                   | Septuagint                                                                                      |
|:---------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------|
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | ο                                                                                               |
| ואף כי                                                                           | δε                                                                                              |
| היין                                                                             | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ο κατοινωμενος |
| בוגד                                                                             | και καταφρονητης                                                                                |
| גבר                                                                              | ανηρ                                                                                            |
| יהיר                                                                             | αλαζων                                                                                          |
| ולא                                                                              | ουδεν μη                                                                                        |
| ינוה                                                                             | περανη                                                                                          |
| אשר                                                                              | ος                                                                                              |
| הרחיב                                                                            | επλατυνεν                                                                                       |
| כשאול                                                                            | καθως ο αδης                                                                                    |
| נפשו                                                                             | την ψυχην αυτου                                                                                 |
| והוא                                                                             | και ουτος                                                                                       |
| כמות                                                                             | ως θανατος                                                                                      |
| ולא                                                                              | ουκ                                                                                             |
| ישבע                                                                             | εμπιπλαμενος                                                                                    |
| ויאסף                                                                            | και επισυναξει                                                                                  |
| אליו                                                                             | επ' αυτον                                                                                       |
| כל                                                                               | παντα                                                                                           |
| הגוים                                                                            | τα εθνη                                                                                         |
| ויקבץ                                                                            | και εισδεξεται                                                                                  |
| אליו                                                                             | προς αυτον                                                                                      |
| כל                                                                               | παντας                                                                                          |
| העמים                                                                            | τους λαους                                                                                      |
: Habakkuk chapter 2, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text                                                                   | Tov's retroversion              | Septuagint                                                                                     |
|:---------------------------------------------------------------------------------|:--------------------------------|:-----------------------------------------------------------------------------------------------|
| הלוא                                                                             |                                 | ουχι                                                                                           |
| אלה                                                                              |                                 | ταυτα                                                                                          |
| כלם                                                                              |                                 | παντα                                                                                          |
| [עליו]{.potential-difference}                                                    | [משל]{.potential-difference}    | [παραβολην]{.potential-difference}                                                             |
| [משל]{.potential-difference}                                                     | [עליו]{.potential-difference}   | [κατ' αυτου]{.potential-difference}                                                            |
| ישאו                                                                             |                                 | λημψονται                                                                                      |
| [ומליצה •^[Questionable notation, equivalent, etc.]]{.potential-difference}      | [וחידות]{.potential-difference} | [και προβλημα]{.potential-difference}                                                          |
| [•^[Questionable notation, equivalent, etc.] חידות]{.potential-difference}       | [מליצה]{.potential-difference}  | [εις διηγησιν]{.potential-difference}                                                          |
| לו                                                                               |                                 | αυτου                                                                                          |
| ויאמר                                                                            |                                 | και ερουσιν                                                                                    |
| הוי                                                                              |                                 | ουαι                                                                                           |
| המרבה                                                                            |                                 | ο πληθυνων                                                                                     |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     |                                 | [εαυτω]{.potential-difference}                                                                 |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                 | τα                                                                                             |
| לא                                                                               |                                 | ουκ                                                                                            |
| לו                                                                               |                                 | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] τα οντα αυτου |
| עד                                                                               |                                 | εως                                                                                            |
| מתי                                                                              |                                 | τινος                                                                                          |
| ומכביד                                                                           |                                 | και βαρυνων                                                                                    |
| [עליו]{.potential-difference}                                                    | [עלו]{.potential-difference}    | [τον κλοιον αυτου]{.potential-difference}                                                      |
| עבטיט                                                                            |                                 | στιβαρως                                                                                       |
: Habakkuk chapter 2, verse 6 { .hover tbl-colwidths="[35,30,35]"}

### Verse 7

| Masoretic text                | Tov's retroversion                                                      | Septuagint                   |
|:------------------------------|:------------------------------------------------------------------------|:-----------------------------|
| [הלוא]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] כי]{.potential-difference} | [οτι]{.potential-difference} |
| פתע                           |                                                                         | εξαιφνης                     |
| יקומו                         |                                                                         | αναστησονται                 |
| נשכיך                         |                                                                         | δακνοντες αυτον              |
| ויקצו                         |                                                                         | και εκνηψουσιν               |
| מזעזעיך                       |                                                                         | οι επιβουλοι σου             |
| והיית                         |                                                                         | και εση                      |
| למשסות                        |                                                                         | εις διαρπαγην                |
| למו                           |                                                                         | αυτοις                       |
: Habakkuk chapter 2, verse 7 { .hover tbl-colwidths="[35,30,35]"}

### Verse 8

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| כי               | διοτι             |
| אתה              | συ                |
| שלות             | εσκυλευσας        |
| גוים             | εθνη              |
| רבים             | πολλα             |
| ישלוך            | σκυλευσουσιν σε   |
| כל               | παντες            |
| יתר              | οι υπολελειμμενοι |
| עמים             | λαοι              |
| מדמי             | δι' αιματα        |
| אדם              | ανθρωπων          |
| וחמס             | και ασεβειας      |
| ארץ              | γης               |
| קריה             | και πολεως        |
| וכל              | και παντων        |
| ישבי             | των κατοικουντων  |
| בה               | αυτην             |
: Habakkuk chapter 2, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| הוי              | ω               |
| בצע              | ο πλεονεκτων    |
| בצע              | πλεονεξιαν      |
| רע               | κακην           |
| לביתו            | τω οικω αυτου   |
| לשום             | του ταξαι       |
| במרום            | εις υψος        |
| קנו              | νοσσιαν αυτου   |
| להנצל            | του εκσπασθηναι |
| מכף              | εκ χειρος       |
| רע               | κακων           |
: Habakkuk chapter 2, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                 | Septuagint    |
|:-----------------------------------------------|:--------------|
| יעצת                                           | εβουλευσω     |
| בשת                                            | αισχυνην      |
| לביתך                                          | τω οικω σου   |
| קצות •^[Difference in vocalization (reading).] | συνεπερανας   |
| עמים                                           | λαους         |
| רבים                                           | πολλους       |
| וחוטא                                          | και εξημαρτεν |
| נפשך                                           | η ψυχη σου    |
: Habakkuk chapter 2, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| כי               | διοτι          |
| אבן              | λιθος          |
| מקיר             | εκ τοιχου      |
| תזעק             | βοησεται       |
| וכפיס            | και κανθαρος   |
| מעץ              | εκ ξυλου       |
| יעננה            | φθεγξεται αυτα |
: Habakkuk chapter 2, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| הוי              | ουαι          |
| בנה              | ο οικοδομων   |
| עיר              | πολιν         |
| בדמים            | εν αιμασιν    |
| וכונן            | και ετοιμαζων |
| קריה             | πολιν         |
| בעולה            | εν αδικιαις   |
: Habakkuk chapter 2, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                               | Tov's retroversion                                                                                    | Septuagint                     |
|:---------------------------------------------|:------------------------------------------------------------------------------------------------------|:-------------------------------|
| הלוא                                         |                                                                                                       | ου                             |
| הנה                                          |                                                                                                       | ταυτα εστιν                    |
| מאת                                          |                                                                                                       | παρα                           |
| יהוה                                         |                                                                                                       | κυριου                         |
| צבאות                                        |                                                                                                       | παντοκρατορος                  |
| וייגעו                                       |                                                                                                       | και εξελιπον                   |
| עמים                                         |                                                                                                       | λαοι                           |
| בדי •^[Omission of preposition or particle.] |                                                                                                       | ικανοι                         |
| אש •^[Addition of preposition or particle.]  |                                                                                                       | εν πυρι                        |
| ולאמים                                       |                                                                                                       | και εθνη                       |
| [בדי ריק]{.potential-difference}             | [רבים •^[Two words of MT joined into one word in the parent text of the LXX.]]{.potential-difference} | [πολλα]{.potential-difference} |
| יעפו                                         |                                                                                                       | ωλιγοψυχησαν                   |
: Habakkuk chapter 2, verse 13 { .hover tbl-colwidths="[35,30,35]"}

### Verse 14

| Masoretic text                 | Tov's retroversion                                                                                     | Septuagint                      |
|:-------------------------------|:-------------------------------------------------------------------------------------------------------|:--------------------------------|
| כי                             |                                                                                                        | οτι                             |
| תמלא                           |                                                                                                        | πλησθησεται                     |
| הארץ                           |                                                                                                        | η γη                            |
| לדעת                           |                                                                                                        | του γνωναι                      |
| את כבוד                        |                                                                                                        | την δοξαν                       |
| יהוה                           |                                                                                                        | κυριου                          |
| כמים                           |                                                                                                        | ως υδωρ                         |
| יכסו                           |                                                                                                        | κατακαλυψει                     |
| [על ים]{.potential-difference} | [עליהם •^[Two words of MT joined into one word in the parent text of the LXX.]]{.potential-difference} | [αυτους]{.potential-difference} |
: Habakkuk chapter 2, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text                                 | Septuagint        |
|:-----------------------------------------------|:------------------|
| הוי                                            | ω                 |
| משקה                                           | ο ποτιζων         |
| רעהו                                           | τον πλησιον αυτου |
| מספח •^[Difference in vocalization (reading).] | ανατροπη          |
| חמתך                                           | θολερα            |
| ואף                                            | και               |
| שכר                                            | μεθυσκων          |
| למען                                           | οπως              |
| הביט                                           | επιβλεπη          |
| על                                             | επι               |
| מעוריהם •^[Etymological exegesis.] מערה        | τα σπηλαια αυτων  |
: Habakkuk chapter 2, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text                                                                                                            | Tov's retroversion                                                                                                                   | Septuagint                                                                                                                          |
|:--------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------|
| שבעת •^[Difference in vocalization (reading).]                                                                            |                                                                                                                                      | πλησμονην                                                                                                                           |
| קלון                                                                                                                      |                                                                                                                                      | ατιμιας                                                                                                                             |
| מכבוד                                                                                                                     |                                                                                                                                      | εκ δοξης                                                                                                                            |
| שתה                                                                                                                       |                                                                                                                                      | πιε                                                                                                                                 |
| גם                                                                                                                        |                                                                                                                                      | και                                                                                                                                 |
| אתה                                                                                                                       |                                                                                                                                      | συ                                                                                                                                  |
| [והערל]{.potential-difference}                                                                                            | [והרעל •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)]]{.potential-difference} | [και διασαλευθητι •^[Reference to doublet (occurring between the two elements of the doublet.] και σεισθητι]{.potential-difference} |
| תסוב                                                                                                                      |                                                                                                                                      | εκυκλωσεν                                                                                                                           |
| עליך                                                                                                                      |                                                                                                                                      | επι σε                                                                                                                              |
| כוס                                                                                                                       |                                                                                                                                      | ποτηριον                                                                                                                            |
| ימין                                                                                                                      |                                                                                                                                      | δεξιας                                                                                                                              |
| יהוה                                                                                                                      |                                                                                                                                      | κυριου                                                                                                                              |
| וקיקלון •^[Etymological exegesis.] קוה •^[One word of MT separated into two or more words in the parent text of the LXX.] |                                                                                                                                      | και συνηχθη ατιμια                                                                                                                  |
| על                                                                                                                        |                                                                                                                                      | επι                                                                                                                                 |
| כבודך                                                                                                                     |                                                                                                                                      | την δοξαν σου                                                                                                                       |
: Habakkuk chapter 2, verse 16 { .hover tbl-colwidths="[35,30,35]"}

### Verse 17

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| כי               | διοτι            |
| חמס              | ασεβεια          |
| לבנון            | του λιβανου      |
| יכסך             | καλυψει σε       |
| ושד              | και ταλαιπωρια   |
| בהמות            | θηριων           |
| יחיתן            | πτοησει σε       |
| מדמי             | δια αιματα       |
| אדם              | ανθρωπων         |
| וחמס             | και ασεβειας     |
| ארץ              | γης              |
| קריה             | και πολεως       |
| וכל              | και παντων       |
| ישבי             | των κατοικουντων |
| בה               | αυτην            |
: Habakkuk chapter 2, verse 17 { .hover tbl-colwidths="[50,50]"}

### Verse 18

| Masoretic text                                 | Tov's retroversion            | Septuagint                               |
|:-----------------------------------------------|:------------------------------|:-----------------------------------------|
| מה                                             |                               | τι                                       |
| הועיל                                          |                               | ωφελει                                   |
| פסל                                            |                               | γλυπτον                                  |
| כי                                             |                               | οτι                                      |
| פסלו                                           |                               | εγλυψαν αυτο                             |
| יצרו •^[Difference in vocalization (reading).] |                               | επλασαν αυτο                             |
| מסכה                                           |                               | χωνευμα                                  |
| ומורה •^[Etymological exegesis.] מראה          |                               | φαντασιαν                                |
| שקר                                            |                               | ψευδη                                    |
| כי                                             |                               | οτι                                      |
| בטח                                            |                               | πεποιθεν                                 |
| יצר                                            |                               | ο πλασας                                 |
| [יצרו]{.potential-difference}                  | [עליו]{.potential-difference} | [επι]{.potential-difference}             |
| [עליו]{.potential-difference}                  | [יצרו]{.potential-difference} | [το πλασμα αυτου]{.potential-difference} |
| לעשות                                          |                               | του ποιησαι                              |
| אלילים                                         |                               | ειδωλα                                   |
| אלמים                                          |                               | κωφα                                     |
: Habakkuk chapter 2, verse 18 { .hover tbl-colwidths="[35,30,35]"}

### Verse 19

| Masoretic text                          | Septuagint     |
|:----------------------------------------|:---------------|
| הוי                                     | ουαι           |
| אמר                                     | ο λεγων        |
| לעץ                                     | τω ξυλω        |
| הקיצה                                   | εκνηψον        |
| עורי                                    | εξεγερθητι     |
| לאבן                                    | και τω λιθω    |
| דומם •^[Etymological exegesis.] רום .dr | υψωθητι        |
| הוא                                     | και αυτο εστιν |
| יורה •^[Etymological exegesis.] מראה    | φαντασια       |
| הנה                                     | τουτο δε       |
| הוא                                     | εστιν          |
| תפוש                                    | ελασμα         |
| זהב                                     | χρυσιου        |
| וכסף                                    | και αργυριου   |
| וכל                                     | και παν        |
| רוח                                     | πνευμα         |
| אין                                     | ουκ εστιν      |
| בקרבו                                   | εν αυτω        |
: Habakkuk chapter 2, verse 19 { .hover tbl-colwidths="[50,50]"}

### Verse 20

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| ויהוה            | ο δε κυριος        |
| בהיכל            | εν ναω             |
| קדשו             | αγιω αυτου         |
| הס               | ευλαβεισθω         |
| מפניו            | απο προσωπου αυτου |
| כל               | πασα               |
| הארץ             | η γη               |
: Habakkuk chapter 2, verse 20 { .hover tbl-colwidths="[50,50]"}

## Chapter 3

### Verse 1

| Masoretic text                  | Tov's retroversion                                                                 | Septuagint                    |
|:--------------------------------|:-----------------------------------------------------------------------------------|:------------------------------|
| תפלה                            |                                                                                    | προσευχη                      |
| לחבקוק                          |                                                                                    | αμβακουμ                      |
| הנביא                           |                                                                                    | του προφητου                  |
| על                              |                                                                                    | μετα                          |
| [שגינות]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] נגינות <3.19>]{.potential-difference} | [ωδης]{.potential-difference} |
: Habakkuk chapter 3, verse 1 { .hover tbl-colwidths="[35,30,35]"}

### Verse 2

| Masoretic text                                                                                                                                           | Tov's retroversion               | Septuagint                                                                                                                                                                                                                                                                                                                                                         |
|:---------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| יהוה                                                                                                                                                     |                                  | κυριε                                                                                                                                                                                                                                                                                                                                                              |
| שמעתי                                                                                                                                                    |                                  | εισακηκοα                                                                                                                                                                                                                                                                                                                                                          |
| שמעך                                                                                                                                                     |                                  | την ακοην σου                                                                                                                                                                                                                                                                                                                                                      |
| [יראתי]{.potential-difference}                                                                                                                           | [{d}@ראה]{.potential-difference} | [και εφοβηθην •^[Reference to doublet (occurring between the two elements of the doublet.] κατενοησα •^[Reference to doublet (occurring between the two elements of the doublet.] •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.]]{.potential-difference} |
| •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.] |                                  | {...και εξεστην}                                                                                                                                                                                                                                                                                                                                                   |
| [יהוה]{.potential-difference}                                                                                                                            |                                  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}                                                                                                                                                                                                                                                                             |
| פעלך                                                                                                                                                     |                                  | τα εργα σου                                                                                                                                                                                                                                                                                                                                                        |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                  | και εξεστην                                                                                                                                                                                                                                                                                                                                                        |
| בקרב                                                                                                                                                     |                                  | εν μεσω                                                                                                                                                                                                                                                                                                                                                            |
| שנים •^[Difference in vocalization (reading).]                                                                                                           |                                  | δυο                                                                                                                                                                                                                                                                                                                                                                |
| חייהו •^[Difference in vocalization (reading).]                                                                                                          |                                  | ζωων                                                                                                                                                                                                                                                                                                                                                               |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                                             |                                  | [γνωσθηση]{.potential-difference}                                                                                                                                                                                                                                                                                                                                  |
| בקרב •^[Difference in vocalization (reading).]                                                                                                           |                                  | εν τω εγγιζειν •^[Reference to doublet (occurring between the two elements of the doublet.] {...εν τω •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.]                                                                                                     |
| •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.] |                                  | παρειναι                                                                                                                                                                                                                                                                                                                                                           |
| שנים                                                                                                                                                     |                                  | τα ετη •^[Reference to doublet (occurring between the two elements of the doublet.] {...τον καιρον}                                                                                                                                                                                                                                                                |
| תודיע                                                                                                                                                    |                                  | επιγνωσθηση •^[Reference to doublet (occurring between the two elements of the doublet.] •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] αναδειχθηση                                                                                                                                                                              |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                  | εν τω παρειναι                                                                                                                                                                                                                                                                                                                                                     |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                  | τον καιρον                                                                                                                                                                                                                                                                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                  | αναδειχθηση                                                                                                                                                                                                                                                                                                                                                        |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                  | εν τω ταραχθηναι                                                                                                                                                                                                                                                                                                                                                   |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                  | την ψυχην μου                                                                                                                                                                                                                                                                                                                                                      |
| ברגז                                                                                                                                                     |                                  | {...εν τω ταραχθηναι}{d} εν οργη                                                                                                                                                                                                                                                                                                                                   |
| [רחם]{.potential-difference}                                                                                                                             | [{d}רוחי]{.potential-difference} | [{...την ψυχην μου} •^[Reference to doublet (occurring between the two elements of the doublet.] ελεους]{.potential-difference}                                                                                                                                                                                                                                    |
| תזכור                                                                                                                                                    |                                  | μνησθηση                                                                                                                                                                                                                                                                                                                                                           |
: Habakkuk chapter 3, verse 2 { .hover tbl-colwidths="[35,30,35]"}

### Verse 3

| Masoretic text                | Tov's retroversion            | Septuagint                                |
|:------------------------------|:------------------------------|:------------------------------------------|
| אלוה                          |                               | ο θεος                                    |
| מתימן                         |                               | εκ θαιμαν                                 |
| יבוא                          |                               | ηξει                                      |
| וקדוש                         |                               | και ο αγιος                               |
| מהר                           |                               | εξ ορους                                  |
| [פארן]{.potential-difference} | [פארה]{.potential-difference} | [κατασκιου δασεος]{.potential-difference} |
| סלה                           |                               | διαψαλμα                                  |
| כסה                           |                               | εκαλυψεν                                  |
| שמים                          |                               | ουρανους                                  |
| הודו                          |                               | η αρετη αυτου                             |
| ותהלתו                        |                               | και αινεσεως αυτου                        |
| מלאה                          |                               | πληρης                                    |
| הארץ                          |                               | η γη                                      |
: Habakkuk chapter 3, verse 3 { .hover tbl-colwidths="[35,30,35]"}

### Verse 4

| Masoretic text                       | Septuagint                                                                                         |
|:-------------------------------------|:---------------------------------------------------------------------------------------------------|
| ונגה                                 | και φεγγος αυτου                                                                                   |
| כאור                                 | ως φως                                                                                             |
| תהיה                                 | εσται                                                                                              |
| קרנים                                | κερατα                                                                                             |
| מידו לו                              | εν χερσιν αυτου                                                                                    |
| ושם =vs                              | και εθετο                                                                                          |
| חביון •^[Etymological exegesis.] חבב | αγαπησιν                                                                                           |
| *עזה **עזו                           | κραταιαν •^[Reference to doublet (occurring between the two elements of the doublet.] ισχυος αυτου |
: Habakkuk chapter 3, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                | Tov's retroversion                                                        | Septuagint                           |
|:----------------------------------------------|:--------------------------------------------------------------------------|:-------------------------------------|
| לפניו                                         |                                                                           | προ προσωπου αυτου                   |
| ילך                                           |                                                                           | πορευσεται                           |
| דבר •^[Difference in vocalization (reading).] |                                                                           | λογος                                |
| ויצא                                          |                                                                           | και εξελευσεται                      |
| [רשף]{.potential-difference}                  | [•^[Questionable notation, equivalent, etc.] שרוך]{.potential-difference} | [εν πεδιλοις]{.potential-difference} |
| לרגליו                                        |                                                                           | οι ποδες αυτου                       |
: Habakkuk chapter 3, verse 5 { .hover tbl-colwidths="[35,30,35]"}

### Verse 6

| Masoretic text                       | Tov's retroversion                    | Septuagint                           |
|:-------------------------------------|:--------------------------------------|:-------------------------------------|
| עמד                                  |                                       | εστη                                 |
| וימדד •^[Etymological exegesis.] נוד |                                       | και εσαλευθη                         |
| ארץ                                  |                                       | η γη                                 |
| ראה                                  |                                       | επεβλεψεν                            |
| [ויתר]{.potential-difference}        | [ויתך <na1.6>]{.potential-difference} | [και διετακη]{.potential-difference} |
| גוים                                 |                                       | εθνη                                 |
| ויתפצצו <na1.6>                      |                                       | διεθρυβη                             |
| הררי                                 |                                       | τα ορη                               |
| עד                                   |                                       | βια                                  |
| שחו                                  |                                       | ετακησαν                             |
| גבעות                                |                                       | βουνοι                               |
| עולם                                 |                                       | αιωνιοι                              |
| הליכות                               |                                       | πορειας [7]                          |
| עולם                                 |                                       | αιωνιας [7]                          |
| לו                                   |                                       | αυτου [7]                            |
: Habakkuk chapter 3, verse 6 { .hover tbl-colwidths="[35,30,35]"}

### Verse 7

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| תחת              | αντι          |
| און              | κοπων         |
| ראיתי            | ειδον         |
| אהלי             | σκηνωματα     |
| כושן             | αιθιοπων      |
| ירגזון           | πτοηθησονται  |
| יריעות           | και αι σκηναι |
| ארץ              | γης           |
| מדין             | μαδιαμ        |
: Habakkuk chapter 3, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| הבנהרים          | μη εν ποταμοις    |
| חרה              | ωργισθης          |
| יהוה             | κυριε             |
| אם               | η                 |
| בנהרים           | εν ποταμοις       |
| אפך              | ο θυμος σου       |
| אם               | η                 |
| בים              | εν θαλασση        |
| עברתך            | το ορμημα σου     |
| כי               | οτι               |
| תרכב             | επιβηση           |
| על               | επι               |
| סוסיך            | τους ιππους σου   |
| מרכבתיך          | και η ιππασια σου |
| ישועה            | σωτηρια           |
: Habakkuk chapter 3, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                                                   | Tov's retroversion                | Septuagint                                                                                                                  |
|:---------------------------------------------------------------------------------|:----------------------------------|:----------------------------------------------------------------------------------------------------------------------------|
| עריה                                                                             |                                   | εντεινων                                                                                                                    |
| [תעור]{.potential-difference}                                                    | [תעיר .wy]{.potential-difference} | [εντενεις]{.potential-difference}                                                                                           |
| קשתך                                                                             |                                   | το τοξον σου                                                                                                                |
| [שבעות]{.potential-difference}                                                   |                                   | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}                                      |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                   | επι                                                                                                                         |
| מטות                                                                             |                                   | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι τα σκηπτρα |
| אמר                                                                              |                                   | λεγει                                                                                                                       |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     |                                   | [κυριος]{.potential-difference}                                                                                             |
| סלה                                                                              |                                   | διαψαλμα                                                                                                                    |
| נהרות                                                                            |                                   | ποταμων                                                                                                                     |
| תבקע •^[Change from active to passive form in verbs.]                            |                                   | ραγησεται                                                                                                                   |
| ארץ                                                                              |                                   | γη                                                                                                                          |
: Habakkuk chapter 3, verse 9 { .hover tbl-colwidths="[35,30,35]"}

### Verse 10

| Masoretic text                                                                                 | Tov's retroversion                                                                                               | Septuagint                    |
|:-----------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------|:------------------------------|
| ראוך                                                                                           |                                                                                                                  | οψονται σε                    |
| יחילו                                                                                          |                                                                                                                  | και ωδινησουσιν               |
| [הרים]{.potential-difference}                                                                  | [•^[Questionable notation, equivalent, etc.] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [λαοι]{.potential-difference} |
| זרם •^[Difference in vocalization (reading).]                                                  |                                                                                                                  | σκορπιζων                     |
| מים                                                                                            |                                                                                                                  | υδατα                         |
| עבר •^[Difference in vocalization (reading).]                                                  |                                                                                                                  | πορειας αυτου                 |
| נתן                                                                                            |                                                                                                                  | εδωκεν                        |
| תהום                                                                                           |                                                                                                                  | η αβυσσος                     |
| קולו                                                                                           |                                                                                                                  | φωνην αυτης                   |
| רום                                                                                            |                                                                                                                  | υψος                          |
| ידיהו •^[Etymological exegesis.] ראה .dr                                                       |                                                                                                                  | φαντασιας αυτης               |
| נשא •^[Difference in vocalization (reading).] •^[Change from active to passive form in verbs.] |                                                                                                                  | επηρθη                        |
: Habakkuk chapter 3, verse 10 { .hover tbl-colwidths="[35,30,35]"}

### Verse 11

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| שמש              | ο ηλιος           |
| ירח              | και η σεληνη      |
| עמד              | εστη              |
| זבלה             | εν τη ταξει αυτης |
| לאור             | εις φως           |
| חציך             | βολιδες σου       |
| יהלכו            | πορευσονται       |
| לנגה             | εις φεγγος        |
| ברק              | αστραπης          |
| חניתך            | οπλων σου         |
: Habakkuk chapter 3, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                | Tov's retroversion                | Septuagint                         |
|:------------------------------|:----------------------------------|:-----------------------------------|
| בזעם                          |                                   | εν απειλη                          |
| [תצעד]{.potential-difference} | [תצער .dr]{.potential-difference} | [ολιγωσεις]{.potential-difference} |
| ארץ                           |                                   | γην                                |
| באף                           |                                   | και εν θυμω                        |
| תדוש                          |                                   | καταξεις                           |
| גוים                          |                                   | εθνη                               |
: Habakkuk chapter 3, verse 12 { .hover tbl-colwidths="[35,30,35]"}

### Verse 13

| Masoretic text                                                                   | Tov's retroversion                 | Septuagint                                                                                                               |
|:---------------------------------------------------------------------------------|:-----------------------------------|:-------------------------------------------------------------------------------------------------------------------------|
| יצאת                                                                             |                                    | εξηλθες                                                                                                                  |
| לישע                                                                             |                                    | εις σωτηριαν                                                                                                             |
| עמך                                                                              |                                    | λαου σου                                                                                                                 |
| לישע                                                                             |                                    | του σωσαι                                                                                                                |
| את משיחך •^[Difference in vocalization (reading).]                               |                                    | τους χριστους σου                                                                                                        |
| מחצת                                                                             |                                    | εβαλες                                                                                                                   |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                    | εις                                                                                                                      |
| ראש                                                                              |                                    | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις κεφαλας |
| [מבית]{.potential-difference}                                                    | [רשע]{.potential-difference}       | [ανομων]{.potential-difference}                                                                                          |
| [רשע]{.potential-difference}                                                     | [מבית ■מות]{.potential-difference} | [θανατον]{.potential-difference}                                                                                         |
| ערות •^[Etymological exegesis.]                                                  |                                    | εξηγειρας                                                                                                                |
| יסוד                                                                             |                                    | δεσμους                                                                                                                  |
| עד                                                                               |                                    | εως                                                                                                                      |
| צואר                                                                             |                                    | τραχηλου                                                                                                                 |
| סלה                                                                              |                                    | διαψαλμα                                                                                                                 |
: Habakkuk chapter 3, verse 13 { .hover tbl-colwidths="[35,30,35]"}

### Verse 14

| Masoretic text                                                                     | Tov's retroversion                                                                                                           | Septuagint                                        |
|:-----------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------|
| נקבת                                                                               |                                                                                                                              | διεκοψας                                          |
| במטיו                                                                              |                                                                                                                              | εν εκστασει {cεκτασει}                            |
| ראש                                                                                |                                                                                                                              | κεφαλας                                           |
| *פרזו **פרזיו                                                                      |                                                                                                                              | δυναστων                                          |
| יסערו                                                                              |                                                                                                                              | σεισθησονται                                      |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}       |                                                                                                                              | [εν αυτη]{.potential-difference}                  |
| להפיצני •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] פצח |                                                                                                                              | διανοιξουσιν                                      |
| [עליצתם]{.potential-difference}                                                    | [•^[Questionable notation, equivalent, etc.] מצלתמ, •^[Questionable notation, equivalent, etc.] @אלץ]{.potential-difference} | [χαλινους αυτων <za14.20>]{.potential-difference} |
| כמו                                                                                |                                                                                                                              | ως                                                |
| לאכל                                                                               |                                                                                                                              | εσθων                                             |
| עני                                                                                |                                                                                                                              | πτωχος                                            |
| במסתר                                                                              |                                                                                                                              | λαθρα                                             |
: Habakkuk chapter 3, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text                                | Septuagint      |
|:----------------------------------------------|:----------------|
| דרכת                                          | και επεβιβασας  |
| בים                                           | εις θαλασσαν    |
| סוסיך                                         | τους ιππους σου |
| חמר •^[Difference in vocalization (reading).] | ταρασσοντας     |
| מים                                           | υδωρ            |
| רבים                                          | πολυ            |
: Habakkuk chapter 3, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text                                        | Tov's retroversion                                                        | Septuagint                          |
|:------------------------------------------------------|:--------------------------------------------------------------------------|:------------------------------------|
| שמעתי                                                 |                                                                           | εφυλαξαμην                          |
| ותרגז                                                 |                                                                           | και επτοηθη                         |
| בטני                                                  |                                                                           | η κοιλια μου                        |
| לקול                                                  |                                                                           | απο φωνης                           |
| צללו •^[Etymological exegesis.] צלהa                  |                                                                           | προσευχης                           |
| שפתי                                                  |                                                                           | χειλεων μου                         |
| יבוא                                                  |                                                                           | και εισηλθεν                        |
| רקב                                                   |                                                                           | τρομος                              |
| בעצמי                                                 |                                                                           | εις τα οστα μου                     |
| ותחתי                                                 |                                                                           | και υποκατωθεν μου                  |
| ארגז •^[Change from active to passive form in verbs.] |                                                                           | εταραχθη                            |
| [אשר]{.potential-difference}                          | [•^[Questionable notation, equivalent, etc.] אשור]{.potential-difference} | [η εξις μου]{.potential-difference} |
| אנוח                                                  |                                                                           | αναπαυσομαι                         |
| ליום                                                  |                                                                           | εν ημερα                            |
| צרה                                                   |                                                                           | θλιψεως                             |
| לעלות                                                 |                                                                           | του αναβηναι                        |
| לעם                                                   |                                                                           | εις λαον                            |
| יגודנו •^[Etymological exegesis.] גור                 |                                                                           | παροικιας μου                       |
: Habakkuk chapter 3, verse 16 { .hover tbl-colwidths="[35,30,35]"}

### Verse 17

| Masoretic text                 | Tov's retroversion                  | Septuagint                            |
|:-------------------------------|:------------------------------------|:--------------------------------------|
| כי                             |                                     | διοτι                                 |
| תאנה                           |                                     | συκη                                  |
| לא                             |                                     | ου                                    |
| [תפרח]{.potential-difference}  | [תפרה .xh]{.potential-difference}   | [καρποφορησει]{.potential-difference} |
| ואין                           |                                     | και ουκ εσται                         |
| יבול                           |                                     | γενηματα                              |
| בגפנים                         |                                     | εν ταις αμπελοις                      |
| כחש                            |                                     | ψευσεται                              |
| מעשה                           |                                     | εργον                                 |
| זית                            |                                     | ελαιας                                |
| ושדמות                         |                                     | και τα πεδια                          |
| לא                             |                                     | ου                                    |
| עשה                            |                                     | ποιησει                               |
| אכל                            |                                     | βρωσιν                                |
| גזר                            |                                     | εξελιπον                              |
| [ממכלה]{.potential-difference} | [ממאכלה .אט]{.potential-difference} | [απο βρωσεως]{.potential-difference}  |
| צאן                            |                                     | προβατα                               |
| ואין                           |                                     | και ουχ υπαρχουσιν                    |
| בקר                            |                                     | βοες                                  |
| ברפתים                         |                                     | επι φατναις                           |
: Habakkuk chapter 3, verse 17 { .hover tbl-colwidths="[35,30,35]"}

### Verse 18

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| ואני             | εγω δε        |
| ביהוה            | εν τω κυριω   |
| אעלוזה           | αγαλλιασομαι  |
| אגילה            | χαρησομαι     |
| באלהי            | επι τω θεω    |
| ישעי             | τω σωτηρι μου |
: Habakkuk chapter 3, verse 18 { .hover tbl-colwidths="[50,50]"}

### Verse 19

| Masoretic text                        | Septuagint      |
|:--------------------------------------|:----------------|
| יהוה                                  | κυριος          |
| אדני                                  | ο θεος          |
| חילי                                  | δυναμις μου     |
| וישם                                  | και ταξει       |
| רגלי                                  | τους ποδας μου  |
| כאילות •^[Etymological exegesis.] כלה | εις συντελειαν  |
| ועל                                   | επι             |
| במותי                                 | τα υψηλα        |
| ידרכני                                | επιβιβα με      |
| למנצח                                 | του νικησαι     |
| בנגינותי                              | εν τη ωδη αυτου |
: Habakkuk chapter 3, verse 19 { .hover tbl-colwidths="[50,50]"}

