# Haggai

The tables below show the Hebrew and Greek texts aligned vertically. When a Hebrew verse number does not match the Greek counterpart, the editors added a note with the corresponding verse number between square brackets.

## Chapter 1

### Verse 1

| Masoretic text                                                                           | Septuagint                                                                                                            |
|:-----------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------|
| בשנת                                                                                     | εν {..ετει}                                                                                                           |
| שתים                                                                                     | τω δευτερω                                                                                                            |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]         | ετει                                                                                                                  |
| לדריוש                                                                                   | επι δαρειου                                                                                                           |
| המלך                                                                                     | του βασιλεως                                                                                                          |
| בחדש                                                                                     | εν τω μηνι                                                                                                            |
| הששי                                                                                     | τω εκτω                                                                                                               |
| ביום אחד                                                                                 | μια                                                                                                                   |
| לחדש                                                                                     | του μηνος                                                                                                             |
| היה                                                                                      | εγενετο                                                                                                               |
| דבר                                                                                      | λογος                                                                                                                 |
| יהוה                                                                                     | κυριου                                                                                                                |
| ביד                                                                                      | εν χειρι                                                                                                              |
| חגי                                                                                      | αγγαιου                                                                                                               |
| הנביא                                                                                    | του προφητου                                                                                                          |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}             | [λεγων]{.potential-difference}                                                                                        |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;אמר <2.2>]{.potential-difference} | [ειπον]{.potential-difference}                                                                                        |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;נא <2.2>]{.potential-difference}  | [δη]{.potential-difference}                                                                                           |
| אל                                                                                       | προς                                                                                                                  |
| זרבבל                                                                                    | ζοροβαβελ                                                                                                             |
| בן                                                                                       | τον του                                                                                                               |
| שאלתיאל                                                                                  | σαλαθιηλ                                                                                                              |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]         | εκ                                                                                                                    |
| פחת                                                                                      | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εκ φυλης |
| יהודה                                                                                    | ιουδα                                                                                                                 |
| ואל                                                                                      | και προς                                                                                                              |
| יהושע                                                                                    | ιησουν                                                                                                                |
| בן                                                                                       | τον του                                                                                                               |
| יהוצדק                                                                                   | ιωσεδεκ                                                                                                               |
| הכהן                                                                                     | τον ιερεα                                                                                                             |
| הגדול                                                                                    | τον μεγαν                                                                                                             |
| לאמר                                                                                     | λεγων                                                                                                                 |
: Haggai chapter 1, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                                                   | Septuagint                                                                                                                                       |
|:---------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------|
| כה                                                                               | ταδε                                                                                                                                             |
| אמר                                                                              | λεγει                                                                                                                                            |
| יהוה                                                                             | κυριος                                                                                                                                           |
| צבאות                                                                            | παντοκρατωρ                                                                                                                                      |
| לאמר                                                                             | λεγων                                                                                                                                            |
| העם                                                                              | ο λαος                                                                                                                                           |
| הזה                                                                              | ουτος                                                                                                                                            |
| אמרו                                                                             | λεγουσιν                                                                                                                                         |
| לא                                                                               | ουχ                                                                                                                                              |
| [עת]{.potential-difference}                                                      | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] {.. •^[Questionable notation, equivalent, etc.] ο καιροσ}]{.potential-difference} |
| בא                                                                               | ηκει                                                                                                                                             |
| עת                                                                               | ο καιρος                                                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | του οικοδομησαι                                                                                                                                  |
| בית                                                                              | τον οικον                                                                                                                                        |
| יהוה                                                                             | κυριου                                                                                                                                           |
| להבנות                                                                           | {..του οικοδομησαι}                                                                                                                              |
: Haggai chapter 1, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ויהי             | και εγενετο  |
| דבר              | λογος        |
| יהוה             | κυριου       |
| ביד              | εν χειρι     |
| חגי              | αγγαιου      |
| הנביא            | του προφητου |
| לאמר             | λεγων        |
: Haggai chapter 1, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text                                                                   | Septuagint               |
|:---------------------------------------------------------------------------------|:-------------------------|
| העת                                                                              | ει {...μεν εστιν} καιρος |
| לכם אתם                                                                          | υμιν                     |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | μεν εστιν                |
| לשבת                                                                             | του οικειν               |
| בבתיכם                                                                           | εν οικοις υμων           |
| ספונים                                                                           | κοιλοσταθμοις            |
| והבית                                                                            | ο δε οικος               |
| הזה                                                                              | ουτος                    |
| חרב                                                                              | εξηρημωται               |
: Haggai chapter 1, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                               | Septuagint                  |
|:-----------------------------------------------------------------------------|:----------------------------|
| ועתה                                                                         | και νυν                     |
| כה                                                                           | ταδε                        |
| אמר                                                                          | λεγει                       |
| יהוה                                                                         | κυριος                      |
| צבאות                                                                        | παντοκρατωρ                 |
| שימו                                                                         | ταξατε                      |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [δη]{.potential-difference} |
| לבבכם                                                                        | τας καρδιας υμων            |
| על                                                                           | εις                         |
| דרכיכם                                                                       | τας οδους υμων              |
: Haggai chapter 1, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text   | Septuagint                  |
|:-----------------|:----------------------------|
| זרעתם            | εσπειρατε                   |
| הרבה             | πολλα                       |
| והבא             | και εισηνεγκατε             |
| מעט              | ολιγα                       |
| אכול             | εφαγετε                     |
| ואין             | και ουκ                     |
| לשבעה            | εις πλησμονην               |
| שתו              | επιετε                      |
| ואין             | και ουκ                     |
| לשכרה            | εις μεθην                   |
| לבוש             | περιεβαλεσθε                |
| ואין             | και ουκ                     |
| לחם              | εθερμανθητε                 |
| לו               | εν αυτοις                   |
| והמשתכר          | και ο τους μισθους συναγων  |
| משתכר            | {..dτους μισθουσ} συνηγαγεν |
| אל               | εις                         |
| צרור             | δεσμον                      |
| נקוב             | τετρυπημενον                |
: Haggai chapter 1, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| כה               | ταδε             |
| אמר              | λεγει            |
| יהוה             | κυριος           |
| צבאות            | παντοκρατωρ      |
| שימו             | θεσθε            |
| לבבכם            | τας καρδιας υμων |
| על               | εις              |
| דרכיכם           | τας οδους υμων   |
: Haggai chapter 1, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                                                   | Tov's retroversion              | Septuagint                                                                                                               |
|:---------------------------------------------------------------------------------|:--------------------------------|:-------------------------------------------------------------------------------------------------------------------------|
| עלו                                                                              |                                 | αναβητε                                                                                                                  |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                 | επι                                                                                                                      |
| ההר                                                                              |                                 | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι το ορος |
| [והבאתם]{.potential-difference}                                                  | [ובראתם]{.potential-difference} | [και κοψατε]{.potential-difference}                                                                                      |
| עץ                                                                               |                                 | ξυλα                                                                                                                     |
| ובנו                                                                             |                                 | και οικοδομησατε                                                                                                         |
| הבית                                                                             |                                 | τον οικον                                                                                                                |
| וארצה                                                                            |                                 | και ευδοκησω                                                                                                             |
| בו                                                                               |                                 | εν αυτω                                                                                                                  |
| *ואכבד **ואכבדה                                                                  |                                 | και ενδοξασθησομαι                                                                                                       |
| אמר                                                                              |                                 | ειπεν                                                                                                                    |
| יהוה                                                                             |                                 | κυριος                                                                                                                   |
: Haggai chapter 1, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text                                                                           | Septuagint                                                                                                                 |
|:-----------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------|
| פנה                                                                                      | επεβλεψατε                                                                                                                 |
| אל                                                                                       | εις                                                                                                                        |
| הרבה                                                                                     | πολλα                                                                                                                      |
| והנה                                                                                     | και εγενετο                                                                                                                |
| למעט                                                                                     | ολιγα                                                                                                                      |
| והבאתם                                                                                   | και εισηνεχθη                                                                                                              |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]         | εις                                                                                                                        |
| הבית                                                                                     | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις τον οικον |
| ונפחתי                                                                                   | και εξεφυσησα                                                                                                              |
| בו                                                                                       | αυτα                                                                                                                       |
| יען                                                                                      | δια τουτο                                                                                                                  |
| מה                                                                                       | ταδε                                                                                                                       |
| נאם                                                                                      | λεγει                                                                                                                      |
| יהוה                                                                                     | κυριος                                                                                                                     |
| צבאות                                                                                    | παντοκρατωρ                                                                                                                |
| יען •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] אשר | ανθ' ων                                                                                                                    |
| ביתי                                                                                     | ο οικος μου                                                                                                                |
| אשר                                                                                      | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                           |
| הוא                                                                                      | εστιν                                                                                                                      |
| חרב                                                                                      | ερημος                                                                                                                     |
| ואתם                                                                                     | υμεις δε                                                                                                                   |
| רצים                                                                                     | διωκετε                                                                                                                    |
| איש                                                                                      | εκαστος                                                                                                                    |
| לביתו                                                                                    | εις τον οικον αυτου                                                                                                        |
: Haggai chapter 1, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                 | Septuagint                                                                             |
|:-------------------------------|:---------------------------------------------------------------------------------------|
| על כן                          | δια τουτο                                                                              |
| [עליכם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| כלאו                           | ανεξει                                                                                 |
| שמים                           | ο ουρανος                                                                              |
| מטל                            | απο δροσου                                                                             |
| והארץ                          | και η γη                                                                               |
| כלאה                           | υποστελειται                                                                           |
| יבולה                          | τα εκφορια αυτης                                                                       |
: Haggai chapter 1, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                                | Septuagint       |
|:----------------------------------------------|:-----------------|
| ואקרא                                         | και επαξω        |
| חרב •^[Difference in vocalization (reading).] | ρομφαιαν         |
| על                                            | επι              |
| הארץ                                          | την γην          |
| ועל                                           | και επι          |
| ההרים                                         | τα ορη           |
| ועל                                           | και επι          |
| הדגן                                          | τον σιτον        |
| ועל                                           | και επι          |
| התירוש                                        | τον οινον        |
| ועל                                           | και επι          |
| היצהר                                         | το ελαιον        |
| ועל אשר                                       | και οσα          |
| תוציא                                         | εκφερει          |
| האדמה                                         | η γη             |
| ועל                                           | και επι          |
| האדם                                          | τους ανθρωπους   |
| ועל                                           | και επι          |
| הבהמה                                         | τα κτηνη         |
| ועל                                           | και επι          |
| כל                                            | παντας           |
| יגיע                                          | τους πονους      |
| כפים                                          | των χειρων αυτων |
: Haggai chapter 1, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                                                                                                                       | Septuagint                                                                                                                                     |
|:-------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------|
| וישמע                                                                                                                                | και ηκουσεν                                                                                                                                    |
| זרבבל                                                                                                                                | ζοροβαβελ                                                                                                                                      |
| בן                                                                                                                                   | ο του                                                                                                                                          |
| שלתיאל                                                                                                                               | σαλαθιηλ                                                                                                                                       |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                     | εκ                                                                                                                                             |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;פחת <1.14>]{.potential-difference}                                            | [•^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εκ φυλης]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Introducing reconstructed proper noun.] יהודה <1.14>]{.potential-difference} | [ιουδα]{.potential-difference}                                                                                                                 |
| ויהושע                                                                                                                               | και ιησους                                                                                                                                     |
| בן                                                                                                                                   | ο του                                                                                                                                          |
| יהוצדק                                                                                                                               | ιωσεδεκ                                                                                                                                        |
| הכהן                                                                                                                                 | ο ιερευς                                                                                                                                       |
| הגדול                                                                                                                                | ο μεγας                                                                                                                                        |
| וכל                                                                                                                                  | και παντες                                                                                                                                     |
| שארית                                                                                                                                | οι καταλοιποι                                                                                                                                  |
| העם                                                                                                                                  | του λαου                                                                                                                                       |
| בקול                                                                                                                                 | της φωνης                                                                                                                                      |
| יהוה                                                                                                                                 | κυριου                                                                                                                                         |
| אלהיהם                                                                                                                               | του θεου αυτων                                                                                                                                 |
| ועל דברי                                                                                                                             | και των λογων                                                                                                                                  |
| חגי                                                                                                                                  | αγγαιου                                                                                                                                        |
| הנביא                                                                                                                                | του προφητου                                                                                                                                   |
| כאשר                                                                                                                                 | καθοτι                                                                                                                                         |
| שלחו                                                                                                                                 | εξαπεστειλεν αυτον                                                                                                                             |
| יהוה                                                                                                                                 | κυριος                                                                                                                                         |
| אלהיהם                                                                                                                               | ο θεος αυτων                                                                                                                                   |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                         | [προς αυτους]{.potential-difference}                                                                                                           |
| וייראו                                                                                                                               | και εφοβηθη                                                                                                                                    |
| העם                                                                                                                                  | ο λαος                                                                                                                                         |
| מפני                                                                                                                                 | απο προσωπου                                                                                                                                   |
| יהוה                                                                                                                                 | κυριου                                                                                                                                         |
: Haggai chapter 1, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                   | Septuagint                                                                             |
|:---------------------------------|:---------------------------------------------------------------------------------------|
| ויאמר                            | και ειπεν                                                                              |
| חגי                              | αγγαιος                                                                                |
| מלאך                             | ο αγγελος                                                                              |
| יהוה                             | κυριου                                                                                 |
| [במלאכות]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [יהוה]{.potential-difference}    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| לעם                              | τω λαω                                                                                 |
| [לאמר]{.potential-difference}    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| אני                              | εγω ειμι                                                                               |
| אתכם                             | μεθ' υμων                                                                              |
| נאם                              | λεγει                                                                                  |
| יהוה                             | κυριος                                                                                 |
: Haggai chapter 1, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                                   | Septuagint                                                                                                            |
|:---------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------|
| ויער                                                                             | και εξηγειρεν                                                                                                         |
| יהוה                                                                             | κυριος                                                                                                                |
| את רוח                                                                           | το πνευμα                                                                                                             |
| זרבבל                                                                            | ζοροβαβελ                                                                                                             |
| בן                                                                               | του                                                                                                                   |
| שלתיאל                                                                           | σαλαθιηλ                                                                                                              |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εκ                                                                                                                    |
| פחת                                                                              | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εκ φυλης |
| יהודה                                                                            | ιουδα                                                                                                                 |
| ואת רוח                                                                          | και το πνευμα                                                                                                         |
| יהושע                                                                            | ιησου                                                                                                                 |
| בן                                                                               | του                                                                                                                   |
| יהוצדק                                                                           | ιωσεδεκ                                                                                                               |
| הכהן                                                                             | του ιερεως                                                                                                            |
| הגדול                                                                            | του μεγαλου                                                                                                           |
| ואת רוח                                                                          | και το πνευμα                                                                                                         |
| כל                                                                               | {..παντοσ}                                                                                                            |
| שארית                                                                            | των καταλοιπων                                                                                                        |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | παντος                                                                                                                |
| העם                                                                              | του λαου                                                                                                              |
| ויבאו                                                                            | και εισηλθον                                                                                                          |
| ויעשו                                                                            | και εποιουν                                                                                                           |
| מלאכה                                                                            | εργα                                                                                                                  |
| בבית                                                                             | εν τω οικω                                                                                                            |
| יהוה                                                                             | κυριου                                                                                                                |
| צבאות                                                                            | παντοκρατορος                                                                                                         |
| אלהיהם                                                                           | θεου αυτων                                                                                                            |
: Haggai chapter 1, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text                                                                   | Septuagint            |
|:---------------------------------------------------------------------------------|:----------------------|
| ביום עשרים וארבעה                                                                | τη τετραδι και εικαδι |
| לחדש                                                                             | του μηνος             |
| בששי                                                                             | του εκτου             |
| בשנת                                                                             | τω {..ετει}           |
| שתים                                                                             | δευτερω               |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | ετει                  |
| לדריוש                                                                           | επι δαρειου           |
| המלך                                                                             | του βασιλεως          |
: Haggai chapter 1, verse 15 { .hover tbl-colwidths="[50,50]"}

## Chapter 2

### Verse 1

| Masoretic text                   | Tov's retroversion           | Septuagint                        |
|:---------------------------------|:-----------------------------|:----------------------------------|
| בשביעי                           |                              | τω εβδομω μηνι                    |
| בעשרים ואחד                      |                              | μια και εικαδι                    |
| לחדש                             |                              | του μηνος                         |
| [היה דבר]{.potential-difference} | [דבר]{.potential-difference} | [ελαλησεν]{.potential-difference} |
| יהוה                             |                              | κυριος                            |
| ביד                              |                              | εν χειρι                          |
| חגי                              |                              | αγγαιου                           |
| הנביא                            |                              | του προφητου                      |
| לאמר                             |                              | λεγων                             |
: Haggai chapter 2, verse 1 { .hover tbl-colwidths="[35,30,35]"}

### Verse 2

| Masoretic text                                                                           | Septuagint                                                                                                            |
|:-----------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------|
| אמר                                                                                      | ειπον                                                                                                                 |
| נא                                                                                       | δη                                                                                                                    |
| אל                                                                                       | προς                                                                                                                  |
| זרבבל                                                                                    | ζοροβαβελ                                                                                                             |
| בן                                                                                       | τον του                                                                                                               |
| שלתיאל                                                                                   | σαλαθιηλ                                                                                                              |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]         | εκ                                                                                                                    |
| פחת                                                                                      | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εκ φυλης |
| יהודה                                                                                    | ιουδα                                                                                                                 |
| ואל                                                                                      | και προς                                                                                                              |
| יהושע                                                                                    | ιησουν                                                                                                                |
| בן                                                                                       | τον του                                                                                                               |
| יהוצדק                                                                                   | ιωσεδεκ                                                                                                               |
| הכהן                                                                                     | τον ιερεα                                                                                                             |
| הגדול                                                                                    | τον μεγαν                                                                                                             |
| ואל                                                                                      | και προς                                                                                                              |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;כל <1.14>]{.potential-difference} | [παντας]{.potential-difference}                                                                                       |
| שארית                                                                                    | τους καταλοιπους                                                                                                      |
| העם                                                                                      | του λαου                                                                                                              |
| לאמר                                                                                     | λεγων                                                                                                                 |
: Haggai chapter 2, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                 | Septuagint                                                                             |
|:-------------------------------|:---------------------------------------------------------------------------------------|
| מי                             | τις                                                                                    |
| בכם                            | εξ υμων                                                                                |
| [הנשאר]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| אשר                            | ος                                                                                     |
| ראה                            | ειδεν                                                                                  |
| את הבית                        | τον οικον                                                                              |
| הזה                            | τουτον                                                                                 |
| בכבודו                         | εν τη δοξη αυτου                                                                       |
| הראשון                         | τη εμπροσθεν                                                                           |
| ומה                            | και πως                                                                                |
| אתם                            | υμεις                                                                                  |
| ראים                           | βλεπετε                                                                                |
| אתו                            | αυτον                                                                                  |
| עתה                            | νυν                                                                                    |
| [הלוא]{.potential-difference}  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| כמהו                           | καθως                                                                                  |
| כאין                           | ουχ υπαρχοντα                                                                          |
| בעיניכם                        | ενωπιον υμων                                                                           |
: Haggai chapter 2, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text                                                                   | Septuagint     |
|:---------------------------------------------------------------------------------|:---------------|
| ועתה                                                                             | και νυν        |
| חזק                                                                              | κατισχυε       |
| זרבבל                                                                            | ζοροβαβελ      |
| נאם                                                                              | λεγει          |
| יהוה                                                                             | κυριος         |
| וחזק                                                                             | και κατισχυε   |
| יהושע                                                                            | ιησου          |
| בן                                                                               | ο του          |
| יהוצדק                                                                           | ιωσεδεκ        |
| הכהן                                                                             | ο ιερευς       |
| הגדול                                                                            | ο μεγας        |
| וחזק                                                                             | και κατισχυετω |
| כל                                                                               | πας            |
| עם                                                                               | ο λαος         |
| הארץ                                                                             | της γης        |
| נאם                                                                              | λεγει          |
| יהוה                                                                             | κυριος         |
| ועשו                                                                             | και ποιειτε    |
| כי                                                                               | διοτι          |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | μεθ' υμων      |
| אני                                                                              | εγω ειμι       |
| אתכם                                                                             | {..μεθ' υμων}  |
| נאם                                                                              | λεγει          |
| יהוה                                                                             | κυριος         |
| צבאות                                                                            | παντοκρατωρ    |
: Haggai chapter 2, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                   | Septuagint                                                                                                                           |
|:---------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------|
| [את הדבר]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [אשר]{.potential-difference}     | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [כרתי]{.potential-difference}    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [אתכם]{.potential-difference}    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [בצאתכם]{.potential-difference}  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [ממצרים]{.potential-difference}  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| ורוחי                            | και το πνευμα μου                                                                                                                    |
| עמדת                             | εφεστηκεν                                                                                                                            |
| בתוככם                           | εν μεσω υμων                                                                                                                         |
| אל תיראו                         | θαρσειτε                                                                                                                             |
: Haggai chapter 2, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text               | Septuagint                                                                             |
|:-----------------------------|:---------------------------------------------------------------------------------------|
| כי                           | διοτι                                                                                  |
| כה                           | ταδε                                                                                   |
| אמר                          | λεγει                                                                                  |
| יהוה                         | κυριος                                                                                 |
| צבאות                        | παντοκρατωρ                                                                            |
| עוד                          | ετι                                                                                    |
| אחת מעט                      | απαξ                                                                                   |
| [היא]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ואני                         | εγω                                                                                    |
| מרעיש                        | σεισω                                                                                  |
| את השמים                     | τον ουρανον                                                                            |
| ואת הארץ                     | και την γην                                                                            |
| ואת הים                      | και την θαλασσαν                                                                       |
| ואת החרבה                    | και την ξηραν                                                                          |
: Haggai chapter 2, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                                 | Septuagint   |
|:-----------------------------------------------|:-------------|
| והרעשתי                                        | και συσσεισω |
| את כל                                          | παντα        |
| הגוים                                          | τα εθνη      |
| ובאו                                           | και ηξει     |
| חמדת •^[Difference in vocalization (reading).] | τα εκλεκτα   |
| כל                                             | παντων       |
| הגוים                                          | των εθνων    |
| ומלאתי                                         | και πλησω    |
| את הבית                                        | τον οικον    |
| הזה                                            | τουτον       |
| כבוד                                           | δοξης        |
| אמר                                            | λεγει        |
| יהוה                                           | κυριος       |
| צבאות                                          | παντοκρατωρ  |
: Haggai chapter 2, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| לי               | εμον         |
| הכסף             | το αργυριον  |
| ולי              | και εμον     |
| הזהב             | το χρυσιον   |
| נאם              | λεγει        |
| יהוה             | κυριος       |
| צבאות            | παντοκρατωρ  |
: Haggai chapter 2, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                                                                                             | Septuagint                               |
|:---------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------|
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                               | [διοτι]{.potential-difference}           |
| גדול                                                                                                                       | μεγαλη                                   |
| יהיה                                                                                                                       | εσται                                    |
| כבוד                                                                                                                       | η δοξα                                   |
| הבית                                                                                                                       | του οικου                                |
| הזה                                                                                                                        | τουτου                                   |
| האחרון                                                                                                                     | η εσχατη                                 |
| מן                                                                                                                         | υπερ                                     |
| הראשון                                                                                                                     | την πρωτην                               |
| אמר                                                                                                                        | λεγει                                    |
| יהוה                                                                                                                       | κυριος                                   |
| צבאות                                                                                                                      | παντοκρατωρ                              |
| ובמקום                                                                                                                     | και εν τω τοπω                           |
| הזה                                                                                                                        | τουτω                                    |
| אתן                                                                                                                        | δωσω                                     |
| שלום                                                                                                                       | ειρηνην                                  |
| נאם                                                                                                                        | λεγει                                    |
| יהוה                                                                                                                       | κυριος                                   |
| צבאות                                                                                                                      | παντοκρατωρ                              |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και ειρηνην]{.potential-difference}     |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [ψυχης]{.potential-difference}           |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [εις περιποιησιν]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [παντι]{.potential-difference}           |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [τω κτιζοντι]{.potential-difference}     |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [του αναστησαι]{.potential-difference}   |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [τον ναον]{.potential-difference}        |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [τουτον]{.potential-difference}          |
: Haggai chapter 2, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| בעשרים וארבעה    | τετραδι και εικαδι |
| לתשיעי           | του ενατου μηνος   |
| בשנת             | ετους              |
| שתים             | δευτερου           |
| לדריוש           | επι δαρειου        |
| היה              | εγενετο            |
| דבר              | λογος              |
| יהוה             | κυριου             |
| אל               | προς               |
| חגי              | αγγαιον            |
| הנביא            | τον προφητην       |
| לאמר             | λεγων              |
: Haggai chapter 2, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text              | Septuagint                                                                             |
|:----------------------------|:---------------------------------------------------------------------------------------|
| כה                          | ταδε                                                                                   |
| אמר                         | λεγει                                                                                  |
| יהוה                        | κυριος                                                                                 |
| צבאות                       | παντοκρατωρ                                                                            |
| שאל                         | επερωτησον                                                                             |
| [נא]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| את הכהנים                   | τους ιερεις                                                                            |
| תורה                        | νομον                                                                                  |
| לאמר                        | λεγων                                                                                  |
: Haggai chapter 2, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text   | Septuagint                 |
|:-----------------|:---------------------------|
| הן               | εαν                        |
| ישא              | λαβη                       |
| איש              | ανθρωπος                   |
| בשר              | κρεας                      |
| קדש              | αγιον                      |
| בכנף             | εν τω ακρω                 |
| בגדו             | του ιματιου αυτου          |
| ונגע             | και αψηται                 |
| בכנפו            | το ακρον του ιματιου αυτου |
| אל הלחם          | αρτου                      |
| ואל הנזיד        | η εψεματος                 |
| ואל היין         | η οινου                    |
| ואל שמן          | η ελαιου                   |
| ואל כל           | η παντος                   |
| מאכל             | βρωματος                   |
| היקדש            | ει αγιασθησεται            |
| ויענו            | και απεκριθησαν            |
| הכהנים           | οι ιερεις                  |
| ויאמרו           | και ειπαν                  |
| לא               | ου                         |
: Haggai chapter 2, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                                                   | Septuagint                                                                                                            |
|:---------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------|
| ויאמר                                                                            | και ειπεν                                                                                                             |
| חגי                                                                              | αγγαιος                                                                                                               |
| אם                                                                               | εαν                                                                                                                   |
| יגע                                                                              | αψηται                                                                                                                |
| טמא                                                                              | μεμιαμμενος                                                                                                           |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | επι                                                                                                                   |
| נפש                                                                              | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι ψυχη |
| בכל                                                                              | απο παντος                                                                                                            |
| אלה                                                                              | τουτων                                                                                                                |
| היטמא                                                                            | ει μιανθησεται                                                                                                        |
| ויענו                                                                            | και απεκριθησαν                                                                                                       |
| הכהנים                                                                           | οι ιερεις                                                                                                             |
| ויאמרו                                                                           | και ειπαν                                                                                                             |
| יטמא                                                                             | μιανθησεται                                                                                                           |
: Haggai chapter 2, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                                                                                              | Tov's retroversion             | Septuagint                                  |
|:--------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------|:--------------------------------------------|
| ויען                                                                                                                                        |                                | και απεκριθη                                |
| חגי                                                                                                                                         |                                | αγγαιος                                     |
| ויאמר                                                                                                                                       |                                | και ειπεν                                   |
| כן                                                                                                                                          |                                | ουτως                                       |
| העם                                                                                                                                         |                                | ο λαος                                      |
| הזה                                                                                                                                         |                                | ουτος                                       |
| וכן                                                                                                                                         |                                | και ουτως                                   |
| הגוי                                                                                                                                        |                                | το εθνος                                    |
| הזה                                                                                                                                         |                                | τουτο                                       |
| לפני                                                                                                                                        |                                | ενωπιον εμου                                |
| נאם                                                                                                                                         |                                | λεγει                                       |
| יהוה                                                                                                                                        |                                | κυριος                                      |
| וכן                                                                                                                                         |                                | και ουτως                                   |
| כל                                                                                                                                          |                                | παντα                                       |
| מעשה                                                                                                                                        |                                | τα εργα                                     |
| ידיהם                                                                                                                                       |                                | των χειρων αυτων                            |
| ואשר                                                                                                                                        |                                | και ος εαν                                  |
| יקריבו                                                                                                                                      |                                | εγγιση                                      |
| שם                                                                                                                                          |                                | εκει                                        |
| טמא הוא                                                                                                                                     |                                | μιανθησεται                                 |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference}                  | [יען]{.potential-difference}   | [ενεκεν]{.potential-difference}             |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference}                  | [משאתם]{.potential-difference} | [των λημματων αυτων]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference}                  | [בשחר]{.potential-difference}  | [των ορθρινων]{.potential-difference}       |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference}                  |                                | [οδυνηθησονται]{.potential-difference}      |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference}                  |                                | [απο προσωπου]{.potential-difference}       |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference}                  |                                | [πονων αυτων]{.potential-difference}        |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;שנאו <am5.10>]{.potential-difference}  |                                | [και εμισειτε]{.potential-difference}       |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;בשער <am5.10>]{.potential-difference}  |                                | [εν πυλαις]{.potential-difference}          |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;מוכיח <am5.10>]{.potential-difference} |                                | [ελεγχοντας]{.potential-difference}         |
: Haggai chapter 2, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text   | Septuagint           |
|:-----------------|:---------------------|
| ועתה             | και νυν              |
| שימו             | θεσθε                |
| נא               | δη                   |
| לבבכם            | εις τας καρδιας υμων |
| מן               | απο                  |
| היום             | της ημερας           |
| הזה              | ταυτης               |
| ומעלה            | και υπερανω          |
| מטרם             | προ                  |
| שום              | του θειναι           |
| אבן              | λιθον                |
| אל               | επι                  |
| אבן              | λιθον                |
| בהיכל            | εν τω ναω            |
| יהוה             | κυριου               |
: Haggai chapter 2, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text                                                               | Tov's retroversion                                                                                                   | Septuagint                             |
|:-----------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------|:---------------------------------------|
| [מהיותם]{.potential-difference}                                              | [מה הייתם •^[One word of MT separated into two or more words in the parent text of the LXX.]]{.potential-difference} | [τινες ητε οτε]{.potential-difference} |
| בא                                                                           |                                                                                                                      | ενεβαλλετε                             |
| אל                                                                           |                                                                                                                      | εις                                    |
| ערמת                                                                         |                                                                                                                      | κυψελην                                |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                                                                                                      | [κριθης]{.potential-difference}        |
| עשרים                                                                        |                                                                                                                      | εικοσι                                 |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                                                                                                      | [σατα]{.potential-difference}          |
| והיתה                                                                        |                                                                                                                      | και εγενετο                            |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                                                                                                      | [κριθης]{.potential-difference}        |
| עשרה                                                                         |                                                                                                                      | δεκα                                   |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                                                                                                      | [σατα]{.potential-difference}          |
| בא                                                                           |                                                                                                                      | και εισεπορευεσθε                      |
| אל                                                                           |                                                                                                                      | εις                                    |
| היקב                                                                         |                                                                                                                      | το υποληνιον                           |
| לחשף                                                                         |                                                                                                                      | εξαντλησαι                             |
| חמשים                                                                        |                                                                                                                      | πεντηκοντα                             |
| פורה                                                                         |                                                                                                                      | μετρητας                               |
| והיתה                                                                        |                                                                                                                      | και εγενοντο                           |
| עשרים                                                                        |                                                                                                                      | εικοσι                                 |
: Haggai chapter 2, verse 16 { .hover tbl-colwidths="[35,30,35]"}

### Verse 17

| Masoretic text                                                               | Tov's retroversion               | Septuagint                                  |
|:-----------------------------------------------------------------------------|:---------------------------------|:--------------------------------------------|
| הכיתי                                                                        |                                  | επαταξα                                     |
| אתכם                                                                         |                                  | υμας                                        |
| [בשדפון •^[Questionable notation, equivalent, etc.]]{.potential-difference}  | [בירקון]{.potential-difference}  | [εν αφορια]{.potential-difference}          |
| [•^[Questionable notation, equivalent, etc.] ובירקון]{.potential-difference} | [ובשדפון]{.potential-difference} | [και εν ανεμοφθορια]{.potential-difference} |
| ובברד                                                                        |                                  | και εν χαλαζη                               |
| את כל                                                                        |                                  | παντα                                       |
| מעשה                                                                         |                                  | τα εργα                                     |
| ידיכם                                                                        |                                  | των χειρων υμων                             |
| ואין                                                                         |                                  | και ουκ                                     |
| אתכם                                                                         |                                  | επεστρεψατε                                 |
| אלי                                                                          |                                  | προς με                                     |
| נאם                                                                          |                                  | λεγει                                       |
| יהוה                                                                         |                                  | κυριος                                      |
: Haggai chapter 2, verse 17 { .hover tbl-colwidths="[35,30,35]"}

### Verse 18

| Masoretic text                                 | Septuagint                   |
|:-----------------------------------------------|:-----------------------------|
| שימו                                           | υποταξατε                    |
| נא                                             | δη                           |
| לבבכם                                          | τας καρδιας υμων             |
| מן                                             | απο                          |
| היום                                           | της ημερας                   |
| הזה                                            | ταυτης                       |
| ומעלה                                          | και επεκεινα                 |
| מיום עשרים וארבעה                              | απο της τετραδος και εικαδος |
| לתשיעי                                         | του ενατου μηνος             |
| למן                                            | και απο                      |
| היום                                           | της ημερας                   |
| אשר                                            | ης                           |
| יסד                                            | εθεμελιωθη                   |
| היכל                                           | ο ναος                       |
| יהוה                                           | κυριου                       |
| שימו                                           | θεσθε                        |
| לבבכם •^[Addition of preposition or particle.] | εν ταις καρδιαις υμων        |
: Haggai chapter 2, verse 18 { .hover tbl-colwidths="[50,50]"}

### Verse 19

| Masoretic text                                                                   | Tov's retroversion             | Septuagint                                                                                  |
|:---------------------------------------------------------------------------------|:-------------------------------|:--------------------------------------------------------------------------------------------|
| העוד                                                                             |                                | ει ετι                                                                                      |
| [הזרע]{.potential-difference}                                                    | [ידע]{.potential-difference}   | [επιγνωσθησεται]{.potential-difference}                                                     |
| [במגורה]{.potential-difference}                                                  | [בגורן]{.potential-difference} | [επι της αλω]{.potential-difference}                                                        |
| [ועד]{.potential-difference}                                                     | [ועוד]{.potential-difference}  | [και ει ετι]{.potential-difference}                                                         |
| הגפן                                                                             |                                | η αμπελος                                                                                   |
| והתאנה                                                                           |                                | και η συκη                                                                                  |
| והרמון                                                                           |                                | και η ροα                                                                                   |
| ועץ                                                                              |                                | και τα ξυλα                                                                                 |
| הזית                                                                             |                                | της ελαιας                                                                                  |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                | τα                                                                                          |
| לא                                                                               |                                | ου                                                                                          |
| נשא                                                                              |                                | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] τα φεροντα |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [פרי]{.potential-difference}   | [καρπον]{.potential-difference}                                                             |
| מן                                                                               |                                | απο                                                                                         |
| היום                                                                             |                                | της ημερας                                                                                  |
| הזה                                                                              |                                | ταυτης                                                                                      |
| אברך                                                                             |                                | ευλογησω                                                                                    |
: Haggai chapter 2, verse 19 { .hover tbl-colwidths="[35,30,35]"}

### Verse 20

| Masoretic text                                                               | Tov's retroversion                   | Septuagint                            |
|:-----------------------------------------------------------------------------|:-------------------------------------|:--------------------------------------|
| ויהי                                                                         |                                      | και εγενετο                           |
| דבר                                                                          |                                      | λογος                                 |
| יהוה                                                                         |                                      | κυριου                                |
| שנית                                                                         |                                      | εκ δευτερου                           |
| אל                                                                           |                                      | προς                                  |
| חגי                                                                          |                                      | αγγαιον                               |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [הנביא <q4e>]{.potential-difference} | [τον προφητην]{.potential-difference} |
| בעשרים וארבעה                                                                |                                      | τετραδι και εικαδι                    |
| לחדש                                                                         |                                      | του μηνος                             |
| לאמר                                                                         |                                      | λεγων                                 |
: Haggai chapter 2, verse 20 { .hover tbl-colwidths="[35,30,35]"}

### Verse 21

| Masoretic text                                                                                                                        | Septuagint                                                                                                            |
|:--------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------|
| אמר                                                                                                                                   | ειπον                                                                                                                 |
| אל                                                                                                                                    | προς                                                                                                                  |
| זרבבל                                                                                                                                 | ζοροβαβελ                                                                                                             |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;בן <2.2>]{.potential-difference}                                               | [τον του]{.potential-difference}                                                                                      |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Introducing reconstructed proper noun.] שאלתיאל <2.2>]{.potential-difference} | [σαλαθιηλ]{.potential-difference}                                                                                     |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                      | εκ                                                                                                                    |
| פחת                                                                                                                                   | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εκ φυλης |
| יהודה                                                                                                                                 | ιουδα                                                                                                                 |
| לאמר                                                                                                                                  | λεγων                                                                                                                 |
| אני                                                                                                                                   | εγω                                                                                                                   |
| מרעיש                                                                                                                                 | σειω                                                                                                                  |
| את השמים                                                                                                                              | τον ουρανον                                                                                                           |
| ואת הארץ                                                                                                                              | και την γην                                                                                                           |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;ואת הים <2.6>]{.potential-difference}                                          | [και την θαλασσαν]{.potential-difference}                                                                             |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;ואת החרבה <2.6>]{.potential-difference}                                        | [και την ξηραν]{.potential-difference}                                                                                |
: Haggai chapter 2, verse 21 { .hover tbl-colwidths="[50,50]"}

### Verse 22

| Masoretic text                                                                   | Septuagint                                                                                                                          |
|:---------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------|
| והפכתי                                                                           | και καταστρεψω                                                                                                                      |
| כסא                                                                              | θρονους                                                                                                                             |
| ממלכות                                                                           | βασιλεων                                                                                                                            |
| והשמדתי                                                                          | και ολεθρευσω                                                                                                                       |
| חזק                                                                              | δυναμιν                                                                                                                             |
| ממלכות                                                                           | βασιλεων                                                                                                                            |
| הגוים                                                                            | των εθνων                                                                                                                           |
| והפכתי                                                                           | και καταστρεψω                                                                                                                      |
| מרכבה                                                                            | αρματα                                                                                                                              |
| ורכביה                                                                           | και αναβατας                                                                                                                        |
| וירדו                                                                            | και καταβησονται                                                                                                                    |
| סוסים                                                                            | ιπποι                                                                                                                               |
| ורכביהם                                                                          | και αναβαται αυτων                                                                                                                  |
| איש                                                                              | εκαστος                                                                                                                             |
| בחרב                                                                             | εν ρομφαια                                                                                                                          |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | προς                                                                                                                                |
| אחיו                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] προς τον αδελφον αυτου |
: Haggai chapter 2, verse 22 { .hover tbl-colwidths="[50,50]"}

### Verse 23

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| ביום             | εν τη ημερα    |
| ההוא             | εκεινη         |
| נאם              | λεγει          |
| יהוה             | κυριος         |
| צבאות            | παντοκρατωρ    |
| אקחך             | λημψομαι σε    |
| זרבבל            | ζοροβαβελ      |
| בן               | τον του        |
| שאלתיאל          | σαλαθιηλ       |
| עבדי             | τον δουλον μου |
| נאם              | λεγει          |
| יהוה             | κυριος         |
| ושמתיך           | και θησομαι σε |
| כחותם            | ως σφραγιδα    |
| כי               | διοτι          |
| בך               | σε             |
| בחרתי            | ηρετισα        |
| נאם              | λεγει          |
| יהוה             | κυριος         |
| צבאות            | παντοκρατωρ    |
: Haggai chapter 2, verse 23 { .hover tbl-colwidths="[50,50]"}

