# Joel

## Chapter 1

### Verse 1

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| דבר                    | λογος                |
| יהוה                   | κυριου               |
| אשר                    | ος                   |
| היה                    | εγενηθη              |
| אל                     | προς                 |
| יואל                   | ιωηλ                 |
| בן                     | τον του              |
| פתואל                  | βαθουηλ              |
: Joel chapter 1, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text (BHS)                                | Rahlf's Septuagint   |
|:----------------------------------------------------|:---------------------|
| שמעו                                                | ακουσατε             |
| •^[Element 'added' in the Greek (plus in the LXX).] | δη                   |
| זאת                                                 | ταυτα                |
| הזקנים                                              | οι πρεσβυτεροι       |
| והאזינו                                             | και ενωτισασθε       |
| כל                                                  | παντες               |
| יושבי                                               | οι κατοικουντες      |
| הארץ                                                | την γην              |
| ההיתה                                               | ει γεγονεν           |
| זאת                                                 | τοιαυτα              |
| בימיכם                                              | εν ταις ημεραις υμων |
| ואם                                                 | η                    |
| בימי                                                | εν ταις ημεραις      |
| אבתיכם                                              | των πατερων υμων     |
: Joel chapter 1, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| עליה                   | υπερ αυτων           |
| לבניכם                 | τοις τεκνοις υμων    |
| ספרו                   | διηγησασθε           |
| ובניכם                 | και τα τεκνα υμων    |
| לבניהם                 | τοις τεκνοις αυτων   |
| ובניהם                 | και τα τεκνα αυτων   |
| לדור                   | εις γενεαν           |
| אחר                    | ετεραν               |
: Joel chapter 1, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| יתר                    | τα καταλοιπα         |
| הגזם                   | της καμπης           |
| אכל                    | κατεφαγεν            |
| הארבה                  | η ακρις              |
| ויתר                   | και τα καταλοιπα     |
| הארבה                  | της ακριδος          |
| אכל                    | κατεφαγεν            |
| הילק                   | ο βρουχος            |
| ויתר                   | και τα καταλοιπα     |
| הילק                   | του βρουχου          |
| אכל                    | κατεφαγεν            |
| החסיל                  | η ερυσιβη            |
: Joel chapter 1, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text (BHS)                                              | Tov's retroversion   | Rahlf's Septuagint   |
|:------------------------------------------------------------------|:---------------------|:---------------------|
| הקיצו                                                             |                      | εκνηψατε             |
| שכורים                                                            |                      | οι μεθυοντες         |
| •^[Element 'added' in the Greek (plus in the LXX).]               | מיינם                | εξ οινου αυτων       |
| ובכו                                                              |                      | και κλαυσατε         |
| והיללו                                                            |                      | θρηνησατε            |
| כל                                                                |                      | παντες               |
| שתי                                                               |                      | οι πινοντες          |
| יין                                                               |                      | οινον                |
| על                                                                |                      | εις                  |
| עסיס                                                              |                      | μεθην                |
| כי                                                                |                      | οτι                  |
| נכרת                                                              |                      | εξηρται              |
| מפיכם                                                             |                      | εκ στοματος υμων     |
| •^[Element 'added' in the Greek (plus in the LXX).] =;שמחה <1.16> |                      | ευφροσυνη            |
| •^[Element 'added' in the Greek (plus in the LXX).] =;וגיל <1.16> |                      | και χαρα             |
: Joel chapter 1, verse 5 { .hover tbl-colwidths="[35,30,35]"}

### Verse 6

| Masoretic text (BHS)                           | Rahlf's Septuagint                                                               |
|:-----------------------------------------------|:---------------------------------------------------------------------------------|
| כי                                             | οτι                                                                              |
| גוי                                            | εθνος                                                                            |
| עלה                                            | ανεβη                                                                            |
| על                                             | επι                                                                              |
| ארצי                                           | την γην μου                                                                      |
| עצום                                           | ισχυρον                                                                          |
| ואין מספר                                      | και αναριθμητον                                                                  |
| שניו                                           | οι οδοντες αυτου                                                                 |
| שני                                            | οδοντες                                                                          |
| אריה                                           | λεοντος                                                                          |
| ומתלעות                                        | και αι μυλαι                                                                     |
| •^[Stylistic or grammatical transposition.] לו | αυτου                                                                            |
| לביא                                           | σκυμνου                                                                          |
| לו                                             | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |
: Joel chapter 1, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text (BHS)   | Tov's retroversion                                                                                              | Rahlf's Septuagint   |
|:-----------------------|:----------------------------------------------------------------------------------------------------------------|:---------------------|
| שם                     |                                                                                                                 | εθετο                |
| גפני                   |                                                                                                                 | την αμπελον μου      |
| לשמה                   |                                                                                                                 | εις αφανισμον        |
| ותאנתי                 |                                                                                                                 | και τας συκας μου    |
| לקצפה                  |                                                                                                                 | εις συγκλασμον       |
| חשף                    | חפש {!}p •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)]  | ερευνων              |
| חשפה                   | חפשה {!}p •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)] | εξηρευνησεν αυτην    |
| והשליך                 |                                                                                                                 | και ερριψεν          |
| הלבינו                 |                                                                                                                 | ελευκανεν            |
| שריגיה                 |                                                                                                                 | κληματα αυτης        |
: Joel chapter 1, verse 7 { .hover tbl-colwidths="[35,30,35]"}

### Verse 8

| Masoretic text (BHS)                              | Tov's retroversion   | Rahlf's Septuagint                                                                                                                                                     |
|:--------------------------------------------------|:---------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| אלי                                               | {d}עלי .אע           | θρηνησον •^[Reference to doublet (occurring between the two elements of the doublet.] προς με                                                                          |
| כבתולה •^[Difference in preposition or particle.] |                      | υπερ νυμφην                                                                                                                                                            |
| חגרת                                              |                      | περιεζωσμενην                                                                                                                                                          |
| שק                                                |                      | σακκον                                                                                                                                                                 |
| על                                                |                      | επι                                                                                                                                                                    |
| בעל                                               |                      | τον ανδρα                                                                                                                                                              |
| נעוריה                                            |                      | αυτης •^[Difference in sequence between MT and LXX, denoted after the first Hebrew word and before the second one, as well as between two Greek words.] τον παρθενικον |
: Joel chapter 1, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text (BHS)   | Tov's retroversion   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|:---------------------|
| הכרת                   |                      | εξηρται              |
| מנחה                   |                      | θυσια                |
| ונסך                   |                      | και σπονδη           |
| מבית                   |                      | εξ οικου             |
| יהוה                   |                      | κυριου               |
| אבלו                   |                      | πενθειτε             |
| הכהנים                 |                      | οι ιερεις            |
| משרתי                  |                      | οι λειτουργουντες    |
| יהוה                   | מזבח                 | θυσιαστηριω          |
: Joel chapter 1, verse 9 { .hover tbl-colwidths="[35,30,35]"}

### Verse 10

| Masoretic text (BHS)                                | Rahlf's Septuagint   |
|:----------------------------------------------------|:---------------------|
| •^[Element 'added' in the Greek (plus in the LXX).] | οτι                  |
| שדד                                                 | τεταλαιπωρηκεν       |
| שדה                                                 | τα πεδια             |
| אבלה                                                | πενθειτω             |
| אדמה                                                | η γη                 |
| כי                                                  | οτι                  |
| שדד                                                 | τεταλαιπωρηκεν       |
| דגן                                                 | σιτος                |
| הוביש                                               | εξηρανθη             |
| תירוש                                               | οινος                |
| אמלל                                                | ωλιγωθη              |
| יצהר                                                | ελαιον               |
: Joel chapter 1, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text (BHS)                            | Rahlf's Septuagint                                                                                                 |
|:------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------|
| הבישו                                           | εξηρανθησαν                                                                                                        |
| אכרים                                           | οι γεωργοι                                                                                                         |
| הילילו                                          | θρηνειτε                                                                                                           |
| כרמים •^[Difference in vocalization (reading).] | κτηματα                                                                                                            |
| על                                              | υπερ                                                                                                               |
| חטה                                             | πυρου                                                                                                              |
| ועל                                             | και •^[Distributive rendering, occurring once in the translation but referring to more than one Hebrew word.] υπερ |
| שערה                                            | κριθης                                                                                                             |
| כי                                              | οτι                                                                                                                |
| אבד                                             | απολωλεν                                                                                                           |
| קציר                                            | τρυγητος                                                                                                           |
| שדה •^[Addition of preposition or particle.]    | εξ αγρου                                                                                                           |
: Joel chapter 1, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text (BHS)   | Rahlf's Septuagint                                            |
|:-----------------------|:--------------------------------------------------------------|
| הגפן                   | η αμπελος                                                     |
| הובישה                 | εξηρανθη                                                      |
| והתאנה                 | και αι συκαι                                                  |
| אמללה                  | ωλιγωθησαν                                                    |
| רמון                   | ροα                                                           |
| גם                     | και                                                           |
| תמר                    | φοινιξ                                                        |
| ותפוח                  | και μηλον                                                     |
| כל                     | και παντα                                                     |
| עצי                    | τα ξυλα                                                       |
| השדה                   | του αγρου                                                     |
| יבשו                   | εξηρανθησαν                                                   |
| כי                     | οτι                                                           |
| הביש                   | ησχυναν                                                       |
| ששון                   | χαραν                                                         |
| מן                     | •^[Hebrew counterpart lacking in the LXX (minus in the LXX).] |
| בני                    | οι υιοι                                                       |
| אדם                    | των ανθρωπων                                                  |
: Joel chapter 1, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| חגרו                   | περιζωσασθε          |
| וספדו                  | και κοπτεσθε         |
| הכהנים                 | οι ιερεις            |
| הילילו                 | θρηνειτε             |
| משרתי                  | οι λειτουργουντες    |
| מזבח                   | θυσιαστηριω          |
| באו                    | εισελθατε            |
| לינו                   | υπνωσατε             |
| בשקים                  | εν σακκοις           |
| משרתי                  | λειτουργουντες       |
| אלהי                   | θεω                  |
| כי                     | οτι                  |
| נמנע                   | απεσχηκεν            |
| מבית                   | εξ οικου             |
| אלהיכם                 | θεου υμων            |
| מנחה                   | θυσια                |
| ונסך                   | και σπονδη           |
: Joel chapter 1, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text (BHS)                                                             | Tov's retroversion                                | Rahlf's Septuagint                                                                                                     |
|:---------------------------------------------------------------------------------|:--------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------|
| קדשו                                                                             |                                                   | αγιασατε                                                                                                               |
| צום                                                                              |                                                   | νηστειαν                                                                                                               |
| קראו                                                                             |                                                   | κηρυξατε                                                                                                               |
| עצרה                                                                             |                                                   | θεραπειαν                                                                                                              |
| אספו                                                                             |                                                   | συναγαγετε                                                                                                             |
| זקנים                                                                            |                                                   | πρεσβυτερους                                                                                                           |
| כל                                                                               |                                                   | παντας                                                                                                                 |
| ישבי                                                                             |                                                   | κατοικουντας                                                                                                           |
| הארץ                                                                             |                                                   | γην                                                                                                                    |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                                   | εις                                                                                                                    |
| בית                                                                              |                                                   | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις οικον |
| יהוה                                                                             |                                                   | •^[Hebrew counterpart lacking in the LXX (minus in the LXX).]                                                          |
| אלהיכם                                                                           |                                                   | θεου υμων                                                                                                              |
| וזעקו                                                                            |                                                   | και κεκραξατε                                                                                                          |
| אל                                                                               |                                                   | προς                                                                                                                   |
| יהוה                                                                             |                                                   | κυριον                                                                                                                 |
| •^[Element 'added' in the Greek (plus in the LXX).]                              | •^[Questionable notation, equivalent, etc.] בחזקה | εκτενως                                                                                                                |
: Joel chapter 1, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text (BHS)                                                                                | Tov's retroversion   | Rahlf's Septuagint   |
|:----------------------------------------------------------------------------------------------------|:---------------------|:---------------------|
| אהה •^[Element 'added' in the Greek (plus in the LXX).] •^[Questionable notation, equivalent, etc.] |                      | οιμμοι οιμμοι οιμμοι |
| ליום                                                                                                |                      | εις ημεραν           |
| כי                                                                                                  |                      | οτι                  |
| קרוב                                                                                                |                      | εγγυς                |
| יום                                                                                                 |                      | ημερα                |
| יהוה                                                                                                |                      | κυριου               |
| וכשד                                                                                                |                      | και ως ταλαιπωρια    |
| משדי                                                                                                | משד                  | εκ ταλαιπωριας       |
| יבוא                                                                                                |                      | ηξει                 |
: Joel chapter 1, verse 15 { .hover tbl-colwidths="[35,30,35]"}

### Verse 16

| Masoretic text (BHS)   | Rahlf's Septuagint                                            |
|:-----------------------|:--------------------------------------------------------------|
| הלוא                   | •^[Hebrew counterpart lacking in the LXX (minus in the LXX).] |
| נגד                    | κατεναντι                                                     |
| עינינו                 | των οφθαλμων υμων                                             |
| אכל                    | βρωματα                                                       |
| נכרת                   | εξωλεθρευθη                                                   |
| מבית                   | εξ οικου                                                      |
| אלהינו                 | θεου υμων                                                     |
| שמחה                   | ευφροσυνη                                                     |
| וגיל                   | και χαρα                                                      |
: Joel chapter 1, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text (BHS)   | Tov's retroversion                              | Rahlf's Septuagint   |
|:-----------------------|:------------------------------------------------|:---------------------|
| עבשו                   | •^[Questionable notation, equivalent, etc.] פשו | εσκιρτησαν           |
| פרדות                  | פרות                                            | δαμαλεις             |
| תחת                    |                                                 | επι                  |
| מגרפתיהם               |                                                 | ταις φατναις αυτων   |
| נשמו                   |                                                 | ηφανισθησαν          |
| אצרות                  |                                                 | θησαυροι             |
| נהרסו                  |                                                 | κατεσκαφησαν         |
| ממגרות                 |                                                 | ληνοι                |
| כי                     |                                                 | οτι                  |
| הביש                   |                                                 | εξηρανθη             |
| דגן                    |                                                 | σιτος                |
: Joel chapter 1, verse 17 { .hover tbl-colwidths="[35,30,35]"}

### Verse 18

| Masoretic text (BHS)                  | Tov's retroversion                             | Rahlf's Septuagint   |
|:--------------------------------------|:-----------------------------------------------|:---------------------|
| מה                                    |                                                | τι                   |
| נאנחה •^[Etymological exegesis.] הניח |                                                | αποθησομεν           |
| בהמה                                  | בהמה •^[Difference in vocalization (reading).] | εαυτοις              |
| נבכו •^[Etymological exegesis.] בכה   |                                                | εκλαυσαν             |
| עדרי                                  |                                                | βουκολια             |
| בקר                                   |                                                | βοων                 |
| כי                                    |                                                | οτι                  |
| אין                                   |                                                | ουχ υπηρχεν          |
| מרעה                                  |                                                | νομη                 |
| להם                                   |                                                | αυτοις               |
| גם                                    |                                                | και                  |
| עדרי                                  |                                                | τα ποιμνια           |
| הצאן                                  |                                                | των προβατων         |
| נאשמו •^[Etymological exegesis.] שמם  |                                                | ηφανισθησαν          |
: Joel chapter 1, verse 18 { .hover tbl-colwidths="[35,30,35]"}

### Verse 19

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| אליך                   | προς σε              |
| יהוה                   | κυριε                |
| אקרא                   | βοησομαι             |
| כי                     | οτι                  |
| אש                     | πυρ                  |
| אכלה                   | ανηλωσεν             |
| נאות                   | τα ωραια             |
| מדבר                   | της ερημου           |
| ולהבה                  | και φλοξ             |
| להטה                   | ανηψεν               |
| כל                     | παντα                |
| עצי                    | τα ξυλα              |
| השדה                   | του αγρου            |
: Joel chapter 1, verse 19 { .hover tbl-colwidths="[50,50]"}

### Verse 20

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| גם                     | και                  |
| בהמות                  | τα κτηνη             |
| שדה                    | του πεδιου           |
| תערוג                  | ανεβλεψαν            |
| אליך                   | προς σε              |
| כי                     | οτι                  |
| יבשו                   | εξηρανθησαν          |
| אפיקי                  | αφεσεις              |
| מים                    | υδατων               |
| ואש                    | και πυρ              |
| אכלה                   | κατεφαγεν            |
| נאות                   | τα ωραια             |
| המדבר                  | της ερημου           |
: Joel chapter 1, verse 20 { .hover tbl-colwidths="[50,50]"}

## Chapter 2

### Verse 1

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| תקעו                   | σαλπισατε            |
| שופר                   | σαλπιγγι             |
| בציון                  | εν σιων              |
| והריעו                 | κηρυξατε             |
| בהר                    | εν ορει              |
| קדשי                   | αγιω μου             |
| ירגזו                  | και συγχυθητωσαν     |
| כל                     | παντες               |
| ישבי                   | οι κατοικουντες      |
| הארץ                   | την γην              |
| כי                     | διοτι                |
| בא                     | παρεστιν             |
| יום                    | ημερα                |
| יהוה                   | κυριου               |
| כי                     | οτι                  |
| קרוב                   | εγγυς                |
: Joel chapter 2, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text (BHS)                                                             | Rahlf's Septuagint                                                                                                      |
|:---------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------|
| יום                                                                              | ημερα                                                                                                                   |
| חשך                                                                              | σκοτους                                                                                                                 |
| ואפלה                                                                            | και γνοφου                                                                                                              |
| יום                                                                              | ημερα                                                                                                                   |
| ענן                                                                              | νεφελης                                                                                                                 |
| וערפל                                                                            | και ομιχλης                                                                                                             |
| כשחר                                                                             | ως ορθρος                                                                                                               |
| פרש                                                                              | χυθησεται                                                                                                               |
| על                                                                               | επι                                                                                                                     |
| ההרים                                                                            | τα ορη                                                                                                                  |
| עם                                                                               | λαος                                                                                                                    |
| רב                                                                               | πολυς                                                                                                                   |
| ועצום                                                                            | και ισχυρος                                                                                                             |
| כמהו                                                                             | ομοιος αυτω                                                                                                             |
| לא                                                                               | ου                                                                                                                      |
| נהיה                                                                             | γεγονεν                                                                                                                 |
| מן                                                                               | απο                                                                                                                     |
| העולם                                                                            | του αιωνος                                                                                                              |
| ואחריו                                                                           | και μετ' αυτον                                                                                                          |
| לא                                                                               | ου                                                                                                                      |
| יוסף                                                                             | προστεθησεται                                                                                                           |
| עד                                                                               | εως                                                                                                                     |
| שני                                                                              | ετων                                                                                                                    |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εις                                                                                                                     |
| דור                                                                              | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις γενεας |
| ודור                                                                             | γενεων                                                                                                                  |
: Joel chapter 2, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text (BHS)                                                                                                                                   | Tov's retroversion   | Rahlf's Septuagint   |
|:-------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------|:---------------------|
| לפניו                                                                                                                                                  |                      | τα εμπροσθεν αυτου   |
| אכלה •^[Difference in sequence between MT and LXX, denoted after the first Hebrew word and before the second one, as well as between two Greek words.] | אש                   | πυρ                  |
| ואחריו                                                                                                                                                 |                      | και τα οπισω αυτου   |
| תלהט                                                                                                                                                   |                      | αναπτομενη           |
| להבה                                                                                                                                                   |                      | φλοξ                 |
| כגן                                                                                                                                                    |                      | ως παραδεισος        |
| עדן •^[Etymological exegesis.]                                                                                                                         |                      | τρυφης               |
| הארץ                                                                                                                                                   |                      | η γη                 |
| לפניו                                                                                                                                                  |                      | προ προσωπου αυτου   |
| ואחריו                                                                                                                                                 |                      | και τα οπισθεν αυτου |
| מדבר                                                                                                                                                   |                      | πεδιον               |
| שממה                                                                                                                                                   |                      | αφανισμου            |
| וגם                                                                                                                                                    |                      | και                  |
| פליטה                                                                                                                                                  |                      | ανασωζομενος         |
| לא                                                                                                                                                     |                      | ουκ                  |
| היתה                                                                                                                                                   |                      | εσται                |
| לו                                                                                                                                                     |                      | αυτω                 |
: Joel chapter 2, verse 3 { .hover tbl-colwidths="[35,30,35]"}

### Verse 4

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| כמראה                  | ως ορασις            |
| סוסים                  | ιππων                |
| מראהו                  | η οψις αυτων         |
| וכפרשים                | και ως ιππεις        |
| כן                     | ουτως                |
| ירוצון                 | καταδιωξονται        |
: Joel chapter 2, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text (BHS)                                                             | Rahlf's Septuagint                                                                                                       |
|:---------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------|
| כקול                                                                             | ως φωνη                                                                                                                  |
| מרכבות                                                                           | αρματων                                                                                                                  |
| על                                                                               | επι                                                                                                                      |
| ראשי                                                                             | τας κορυφας                                                                                                              |
| ההרים                                                                            | των ορεων                                                                                                                |
| ירקדון                                                                           | εξαλουνται                                                                                                               |
| כקול                                                                             | και ως φωνη                                                                                                              |
| להב                                                                              | φλογος                                                                                                                   |
| אש                                                                               | πυρος                                                                                                                    |
| אכלה                                                                             | κατεσθιουσης                                                                                                             |
| קש                                                                               | καλαμην                                                                                                                  |
| כעם                                                                              | και ως λαος                                                                                                              |
| •^[Element 'added' in the Greek (plus in the LXX).] =;רב <2.2>                   | πολυς                                                                                                                    |
| עצום                                                                             | και ισχυρος                                                                                                              |
| ערוך                                                                             | παρατασσομενος                                                                                                           |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εις                                                                                                                      |
| מלחמה                                                                            | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις πολεμον |
: Joel chapter 2, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text (BHS)   | Tov's retroversion   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|:---------------------|
| מפניו                  |                      | απο προσωπου αυτου   |
| יחילו                  |                      | συντριβησονται       |
| עמים                   |                      | λαοι                 |
| כל                     |                      | παν                  |
| פנים                   |                      | προσωπον             |
| קבצו                   |                      | ως προσκαυμα         |
| פארור                  | פרור                 | χυτρας               |
: Joel chapter 2, verse 6 { .hover tbl-colwidths="[35,30,35]"}

### Verse 7

| Masoretic text (BHS)                                                             | Tov's retroversion   | Rahlf's Septuagint                                                                                                        |
|:---------------------------------------------------------------------------------|:---------------------|:--------------------------------------------------------------------------------------------------------------------------|
| כגבורים                                                                          |                      | ως μαχηται                                                                                                                |
| ירצון                                                                            |                      | δραμουνται                                                                                                                |
| כאנשי                                                                            |                      | και ως ανδρες                                                                                                             |
| מלחמה                                                                            |                      | πολεμισται                                                                                                                |
| יעלו                                                                             |                      | αναβησονται                                                                                                               |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                      | επι                                                                                                                       |
| חומה                                                                             |                      | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι τα τειχη |
| ואיש                                                                             |                      | και εκαστος                                                                                                               |
| בדרכיו                                                                           |                      | εν τη οδω αυτου                                                                                                           |
| ילכון                                                                            |                      | πορευσεται                                                                                                                |
| ולא                                                                              |                      | και ου μη                                                                                                                 |
| יעבטון                                                                           | יעותון               | εκκλινωσιν                                                                                                                |
| ארחותם                                                                           |                      | τας τριβους αυτων                                                                                                         |
: Joel chapter 2, verse 7 { .hover tbl-colwidths="[35,30,35]"}

### Verse 8

| Masoretic text (BHS)   | Tov's retroversion                                   | Rahlf's Septuagint    |
|:-----------------------|:-----------------------------------------------------|:----------------------|
| ואיש                   |                                                      | και εκαστος           |
| אחיו                   |                                                      | απο του αδελφου αυτου |
| לא                     |                                                      | ουκ                   |
| ידחקון                 | •^[Questionable notation, equivalent, etc.] @רחק .dr | αφεξεται              |
| גבר                    | •^[Questionable notation, equivalent, etc.] כבד      | καταβαρυνομενοι       |
| במסלתו                 |                                                      | εν τοις οπλοις αυτων  |
| ילכון                  |                                                      | πορευσονται           |
| ובעד                   |                                                      | και εν                |
| השלח                   |                                                      | τοις βελεσιν αυτων    |
| יפלו                   |                                                      | πεσουνται             |
| לא                     |                                                      | και ου μη             |
| יבצעו                  |                                                      | συντελεσθωσιν         |
: Joel chapter 2, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text (BHS)                | Rahlf's Septuagint   |
|:------------------------------------|:---------------------|
| בעיר                                | της πολεως           |
| ישקו •^[Etymological exegesis.] נשק | επιλημψονται         |
| בחומה                               | και επι των τειχεων  |
| ירצון                               | δραμουνται           |
| בבתים                               | και επι τας οικιας   |
| יעלו                                | αναβησονται          |
| בעד                                 | και δια              |
| החלונים                             | θυριδων              |
| יבאו                                | εισελευσονται        |
| כגנב                                | ως κλεπται           |
: Joel chapter 2, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| לפניו                  | προ προσωπου αυτων   |
| רגזה                   | συγχυθησεται         |
| ארץ                    | η γη                 |
| רעשו                   | και σεισθησεται      |
| שמים                   | ο ουρανος            |
| שמש                    | ο ηλιος              |
| וירח                   | και η σεληνη         |
| קדרו                   | συσκοτασουσιν        |
| וכוכבים                | και τα αστρα         |
| אספו                   | δυσουσιν             |
| נגהם                   | το φεγγος αυτων      |
: Joel chapter 2, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text (BHS)                                          | Tov's retroversion   | Rahlf's Septuagint   |
|:--------------------------------------------------------------|:---------------------|:---------------------|
| ויהוה                                                         |                      | και κυριος           |
| נתן                                                           |                      | δωσει                |
| קולו                                                          |                      | φωνην αυτου          |
| לפני                                                          |                      | προ προσωπου         |
| חילו                                                          |                      | δυναμεως αυτου       |
| כי                                                            |                      | οτι                  |
| רב                                                            |                      | πολλη                |
| •^[Hebrew counterpart lacking in the LXX (minus in the LXX).] |                      | εστιν                |
| מאד                                                           |                      | σφοδρα               |
| מחנהו                                                         |                      | η παρεμβολη αυτου    |
| כי                                                            |                      | οτι                  |
| עצום                                                          |                      | ισχυρα               |
| עשה                                                           | מעשי                 | εργα                 |
| דברו                                                          |                      | λογων αυτου          |
| כי                                                            |                      | διοτι                |
| גדול                                                          |                      | μεγαλη               |
| יום                                                           |                      | η ημερα              |
| יהוה                                                          |                      | του κυριου           |
| •^[Element 'added' in the Greek (plus in the LXX).]           |                      | μεγαλη               |
| ונורא                                                         | ונראה                | και επιφανης         |
| מאד                                                           |                      | σφοδρα               |
| ומי                                                           |                      | και τις              |
| יכילנו •^[Etymological exegesis.] יכל                         |                      | εσται ικανος αυτη    |
: Joel chapter 2, verse 11 { .hover tbl-colwidths="[35,30,35]"}

### Verse 12

| Masoretic text (BHS)                                | Rahlf's Septuagint   |
|:----------------------------------------------------|:---------------------|
| וגם                                                 | και                  |
| עתה                                                 | νυν                  |
| נאם                                                 | λεγει                |
| יהוה                                                | κυριος               |
| •^[Element 'added' in the Greek (plus in the LXX).] | ο θεος υμων          |
| שבו                                                 | επιστραφητε          |
| עדי                                                 | προς με              |
| בכל                                                 | εξ ολης              |
| לבבכם                                               | της καρδιας υμων     |
| ובצום                                               | και εν νηστεια       |
| ובבכי                                               | και εν κλαυθμω       |
| ובמספד                                              | και εν κοπετω        |
: Joel chapter 2, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| וקרעו                  | και διαρρηξατε       |
| לבבכם                  | τας καρδιας υμων     |
| ואל                    | και μη               |
| בגדיכם                 | τα ιματια υμων       |
| ושובו                  | και επιστραφητε      |
| אל                     | προς                 |
| יהוה                   | κυριον               |
| אלהיכם                 | τον θεον υμων        |
| כי                     | οτι                  |
| חנון                   | ελεημων              |
| ורחום                  | και οικτιρμων        |
| הוא                    | εστιν                |
| ארך אפים               | μακροθυμος           |
| ורב חסד                | και πολυελεος        |
| ונחם                   | και μετανοων         |
| על                     | επι                  |
| הרעה                   | ταις κακιαις         |
: Joel chapter 2, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text (BHS)                                | Rahlf's Septuagint   |
|:----------------------------------------------------|:---------------------|
| מי                                                  | τις                  |
| יודע                                                | οιδεν                |
| •^[Element 'added' in the Greek (plus in the LXX).] | ει                   |
| ישוב                                                | επιστρεψει           |
| ונחם                                                | και μετανοησει       |
| והשאיר                                              | και υπολειψεται      |
| אחריו                                               | οπισω αυτου          |
| ברכה                                                | ευλογιαν             |
| מנחה                                                | θυσιαν               |
| ונסך                                                | και σπονδην          |
| ליהוה                                               | κυριω                |
| אלהיכם                                              | τω θεω ημων          |
: Joel chapter 2, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| תקעו                   | σαλπισατε            |
| שופר                   | σαλπιγγι             |
| בציון                  | εν σιων              |
| קדשו                   | αγιασατε             |
| צום                    | νηστειαν             |
| קראו                   | κηρυξατε             |
| עצרה                   | θεραπειαν            |
: Joel chapter 2, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text (BHS)   | Rahlf's Septuagint    |
|:-----------------------|:----------------------|
| אספו                   | συναγαγετε            |
| עם                     | λαον                  |
| קדשו                   | αγιασατε              |
| קהל                    | εκκλησιαν             |
| קבצו                   | εκλεξασθε             |
| זקנים                  | πρεσβυτερους          |
| אספו                   | συναγαγετε            |
| עוללים                 | νηπια                 |
| וינקי                  | θηλαζοντα             |
| שדים                   | μαστους               |
| יצא                    | εξελθατω              |
| חתן                    | νυμφιος               |
| מחדרו                  | εκ του κοιτωνος αυτου |
| וכלה                   | και νυμφη             |
| מחפתה                  | εκ του παστου αυτης   |
: Joel chapter 2, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| בין                    | ανα μεσον            |
| האולם                  | της κρηπιδος         |
| ולמזבח                 | του θυσιαστηριου     |
| יבכו                   | κλαυσονται           |
| הכהנים                 | οι ιερεις            |
| משרתי                  | οι λειτουργουντες    |
| יהוה                   | κυριω                |
| ויאמרו                 | και ερουσιν          |
| חוסה                   | φεισαι               |
| יהוה                   | κυριε                |
| על עמך                 | του λαου σου         |
| ואל                    | και μη               |
| תתן                    | δως                  |
| נחלתך                  | την κληρονομιαν σου  |
| לחרפה                  | εις ονειδος          |
| למשל                   | του καταρξαι         |
| בם                     | αυτων                |
| גוים                   | εθνη                 |
| למה                    | οπως μη              |
| יאמרו                  | ειπωσιν              |
| בעמים                  | εν τοις εθνεσιν      |
| איה                    | που εστιν            |
| אלהיהם                 | ο θεος αυτων         |
: Joel chapter 2, verse 17 { .hover tbl-colwidths="[50,50]"}

### Verse 18

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| ויקנא                  | και εζηλωσεν         |
| יהוה                   | κυριος               |
| לארצו                  | την γην αυτου        |
| ויחמל                  | και εφεισατο         |
| על עמו                 | του λαου αυτου       |
: Joel chapter 2, verse 18 { .hover tbl-colwidths="[50,50]"}

### Verse 19

| Masoretic text (BHS)                                                                    | Rahlf's Septuagint                                                                                                          |
|:----------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|
| ויען                                                                                    | και απεκριθη                                                                                                                |
| יהוה                                                                                    | κυριος                                                                                                                      |
| ויאמר                                                                                   | και ειπεν                                                                                                                   |
| לעמו                                                                                    | τω λαω αυτου                                                                                                                |
| הנני                                                                                    | ιδου εγω                                                                                                                    |
| שלח                                                                                     | εξαποστελλω                                                                                                                 |
| לכם                                                                                     | υμιν                                                                                                                        |
| את הדגן                                                                                 | τον σιτον                                                                                                                   |
| והתירוש                                                                                 | και τον οινον                                                                                                               |
| והיצהר                                                                                  | και το ελαιον                                                                                                               |
| ושבעתם                                                                                  | και εμπλησθησεσθε                                                                                                           |
| אתו                                                                                     | αυτων                                                                                                                       |
| ולא                                                                                     | και ου                                                                                                                      |
| אתן                                                                                     | δωσω                                                                                                                        |
| אתכם                                                                                    | υμας                                                                                                                        |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] לא עוד | ουκετι                                                                                                                      |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]        | εις                                                                                                                         |
| חרפה                                                                                    | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις ονειδισμον |
| בגוים                                                                                   | εν τοις εθνεσι                                                                                                              |
: Joel chapter 2, verse 19 { .hover tbl-colwidths="[50,50]"}

### Verse 20

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| ואת הצפוני             | και τον απο βορρα    |
| ארחיק                  | εκδιωξω              |
| מעליכם                 | αφ' υμων             |
| והדחתיו                | και εξωσω αυτον      |
| אל                     | εις                  |
| ארץ                    | γην                  |
| ציה                    | ανυδρον              |
| ושממה                  | και αφανιω           |
| את פניו                | το προσωπον αυτου    |
| אל                     | εις                  |
| הים                    | την θαλασσαν         |
| הקדמני                 | την πρωτην           |
| וספו                   | και τα οπισω αυτου   |
| אל                     | εις                  |
| הים                    | την θαλασσαν         |
| האחרון                 | την εσχατην          |
| ועלה                   | και αναβησεται       |
| באשו                   | η σαπρια αυτου       |
| ותעל                   | και αναβησεται       |
| צחנתו                  | ο βρομος αυτου       |
| כי                     | οτι                  |
| הגדיל                  | εμεγαλυνεν           |
| לעשות                  | τα εργα αυτου        |
: Joel chapter 2, verse 20 { .hover tbl-colwidths="[50,50]"}

### Verse 21

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| אל תיראי               | θαρσει               |
| אדמה                   | γη                   |
| גילי                   | χαιρε                |
| ושמחי                  | και ευφραινου        |
| כי                     | οτι                  |
| הגדיל                  | εμεγαλυνεν           |
| יהוה                   | κυριος               |
| לעשות                  | του ποιησαι          |
: Joel chapter 2, verse 21 { .hover tbl-colwidths="[50,50]"}

### Verse 22

| Masoretic text (BHS)                                                                                                                                   | Tov's retroversion   | Rahlf's Septuagint   |
|:-------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------|:---------------------|
| אל תיראו                                                                                                                                               |                      | θαρσειτε             |
| בהמות                                                                                                                                                  |                      | κτηνη                |
| שדי                                                                                                                                                    |                      | του πεδιου           |
| כי                                                                                                                                                     |                      | οτι                  |
| דשאו                                                                                                                                                   |                      | βεβλαστηκεν          |
| נאות                                                                                                                                                   |                      | πεδια                |
| מדבר                                                                                                                                                   |                      | της ερημου           |
| כי                                                                                                                                                     |                      | οτι                  |
| עץ                                                                                                                                                     |                      | ξυλον                |
| נשא                                                                                                                                                    |                      | ηνεγκεν              |
| פריו                                                                                                                                                   |                      | τον καρπον αυτου     |
| תאנה •^[Difference in sequence between MT and LXX, denoted after the first Hebrew word and before the second one, as well as between two Greek words.] | גפן                  | αμπελος              |
| נתנו                                                                                                                                                   |                      | εδωκαν               |
| חילם                                                                                                                                                   |                      | την ισχυν αυτων      |
: Joel chapter 2, verse 22 { .hover tbl-colwidths="[35,30,35]"}

### Verse 23

| Masoretic text (BHS)   | Tov's retroversion                                   | Rahlf's Septuagint   |
|:-----------------------|:-----------------------------------------------------|:---------------------|
| ובני                   |                                                      | και τα τεκνα         |
| ציון                   |                                                      | σιων                 |
| גילו                   |                                                      | χαιρετε              |
| ושמחו                  |                                                      | και ευφραινεσθε      |
| ביהוה                  |                                                      | επι τω κυριω         |
| אלהיכם                 |                                                      | θεω υμων             |
| כי                     |                                                      | διοτι                |
| נתן                    |                                                      | εδωκεν               |
| לכם                    |                                                      | υμιν                 |
| את המורה               | •^[Questionable notation, equivalent, etc.] את הבריה | τα βρωματα           |
| לצדקה                  |                                                      | εις δικαιοσυνην      |
| ויורד                  |                                                      | και βρεξει           |
| לכם                    |                                                      | υμιν                 |
| גשם                    |                                                      | υετον                |
| מורה                   |                                                      | προιμον              |
| ומלקוש                 |                                                      | και οψιμον           |
| בראשון                 |                                                      | καθως εμπροσθεν      |
: Joel chapter 2, verse 23 { .hover tbl-colwidths="[35,30,35]"}

### Verse 24

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| ומלאו                  | και πλησθησονται     |
| הגרנות                 | αι αλωνες            |
| בר                     | σιτου                |
| והשיקו                 | και υπερεκχυθησονται |
| היקבים                 | αι ληνοι             |
| תירוש                  | οινου                |
| ויצהר                  | και ελαιου           |
: Joel chapter 2, verse 24 { .hover tbl-colwidths="[50,50]"}

### Verse 25

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| ושלמתי                 | και ανταποδωσω       |
| לכם                    | υμιν                 |
| את                     | αντι                 |
| השנים                  | των ετων             |
| אשר                    | ων                   |
| אכל                    | κατεφαγεν            |
| הארבה                  | η ακρις              |
| הילק                   | και ο βρουχος        |
| והחסיל                 | και η ερυσιβη        |
| והגזם                  | και η καμπη          |
| חילי                   | η δυναμις μου        |
| הגדול                  | η μεγαλη             |
| אשר                    | ην                   |
| שלחתי                  | εξαπεστειλα          |
| בכם                    | εις υμας             |
: Joel chapter 2, verse 25 { .hover tbl-colwidths="[50,50]"}

### Verse 26

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| ואכלתם {!}p            | και φαγεσθε          |
| אכול {!}p              | εσθιοντες            |
| ושבוע                  | και εμπλησθησεσθε    |
| והללתם                 | και αινεσετε         |
| את שם                  | το ονομα             |
| יהוה                   | κυριου               |
| אלהיכם                 | του θεου υμων        |
| אשר                    | α                    |
| עשה                    | εποιησεν             |
| עמכם                   | μεθ' υμων            |
| להפליא                 | εις θαυμασια         |
| ולא                    | και ου μη            |
| יבשו                   | καταισχυνθη          |
| עמי                    | ο λαος μου           |
| לעולם                  | εις τον αιωνα        |
: Joel chapter 2, verse 26 { .hover tbl-colwidths="[50,50]"}

### Verse 27

| Masoretic text (BHS)                                                 | Tov's retroversion                                                                      | Rahlf's Septuagint   |
|:---------------------------------------------------------------------|:----------------------------------------------------------------------------------------|:---------------------|
| וידעתם                                                               |                                                                                         | και επιγνωσεσθε      |
| כי                                                                   |                                                                                         | οτι                  |
| בקרב                                                                 |                                                                                         | εν μεσω              |
| ישראל                                                                |                                                                                         | του ισραηλ           |
| אני                                                                  |                                                                                         | εγω ειμι             |
| ואני                                                                 |                                                                                         | και εγω              |
| יהוה                                                                 |                                                                                         | κυριος               |
| אלהיכם                                                               |                                                                                         | ο θεος υμων          |
| ואין                                                                 |                                                                                         | και ουκ εστιν        |
| עוד                                                                  |                                                                                         | ετι                  |
| •^[Element 'added' in the Greek (plus in the LXX).] =;זולתי <is45.5> |                                                                                         | πλην εμου            |
| ולא                                                                  |                                                                                         | και ου μη            |
| יבשו                                                                 |                                                                                         | καταισχυνθωσιν       |
| •^[Element 'added' in the Greek (plus in the LXX).]                  | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] לא עוד | ουκετι               |
| •^[Element 'added' in the Greek (plus in the LXX).]                  |                                                                                         | πας                  |
| עמי                                                                  |                                                                                         | ο λαος μου           |
| לעולם                                                                |                                                                                         | εις τον αιωνα        |
: Joel chapter 2, verse 27 { .hover tbl-colwidths="[35,30,35]"}

## Chapter 3

### Verse 1

| Masoretic text (BHS)                                            | Rahlf's Septuagint      |
|:----------------------------------------------------------------|:------------------------|
| והיה                                                            | και εσται               |
| אחרי כן                                                         | μετα ταυτα              |
| אשפוך                                                           | και εκχεω               |
| את רוחי •^[Difference in preposition or particle.] <nu11.17,25> | απο του πνευματος μου   |
| על                                                              | επι                     |
| כל                                                              | πασαν                   |
| בשר                                                             | σαρκα                   |
| ונבאו                                                           | και προφητευσουσιν      |
| בניכם                                                           | οι υιοι υμων            |
| ובנותיכם                                                        | και αι θυγατερες υμων   |
| זקניכם                                                          | και οι πρεσβυτεροι υμων |
| חלמות                                                           | ενυπνια                 |
| יחלמון                                                          | ενυπνιασθησονται        |
| בחוריכם                                                         | και οι νεανισκοι υμων   |
| חזינות                                                          | ορασεις                 |
| יראו                                                            | οψονται                 |
: Joel chapter 3, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text (BHS)                               | Rahlf's Septuagint    |
|:---------------------------------------------------|:----------------------|
| וגם                                                | και                   |
| על                                                 | επι                   |
| העבדים                                             | τους δουλους          |
| ועל                                                | και επι               |
| השפחות                                             | τας δουλας            |
| בימים                                              | εν ταις ημεραις       |
| ההמה                                               | εκειναις              |
| אשפוך                                              | εκχεω                 |
| את רוחי •^[Difference in preposition or particle.] | απο του πνευματος μου |
: Joel chapter 3, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| ונתתי                  | και δωσω             |
| מופתים                 | τερατα               |
| בשמים                  | εν τω ουρανω         |
| ובארץ                  | και επι της γης      |
| דם                     | αιμα                 |
| ואש                    | και πυρ              |
| ותימרות                | και ατμιδα           |
| עשן                    | καπνου               |
: Joel chapter 3, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| השמש                   | ο ηλιος              |
| יהפך                   | μεταστραφησεται      |
| לחשך                   | εις σκοτος           |
| והירח                  | και η σεληνη         |
| לדם                    | εις αιμα             |
| לפני                   | πριν                 |
| בוא                    | ελθειν               |
| יום                    | ημεραν               |
| יהוה                   | κυριου               |
| הגדול                  | την μεγαλην          |
| והנורא                 | και επιφανη          |
: Joel chapter 3, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text (BHS)                    | Rahlf's Septuagint   |
|:----------------------------------------|:---------------------|
| והיה                                    | και εσται            |
| כל                                      | πας                  |
| אשר                                     | ος αν                |
| יקרא                                    | επικαλεσηται         |
| בשם                                     | το ονομα             |
| יהוה                                    | κυριου               |
| ימלט                                    | σωθησεται            |
| כי                                      | οτι                  |
| בהר                                     | εν τω ορει           |
| ציון                                    | σιων                 |
| ובירושלם                                | και εν ιερουσαλημ    |
| תהיה                                    | εσται                |
| פליטה                                   | ανασωζομενος         |
| כאשר                                    | καθοτι               |
| אמר                                     | ειπεν                |
| יהוה                                    | κυριος               |
| ובשרידים •^[Etymological exegesis.] בשר | και ευαγγελιζομενοι  |
| אשר                                     | ους                  |
| יהוה                                    | κυριος               |
| קרא                                     | προσκεκληται         |
: Joel chapter 3, verse 5 { .hover tbl-colwidths="[50,50]"}

## Chapter 4

### Verse 1

| Masoretic text (BHS)                                    | Rahlf's Septuagint   |
|:--------------------------------------------------------|:---------------------|
| כי                                                      | διοτι                |
| הנה •^[Element 'added' in the Greek (plus in the LXX).] | ιδου εγω             |
| בימים                                                   | εν ταις ημεραις      |
| ההמה                                                    | εκειναις             |
| ובעת                                                    | και εν τω καιρω      |
| ההיא                                                    | εκεινω               |
| אשר                                                     | οταν                 |
| *אשוב **אשיב •^[Agreement of LXX with qere.]            | επιστρεψω            |
| את שבות                                                 | την αιχμαλωσιαν      |
| יהודה                                                   | ιουδα                |
| וירושלם                                                 | και ιερουσαλημ       |
: Joel chapter 4, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text (BHS)   | Rahlf's Septuagint      |
|:-----------------------|:------------------------|
| וקבצתי                 | και συναξω              |
| את כל                  | παντα                   |
| הגוים                  | τα εθνη                 |
| והורדתים               | και καταξω αυτα         |
| אל                     | εις                     |
| עמק                    | την κοιλαδα             |
| יהושפט                 | ιωσαφατ                 |
| ונשפטתי                | και διακριθησομαι       |
| עמם                    | προς αυτους             |
| שם                     | εκει                    |
| על                     | υπερ                    |
| עמי                    | του λαου μου            |
| ונחלתי                 | και της κληρονομιας μου |
| ישראל                  | ισραηλ                  |
| אשר                    | οι                      |
| פזרו                   | διεσπαρησαν             |
| בגוים                  | εν τοις εθνεσιν         |
| ואת ארצי               | και την γην μου         |
| חלקו                   | καταδιειλαντο           |
: Joel chapter 4, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| ואל                    | και επι              |
| עמי                    | τον λαον μου         |
| ידו                    | εβαλον               |
| גורל                   | κληρους              |
| ויתנו                  | και εδωκαν           |
| הילד                   | τα παιδαρια          |
| בזונה                  | πορναις              |
| והילדה                 | και τα κορασια       |
| מכרו                   | επωλουν              |
| ביין                   | αντι οινου           |
| וישתו                  | και επινον           |
: Joel chapter 4, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| וגם                    | και                  |
| מה                     | τι                   |
| אתם                    | και υμεις            |
| לי                     | εμοι                 |
| צר                     | τυρος                |
| וצידון                 | και σιδων            |
| וכל                    | και πασα             |
| גלילות                 | γαλιλαια             |
| פלשת                   | αλλοφυλων            |
| הגמול                  | μη ανταποδομα        |
| אתם                    | υμεις                |
| משלמים                 | ανταποδιδοτε         |
| עלי                    | μοι                  |
| ואם                    | η                    |
| גמלים                  | μνησικακειτε         |
| אתם                    | υμεις                |
| עלי                    | επ' εμοι             |
| קל                     | οξεως                |
| מהרה                   | και ταχεως           |
| אשיב                   | ανταποδωσω           |
| גמלכם                  | το ανταποδομα υμων   |
| בראשכם                 | εις κεφαλας υμων     |
: Joel chapter 4, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| אשר                    | ανθ' ων              |
| כספי                   | το αργυριον μου      |
| וזהבי                  | και το χρυσιον μου   |
| לקחתם                  | ελαβετε              |
| ומחמדי                 | και τα επιλεκτα μου  |
| הטבים                  | και τα καλα          |
| הבאתם                  | εισηνεγκατε          |
| להיכליכם               | εις τους ναους υμων  |
: Joel chapter 4, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| ובני                   | και τους υιους       |
| יהודה                  | ιουδα                |
| ובני                   | και τους υιους       |
| ירושלם                 | ιερουσαλημ           |
| מכרתם                  | απεδοσθε             |
| לבני                   | τοις υιοις           |
| היונים                 | των ελληνων          |
| למען                   | οπως                 |
| הרחיקם                 | εξωσητε αυτους       |
| מעל                    | εκ                   |
| גבולם                  | των οριων αυτων      |
: Joel chapter 4, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| הנני                   | ιδου εγω             |
| מעירם                  | εξεγειρω αυτους      |
| מן                     | εκ                   |
| המקום                  | του τοπου            |
| אשר                    | ου                   |
| מכרתם                  | απεδοσθε             |
| אתם                    | αυτους               |
| שמה                    | εκει                 |
| והשבתי                 | και ανταποδωσω       |
| גמלכם                  | το ανταποδομα υμων   |
| בראשכם                 | εις κεφαλας υμων     |
: Joel chapter 4, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text (BHS)                                                                | Rahlf's Septuagint     |
|:------------------------------------------------------------------------------------|:-----------------------|
| ומכרתי                                                                              | και αποδωσομαι         |
| את בניכם                                                                            | τους υιους υμων        |
| ואת בנותיכם                                                                         | και τας θυγατερας υμων |
| ביד                                                                                 | εις χειρας             |
| בני                                                                                 | υιων                   |
| יהודה                                                                               | ιουδα                  |
| ומכרום                                                                              | και αποδωσονται αυτους |
| לשבאים •^[Etymological exegesis.] שבה •^[Difference in vocalization (reading).] .א- | εις αιχμαλωσιαν        |
| אל                                                                                  | εις                    |
| גוי                                                                                 | εθνος                  |
| רחוק                                                                                | μακραν απεχον          |
| כי                                                                                  | οτι                    |
| יהוה                                                                                | κυριος                 |
| דבר                                                                                 | ελαλησεν               |
: Joel chapter 4, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| קראו                   | κηρυξατε             |
| זאת                    | ταυτα                |
| בגוים                  | εν τοις εθνεσιν      |
| קדשו                   | αγιασατε             |
| מלחמה                  | πολεμον              |
| העירו                  | εξεγειρατε           |
| הגבורים                | τους μαχητας         |
| יגשו                   | προσαγαγετε          |
| יעלו                   | και αναβαινετε       |
| כל                     | παντες               |
| אנשי                   | ανδρες               |
| המלחמה                 | πολεμισται           |
: Joel chapter 4, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text (BHS)                                | Rahlf's Septuagint   |
|:----------------------------------------------------|:---------------------|
| כתו                                                 | συγκοψατε            |
| אתיכם                                               | τα αροτρα υμων       |
| לחרבות                                              | εις ρομφαιας         |
| ומזמרתיכם                                           | και τα δρεπανα υμων  |
| לרמחים                                              | εις σειρομαστας      |
| החלש                                                | ο αδυνατος           |
| יאמר                                                | λεγετω               |
| •^[Element 'added' in the Greek (plus in the LXX).] | οτι                  |
| גבור                                                | ισχυω                |
| אני                                                 | εγω                  |
: Joel chapter 4, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text (BHS)   | Tov's retroversion                             | Rahlf's Septuagint   |
|:-----------------------|:-----------------------------------------------|:---------------------|
| עושו                   |                                                | συναθροιζεσθε        |
| ובאו                   |                                                | και εισπορευεσθε     |
| כל                     |                                                | παντα                |
| הגוים                  |                                                | τα εθνη              |
| מסביב                  |                                                | κυκλοθεν             |
| ונקבצו                 |                                                | και συναχθητε        |
| שמה                    |                                                | εκει                 |
| הנחת                   | הנחת •^[Difference in vocalization (reading).] | ο πραυς              |
| יהוה                   | יהיה .wy                                       | εστω                 |
| גבוריך                 |                                                | μαχητης              |
: Joel chapter 4, verse 11 { .hover tbl-colwidths="[35,30,35]"}

### Verse 12

| Masoretic text (BHS)                                | Rahlf's Septuagint   |
|:----------------------------------------------------|:---------------------|
| יעורו                                               | εξεγειρεσθωσαν       |
| ויעלו                                               | και αναβαινετωσαν    |
| •^[Element 'added' in the Greek (plus in the LXX).] | παντα                |
| הגוים                                               | τα εθνη              |
| אל                                                  | εις                  |
| עמק                                                 | την κοιλαδα          |
| יהושפט                                              | ιωσαφατ              |
| כי                                                  | διοτι                |
| שם                                                  | εκει                 |
| אשב                                                 | καθιω                |
| לשפט                                                | του διακριναι        |
| את כל                                               | παντα                |
| הגוים                                               | τα εθνη              |
| מסביב                                               | κυκλοθεν             |
: Joel chapter 4, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text (BHS)   | Tov's retroversion                                                                                                      | Rahlf's Septuagint   |
|:-----------------------|:------------------------------------------------------------------------------------------------------------------------|:---------------------|
| שלחו                   |                                                                                                                         | εξαποστειλατε        |
| מגל                    |                                                                                                                         | δρεπανα              |
| כי                     |                                                                                                                         | οτι                  |
| בשל                    |                                                                                                                         | παρεστηκεν           |
| קציר                   |                                                                                                                         | τρυγητος             |
| באו                    |                                                                                                                         | εισπορευεσθε         |
| רדו                    | דרכו •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (interchange of R/D, etc.)] | πατειτε              |
| כי                     |                                                                                                                         | διοτι                |
| מלאה                   |                                                                                                                         | πληρης               |
| גת                     |                                                                                                                         | η ληνος              |
| השיקו                  |                                                                                                                         | υπερεκχειται         |
| היקבים                 |                                                                                                                         | τα υποληνια          |
| כי                     |                                                                                                                         | οτι                  |
| רבה                    |                                                                                                                         | πεπληθυνται          |
| רעתם                   |                                                                                                                         | τα κακα αυτων        |
: Joel chapter 4, verse 13 { .hover tbl-colwidths="[35,30,35]"}

### Verse 14

| Masoretic text (BHS)                  | Rahlf's Septuagint   |
|:--------------------------------------|:---------------------|
| המונים •^[Etymological exegesis.] המה | ηχοι                 |
| המונים •^[Etymological exegesis.] המה | εξηχησαν             |
| בעמק                                  | εν τη κοιλαδι        |
| החרוץ                                 | της δικης            |
| כי                                    | οτι                  |
| קרוב                                  | εγγυς                |
| יום                                   | ημερα                |
| יהוה                                  | κυριου               |
| בעמק                                  | εν τη κοιλαδι        |
| החרוץ                                 | της δικης            |
: Joel chapter 4, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| שמש                    | ο ηλιος              |
| וירח                   | και η σεληνη         |
| קדרו                   | συσκοτασουσιν        |
| וכוכבים                | και οι αστερες       |
| אספו                   | δυσουσιν             |
| נגהם                   | φεγγος αυτων         |
: Joel chapter 4, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text (BHS)                                | Rahlf's Septuagint                                                                                                                                            |
|:----------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ויהוה                                               | ο •^[Difference in sequence between MT and LXX, denoted after the first Hebrew word and before the second one, as well as between two Greek words.] δε κυριος |
| מציון                                               | εκ σιων                                                                                                                                                       |
| ישאג                                                | ανακεκραξεται                                                                                                                                                 |
| ומירושלם                                            | και εξ ιερουσαλημ                                                                                                                                             |
| יתן                                                 | δωσει                                                                                                                                                         |
| קולו                                                | φωνην αυτου                                                                                                                                                   |
| ורעשו                                               | και σεισθησεται                                                                                                                                               |
| שמים                                                | ο ουρανος                                                                                                                                                     |
| וארץ                                                | και η γη                                                                                                                                                      |
| ויהוה                                               | ο •^[Difference in sequence between MT and LXX, denoted after the first Hebrew word and before the second one, as well as between two Greek words.] δε κυριος |
| מחסה •^[Etymological exegesis.] חוס                 | φεισεται                                                                                                                                                      |
| לעמו                                                | του λαου αυτου                                                                                                                                                |
| ומעוז                                               | και ενισχυσει                                                                                                                                                 |
| •^[Element 'added' in the Greek (plus in the LXX).] | κυριος                                                                                                                                                        |
| לבני                                                | τους υιους                                                                                                                                                    |
| ישראל                                               | ισραηλ                                                                                                                                                        |
: Joel chapter 4, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text (BHS)                                                                    | Rahlf's Septuagint   |
|:----------------------------------------------------------------------------------------|:---------------------|
| וידעתם                                                                                  | και επιγνωσεσθε      |
| כי                                                                                      | διοτι                |
| אני                                                                                     | εγω                  |
| יהוה                                                                                    | κυριος               |
| אלהיכם                                                                                  | ο θεος υμων          |
| שכן                                                                                     | ο κατασκηνων         |
| בציון                                                                                   | εν σιων              |
| •^[Notation in Hebrew column of elements repeated in the translation.] ב הר             | εν ορει              |
| קדשי                                                                                    | αγιω μου             |
| והיתה                                                                                   | και εσται            |
| ירושלם                                                                                  | ιερουσαλημ           |
| •^[Element 'added' in the Greek (plus in the LXX).]                                     | πολις                |
| קדש                                                                                     | αγια                 |
| וזרים                                                                                   | και αλλογενεις       |
| לא                                                                                      | ου                   |
| יעברו                                                                                   | διελευσονται         |
| בה                                                                                      | δι' αυτης            |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] לא עוד | ουκετι               |
: Joel chapter 4, verse 17 { .hover tbl-colwidths="[50,50]"}

### Verse 18

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| והיה                   | και εσται            |
| ביום                   | εν τη ημερα          |
| ההוא                   | εκεινη               |
| יטפו                   | αποσταλαξει          |
| ההרים                  | τα ορη               |
| עסיס                   | γλυκασμον            |
| והגבעות                | και οι βουνοι        |
| תלכנה                  | ρυησονται            |
| חלב                    | γαλα                 |
| וכל                    | και πασαι            |
| אפיקי                  | αι αφεσεις           |
| יהודה                  | ιουδα                |
| ילכו                   | ρυησονται            |
| מים                    | υδατα                |
| ומעין                  | και πηγη             |
| מבית                   | εξ οικου             |
| יהוה                   | κυριου               |
| יצא                    | εξελευσεται          |
| והשקה                  | και ποτιει           |
| את נחל                 | τον χειμαρρουν       |
| השטים                  | των σχοινων          |
: Joel chapter 4, verse 18 { .hover tbl-colwidths="[50,50]"}

### Verse 19

| Masoretic text (BHS)   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|
| מצרים                  | αιγυπτος             |
| לשממה                  | εις αφανισμον        |
| תהיה                   | εσται                |
| ואדום                  | και η ιδουμαια       |
| למדבר                  | εις πεδιον           |
| שממה                   | αφανισμου            |
| תהיה                   | εσται                |
| מחמס                   | εξ αδικιων           |
| בני                    | υιων                 |
| יהודה                  | ιουδα                |
| אשר                    | ανθ' ων              |
| שפכו                   | εξεχεαν              |
| דם                     | αιμα                 |
| נקיא                   | δικαιον              |
| בארצם                  | εν τη γη αυτων       |
: Joel chapter 4, verse 19 { .hover tbl-colwidths="[50,50]"}

### Verse 20

| Masoretic text (BHS)   | Rahlf's Septuagint                                                                                                                                             |
|:-----------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ויהודה                 | η •^[Difference in sequence between MT and LXX, denoted after the first Hebrew word and before the second one, as well as between two Greek words.] δε ιουδαια |
| לעולם                  | εις τον αιωνα                                                                                                                                                  |
| תשב                    | κατοικηθησεται                                                                                                                                                 |
| וירושלם                | και ιερουσαλημ                                                                                                                                                 |
| לדור                   | εις γενεας                                                                                                                                                     |
| ודור                   | γενεων                                                                                                                                                         |
: Joel chapter 4, verse 20 { .hover tbl-colwidths="[50,50]"}

### Verse 21

| Masoretic text (BHS)   | Tov's retroversion   | Rahlf's Septuagint   |
|:-----------------------|:---------------------|:---------------------|
| ונקיתי                 | ונקמתי .ym           | και εκδικησω         |
| דמם                    |                      | το αιμα αυτων        |
| לא                     |                      | και ου μη            |
| נקיתי                  |                      | αθωωσω               |
| ויהוה                  |                      | και κυριος           |
| שכן                    |                      | κατασκηνωσει         |
| בציון                  |                      | εν σιων              |
: Joel chapter 4, verse 21 { .hover tbl-colwidths="[35,30,35]"}

