# Joshua (Alexandrinus)

The tables below show the Hebrew and Greek texts aligned vertically. When a Hebrew verse number does not match the Greek counterpart, the editors added a note with the corresponding verse number between square brackets.

## Chapter 15

### Verse 21

| Masoretic text                                                               | Septuagint                     |
|:-----------------------------------------------------------------------------|:-------------------------------|
| ויהיו                                                                        | εγενηθησαν δε                  |
| הערים                                                                        | αι πολεις αυτων                |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [πολις]{.potential-difference} |
| מקצה                                                                         | πρωτη                          |
| למטה                                                                         | φυλης                          |
| בני                                                                          | υιων                           |
| יהודה                                                                        | ιουδα                          |
| אל                                                                           | εφ'                            |
| גבול                                                                         | οριων                          |
| אדום                                                                         | εδωμ                           |
| בנגבה                                                                        | επι της ερημου                 |
| קבצאל                                                                        | καβσεηλ                        |
| ועדר                                                                         | και εδραι                      |
| ויגור                                                                        | και ιαγουρ                     |
: Joshua (Alexandrinus) chapter 15, verse 21 { .hover tbl-colwidths="[50,50]"}

### Verse 22

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| וקינה            | και κινα     |
| ודימונה          | και διμωνα   |
| ועדעדה           | και αδαδα    |
: Joshua (Alexandrinus) chapter 15, verse 22 { .hover tbl-colwidths="[50,50]"}

### Verse 23

| Masoretic text                 | Septuagint                                                                             |
|:-------------------------------|:---------------------------------------------------------------------------------------|
| וקדש                           | και κεδες                                                                              |
| [וחצור]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ויתנן זיף                      | και ιθναζιφ [24]                                                                       |
: Joshua (Alexandrinus) chapter 15, verse 23 { .hover tbl-colwidths="[50,50]"}

### Verse 24

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| וטלם             | και τελεμ    |
| ובעלות           | και βαλωθ    |
: Joshua (Alexandrinus) chapter 15, verse 24 { .hover tbl-colwidths="[50,50]"}

### Verse 25

| Masoretic text                 | Septuagint                                                                             |
|:-------------------------------|:---------------------------------------------------------------------------------------|
| [וחצור]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [חדתה]{.potential-difference}  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| וקריות                         | και πολις                                                                              |
| חצרון                          | ασερων                                                                                 |
| היא                            | αυτη                                                                                   |
| חצור                           | ασωρ                                                                                   |
: Joshua (Alexandrinus) chapter 15, verse 25 { .hover tbl-colwidths="[50,50]"}

### Verse 26

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| אמם              | αμαμ         |
| ושמע             | και σαμαα    |
| ומולדה           | και μωλαδα   |
: Joshua (Alexandrinus) chapter 15, verse 26 { .hover tbl-colwidths="[50,50]"}

### Verse 27

| Masoretic text                  | Septuagint                                                                             |
|:--------------------------------|:---------------------------------------------------------------------------------------|
| וחצר גדה                        | και ασεργαδδα                                                                          |
| [וחשמון]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ובית פלט                        | και βαιθφαλεθ                                                                          |
: Joshua (Alexandrinus) chapter 15, verse 27 { .hover tbl-colwidths="[50,50]"}

### Verse 28

| Masoretic text                                                                                 | Septuagint                                     |
|:-----------------------------------------------------------------------------------------------|:-----------------------------------------------|
| וחצר שועל                                                                                      | και ασαρσουλα                                  |
| ובאר שבע                                                                                       | και βηρσαβεε                                   |
| ובזיותיה =;ובנותיהן <15.45>                                                                    | και αι κωμαι αυτων                             |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;וחצריהן <15.45>]{.potential-difference} | [και αι επαυλεις αυτων]{.potential-difference} |
: Joshua (Alexandrinus) chapter 15, verse 28 { .hover tbl-colwidths="[50,50]"}

### Verse 29

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| בעלה             | βααλα        |
| ועיים            | και αυιμ     |
| ועצם             | και ασεμ     |
: Joshua (Alexandrinus) chapter 15, verse 29 { .hover tbl-colwidths="[50,50]"}

### Verse 30

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ואלתולד          | και ελθωδαδ  |
| וכסיל            | και χασιλ    |
| וחרמה            | και ερμα     |
: Joshua (Alexandrinus) chapter 15, verse 30 { .hover tbl-colwidths="[50,50]"}

### Verse 31

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| וצקלג            | και σικελεγ  |
| ומדמנה           | και μεδεβηνα |
| וסנסנה           | και σανσαννα |
: Joshua (Alexandrinus) chapter 15, verse 31 { .hover tbl-colwidths="[50,50]"}

### Verse 32

| Masoretic text                | Septuagint                                                                             |
|:------------------------------|:---------------------------------------------------------------------------------------|
| ולבאות                        | και λαβωθ                                                                              |
| ושלחים                        | και σελειμ                                                                             |
| [ועין]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ורמון                         | και ρεμμων                                                                             |
| [כל]{.potential-difference}   | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ערים                          | πολεις                                                                                 |
| עשרים ותשע                    | εικοσι και εννεα                                                                       |
| וחצריהן                       | και αι κωμαι αυτων                                                                     |
: Joshua (Alexandrinus) chapter 15, verse 32 { .hover tbl-colwidths="[50,50]"}

### Verse 33

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| בשפלה            | εν τη πεδινη |
| אשתאול           | εσθαολ       |
| וצרעה            | και σαραα    |
| ואשנה            | και ασνα     |
: Joshua (Alexandrinus) chapter 15, verse 33 { .hover tbl-colwidths="[50,50]"}

### Verse 34

| Masoretic text                                                               | Septuagint                                                                             |
|:-----------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [και ραμεν]{.potential-difference}                                                     |
| וזנוח                                                                        | και ζανω                                                                               |
| ועין גנים                                                                    | και αδιαθαιμ                                                                           |
| [תפוח]{.potential-difference}                                                | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| והעינם                                                                       | και ηναιμ                                                                              |
: Joshua (Alexandrinus) chapter 15, verse 34 { .hover tbl-colwidths="[50,50]"}

### Verse 35

| Masoretic text                                                               | Septuagint                         |
|:-----------------------------------------------------------------------------|:-----------------------------------|
| ירמות                                                                        | και ιεριμουθ                       |
| ועדלם                                                                        | και οδολλαμ                        |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [και νεμρα]{.potential-difference} |
| שוכה                                                                         | και σωχω                           |
| ועזקה                                                                        | και αζηκα                          |
: Joshua (Alexandrinus) chapter 15, verse 35 { .hover tbl-colwidths="[50,50]"}

### Verse 36

| Masoretic text                                                                                | Septuagint                                                                             |
|:----------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| ושערים                                                                                        | και σαργαριμ                                                                           |
| [ועדיתים]{.potential-difference}                                                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| והגדרה                                                                                        | και γαδηρα                                                                             |
| [וגדרתים]{.potential-difference}                                                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;וחצריה <15.45>]{.potential-difference} | [και αι επαυλεις αυτης]{.potential-difference}                                         |
| ערים                                                                                          | πολεις                                                                                 |
| ארבע עשרה                                                                                     | δεκα τεσσαρες                                                                          |
| וחצריהן                                                                                       | και αι κωμαι αυτων                                                                     |
: Joshua (Alexandrinus) chapter 15, verse 36 { .hover tbl-colwidths="[50,50]"}

### Verse 37

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| צנן              | σενναν        |
| וחדשה            | και αδασα     |
| ומגדל גד         | και μαγδαλγαδ |
: Joshua (Alexandrinus) chapter 15, verse 37 { .hover tbl-colwidths="[50,50]"}

### Verse 38

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ודלען            | και δαλααν   |
| והמצפה           | και μασφα    |
| ויקתאל           | και ιεχθαηλ  |
: Joshua (Alexandrinus) chapter 15, verse 38 { .hover tbl-colwidths="[50,50]"}

### Verse 39

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| לכיש             | και λαχις    |
| ובצקת            | και βαζκαθ   |
| ועגלון           | και αγλων    |
: Joshua (Alexandrinus) chapter 15, verse 39 { .hover tbl-colwidths="[50,50]"}

### Verse 40

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| וכבון            | και χαββα    |
| ולחמס            | και λαμας    |
| וכתליש           | και χαθλως   |
: Joshua (Alexandrinus) chapter 15, verse 40 { .hover tbl-colwidths="[50,50]"}

### Verse 41

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| וגדרות           | και γαδηρωθ        |
| בית דגון         | και βηθδαγων       |
| ונעמה            | και νωμα           |
| ומקדה            | και μακηδα         |
| ערים             | πολεις             |
| שש עשרה          | δεκαεξ             |
| וחצריהן          | και αι κωμαι αυτων |
: Joshua (Alexandrinus) chapter 15, verse 41 { .hover tbl-colwidths="[50,50]"}

### Verse 42

| Masoretic text                | Septuagint                                                                             |
|:------------------------------|:---------------------------------------------------------------------------------------|
| לבנה                          | λεβνα                                                                                  |
| ועתר                          | και αθερ                                                                               |
| [ועשן]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
: Joshua (Alexandrinus) chapter 15, verse 42 { .hover tbl-colwidths="[50,50]"}

### Verse 43

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ויפתח            | και ιεφθα    |
| ואשנה            | και ασεννα   |
| ונציב            | και νεσιβ    |
: Joshua (Alexandrinus) chapter 15, verse 43 { .hover tbl-colwidths="[50,50]"}

### Verse 44

| Masoretic text                                                               | Septuagint                        |
|:-----------------------------------------------------------------------------|:----------------------------------|
| וקעילה                                                                       | και κειλα                         |
| ואכזיב                                                                       | και αχζιβ                         |
| ומראשה                                                                       | και μαρησα                        |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [και εδωμ]{.potential-difference} |
| ערים                                                                         | πολεις                            |
| תשע                                                                          | εννεα                             |
| וחצריהן                                                                      | και αι κωμαι αυτων                |
: Joshua (Alexandrinus) chapter 15, verse 44 { .hover tbl-colwidths="[50,50]"}

### Verse 45

| Masoretic text   | Septuagint            |
|:-----------------|:----------------------|
| עקרון            | ακκαρων               |
| ובנתיה           | και αι κωμαι αυτης    |
| וחצריה           | και αι επαυλεις αυτης |
: Joshua (Alexandrinus) chapter 15, verse 45 { .hover tbl-colwidths="[50,50]"}

### Verse 46

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| מעקרון           | και απο ακκαρων    |
| וימה             | ιεμναι             |
| כל               | και πασαι          |
| אשר              | οσαι εισιν         |
| על יד            | πλησιον            |
| אשדוד            | ασδωδ              |
| וחצריהן          | και αι κωμαι αυτων |
: Joshua (Alexandrinus) chapter 15, verse 46 { .hover tbl-colwidths="[50,50]"}

### Verse 47

| Masoretic text                                 | Septuagint                                                                                   |
|:-----------------------------------------------|:---------------------------------------------------------------------------------------------|
| [אשדוד]{.potential-difference}                 | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}       |
| [בנותיה]{.potential-difference}                | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] αυτης]{.potential-difference} |
| וחצריה                                         | και αι επαυλεις αυτης                                                                        |
| עזה                                            | γαζα                                                                                         |
| בנותיה                                         | και αι κωμαι αυτης                                                                           |
| וחצריה                                         | και αι επαυλεις αυτης                                                                        |
| עד                                             | εως                                                                                          |
| נחל                                            | του χειμαρρου                                                                                |
| מצרים                                          | αιγυπτου                                                                                     |
| והים                                           | και η θαλασσα                                                                                |
| *הגבול **הגדול •^[Agreement of LXX with qere.] | η μεγαλη                                                                                     |
| וגבול                                          | διοριζει                                                                                     |
: Joshua (Alexandrinus) chapter 15, verse 47 { .hover tbl-colwidths="[50,50]"}

### Verse 48

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| ובהר             | και εν τη ορεινη |
| שמיר             | σαφιρ            |
| ויתיר            | και ιεθερ        |
| ושוכה            | και σωχω         |
: Joshua (Alexandrinus) chapter 15, verse 48 { .hover tbl-colwidths="[50,50]"}

### Verse 49

| Masoretic text                | Tov's retroversion                                                                                                                               | Septuagint                         |
|:------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------|
| [ודנה]{.potential-difference} | [ורנה •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (interchange of R/D, etc.)]]{.potential-difference} | [και ρεννα]{.potential-difference} |
| וקרית                         |                                                                                                                                                  | πολις                              |
| [סנה]{.potential-difference}  | [ספר]{.potential-difference}                                                                                                                     | [γραμματων]{.potential-difference} |
| היא                           |                                                                                                                                                  | αυτη εστιν                         |
| דבר                           |                                                                                                                                                  | δαβιρ                              |
: Joshua (Alexandrinus) chapter 15, verse 49 { .hover tbl-colwidths="[35,30,35]"}

### Verse 50

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| וענב             | και ανωβ     |
| ואשתמה           | και εσθεμω   |
| וענים            | και ανιμ     |
: Joshua (Alexandrinus) chapter 15, verse 50 { .hover tbl-colwidths="[50,50]"}

### Verse 51

| Masoretic text                                                                      | Septuagint                    |
|:------------------------------------------------------------------------------------|:------------------------------|
| וגשן                                                                                | και γοσομ                     |
| וחלן                                                                                | και χιλουων                   |
| וגלה                                                                                | και γηλων                     |
| ערים                                                                                | πολεις                        |
| [אחת עשרה •^[Difference in numbers between MT and the LXX.]]{.potential-difference} | [δεκα]{.potential-difference} |
| וחצריהן                                                                             | και αι κωμαι αυτων            |
: Joshua (Alexandrinus) chapter 15, verse 51 { .hover tbl-colwidths="[50,50]"}

### Verse 52

| Masoretic text                 | Tov's retroversion             | Septuagint                         |
|:-------------------------------|:-------------------------------|:-----------------------------------|
| ארב                            |                                | ερεβ                               |
| [ורומה]{.potential-difference} | [ואשען]{.potential-difference} | [και εσαν]{.potential-difference}  |
| [ואשען]{.potential-difference} | [ורומה]{.potential-difference} | [και ρουμα]{.potential-difference} |
: Joshua (Alexandrinus) chapter 15, verse 52 { .hover tbl-colwidths="[35,30,35]"}

### Verse 53

| Masoretic text                                 | Septuagint      |
|:-----------------------------------------------|:----------------|
| *וינים **וינום •^[Agreement of LXX with qere.] | και ιανουμ      |
| ובית תפוח                                      | και βαιθθαπφουε |
| ואפקה                                          | και αφακα       |
: Joshua (Alexandrinus) chapter 15, verse 53 { .hover tbl-colwidths="[50,50]"}

### Verse 54

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| וחמטה            | και χαμματα        |
| וקרית ארבע       | και πολις αρβο     |
| היא              | αυτη εστιν         |
| חברון            | χεβρων             |
| וציער            | και σιωρ           |
| ערים             | πολεις             |
| תשע              | εννεα              |
| וחצריהן          | και αι κωμαι αυτων |
: Joshua (Alexandrinus) chapter 15, verse 54 { .hover tbl-colwidths="[50,50]"}

### Verse 55

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| מעון             | μαων         |
| כרמל             | και χερμελ   |
| וזיף             | και ζιφ      |
| ויוטה            | και ιεττα    |
: Joshua (Alexandrinus) chapter 15, verse 55 { .hover tbl-colwidths="[50,50]"}

### Verse 56

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| ויזרעאל          | και ιεζραελ       |
| ויקדעם           | και ιεκδααμ       |
| וזנוח הקין       | και ζανωακιμ [57] |
: Joshua (Alexandrinus) chapter 15, verse 56 { .hover tbl-colwidths="[50,50]"}

### Verse 57

| Masoretic text                                                                 | Septuagint                     |
|:-------------------------------------------------------------------------------|:-------------------------------|
| גבעה                                                                           | και γαβαα                      |
| ותמנה                                                                          | και θαμνα                      |
| ערים                                                                           | πολεις                         |
| [עשר •^[Difference in numbers between MT and the LXX.]]{.potential-difference} | [εννεα]{.potential-difference} |
| וחצריהן                                                                        | και αι κωμαι αυτων             |
: Joshua (Alexandrinus) chapter 15, verse 57 { .hover tbl-colwidths="[50,50]"}

### Verse 58

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| חלחול            | αλουλ        |
| בית צור          | και βαιθσουρ |
| וגדור            | και γεδωρ    |
: Joshua (Alexandrinus) chapter 15, verse 58 { .hover tbl-colwidths="[50,50]"}

### Verse 59

| Masoretic text                                                                                                             | Septuagint                                  |
|:---------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------|
| ומערת                                                                                                                      | και μαρωθ                                   |
| ובית ענות                                                                                                                  | και βαιθανωθ                                |
| ואלתקן                                                                                                                     | και ελθεκεν                                 |
| ערים                                                                                                                       | πολεις                                      |
| שש                                                                                                                         | εξ                                          |
| וחצריהן                                                                                                                    | και αι κωμαι αυτων                          |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [θεκω]{.potential-difference}               |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και εφραθα]{.potential-difference}         |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [αυτη εστιν]{.potential-difference}         |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [βηθλεεμ]{.potential-difference}            |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και φαγωρ]{.potential-difference}          |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και αιταμ]{.potential-difference}          |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και κουλον]{.potential-difference}         |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και ταταμι]{.potential-difference}         |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και σωρης]{.potential-difference}          |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και καρεμ]{.potential-difference}          |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και γαλλιμ]{.potential-difference}         |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και βαιθηρ]{.potential-difference}         |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και μανοχω]{.potential-difference}         |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [πολεις]{.potential-difference}             |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [ενδεκα]{.potential-difference}             |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} | [και αι κωμαι αυτων]{.potential-difference} |
: Joshua (Alexandrinus) chapter 15, verse 59 { .hover tbl-colwidths="[50,50]"}

### Verse 60

| Masoretic text                                                                                  | Septuagint                                                                             |
|:------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| קרית בעל                                                                                        | καριαθβααλ                                                                             |
| [היא]{.potential-difference}                                                                    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [קרית]{.potential-difference}                                                                   | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [יערים]{.potential-difference}                                                                  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| והרבה                                                                                           | και απεββα                                                                             |
| ערים                                                                                            | πολεις                                                                                 |
| שתים                                                                                            | δυο                                                                                    |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;ובנותיהן <15.45>]{.potential-difference} | [και αι κωμαι αυτων]{.potential-difference}                                            |
| וחצריהן                                                                                         | και αι επαυλεις αυτων                                                                  |
: Joshua (Alexandrinus) chapter 15, verse 60 { .hover tbl-colwidths="[50,50]"}

### Verse 61

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| במדבר            | βαδδαργις    |
| בית הערבה        | και βηθαραβα |
| מדין             | και μαδων    |
| וסככה            | και σοχοχα   |
: Joshua (Alexandrinus) chapter 15, verse 61 { .hover tbl-colwidths="[50,50]"}

### Verse 62

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| והנבשן           | και νεβσαν         |
| ועיר             | και αι πολεις      |
| המלח             | αλων               |
| ועין גדי         | και ηνγαδδι        |
| ערים             | πολεις             |
| שש               | επτα               |
| וחצריהן          | και αι κωμαι αυτων |
: Joshua (Alexandrinus) chapter 15, verse 62 { .hover tbl-colwidths="[50,50]"}

## Chapter 18

### Verse 21

| Masoretic text                      | Septuagint                                                                                                                           |
|:------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------|
| [והיו]{.potential-difference}       | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [הערים]{.potential-difference}      | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [למטה]{.potential-difference}       | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [בני]{.potential-difference}        | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [בנימן]{.potential-difference}      | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [למשפחותיהם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| [יריחו]{.potential-difference}      | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Long minus or plus (at least four lines).]]{.potential-difference} |
| ובית חגלה                           | βηθαγλα                                                                                                                              |
| ועמק קציץ                           | και αμεκκασις                                                                                                                        |
: Joshua (Alexandrinus) chapter 18, verse 21 { .hover tbl-colwidths="[50,50]"}

### Verse 22

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| ובית הערבה       | και βαιθαραβα |
| וצמרים           | και σεμριμ    |
| ובית אל          | και βηθηλ     |
: Joshua (Alexandrinus) chapter 18, verse 22 { .hover tbl-colwidths="[50,50]"}

### Verse 23

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| והעוים           | και αυιμ     |
| והפרה            | και αφαρ     |
| ועפרה            | και αφρα     |
: Joshua (Alexandrinus) chapter 18, verse 23 { .hover tbl-colwidths="[50,50]"}

### Verse 24

| Masoretic text                                                               | Septuagint                                                                             |
|:-----------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [και αικαρεν]{.potential-difference}                                                   |
| וכפר *העמני **העמנה                                                          | και καφηραμμιν                                                                         |
| [והעפני]{.potential-difference}                                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| וגבע                                                                         | και γαβαα                                                                              |
| ערים                                                                         | πολεις                                                                                 |
| שתים עשרה                                                                    | δωδεκα                                                                                 |
| וחצריהן                                                                      | και αι κωμαι αυτων                                                                     |
: Joshua (Alexandrinus) chapter 18, verse 24 { .hover tbl-colwidths="[50,50]"}

### Verse 25

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| גבעון            | γαβαων       |
| והרמה            | και ραμα     |
| ובארות           | και βηρωθ    |
: Joshua (Alexandrinus) chapter 18, verse 25 { .hover tbl-colwidths="[50,50]"}

### Verse 26

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| והמצפה           | και μασφα    |
| והכפירה          | και χεφιρα   |
| והמצה            | και αμωσα    |
: Joshua (Alexandrinus) chapter 18, verse 26 { .hover tbl-colwidths="[50,50]"}

### Verse 27

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ורקם             | και ρεκεμ    |
| וירפאל           | και ιερφαηλ  |
| ותראלה           | και θαραλα   |
: Joshua (Alexandrinus) chapter 18, verse 27 { .hover tbl-colwidths="[50,50]"}

## Chapter 19

### Verse 1

| Masoretic text                    | Septuagint                                                                             |
|:----------------------------------|:---------------------------------------------------------------------------------------|
| ויצא                              | και εξηλθεν                                                                            |
| הגורל                             | ο κληρος                                                                               |
| השני                              | ο δευτερος                                                                             |
| לשמעון                            | τω συμεων                                                                              |
| [למטה]{.potential-difference}     | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [בני]{.potential-difference}      | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [שמעון]{.potential-difference}    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [למשפחותם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ויהי                              | και εγενηθη                                                                            |
| נחלתם                             | η κληρονομια αυτων                                                                     |
| בתוך                              | ανα μεσον                                                                              |
| נחלת                              | κληρου                                                                                 |
| בני                               | υιων                                                                                   |
| יהודה                             | ιουδα                                                                                  |
: Joshua (Alexandrinus) chapter 19, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text               | Septuagint                                                                             |
|:-----------------------------|:---------------------------------------------------------------------------------------|
| ויהי                         | και εγενηθη                                                                            |
| [להם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| בנחלתם                       | ο κληρος αυτων                                                                         |
| באר שבע                      | βηρσαβεε                                                                               |
| ושבע                         | και σαβεε                                                                              |
| ומולדה                       | και μωλαδα                                                                             |
: Joshua (Alexandrinus) chapter 19, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| וחצר             | και ασερσουαλ |
| שועל             | και βαθουλ    |
| ובלה             | και βωλα      |
| ועצם             | και ασομ      |
: Joshua (Alexandrinus) chapter 19, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text                 | Septuagint                                                                             |
|:-------------------------------|:---------------------------------------------------------------------------------------|
| ואלתולד                        | και ελθουλαδ                                                                           |
| [ובתול]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| וחרמה                          | και ερμα                                                                               |
: Joshua (Alexandrinus) chapter 19, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| וצקלג            | και σεκελα         |
| ובית המרכבות     | και βαιθαμμαρχαβωθ |
| וחצר סוסה        | και ασερσουσιμ     |
: Joshua (Alexandrinus) chapter 19, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text                  | Tov's retroversion                                                            | Septuagint                                  |
|:--------------------------------|:------------------------------------------------------------------------------|:--------------------------------------------|
| ובית לבאות                      |                                                                               | και βαιθλαβαθ                               |
| [ושרוחן]{.potential-difference} | [ושדיהם •^[Difference in vocalization (reading).] .dr]{.potential-difference} | [και οι αγροι αυτων]{.potential-difference} |
| ערים                            |                                                                               | πολεις                                      |
| שלש עשרה                        |                                                                               | δεκα τρεις                                  |
| וחצריהן                         |                                                                               | και αι κωμαι αυτων                          |
: Joshua (Alexandrinus) chapter 19, verse 6 { .hover tbl-colwidths="[35,30,35]"}

### Verse 7

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| עין              | αιν                |
| רמון             | και ρεμμων         |
| ועתר             | και εθερ           |
| ועשן             | και ασαν           |
| ערים             | πολεις             |
| ארבע             | τεσσαρες           |
| וחצריהן          | και αι κωμαι αυτων |
: Joshua (Alexandrinus) chapter 19, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                                               | Tov's retroversion            | Septuagint                                                                             |
|:-----------------------------------------------------------------------------|:------------------------------|:---------------------------------------------------------------------------------------|
| [וכל]{.potential-difference}                                                 |                               | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [החצרים]{.potential-difference}                                              |                               | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| אשר                                                                          |                               | αι                                                                                     |
| סביבות                                                                       |                               | περικυκλω                                                                              |
| הערים                                                                        |                               | των πολεων                                                                             |
| האלה                                                                         |                               | τουτων                                                                                 |
| עד                                                                           |                               | εως                                                                                    |
| בעלת באר ראמת                                                                |                               | βααλεθβηρραμωθ                                                                         |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [מבוא]{.potential-difference} | [πορευομενων]{.potential-difference}                                                   |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                               | [ιαμεθ]{.potential-difference}                                                         |
| נגב                                                                          |                               | κατα λιβα                                                                              |
| זאת                                                                          |                               | αυτη                                                                                   |
| נחלת                                                                         |                               | η κληρονομια                                                                           |
| מטה                                                                          |                               | φυλης                                                                                  |
| בני                                                                          |                               | υιων                                                                                   |
| שמעון                                                                        |                               | συμεων                                                                                 |
| למשפחתם                                                                      |                               | κατα δημους αυτων                                                                      |
: Joshua (Alexandrinus) chapter 19, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text                                                                        | Septuagint                                                                             |
|:--------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| מחבל                                                                                  | απο του κληρου                                                                         |
| [בני]{.potential-difference}                                                          | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| יהודה                                                                                 | ιουδα                                                                                  |
| נחלת                                                                                  | η κληρονομια                                                                           |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}          | [φυλης]{.potential-difference}                                                         |
| בני                                                                                   | υιων                                                                                   |
| שמעון                                                                                 | συμεων                                                                                 |
| כי                                                                                    | οτι                                                                                    |
| היה                                                                                   | εγενηθη                                                                                |
| חלק                                                                                   | μερις                                                                                  |
| בני                                                                                   | υιων                                                                                   |
| יהודה                                                                                 | ιουδα                                                                                  |
| רב •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ם | μειζων                                                                                 |
| מהם                                                                                   | της αυτων                                                                              |
| וינחלו                                                                                | και εκληρονομησαν                                                                      |
| בני                                                                                   | οι υιοι                                                                                |
| שמעון                                                                                 | συμεων                                                                                 |
| בתוך                                                                                  | εν μεσω                                                                                |
| נחלתם                                                                                 | του κληρου αυτων                                                                       |
: Joshua (Alexandrinus) chapter 19, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                | Septuagint                                                                                |
|:------------------------------|:------------------------------------------------------------------------------------------|
| ויעל                          | και εξηλθεν                                                                               |
| הגורל                         | ο κληρος                                                                                  |
| השלישי                        | ο τριτος                                                                                  |
| [לבני]{.potential-difference} | [τω •^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| זבולן                         | ζαβουλων                                                                                  |
| למשפחתם                       | κατα δημους αυτων                                                                         |
| ויהי                          | και εσται                                                                                 |
| גבול                          | τα ορια                                                                                   |
| נחלתם                         | της κληρονομιας αυτων                                                                     |
| עד                            | εως                                                                                       |
| שריד                          | σαριδ                                                                                     |
: Joshua (Alexandrinus) chapter 19, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                | Septuagint                                                                             |
|:------------------------------|:---------------------------------------------------------------------------------------|
| [עלה]{.potential-difference}  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| גבולם                         | τα ορια αυτων                                                                          |
| לימה                          | η θαλασσα                                                                              |
| ומרעלה                        | και μαραλα                                                                             |
| ופגע                          | και συναψει                                                                            |
| בדבשת                         | επι δαβασθαι                                                                           |
| [ופגע]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| אל                            | εις                                                                                    |
| הנחל                          | την φαραγγα                                                                            |
| אשר                           | η εστιν                                                                                |
| על פני                        | κατα προσωπον                                                                          |
| יקנעם                         | ιεκναμ                                                                                 |
: Joshua (Alexandrinus) chapter 19, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                                                                   | Septuagint                                                                                                                |
|:---------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------|
| ושב                                                                              | και αναστρεψει                                                                                                            |
| משריד                                                                            | απο σαριδ                                                                                                                 |
| קדמה                                                                             | εξ εναντιας                                                                                                               |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | απο                                                                                                                       |
| מזרח                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] απο ανατολων |
| השמש                                                                             | σαμς                                                                                                                      |
| על                                                                               | επι                                                                                                                       |
| גבול                                                                             | τα ορια                                                                                                                   |
| כסלת                                                                             | χασαλωθ                                                                                                                   |
| תבר                                                                              | θαβωρ                                                                                                                     |
| ויצא                                                                             | και διελευσεται                                                                                                           |
| אל                                                                               | επι                                                                                                                       |
| הדברת                                                                            | δαβραθ                                                                                                                    |
| ועלה                                                                             | και προσαναβησεται                                                                                                        |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | επι                                                                                                                       |
| יפיע                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι ιαφαγαι  |
: Joshua (Alexandrinus) chapter 19, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                                                   | Septuagint                                                                                                              |
|:---------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------|
| ומשם                                                                             | και εκειθεν                                                                                                             |
| עבר                                                                              | περιελευσεται                                                                                                           |
| קדמה                                                                             | εξ εναντιας                                                                                                             |
| מזרחה                                                                            | επ' ανατολας                                                                                                            |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | επι                                                                                                                     |
| גתה                                                                              | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι γεθθα  |
| [חפר]{.potential-difference}                                                     | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}                                  |
| [עתה]{.potential-difference}                                                     | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}                                  |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [επι]{.potential-difference}                                                                                            |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [πολιν]{.potential-difference}                                                                                          |
| קצין                                                                             | κασιμ                                                                                                                   |
| ויצא                                                                             | και διελευσεται                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | επι                                                                                                                     |
| רמון                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι ρεμμων |
| המתאר                                                                            | αμμαθαριμ                                                                                                               |
| הנעה                                                                             | αννουα                                                                                                                  |
: Joshua (Alexandrinus) chapter 19, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                                   | Septuagint                                                                                                                  |
|:---------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|
| ונסב אתו =vpa                                                                    | και περιελευσεται                                                                                                           |
| הגבול                                                                            | επι τα ορια                                                                                                                 |
| מצפון                                                                            | βορρα                                                                                                                       |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | επι                                                                                                                         |
| חנתן                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι ενναθωθ    |
| והיו                                                                             | και εσται                                                                                                                   |
| תצאתיו                                                                           | η διεξοδος αυτων                                                                                                            |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | επι                                                                                                                         |
| גי יפתח אל                                                                       | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι γαιιεφθαηλ |
: Joshua (Alexandrinus) chapter 19, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text                     | Septuagint                                                                             |
|:-----------------------------------|:---------------------------------------------------------------------------------------|
| וקטת                               | και κατταθ                                                                             |
| ונהלל                              | και νααλωλ                                                                             |
| ושמרון                             | και σεμρων                                                                             |
| וידאלה                             | και ιαδηλα                                                                             |
| ובית לחם                           | και βαιθλεεμ                                                                           |
| [ערים]{.potential-difference}      | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [שתים עשרה]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [וחצריהן]{.potential-difference}   | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
: Joshua (Alexandrinus) chapter 19, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text                                                               | Septuagint                         |
|:-----------------------------------------------------------------------------|:-----------------------------------|
| זאת                                                                          | αυτη                               |
| נחלת                                                                         | η κληρονομια                       |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [της φυλης]{.potential-difference} |
| בני                                                                          | υιων                               |
| זבולן                                                                        | ζαβουλων                           |
| למשפחתם                                                                      | κατα δημους αυτων                  |
| הערים                                                                        | αι πολεις                          |
| האלה                                                                         | αυται                              |
| וחצריהן                                                                      | και αι κωμαι αυτων                 |
: Joshua (Alexandrinus) chapter 19, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text                    | Septuagint                                                                             |
|:----------------------------------|:---------------------------------------------------------------------------------------|
| ליששכר                            | και τω ισσαχαρ                                                                         |
| יצא                               | εξηλθεν                                                                                |
| הגורל                             | ο κληρος                                                                               |
| הרביעי                            | ο τεταρτος                                                                             |
| [לבני]{.potential-difference}     | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [יששכר]{.potential-difference}    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [למשפחותם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
: Joshua (Alexandrinus) chapter 19, verse 17 { .hover tbl-colwidths="[50,50]"}

### Verse 18

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| ויהי             | και εγενηθη   |
| גבולם            | τα ορια αυτων |
| יזרעאלה          | ιεζραελ       |
| והכסולת          | και αχασελωθ  |
| ושונם            | και σουναμ    |
: Joshua (Alexandrinus) chapter 19, verse 18 { .hover tbl-colwidths="[50,50]"}

### Verse 19

| Masoretic text                                                               | Septuagint                         |
|:-----------------------------------------------------------------------------|:-----------------------------------|
| וחפרים                                                                       | και αφεραιμ                        |
| ושיאן                                                                        | και σιαν                           |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [και ρεναθ]{.potential-difference} |
| ואנחרת                                                                       | και αναρεθ                         |
: Joshua (Alexandrinus) chapter 19, verse 19 { .hover tbl-colwidths="[50,50]"}

### Verse 20

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| והרבית           | και ραββωθ   |
| וקשיון           | και κεσιων   |
| ואבץ             | και αεμε     |
: Joshua (Alexandrinus) chapter 19, verse 20 { .hover tbl-colwidths="[50,50]"}

### Verse 21

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| ורמת             | και ραμαθ     |
| ועין גנים        | και ηνγαννιμ  |
| ועין חדה         | και ηναδδα    |
| ובית פצץ         | και βαιθφασης |
: Joshua (Alexandrinus) chapter 19, verse 21 { .hover tbl-colwidths="[50,50]"}

### Verse 22

| Masoretic text                              | Tov's retroversion           | Septuagint                                                                             |
|:--------------------------------------------|:-----------------------------|:---------------------------------------------------------------------------------------|
| ופגע                                        |                              | και συναψει                                                                            |
| הגבול                                       |                              | τα ορια                                                                                |
| בתבור                                       |                              | επι θαβωθ                                                                              |
| [*ושחצומה **ושחצימה]{.potential-difference} | [ימה]{.potential-difference} | [και επι σασιμα κατα θαλασσαν]{.potential-difference}                                  |
| ובית שמש                                    |                              | και βαιθσμας                                                                           |
| והיו                                        |                              | και εσται                                                                              |
| תצאות                                       |                              | η διεξοδος                                                                             |
| גבולם                                       |                              | των οριων αυτων                                                                        |
| הירדן                                       |                              | ο ιορδανης                                                                             |
| [ערים]{.potential-difference}               |                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [שש עשרה]{.potential-difference}            |                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [וחצריהן]{.potential-difference}            |                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
: Joshua (Alexandrinus) chapter 19, verse 22 { .hover tbl-colwidths="[35,30,35]"}

### Verse 23

| Masoretic text   | Septuagint            |
|:-----------------|:----------------------|
| זאת              | αυτη                  |
| נחלת             | η κληρονομια          |
| מטה              | φυλης                 |
| בני              | υιων                  |
| יששכר            | ισσαχαρ               |
| למשפחתם          | κατα δημους αυτων     |
| הערים            | αι πολεις             |
| וחצריהן          | και αι επαυλεις αυτων |
: Joshua (Alexandrinus) chapter 19, verse 23 { .hover tbl-colwidths="[50,50]"}

### Verse 24

| Masoretic text                | Septuagint                                                                             |
|:------------------------------|:---------------------------------------------------------------------------------------|
| ויצא                          | και εξηλθεν                                                                            |
| הגורל                         | ο κληρος                                                                               |
| החמישי                        | ο πεμπτος                                                                              |
| [למטה]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [בני]{.potential-difference}  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| אשר                           | ασηρ                                                                                   |
| למשפחותם                      | κατα δημους αυτων                                                                      |
: Joshua (Alexandrinus) chapter 19, verse 24 { .hover tbl-colwidths="[50,50]"}

### Verse 25

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| ויהי             | και εγενηθη   |
| גבולם            | τα ορια αυτων |
| חלקת             | χελκαθ        |
| וחלי             | και οολι      |
| ובטן             | και βατνε     |
| ואכשף            | και αχσαφ     |
: Joshua (Alexandrinus) chapter 19, verse 25 { .hover tbl-colwidths="[50,50]"}

### Verse 26

| Masoretic text                  | Septuagint                                                                             |
|:--------------------------------|:---------------------------------------------------------------------------------------|
| [ואלמלך]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ועמעד                           | και αμαδ                                                                               |
| ומשאל                           | και μασαλ                                                                              |
| ופגע                            | και συναψει                                                                            |
| בכרמל                           | τω καρμηλω                                                                             |
| הימה                            | κατα θαλασσαν                                                                          |
| ובשיחור                         | και τω σιωρ                                                                            |
| לבנת                            | και λαβαναθ                                                                            |
: Joshua (Alexandrinus) chapter 19, verse 26 { .hover tbl-colwidths="[50,50]"}

### Verse 27

| Masoretic text                                                                   | Septuagint                                                                                                                |
|:---------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------|
| ושב                                                                              | και επιστρεψει                                                                                                            |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | απ'                                                                                                                       |
| מזרח                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] απ' ανατολων |
| השמש                                                                             | ηλιου                                                                                                                     |
| בית דגן                                                                          | βηθδαγων                                                                                                                  |
| ופגע                                                                             | και συναψει                                                                                                               |
| בזבלון                                                                           | τω ζαβουλων                                                                                                               |
| ובגי                                                                             | και εν γαι                                                                                                                |
| יפתח                                                                             | ιεφθαηλ                                                                                                                   |
| אל צפונה                                                                         | κατα βορραν                                                                                                               |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [και εισελευσεται]{.potential-difference}                                                                                 |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [τα ορια]{.potential-difference}                                                                                          |
| בית העמק                                                                         | σαφθαβηθαεμεκ                                                                                                             |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [και πορευσεται]{.potential-difference}                                                                                   |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [το μεθοριον]{.potential-difference}                                                                                      |
| ונעיאל                                                                           | ανιηλ                                                                                                                     |
| ויצא                                                                             | και διελευσεται                                                                                                           |
| אל                                                                               | εις                                                                                                                       |
| כבול                                                                             | χαβωλ                                                                                                                     |
| משמאל                                                                            | πο αριστερων                                                                                                              |
: Joshua (Alexandrinus) chapter 19, verse 27 { .hover tbl-colwidths="[50,50]"}

### Verse 28

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ועברן            | και αχραν    |
| ורחב             | και ροωβ     |
| וחמון            | και αμων     |
| וקנה             | και κανα     |
| עד               | εως          |
| צידון            | σιδωνος      |
| רבה              | της μεγαλης  |
: Joshua (Alexandrinus) chapter 19, verse 28 { .hover tbl-colwidths="[50,50]"}

### Verse 29

| Masoretic text   | Septuagint               |
|:-----------------|:-------------------------|
| ושב              | και αναστρεψει           |
| הגבול            | τα ορια                  |
| הרמה             | εις ραμα                 |
| ועד              | και εως                  |
| עיר              | πολεως                   |
| מבצר             | οχυρωματος               |
| צר               | των τυριων               |
| ושב              | και αναστρεψει           |
| הגבול            | τα ορια                  |
| חסה              | επι ωσα                  |
| *ויהיו **והיו    | και εσται                |
| תצאתיו           | η διεξοδος αυτου         |
| הימה             | η θαλασσα                |
| מחבל             | και απο του σχοινισματος |
| אכזיבה           | αχζιφ                    |
: Joshua (Alexandrinus) chapter 19, verse 29 { .hover tbl-colwidths="[50,50]"}

### Verse 30

| Masoretic text                   | Septuagint                                                                             |
|:---------------------------------|:---------------------------------------------------------------------------------------|
| ועמה                             | και αμμα                                                                               |
| ואפק                             | και αφεκ                                                                               |
| ורחב                             | και ραωβ                                                                               |
| ערים                             | πολεις                                                                                 |
| עשרים ושתים                      | εικοσι δυο                                                                             |
| [וחצריהן]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
: Joshua (Alexandrinus) chapter 19, verse 30 { .hover tbl-colwidths="[50,50]"}

### Verse 31

| Masoretic text                | Septuagint                                                                             |
|:------------------------------|:---------------------------------------------------------------------------------------|
| זאת                           | αυτη                                                                                   |
| נחלת                          | η κληρονομια                                                                           |
| מטה                           | φυλης                                                                                  |
| בני                           | υιων                                                                                   |
| אשר                           | ασηρ                                                                                   |
| למשפחתם                       | κατα δημους αυτων                                                                      |
| הערים                         | πολεις αυτων                                                                           |
| [האלה]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| וחצריהן                       | και αι κωμαι αυτων                                                                     |
: Joshua (Alexandrinus) chapter 19, verse 31 { .hover tbl-colwidths="[50,50]"}

### Verse 32

| Masoretic text                   | Septuagint                                                                             |
|:---------------------------------|:---------------------------------------------------------------------------------------|
| לבני                             | και τω                                                                                 |
| נפתלי                            | νεφθαλι                                                                                |
| יצא                              | εξηλθεν                                                                                |
| הגורל                            | ο κληρος                                                                               |
| הששי                             | ο εκτος                                                                                |
| [לבני]{.potential-difference}    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [נפתלי]{.potential-difference}   | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [למשפחתם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
: Joshua (Alexandrinus) chapter 19, verse 32 { .hover tbl-colwidths="[50,50]"}

### Verse 33

| Masoretic text                 | Tov's retroversion                 | Septuagint                         |
|:-------------------------------|:-----------------------------------|:-----------------------------------|
| ויהי                           |                                    | και εγενετο                        |
| גבולם                          |                                    | τα ορια αυτων                      |
| מחלף                           |                                    | μεελεφ                             |
| מאלון                          |                                    | και μαηλων                         |
| בצעננים                        |                                    | και βεσενανιμ                      |
| [ואדמי]{.potential-difference} | [וארמי .dr]{.potential-difference} | [και αρμαι]{.potential-difference} |
| הנקב                           |                                    | και νακεβ                          |
| ויבנאל                         |                                    | και ιαβνηλ                         |
| עד                             |                                    | εως                                |
| לקום                           |                                    | λακου                              |
| ויהי                           |                                    | και εγενηθησαν                     |
| תצאתיו                         |                                    | αι διεξοδοι αυτου                  |
| הירדן                          |                                    | ο ιορδανης                         |
: Joshua (Alexandrinus) chapter 19, verse 33 { .hover tbl-colwidths="[35,30,35]"}

### Verse 34

| Masoretic text                   | Septuagint                                                                             |
|:---------------------------------|:---------------------------------------------------------------------------------------|
| ושב                              | και επιστρεψει                                                                         |
| הגבול                            | τα ορια                                                                                |
| ימה                              | επι θαλασσαν                                                                           |
| אזנות                            | αζανωθ                                                                                 |
| תבור                             | θαβωρ                                                                                  |
| ויצא                             | και διελευσεται                                                                        |
| משם                              | εκειθεν                                                                                |
| חוקקה                            | εις ικωκ                                                                               |
| ופגע                             | και συναψει                                                                            |
| בזבלון                           | τω ζαβουλων                                                                            |
| מנגב                             | απο νοτου                                                                              |
| ובאשר                            | και τω ασηρ                                                                            |
| פגע                              | συναψει                                                                                |
| מים                              | κατα θαλασσαν                                                                          |
| [וביהודה]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| הירדן                            | και ο ιορδανης                                                                         |
| מזרח                             | απ' ανατολων                                                                           |
| השמש                             | ηλιου                                                                                  |
: Joshua (Alexandrinus) chapter 19, verse 34 { .hover tbl-colwidths="[50,50]"}

### Verse 35

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| וערי             | και πολεις   |
| מבצר             | τειχηρεις    |
| הצדים            | των τυριων   |
| צר               | τυρος        |
| וחמת             | και αμαθ     |
| רקת              | και ρεκκαθ   |
| וכנרת            | και χενερεθ  |
: Joshua (Alexandrinus) chapter 19, verse 35 { .hover tbl-colwidths="[50,50]"}

### Verse 36

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ואדמה            | και αδαμι    |
| והרמה            | και ραμα     |
| וחצור            | και ασωρ     |
: Joshua (Alexandrinus) chapter 19, verse 36 { .hover tbl-colwidths="[50,50]"}

### Verse 37

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| וקדש             | και κεδες     |
| ואדרעי           | και εδραι     |
| ועין חצור        | και πηγη ασορ |
: Joshua (Alexandrinus) chapter 19, verse 37 { .hover tbl-colwidths="[50,50]"}

### Verse 38

| Masoretic text                   | Septuagint                                                                             |
|:---------------------------------|:---------------------------------------------------------------------------------------|
| ויראון                           | και ιαριων                                                                             |
| ומגדל אל                         | και μαγδαλιηλ                                                                          |
| חרם                              | ωραμ                                                                                   |
| ובית ענת                         | και βαιθαναθ                                                                           |
| ובית שמש                         | και θασμους                                                                            |
| ערים                             | πολεις                                                                                 |
| תשע עשרה                         | δεκα εννεα                                                                             |
| [וחצריהן]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
: Joshua (Alexandrinus) chapter 19, verse 38 { .hover tbl-colwidths="[50,50]"}

### Verse 39

| Masoretic text                   | Septuagint                                                                             |
|:---------------------------------|:---------------------------------------------------------------------------------------|
| זאת                              | αυτη                                                                                   |
| נחלת                             | η κληρονομια                                                                           |
| מטה                              | φυλης                                                                                  |
| בני                              | υιων                                                                                   |
| נפתלי                            | νεφθαλι                                                                                |
| [למשפחתם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [הערים]{.potential-difference}   | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [וחצריהן]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
: Joshua (Alexandrinus) chapter 19, verse 39 { .hover tbl-colwidths="[50,50]"}

### Verse 40

| Masoretic text                   | Septuagint                                                                                    |
|:---------------------------------|:----------------------------------------------------------------------------------------------|
| [למטה]{.potential-difference}    | [και τω •^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [בני]{.potential-difference}     | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}        |
| דן                               | δαν                                                                                           |
| [למשפחתם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}        |
| יצא                              | εξηλθεν                                                                                       |
| הגורל                            | ο κληρος                                                                                      |
| השביעי                           | ο εβδομος                                                                                     |
: Joshua (Alexandrinus) chapter 19, verse 40 { .hover tbl-colwidths="[50,50]"}

### Verse 41

| Masoretic text                 | Septuagint                                                                                   |
|:-------------------------------|:---------------------------------------------------------------------------------------------|
| ויהי                           | και εγενηθη                                                                                  |
| גבול                           | τα ορια                                                                                      |
| [נחלתם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] αυτων]{.potential-difference} |
| צרעה                           | σαραα                                                                                        |
| ואשתאול                        | και εσθαολ                                                                                   |
| ועיר                           | και πολις                                                                                    |
| שמש                            | σαμες                                                                                        |
: Joshua (Alexandrinus) chapter 19, verse 41 { .hover tbl-colwidths="[50,50]"}

### Verse 42

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ושעלבין          | και σαλαβιν  |
| ואילון           | και ιααλων   |
| ויתלה            | και ιεθλα    |
: Joshua (Alexandrinus) chapter 19, verse 42 { .hover tbl-colwidths="[50,50]"}

### Verse 43

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ואילון           | και αιλων    |
| ותמנתה           | και θαμνα    |
| ועקרון           | και ακκαρων  |
: Joshua (Alexandrinus) chapter 19, verse 43 { .hover tbl-colwidths="[50,50]"}

### Verse 44

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ואלתקה           | και ελθεκω   |
| וגבתון           | και γαβαθων  |
| ובעלת            | και βααλων   |
: Joshua (Alexandrinus) chapter 19, verse 44 { .hover tbl-colwidths="[50,50]"}

### Verse 45

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| ויהד             | και ιουθ      |
| ובני ברק         | και βανηβαρακ |
| וגת רמון         | και γεθρεμμων |
: Joshua (Alexandrinus) chapter 19, verse 45 { .hover tbl-colwidths="[50,50]"}

