# Malachi

The tables below show the Hebrew and Greek texts aligned vertically. When a Hebrew verse number does not match the Greek counterpart, the editors added a note with the corresponding verse number between square brackets.

## Chapter 1

### Verse 1

| Masoretic text                                                                             | Septuagint                                |
|:-------------------------------------------------------------------------------------------|:------------------------------------------|
| משא                                                                                        | λημμα                                     |
| דבר                                                                                        | λογου                                     |
| יהוה                                                                                       | κυριου                                    |
| אל                                                                                         | επι                                       |
| ישראל                                                                                      | τον ισραηλ                                |
| ביד                                                                                        | εν χειρι                                  |
| מלאכי                                                                                      | αγγελου αυτου                             |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;תשימו <2.2>]{.potential-difference} | [θεσθε]{.potential-difference}            |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}               | [δη]{.potential-difference}               |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;על <2.2>]{.potential-difference}    | [επι]{.potential-difference}              |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;לב <2.2>]{.potential-difference}    | [τας καρδιας υμων]{.potential-difference} |
: Malachi chapter 1, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                                               | Septuagint                  |
|:-----------------------------------------------------------------------------|:----------------------------|
| אהבתי                                                                        | ηγαπησα                     |
| אתכם                                                                         | υμας                        |
| אמר                                                                          | λεγει                       |
| יהוה                                                                         | κυριος                      |
| ואמרתם                                                                       | και ειπατε                  |
| במה                                                                          | εν τινι                     |
| אהבתנו                                                                       | ηγαπησας ημας               |
| הלוא                                                                         | ουκ                         |
| אח                                                                           | αδελφος                     |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [ην]{.potential-difference} |
| עשו                                                                          | ησαυ                        |
| ליעקב                                                                        | του ιακωβ                   |
| נאם                                                                          | λεγει                       |
| יהוה                                                                         | κυριος                      |
| ואהב                                                                         | και ηγαπησα                 |
| את יעקב                                                                      | τον ιακωβ                   |
: Malachi chapter 1, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                       | Septuagint                |
|:-------------------------------------|:--------------------------|
| ואת עשו                              | τον δε ησαυ               |
| שנאתי                                | εμισησα                   |
| ואשים                                | και εταξα                 |
| את הריו                              | τα ορια αυτου             |
| שממה                                 | εις αφανισμον             |
| ואת נחלתו                            | και την κληρονομιαν αυτου |
| לתנות •^[Etymological exegesis.] נתן | εις δοματα                |
| מדבר                                 | ερημου                    |
: Malachi chapter 1, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint          |
|:-----------------|:--------------------|
| כי               | διοτι               |
| תאמר             | ερει                |
| אדום             | η ιδουμαια          |
| רששנו            | κατεστραπται        |
| ונשוב            | και επιστρεψωμεν    |
| ונבנה            | και ανοικοδομησωμεν |
| חרבות            | τας ερημους         |
| כה               | ταδε                |
| אמר              | λεγει               |
| יהוה             | κυριος              |
| צבאות            | παντοκρατωρ         |
| המה              | αυτοι               |
| יבנו             | οικοδομησουσιν      |
| ואני             | και εγω             |
| אהרוס            | καταστρεψω          |
| וקראו            | και επικληθησεται   |
| להם              | αυτοις              |
| גבול             | ορια                |
| רשעה             | ανομιας             |
| והעם             | και λαος            |
| אשר              | εφ' ον              |
| זעם              | παρατετακται        |
| יהוה             | κυριος              |
| עד               | εως                 |
| עולם             | αιωνος              |
: Malachi chapter 1, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                                         | Septuagint           |
|:---------------------------------------------------------------------------------------|:---------------------|
| ועיניכם                                                                                | και οι οφθαλμοι υμων |
| תראינה                                                                                 | οψονται              |
| ואתם                                                                                   | και υμεις            |
| תאמרו                                                                                  | ερειτε               |
| יגדל                                                                                   | εμεγαλυνθη           |
| יהוה                                                                                   | κυριος               |
| מעל •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ל | υπερανω              |
| לגבול                                                                                  | των οριων            |
| ישראל                                                                                  | του ισραηλ           |
: Malachi chapter 1, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| בן               | υιος             |
| יכבד             | δοξαζει          |
| אב               | πατερα           |
| ועבד             | και δουλος       |
| אדניו            | τον κυριον αυτου |
| ואם              | και ει           |
| אב               | πατηρ            |
| אני              | ειμι εγω         |
| איה              | που εστιν        |
| כבודי            | η δοξα μου       |
| ואם              | και ει           |
| אדונים           | κυριος           |
| אני              | ειμι εγω         |
| איה              | που εστιν        |
| מוראי            | ο φοβος μου      |
| אמר              | λεγει            |
| יהוה             | κυριος           |
| צבאות            | παντοκρατωρ      |
| לכם              | υμεις            |
| הכהנים           | οι ιερεις        |
| בוזי             | οι φαυλιζοντες   |
| שמי              | το ονομα μου     |
| ואמרתם           | και ειπατε       |
| במה              | εν τινι          |
| בזינו            | εφαυλισαμεν      |
| את שמך           | το ονομα σου     |
: Malachi chapter 1, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                                                                              | Septuagint                                  |
|:--------------------------------------------------------------------------------------------|:--------------------------------------------|
| מגישים                                                                                      | προσαγοντες                                 |
| על                                                                                          | προς                                        |
| מזבחי                                                                                       | το θυσιαστηριον μου                         |
| לחם                                                                                         | αρτους                                      |
| מגאל                                                                                        | ηλισγημενους                                |
| ואמרתם                                                                                      | και ειπατε                                  |
| במה                                                                                         | εν τινι                                     |
| גאלנוך                                                                                      | ηλισγησαμεν αυτους                          |
| באמרכם                                                                                      | εν τω λεγειν υμας                           |
| שלחן                                                                                        | τραπεζα                                     |
| יהוה                                                                                        | κυριου                                      |
| נבזה                                                                                        | εξουδενωμενη                                |
| הוא                                                                                         | εστιν                                       |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;וניבו <1.12>]{.potential-difference} | [και τα επιτιθεμενα]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;אכל <1.12>]{.potential-difference}   | [βρωματα]{.potential-difference}            |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;נבזה <1.12>]{.potential-difference}  | [εξουδενωμενα]{.potential-difference}       |
: Malachi chapter 1, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                                                   | Septuagint                                                                                      |
|:---------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------|
| וכי                                                                              | διοτι εαν                                                                                       |
| תגשון                                                                            | προσαγαγητε                                                                                     |
| עור                                                                              | τυφλον                                                                                          |
| לזבח •^[Difference in vocalization (reading).]                                   | εις θυσιαν                                                                                      |
| אין                                                                              | ου                                                                                              |
| רע                                                                               | κακον                                                                                           |
| וכי                                                                              | και εαν                                                                                         |
| תגישו                                                                            | προσαγαγητε                                                                                     |
| פסח                                                                              | χωλον                                                                                           |
| וחלה                                                                             | η αρρωστον                                                                                      |
| אין                                                                              | ου                                                                                              |
| רע                                                                               | κακον                                                                                           |
| הקריבהו                                                                          | προσαγαγε •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] αυτο |
| נא                                                                               | δη                                                                                              |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | αυτο                                                                                            |
| לפחתך                                                                            | τω ηγουμενω σου                                                                                 |
| הירצך                                                                            | ει προσδεξεται αυτο                                                                             |
| או הישא                                                                          | ει λημψεται                                                                                     |
| פניך                                                                             | προσωπον σου                                                                                    |
| אמר                                                                              | λεγει                                                                                           |
| יהוה                                                                             | κυριος                                                                                          |
| צבאות                                                                            | παντοκρατωρ                                                                                     |
: Malachi chapter 1, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                   | Septuagint                                                                             |
|:-------------------------------------------------|:---------------------------------------------------------------------------------------|
| ועתה                                             | και νυν                                                                                |
| חלו                                              | εξιλασκεσθε                                                                            |
| [נא]{.potential-difference}                      | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| פני                                              | το προσωπον                                                                            |
| אל                                               | του θεου υμων                                                                          |
| ויחננו                                           | και δεηθητε αυτου                                                                      |
| מידכם •^[Difference in preposition or particle.] | εν χερσιν υμων                                                                         |
| היתה                                             | γεγονεν                                                                                |
| זאת                                              | ταυτα                                                                                  |
| הישא                                             | ει λημψομαι                                                                            |
| מכם                                              | εξ υμων                                                                                |
| פנים                                             | προσωπα υμων                                                                           |
| אמר                                              | λεγει                                                                                  |
| יהוה                                             | κυριος                                                                                 |
| צבאות                                            | παντοκρατωρ                                                                            |
: Malachi chapter 1, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                         | Tov's retroversion              | Septuagint                     |
|:-------------------------------------------------------|:--------------------------------|:-------------------------------|
| [מי]{.potential-difference}                            | [כי .mk]{.potential-difference} | [διοτι]{.potential-difference} |
| גם                                                     |                                 | και                            |
| בכם                                                    |                                 | εν υμιν                        |
| ויסגר •^[Change from active to passive form in verbs.] |                                 | συγκλεισθησονται               |
| דלתים                                                  |                                 | θυραι                          |
| ולא                                                    |                                 | και ουκ                        |
| תאירו                                                  |                                 | αναψετε                        |
| מזבחי                                                  |                                 | το θυσιαστηριον μου            |
| חנם                                                    |                                 | δωρεαν                         |
| אין                                                    |                                 | ουκ εστιν                      |
| לי                                                     |                                 | μου                            |
| חפץ                                                    |                                 | θελημα                         |
| בכם                                                    |                                 | εν υμιν                        |
| אמר                                                    |                                 | λεγει                          |
| יהוה                                                   |                                 | κυριος                         |
| צבאות                                                  |                                 | παντοκρατωρ                    |
| ומנחה                                                  |                                 | και θυσιαν                     |
| לא                                                     |                                 | ου                             |
| ארצה                                                   |                                 | προσδεξομαι                    |
| מידכם                                                  |                                 | εκ των χειρων υμων             |
: Malachi chapter 1, verse 10 { .hover tbl-colwidths="[35,30,35]"}

### Verse 11

| Masoretic text                                                                   | Tov's retroversion                                                        | Septuagint                              |
|:---------------------------------------------------------------------------------|:--------------------------------------------------------------------------|:----------------------------------------|
| כי                                                                               |                                                                           | διοτι                                   |
| ממזרח                                                                            |                                                                           | απ' ανατολων                            |
| שמש                                                                              |                                                                           | ηλιου                                   |
| ועד                                                                              |                                                                           | εως                                     |
| מבואו                                                                            |                                                                           | δυσμων                                  |
| [גדול]{.potential-difference}                                                    | [•^[Questionable notation, equivalent, etc.] @כבד]{.potential-difference} | [{..δεδοξασται}]{.potential-difference} |
| שמי                                                                              |                                                                           | το ονομα μου                            |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                                                           | δεδοξασται                              |
| בגוים                                                                            |                                                                           | εν τοις εθνεσιν                         |
| ובכל                                                                             |                                                                           | και εν παντι                            |
| מקום                                                                             |                                                                           | τοπω                                    |
| מקטר                                                                             |                                                                           | θυμιαμα                                 |
| מגש                                                                              |                                                                           | προσαγεται                              |
| לשמי                                                                             |                                                                           | τω ονοματι μου                          |
| ומנחה                                                                            |                                                                           | και θυσια                               |
| טהורה                                                                            |                                                                           | καθαρα                                  |
| כי                                                                               |                                                                           | διοτι                                   |
| גדול                                                                             |                                                                           | μεγα                                    |
| שמי                                                                              |                                                                           | το ονομα μου                            |
| בגוים                                                                            |                                                                           | εν τοις εθνεσιν                         |
| אמר                                                                              |                                                                           | λεγει                                   |
| יהוה                                                                             |                                                                           | κυριος                                  |
| צבאות                                                                            |                                                                           | παντοκρατωρ                             |
: Malachi chapter 1, verse 11 { .hover tbl-colwidths="[35,30,35]"}

### Verse 12

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| ואתם             | υμεις δε           |
| מחללים           | βεβηλουτε          |
| אותו             | αυτο               |
| באמרכם           | εν τω λεγειν υμας  |
| שלחן             | τραπεζα            |
| אדני             | κυριου             |
| מגאל             | ηλισγημενη         |
| הוא              | εστιν              |
| וניבו            | και τα επιτιθεμενα |
| נבזה             | εξουδενωνται       |
| אכלו             | βρωματα αυτου      |
: Malachi chapter 1, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                                                   | Septuagint                                                                                   |
|:---------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------|
| ואמרתם                                                                           | και ειπατε                                                                                   |
| הנה •^[Difference in vocalization (reading).]                                    | ταυτα •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] εστιν |
| מתלאה                                                                            | εκ κακοπαθειας                                                                               |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εστιν                                                                                        |
| והפחתם                                                                           | και εξεφυσησα                                                                                |
| אותו                                                                             | αυτα                                                                                         |
| אמר                                                                              | λεγει                                                                                        |
| יהוה                                                                             | κυριος                                                                                       |
| צבאות                                                                            | παντοκρατωρ                                                                                  |
| והבאתם                                                                           | και εισεφερετε                                                                               |
| גזול                                                                             | αρπαγματα                                                                                    |
| ואת הפסח                                                                         | και τα χωλα                                                                                  |
| ואת החולה                                                                        | και τα ενοχλουμενα                                                                           |
| והבאתם                                                                           | και εαν φερητε                                                                               |
| את המנחה                                                                         | την θυσιαν                                                                                   |
| הארצה                                                                            | ει προσδεξομαι                                                                               |
| אותה                                                                             | αυτα                                                                                         |
| מידכם                                                                            | εκ των χειρων υμων                                                                           |
| אמר                                                                              | λεγει                                                                                        |
| יהוה                                                                             | κυριος                                                                                       |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [παντοκρατωρ]{.potential-difference}                                                         |
: Malachi chapter 1, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                               | Septuagint                        |
|:-----------------------------------------------------------------------------|:----------------------------------|
| וארור                                                                        | και επικαταρατος                  |
| נוכל                                                                         | ος ην δυνατος                     |
| ויש                                                                          | και υπηρχεν                       |
| בעדרו                                                                        | εν τω ποιμνιω αυτου               |
| זכר                                                                          | αρσεν                             |
| ונדר                                                                         | και ευχη αυτου                    |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [επ' αυτω]{.potential-difference} |
| וזבח                                                                         | και θυει                          |
| משחת                                                                         | διεφθαρμενον                      |
| לאדני                                                                        | τω κυριω                          |
| כי                                                                           | διοτι                             |
| מלך                                                                          | βασιλευς                          |
| גדול                                                                         | μεγας                             |
| אני                                                                          | εγω ειμι                          |
| אמר                                                                          | λεγει                             |
| יהוה                                                                         | κυριος                            |
| צבאות                                                                        | παντοκρατωρ                       |
| ושמי                                                                         | και το ονομα μου                  |
| נורא •^[Etymological exegesis.] נראה                                         | επιφανες                          |
| בגוים                                                                        | εν τοις εθνεσιν                   |
: Malachi chapter 1, verse 14 { .hover tbl-colwidths="[50,50]"}

## Chapter 2

### Verse 1

| Masoretic text                                                                                                                      | Tov's retroversion             | Septuagint                                                                                                 |
|:------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------|:-----------------------------------------------------------------------------------------------------------|
| ועתה                                                                                                                                |                                | και νυν                                                                                                    |
| אליכם                                                                                                                               |                                | •^[Equivalent of the Hebrew or Greek word(s) occurring elsewhere in the verse or context (transposition).] |
| המצוה                                                                                                                               |                                | η εντολη                                                                                                   |
| הזאת                                                                                                                                |                                | αυτη                                                                                                       |
| [•^[Equivalent of the Hebrew or Greek word(s) occurring elsewhere in the verse or context (transposition).]]{.potential-difference} | [אליכם]{.potential-difference} | [προς υμας]{.potential-difference}                                                                         |
| הכהנים                                                                                                                              |                                | οι ιερεις                                                                                                  |
: Malachi chapter 2, verse 1 { .hover tbl-colwidths="[35,30,35]"}

### Verse 2

| Masoretic text                                                               | Tov's retroversion                 | Septuagint                                 |
|:-----------------------------------------------------------------------------|:-----------------------------------|:-------------------------------------------|
| אם                                                                           |                                    | εαν                                        |
| לא                                                                           |                                    | μη                                         |
| תשמעו                                                                        |                                    | ακουσητε                                   |
| ואם                                                                          |                                    | και εαν                                    |
| לא                                                                           |                                    | μη                                         |
| תשימו                                                                        |                                    | θησθε                                      |
| על                                                                           |                                    | εις                                        |
| לב                                                                           |                                    | την καρδιαν υμων                           |
| לתת                                                                          |                                    | του δουναι                                 |
| כבוד                                                                         |                                    | δοξαν                                      |
| לשמי                                                                         |                                    | τω ονοματι μου                             |
| אמר                                                                          |                                    | λεγει                                      |
| יהוה                                                                         |                                    | κυριος                                     |
| צבאות                                                                        |                                    | παντοκρατωρ                                |
| ושלחתי                                                                       |                                    | και εξαποστελω                             |
| בכם                                                                          |                                    | εφ' υμας                                   |
| את המארה                                                                     |                                    | την καταραν                                |
| וארותי                                                                       |                                    | και επικαταρασομαι                         |
| את ברכותיכם                                                                  |                                    | την ευλογιαν υμων                          |
| וגם                                                                          |                                    | και                                        |
| ארותיה                                                                       |                                    | καταρασομαι αυτην                          |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                    | [και διασκεδασω]{.potential-difference}    |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [את ברכתכם]{.potential-difference} | [την ευλογιαν υμων]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [ולא]{.potential-difference}       | [και ουκ]{.potential-difference}           |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [תהיה]{.potential-difference}      | [εσται]{.potential-difference}             |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [בכם]{.potential-difference}       | [εν υμιν]{.potential-difference}           |
| כי                                                                           |                                    | οτι                                        |
| אינכם                                                                        |                                    | υμεις ου                                   |
| שמים                                                                         |                                    | τιθεσθε                                    |
| על                                                                           |                                    | εις                                        |
| לב                                                                           |                                    | την καρδιαν υμων                           |
: Malachi chapter 2, verse 2 { .hover tbl-colwidths="[35,30,35]"}

### Verse 3

| Masoretic text                                    | Septuagint      |
|:--------------------------------------------------|:----------------|
| הנני                                              | ιδου εγω        |
| גער                                               | αφοριζω         |
| לכם                                               | υμιν            |
| את הזרע •^[Difference in vocalization (reading).] | τον ωμον        |
| וזריתי                                            | και σκορπιω     |
| פרש                                               | ηνυστρον        |
| על                                                | επι             |
| פניכם                                             | τα προσωπα υμων |
| פרש                                               | ηνυστρον        |
| חגיכם                                             | εορτων υμων     |
| ונשא                                              | και λημψομαι    |
| אתכם                                              | υμας            |
| אליו                                              | εις το αυτο     |
: Malachi chapter 2, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| וידעתם           | και επιγνωσεσθε  |
| כי               | διοτι            |
| שלחתי            | εγω εξαπεσταλκα  |
| אליכם            | προς υμας        |
| את המצוה         | την εντολην      |
| הזאת             | ταυτην           |
| להיות            | του ειναι        |
| בריתי            | την διαθηκην μου |
| את               | προς             |
| לוי              | τους λευιτας     |
| אמר              | λεγει            |
| יהוה             | κυριος           |
| צבאות            | παντοκρατωρ      |
: Malachi chapter 2, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                                   | Septuagint                                                                                                           |
|:---------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------|
| בריתי                                                                            | η διαθηκη μου                                                                                                        |
| היתה                                                                             | ην                                                                                                                   |
| אתו                                                                              | μετ' αυτου                                                                                                           |
| החיים                                                                            | της ζωης                                                                                                             |
| והשלום                                                                           | και της ειρηνης                                                                                                      |
| ואתנם                                                                            | και εδωκα                                                                                                            |
| לו                                                                               | αυτω                                                                                                                 |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εν                                                                                                                   |
| מורא                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εν φοβω |
| וייראני                                                                          | φοβεισθαι με                                                                                                         |
| ומפני                                                                            | και απο προσωπου                                                                                                     |
| שמי                                                                              | ονοματος μου                                                                                                         |
| נחת                                                                              | στελλεσθαι                                                                                                           |
| הוא                                                                              | αυτον                                                                                                                |
: Malachi chapter 2, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text   | Septuagint          |
|:-----------------|:--------------------|
| תורת             | νομος               |
| אמת              | αληθειας            |
| היתה             | ην                  |
| בפיהו            | εν τω στοματι αυτου |
| ועולה            | και αδικια          |
| לא               | ουχ                 |
| נמצא             | ευρεθη              |
| בשפתיו           | εν χειλεσιν αυτου   |
| בשלום            | εν ειρηνη           |
| ובמישור          | κατευθυνων          |
| הלך              | επορευθη            |
| אתי              | μετ' εμου           |
| ורבים            | και πολλους         |
| השיב             | επεστρεψεν          |
| מעון             | απο αδικιας         |
: Malachi chapter 2, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| כי               | οτι               |
| שפתי             | χειλη             |
| כהן              | ιερεως            |
| ישמרו            | φυλαξεται         |
| דעת              | γνωσιν            |
| ותורה            | και νομον         |
| יבקשו            | εκζητησουσιν      |
| מפיהו            | εκ στοματος αυτου |
| כי               | διοτι             |
| מלאך             | αγγελος           |
| יהוה             | κυριου            |
| צבאות            | παντοκρατορος     |
| הוא              | εστιν             |
: Malachi chapter 2, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                  | Tov's retroversion              | Septuagint                           |
|:--------------------------------|:--------------------------------|:-------------------------------------|
| ואתם                            |                                 | υμεις δε                             |
| סרתם                            |                                 | εξεκλινατε                           |
| מן                              |                                 | εκ                                   |
| הדרך                            |                                 | της οδου                             |
| [הכשלתם]{.potential-difference} | [רבים]{.potential-difference}   | [και πολλους]{.potential-difference} |
| [רבים]{.potential-difference}   | [הכשלתם]{.potential-difference} | [ησθενησατε]{.potential-difference}  |
| בתורה                           |                                 | εν νομω                              |
| שחתם                            |                                 | διεφθειρατε                          |
| ברית                            |                                 | την διαθηκην                         |
| הלוי                            |                                 | του λευι                             |
| אמר                             |                                 | λεγει                                |
| יהוה                            |                                 | κυριος                               |
| צבאות                           |                                 | παντοκρατωρ                          |
: Malachi chapter 2, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| וגם אני          | καγω            |
| נתתי             | δεδωκα          |
| אתכם             | υμας            |
| נבזים            | εξουδενωμενους  |
| ושפלים           | και παρειμενους |
| לכל              | εις παντα       |
| העם              | τα εθνη         |
| כפי אשר          | ανθ' ων         |
| אינכם            | υμεις ουκ       |
| שמרים            | εφυλαξασθε      |
| את דרכי          | τας οδους μου   |
| ונשאים           | αλλα ελαμβανετε |
| פנים             | προσωπα         |
| בתורה            | εν νομω         |
: Malachi chapter 2, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                 | Tov's retroversion             | Septuagint                            |
|:-------------------------------|:-------------------------------|:--------------------------------------|
| הלוא                           |                                | ουχι                                  |
| [אב]{.potential-difference}    | [אל]{.potential-difference}    | [θεος]{.potential-difference}         |
| אחד                            |                                | εις                                   |
| [לכלנו]{.potential-difference} | [בראנו]{.potential-difference} | [εκτισεν υμας]{.potential-difference} |
| הלוא                           |                                | ουχι                                  |
| [אל]{.potential-difference}    | [אב]{.potential-difference}    | [πατηρ]{.potential-difference}        |
| אחד                            |                                | εις                                   |
| [בראנו]{.potential-difference} | [לכלנו]{.potential-difference} | [παντων υμων]{.potential-difference}  |
| מדוע                           |                                | τι οτι                                |
| נבגד                           |                                | εγκατελιπετε                          |
| איש                            |                                | εκαστος                               |
| באחיו                          |                                | τον αδελφον αυτου                     |
| לחלל                           |                                | του βεβηλωσαι                         |
| ברית                           |                                | την διαθηκην                          |
| אבתינו                         |                                | των πατερων υμων                      |
: Malachi chapter 2, verse 10 { .hover tbl-colwidths="[35,30,35]"}

### Verse 11

| Masoretic text                | Tov's retroversion                                                        | Septuagint                               |
|:------------------------------|:--------------------------------------------------------------------------|:-----------------------------------------|
| בגדה                          |                                                                           | εγκατελειφθη                             |
| יהודה                         |                                                                           | ιουδας                                   |
| ותועבה                        |                                                                           | και βδελυγμα                             |
| נעשתה                         |                                                                           | εγενετο                                  |
| בישראל                        |                                                                           | εν τω ισραηλ                             |
| ובירושלם                      |                                                                           | και εν ιερουσαλημ                        |
| כי                            |                                                                           | διοτι                                    |
| חלל                           |                                                                           | εβεβηλωσεν                               |
| יהודה                         |                                                                           | ιουδας                                   |
| קדש                           |                                                                           | τα αγια                                  |
| יהוה                          |                                                                           | κυριου                                   |
| אשר                           |                                                                           | εν οις                                   |
| אהב                           |                                                                           | ηγαπησεν                                 |
| [ובעל]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] @עלל]{.potential-difference} | [και επετηδευσεν]{.potential-difference} |
| בת אל                         |                                                                           | εις θεους                                |
| נכר                           |                                                                           | αλλοτριους                               |
: Malachi chapter 2, verse 11 { .hover tbl-colwidths="[35,30,35]"}

### Verse 12

| Masoretic text                  | Tov's retroversion                                                                                                                                   | Septuagint                   |
|:--------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------|
| יכרת                            |                                                                                                                                                      | εξολεθρευσει                 |
| יהוה                            |                                                                                                                                                      | κυριος                       |
| לאיש                            |                                                                                                                                                      | τον ανθρωπον                 |
| אשר                             |                                                                                                                                                      | τον                          |
| יעשנה                           |                                                                                                                                                      | ποιουντα ταυτα               |
| [ער]{.potential-difference}     | [עד •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (interchange of R/D, etc.)] <q4a>]{.potential-difference} | [εως]{.potential-difference} |
| וענה •^[Etymological exegesis.] |                                                                                                                                                      | και ταπεινωθη                |
| מאהלי                           |                                                                                                                                                      | εκ σκηνωματων                |
| יעקב                            |                                                                                                                                                      | ιακωβ                        |
| ומגיש                           |                                                                                                                                                      | και εκ προσαγοντων           |
| מנחה                            |                                                                                                                                                      | θυσιαν                       |
| ליהוה                           |                                                                                                                                                      | τω κυριω                     |
| צבאות                           |                                                                                                                                                      | παντοκρατορι                 |
: Malachi chapter 2, verse 12 { .hover tbl-colwidths="[35,30,35]"}

### Verse 13

| Masoretic text                | Tov's retroversion                      | Septuagint                         |
|:------------------------------|:----------------------------------------|:-----------------------------------|
| וזאת                          |                                         | και ταυτα                          |
| [שנית]{.potential-difference} | [שנאית =vs .אט]{.potential-difference}  | [α εμισουν]{.potential-difference} |
| תעשו                          |                                         | εποιειτε                           |
| כסות                          |                                         | εκαλυπτετε                         |
| דמעה                          |                                         | δακρυσιν                           |
| את מזבח                       |                                         | το θυσιαστηριον                    |
| יהוה                          |                                         | κυριου                             |
| בכי                           |                                         | και κλαυθμω                        |
| ואנקה                         |                                         | και στεναγμω                       |
| [מאין]{.potential-difference} | [מאון .yw <q4a>]{.potential-difference} | [εκ κοπων]{.potential-difference}  |
| עוד                           |                                         | ετι                                |
| פנות                          |                                         | αξιον επιβλεψαι                    |
| אל                            |                                         | εις                                |
| המנחה                         |                                         | θυσιαν                             |
| ולקחת                         |                                         | η λαβειν                           |
| רצון                          |                                         | δεκτον                             |
| מידכם                         |                                         | εκ των χειρων υμων                 |
: Malachi chapter 2, verse 13 { .hover tbl-colwidths="[35,30,35]"}

### Verse 14

| Masoretic text                                                                          | Septuagint                                                                       |
|:----------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------|
| ואמרתם                                                                                  | και ειπατε                                                                       |
| על מה                                                                                   | ενεκεν τινος                                                                     |
| על כי                                                                                   | οτι                                                                              |
| יהוה                                                                                    | κυριος                                                                           |
| העיד                                                                                    | διεμαρτυρατο                                                                     |
| בינך                                                                                    | ανα μεσον σου                                                                    |
| ובין                                                                                    | και ανα μεσον                                                                    |
| אשת                                                                                     | γυναικος                                                                         |
| נעוריך                                                                                  | νεοτητος σου                                                                     |
| אשר •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] בה | ην                                                                               |
| אתה בגדתה                                                                               | εγκατελιπες                                                                      |
| בה                                                                                      | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |
| והיא                                                                                    | και αυτη                                                                         |
| חברתך                                                                                   | κοινωνος σου                                                                     |
| ואשת                                                                                    | και γυνη                                                                         |
| בריתך                                                                                   | διαθηκης σου                                                                     |
: Malachi chapter 2, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text                                                                   | Tov's retroversion               | Septuagint                                                                              |
|:---------------------------------------------------------------------------------|:---------------------------------|:----------------------------------------------------------------------------------------|
| ולא                                                                              |                                  | και ουκ                                                                                 |
| [אחד]{.potential-difference}                                                     | [אחר .dr]{.potential-difference} | [αλλος]{.potential-difference}                                                          |
| עשה                                                                              |                                  | εποιησεν                                                                                |
| ושאר                                                                             |                                  | και υπολειμμα                                                                           |
| רוח                                                                              |                                  | πνευματος                                                                               |
| לו                                                                               |                                  | αυτου                                                                                   |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     |                                  | [και ειπατε]{.potential-difference}                                                     |
| ומה                                                                              |                                  | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] και τι |
| [האחד]{.potential-difference}                                                    | [אחר .dr]{.potential-difference} | [αλλο]{.potential-difference}                                                           |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     |                                  | [αλλ' η]{.potential-difference}                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                  | σπερμα                                                                                  |
| מבקש                                                                             |                                  | ζητει                                                                                   |
| זרע                                                                              |                                  | {..σπερμα}                                                                              |
| אלהים                                                                            |                                  | ο θεος                                                                                  |
| ונשמרתם                                                                          |                                  | και φυλαξασθε                                                                           |
| ברוחכם                                                                           |                                  | εν τω πνευματι υμων                                                                     |
| ובאשת                                                                            |                                  | και γυναικα                                                                             |
| נעוריך                                                                           |                                  | νεοτητος σου                                                                            |
| אל                                                                               |                                  | μη                                                                                      |
| יבגד                                                                             |                                  | εγκαταλιπης                                                                             |
: Malachi chapter 2, verse 15 { .hover tbl-colwidths="[35,30,35]"}

### Verse 16

| Masoretic text                      | Tov's retroversion                   | Septuagint                        |
|:------------------------------------|:-------------------------------------|:----------------------------------|
| [כי]{.potential-difference}         | [כי אם <q4a>]{.potential-difference} | [αλλα εαν]{.potential-difference} |
| שנא                                 |                                      | μισησας                           |
| שלח                                 |                                      | εξαποστειλης                      |
| אמר                                 |                                      | λεγει                             |
| יהוה                                |                                      | κυριος                            |
| אלהי                                |                                      | ο θεος                            |
| ישראל                               |                                      | του ισραηλ                        |
| וכסה                                |                                      | και καλυψει                       |
| חמס                                 |                                      | ασεβεια                           |
| על                                  |                                      | επι                               |
| לבושו •^[Etymological exegesis.] לב |                                      | τα ενθυμηματα σου                 |
| אמר                                 |                                      | λεγει                             |
| יהוה                                |                                      | κυριος                            |
| צבאות                               |                                      | παντοκρατωρ                       |
| ונשמרתם                             |                                      | και φυλαξασθε                     |
| ברוחכם                              |                                      | εν τω πνευματι υμων               |
| ולא                                 |                                      | και ου μη                         |
| תבגדו                               |                                      | εγκαταλιπητε                      |
: Malachi chapter 2, verse 16 { .hover tbl-colwidths="[35,30,35]"}

### Verse 17

| Masoretic text                                                               | Tov's retroversion                   | Septuagint                        |
|:-----------------------------------------------------------------------------|:-------------------------------------|:----------------------------------|
| הוגעתם                                                                       |                                      | οι παροξυνοντες                   |
| [יהוה]{.potential-difference}                                                | [אלהים <q4a>]{.potential-difference} | [τον θεον]{.potential-difference} |
| בדבריכם                                                                      |                                      | εν τοις λογοις υμων               |
| ואמרתם                                                                       |                                      | και ειπατε                        |
| במה                                                                          |                                      | εν τινι                           |
| הוגענו                                                                       |                                      | παρωξυναμεν                       |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                      | [αυτον]{.potential-difference}    |
| באמרכם                                                                       |                                      | εν τω λεγειν υμας                 |
| כל                                                                           |                                      | πας                               |
| עשה                                                                          |                                      | ποιων                             |
| רע                                                                           |                                      | πονηρον                           |
| טוב                                                                          |                                      | καλον                             |
| בעיני                                                                        |                                      | ενωπιον                           |
| יהוה                                                                         |                                      | κυριου                            |
| ובהם                                                                         |                                      | και εν αυτοις                     |
| הוא                                                                          |                                      | αυτος                             |
| חפץ                                                                          |                                      | ευδοκησεν                         |
| או                                                                           |                                      | και                               |
| איה                                                                          |                                      | που εστιν                         |
| אלהי                                                                         |                                      | ο θεος                            |
| המשפט                                                                        |                                      | της δικαιοσυνης                   |
: Malachi chapter 2, verse 17 { .hover tbl-colwidths="[35,30,35]"}

## Chapter 3

### Verse 1

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| הנני             | ιδου εγω         |
| שלח              | εξαποστελλω      |
| מלאכי            | τον αγγελον μου  |
| ופנה             | και επιβλεψεται  |
| דרך              | οδον             |
| לפני             | προ προσωπου μου |
| ופתאם            | και εξαιφνης     |
| יבוא             | ηξει             |
| אל               | εις              |
| היכלו            | τον ναον εαυτου  |
| האדון            | κυριος           |
| אשר              | ον               |
| אתם              | υμεις            |
| מבקשים           | ζητειτε          |
| ומלאך            | και ο αγγελος    |
| הברית            | της διαθηκης     |
| אשר              | ον               |
| אתם              | υμεις            |
| חפצים            | θελετε           |
| הנה              | ιδου             |
| בא               | ερχεται          |
| אמר              | λεγει            |
| יהוה             | κυριος           |
| צבאות            | παντοκρατωρ      |
: Malachi chapter 3, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                                               | Tov's retroversion          | Septuagint                            |
|:-----------------------------------------------------------------------------|:----------------------------|:--------------------------------------|
| ומי                                                                          |                             | και τις                               |
| מכלכל                                                                        |                             | υπομενει                              |
| את יום                                                                       |                             | ημεραν                                |
| בואו                                                                         |                             | εισοδου αυτου                         |
| ומי                                                                          |                             | η τις                                 |
| העמד                                                                         |                             | υποστησεται                           |
| בהראותו                                                                      |                             | εν τη οπτασια αυτου                   |
| כי                                                                           |                             | διοτι                                 |
| הוא                                                                          |                             | αυτος                                 |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [בא]{.potential-difference} | [εισπορευεται]{.potential-difference} |
| כאש                                                                          |                             | ως πυρ                                |
| מצרף                                                                         |                             | χωνευτηριου                           |
| וכברית                                                                       |                             | και ως ποα                            |
| מכבסים                                                                       |                             | πλυνοντων                             |
: Malachi chapter 3, verse 2 { .hover tbl-colwidths="[35,30,35]"}

### Verse 3

| Masoretic text                                                                       | Septuagint                                 |
|:-------------------------------------------------------------------------------------|:-------------------------------------------|
| וישב                                                                                 | και καθιειται                              |
| מצרף                                                                                 | χωνευων                                    |
| ומטהר                                                                                | και καθαριζων                              |
| כסף •^[Addition of preposition or particle.]                                         | ως το αργυριον                             |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;וכזהב]{.potential-difference} | [και ως το χρυσιον]{.potential-difference} |
| וטהר                                                                                 | και καθαρισει                              |
| את בני                                                                               | τους υιους                                 |
| לוי                                                                                  | λευι                                       |
| וזקק                                                                                 | και χεει                                   |
| אתם                                                                                  | αυτους                                     |
| כזהב                                                                                 | ως το χρυσιον                              |
| וככסף                                                                                | και ως το αργυριον                         |
| והיו                                                                                 | και εσονται                                |
| ליהוה                                                                                | τω κυριω                                   |
| מגישי                                                                                | προσαγοντες                                |
| מנחה                                                                                 | θυσιαν                                     |
| בצדקה                                                                                | εν δικαιοσυνη                              |
: Malachi chapter 3, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| וערבה            | και αρεσει       |
| ליהוה            | τω κυριω         |
| מנחת             | θυσια            |
| יהודה            | ιουδα            |
| וירושלם          | και ιερουσαλημ   |
| כימי             | καθως αι ημεραι  |
| עולם             | του αιωνος       |
| וכשנים           | και καθως τα ετη |
| קדמניות          | τα εμπροσθεν     |
: Malachi chapter 3, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                                      | Tov's retroversion            | Septuagint                                                                                           |
|:------------------------------------------------------------------------------------|:------------------------------|:-----------------------------------------------------------------------------------------------------|
| וקרבתי                                                                              |                               | και προσαξω                                                                                          |
| אליכם                                                                               |                               | προς υμας                                                                                            |
| למשפט                                                                               |                               | εν κρισει                                                                                            |
| והייתי                                                                              |                               | και εσομαι                                                                                           |
| עד                                                                                  |                               | μαρτυς                                                                                               |
| ממהר                                                                                |                               | ταχυς                                                                                                |
| במכשפים                                                                             |                               | επι τας φαρμακους                                                                                    |
| ובמנאפים                                                                            |                               | και επι τας μοιχαλιδας                                                                               |
| ובנשבעים                                                                            |                               | και επι τους ομνυοντας                                                                               |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}        | [בשמי]{.potential-difference} | [τω ονοματι μου]{.potential-difference}                                                              |
| לשקר                                                                                |                               | επι ψευδει                                                                                           |
| ובעשקי                                                                              |                               | και επι τους αποστερουντας                                                                           |
| שכר                                                                                 |                               | μισθον                                                                                               |
| שכיר                                                                                |                               | μισθωτου                                                                                             |
| •^[Notation in Hebrew column of elements repeated in the translation.] ובעשקי       |                               | και τους καταδυναστευοντας                                                                           |
| אלמנה                                                                               |                               | χηραν                                                                                                |
| •^[Notation in Hebrew column of elements repeated in the translation.] ובעשקי       |                               | και τους κονδυλιζοντας                                                                               |
| ויתום                                                                               |                               | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] και ορφανους        |
| ומטי                                                                                |                               | και τους εκκλινοντας                                                                                 |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;משפט]{.potential-difference} |                               | [κρισιν]{.potential-difference}                                                                      |
| גר                                                                                  |                               | προσηλυτου                                                                                           |
| ולא                                                                                 |                               | και τους μη                                                                                          |
| יראוני                                                                              |                               | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] τους φοβουμενους με |
| אמר                                                                                 |                               | λεγει                                                                                                |
| יהוה                                                                                |                               | κυριος                                                                                               |
| צבאות                                                                               |                               | παντοκρατωρ                                                                                          |
: Malachi chapter 3, verse 5 { .hover tbl-colwidths="[35,30,35]"}

### Verse 6

| Masoretic text                                                               | Septuagint                           |
|:-----------------------------------------------------------------------------|:-------------------------------------|
| כי                                                                           | διοτι                                |
| אני                                                                          | εγω                                  |
| יהוה                                                                         | κυριος                               |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [ο θεος υμων]{.potential-difference} |
| לא                                                                           | και ουκ                              |
| שניתי                                                                        | ηλλοιωμαι                            |
| ואתם                                                                         | και υμεις                            |
| בני                                                                          | υιοι                                 |
| יעקב                                                                         | ιακωβ                                |
| לא                                                                           | ουκ                                  |
| כליתם                                                                        | απεχεσθε                             |
: Malachi chapter 3, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                 | Tov's retroversion                                                                                               | Septuagint                               |
|:-------------------------------|:-----------------------------------------------------------------------------------------------------------------|:-----------------------------------------|
| [למימי]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [απο των αδικιων]{.potential-difference} |
| אבתיכם                         |                                                                                                                  | των πατερων υμων                         |
| סרתם                           |                                                                                                                  | εξεκλινατε                               |
| מחקי                           |                                                                                                                  | νομιμα μου                               |
| ולא                            |                                                                                                                  | και ουκ                                  |
| שמרתם                          |                                                                                                                  | εφυλαξασθε                               |
| שובו                           |                                                                                                                  | επιστρεψατε                              |
| אלי                            |                                                                                                                  | προς με                                  |
| ואשובה                         |                                                                                                                  | και επιστραφησομαι                       |
| אליכם                          |                                                                                                                  | προς υμας                                |
| אמר                            |                                                                                                                  | λεγει                                    |
| יהוה                           |                                                                                                                  | κυριος                                   |
| צבאות                          |                                                                                                                  | παντοκρατωρ                              |
| ואמרתם                         |                                                                                                                  | και ειπατε                               |
| במה                            |                                                                                                                  | εν τινι                                  |
| נשוב                           |                                                                                                                  | επιστρεψωμεν                             |
: Malachi chapter 3, verse 7 { .hover tbl-colwidths="[35,30,35]"}

### Verse 8

| Masoretic text                                                                                                                              | Tov's retroversion                                                                                                                   | Septuagint                                                                                                          |
|:--------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------|
| [היקבע]{.potential-difference}                                                                                                              | [היעקב •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)]]{.potential-difference} | [ει πτερνιει]{.potential-difference}                                                                                |
| אדם                                                                                                                                         |                                                                                                                                      | ανθρωπος                                                                                                            |
| אלהים                                                                                                                                       |                                                                                                                                      | θεον                                                                                                                |
| כי                                                                                                                                          |                                                                                                                                      | διοτι                                                                                                               |
| אתם                                                                                                                                         |                                                                                                                                      | υμεις                                                                                                               |
| קבעים •^[Etymological exegesis.] עקב •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)]  |                                                                                                                                      | πτερνιζετε                                                                                                          |
| אתי                                                                                                                                         |                                                                                                                                      | με                                                                                                                  |
| ואמרתם                                                                                                                                      |                                                                                                                                      | και ερειτε                                                                                                          |
| במה                                                                                                                                         |                                                                                                                                      | εν τινι                                                                                                             |
| קבענוך •^[Etymological exegesis.] עקב •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)] |                                                                                                                                      | επτερνικαμεν σε                                                                                                     |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                                |                                                                                                                                      | [οτι •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] εισιν]{.potential-difference} |
| המעשר                                                                                                                                       |                                                                                                                                      | τα επιδεκατα                                                                                                        |
| והתרומה                                                                                                                                     |                                                                                                                                      | και αι απαρχαι                                                                                                      |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                                |                                                                                                                                      | [μεθ' υμων]{.potential-difference}                                                                                  |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                            |                                                                                                                                      | εισιν                                                                                                               |
: Malachi chapter 3, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text                                                                                                                             | Tov's retroversion                                                                                | Septuagint                                |
|:-------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------|:------------------------------------------|
| [במארה]{.potential-difference}                                                                                                             | [ומראים <q4a>]{.potential-difference}                                                             | [και αποβλεποντες]{.potential-difference} |
| אתם                                                                                                                                        |                                                                                                   | υμεις                                     |
| [נארים]{.potential-difference}                                                                                                             | [ראים <q4a>]{.potential-difference}                                                               | [αποβλεπετε]{.potential-difference}       |
| ואתי                                                                                                                                       |                                                                                                   | και εμε                                   |
| אתם                                                                                                                                        |                                                                                                   | υμεις                                     |
| קבעים •^[Etymological exegesis.] עקב •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)] |                                                                                                   | πτερνιζετε                                |
| הגוי                                                                                                                                       |                                                                                                   | το εθνος                                  |
| [כלו]{.potential-difference}                                                                                                               | [כלו •^[Difference in vocalization (reading).] •^[Etymological exegesis.]]{.potential-difference} | [συνετελεσθη]{.potential-difference}      |
: Malachi chapter 3, verse 9 { .hover tbl-colwidths="[35,30,35]"}

### Verse 10

| Masoretic text                                                                                                                      | Tov's retroversion              | Septuagint                                                                                                 |
|:------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------|:-----------------------------------------------------------------------------------------------------------|
| הביאו                                                                                                                               |                                 | και εισηνεγκατε                                                                                            |
| את כל                                                                                                                               |                                 | παντα                                                                                                      |
| המעשר                                                                                                                               |                                 | τα εκφορια                                                                                                 |
| אל                                                                                                                                  |                                 | εις                                                                                                        |
| בית האוצר                                                                                                                           |                                 | τους θησαυρους                                                                                             |
| [•^[Equivalent of the Hebrew or Greek word(s) occurring elsewhere in the verse or context (transposition).]]{.potential-difference} | [ובביתו]{.potential-difference} | [και εν τω οικω αυτου]{.potential-difference}                                                              |
| ויהי                                                                                                                                |                                 | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] και εσται                 |
| טרף                                                                                                                                 |                                 | η διαρπαγη αυτου                                                                                           |
| בביתי                                                                                                                               |                                 | •^[Equivalent of the Hebrew or Greek word(s) occurring elsewhere in the verse or context (transposition).] |
| ובחנוני                                                                                                                             |                                 | επισκεψασθε                                                                                                |
| נא                                                                                                                                  |                                 | δη                                                                                                         |
| בזאת                                                                                                                                |                                 | εν τουτω                                                                                                   |
| אמר                                                                                                                                 |                                 | λεγει                                                                                                      |
| יהוה                                                                                                                                |                                 | κυριος                                                                                                     |
| צבאות                                                                                                                               |                                 | παντοκρατωρ                                                                                                |
| אם                                                                                                                                  |                                 | εαν                                                                                                        |
| לא                                                                                                                                  |                                 | μη                                                                                                         |
| אפתח                                                                                                                                |                                 | ανοιξω                                                                                                     |
| לכם                                                                                                                                 |                                 | υμιν                                                                                                       |
| את ארבות                                                                                                                            |                                 | τους καταρρακτας                                                                                           |
| השמים                                                                                                                               |                                 | του ουρανου                                                                                                |
| והריקתי                                                                                                                             |                                 | και εκχεω                                                                                                  |
| לכם                                                                                                                                 |                                 | υμιν                                                                                                       |
| ברכה                                                                                                                                |                                 | την ευλογιαν μου                                                                                           |
| עד                                                                                                                                  |                                 | εως                                                                                                        |
| בלי די                                                                                                                              |                                 | του ικανωθηναι                                                                                             |
: Malachi chapter 3, verse 10 { .hover tbl-colwidths="[35,30,35]"}

### Verse 11

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| וגערתי           | και διαστελω |
| לכם              | υμιν         |
| באכל             | εις βρωσιν   |
| ולא              | και ου μη    |
| ישחת             | διαφθειρω    |
| לכם              | υμων         |
| את פרי           | τον καρπον   |
| האדמה            | της γης      |
| ולא              | και ου μη    |
| תשכל             | ασθενηση     |
| לכם              | υμων         |
| הגפן             | η αμπελος    |
| בשדה             | η εν τω αγρω |
| אמר              | λεγει        |
| יהוה             | κυριος       |
| צבאות            | παντοκρατωρ  |
: Malachi chapter 3, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| ואשרו            | και μακαριουσιν |
| אתכם             | υμας            |
| כל               | παντα           |
| הגוים            | τα εθνη         |
| כי               | διοτι           |
| תהיו             | εσεσθε          |
| אתם              | υμεις           |
| ארץ              | γη              |
| חפץ              | θελητη          |
| אמר              | λεγει           |
| יהוה             | κυριος          |
| צבאות            | παντοκρατωρ     |
: Malachi chapter 3, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| חזקו             | εβαρυνατε        |
| עלי              | επ' εμε          |
| דבריכם           | τους λογους υμων |
| אמר              | λεγει            |
| יהוה             | κυριος           |
| ואמרתם           | και ειπατε       |
| מה               | εν τινι          |
| נדברנו           | κατελαλησαμεν    |
| עליך             | κατα σου         |
: Malachi chapter 3, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                | Septuagint         |
|:----------------------------------------------|:-------------------|
| אמרתם                                         | ειπατε             |
| שוא                                           | ματαιος            |
| עבד •^[Difference in vocalization (reading).] | ο δουλευων         |
| אלהים                                         | θεω                |
| ומה                                           | και τι             |
| בצע                                           | πλεον              |
| כי                                            | οτι                |
| שמרנו                                         | εφυλαξαμεν         |
| משמרתו                                        | τα φυλαγματα αυτου |
| וכי                                           | και διοτι          |
| הלכנו                                         | επορευθημεν        |
| קדרנית                                        | ικεται             |
| מפני                                          | προ προσωπου       |
| יהוה                                          | κυριου             |
| צבאות                                         | παντοκρατορος      |
: Malachi chapter 3, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text                                                                           | Tov's retroversion                | Septuagint                          |
|:-----------------------------------------------------------------------------------------|:----------------------------------|:------------------------------------|
| ועתה                                                                                     |                                   | και νυν                             |
| אנחנו                                                                                    |                                   | ημεις                               |
| מאשרים                                                                                   |                                   | μακαριζομεν                         |
| [זדים]{.potential-difference}                                                            | [זרים .dr]{.potential-difference} | [αλλοτριους]{.potential-difference} |
| גם                                                                                       |                                   | και                                 |
| נבנו                                                                                     |                                   | ανοικοδομουνται                     |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;כל <3.19>]{.potential-difference} |                                   | [παντες]{.potential-difference}     |
| עשי                                                                                      |                                   | ποιουντες                           |
| רשעה                                                                                     |                                   | ανομα                               |
| גם                                                                                       |                                   | και                                 |
| בחנו                                                                                     |                                   | αντεστησαν                          |
| אלהים                                                                                    |                                   | θεω                                 |
| וימלטו                                                                                   |                                   | και εσωθησαν                        |
: Malachi chapter 3, verse 15 { .hover tbl-colwidths="[35,30,35]"}

### Verse 16

| Masoretic text                                           | Septuagint             |
|:---------------------------------------------------------|:-----------------------|
| אז                                                       | ταυτα                  |
| נדברו                                                    | κατελαλησαν            |
| יראי                                                     | οι φοβουμενοι          |
| יהוה                                                     | τον κυριον             |
| איש                                                      | εκαστος                |
| את רעהו •^[Difference in preposition or particle.] <q4a> | προς τον πλησιον αυτου |
| ויקשב                                                    | και προσεσχεν          |
| יהוה                                                     | κυριος                 |
| וישמע                                                    | και εισηκουσεν         |
| ויכתב                                                    | και εγραψεν            |
| ספר                                                      | βιβλιον                |
| זכרון                                                    | μνημοσυνου             |
| לפניו                                                    | ενωπιον αυτου          |
| ליראי                                                    | τοις φοβουμενοις       |
| יהוה                                                     | τον κυριον             |
| ולחשבי                                                   | και ευλαβουμενοις      |
| שמו                                                      | το ονομα αυτου         |
: Malachi chapter 3, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| והיו <q4a>       | και εσονται     |
| לי               | μοι             |
| אמר              | λεγει           |
| יהוה             | κυριος          |
| צבאות            | παντοκρατωρ     |
| ליום             | εις ημεραν      |
| אשר              | ην              |
| אני              | εγω             |
| עשה              | ποιω            |
| סגלה             | εις περιποιησιν |
| וחמלתי           | και αιρετιω     |
| עליהם            | αυτους          |
| כאשר             | ον τροπον       |
| יחמל             | αιρετιζει       |
| איש              | ανθρωπος        |
| על בנו           | τον υιον αυτου  |
| העבד             | τον δουλευοντα  |
| אתו              | αυτω            |
: Malachi chapter 3, verse 17 { .hover tbl-colwidths="[50,50]"}

### Verse 18

| Masoretic text                | Tov's retroversion                | Septuagint                                    |
|:------------------------------|:----------------------------------|:----------------------------------------------|
| ושבתם                         |                                   | και επιστραφησεσθε                            |
| וראיתם                        |                                   | και οψεσθε                                    |
| בין                           |                                   | ανα μεσον                                     |
| צדיק                          |                                   | δικαιου                                       |
| [לרשע]{.potential-difference} | [ובין רשע]{.potential-difference} | [και ανα μεσον ανομου]{.potential-difference} |
| בין                           |                                   | και ανα μεσον                                 |
| עבד                           |                                   | του δουλευοντος                               |
| אלהים                         |                                   | θεω                                           |
| לאשר                          |                                   | και του                                       |
| לא                            |                                   | μη                                            |
| עבדו                          |                                   | δουλευοντος                                   |
: Malachi chapter 3, verse 18 { .hover tbl-colwidths="[35,30,35]"}

### Verse 19

| Masoretic text                                                                      | Tov's retroversion                | Septuagint                             |
|:------------------------------------------------------------------------------------|:----------------------------------|:---------------------------------------|
| כי                                                                                  |                                   | διοτι                                  |
| הנה                                                                                 |                                   | ιδου                                   |
| היום                                                                                |                                   | ημερα                                  |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}        |                                   | [κυριου]{.potential-difference}        |
| בא                                                                                  |                                   | ερχεται                                |
| בער                                                                                 |                                   | καιομενη                               |
| כתנור                                                                               |                                   | ως κλιβανος                            |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;ולהט]{.potential-difference} |                                   | [και φλεξει]{.potential-difference}    |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;אתם]{.potential-difference}  |                                   | [αυτους]{.potential-difference}        |
| והיו                                                                                |                                   | και εσονται                            |
| כל                                                                                  |                                   | παντες                                 |
| [זדים]{.potential-difference}                                                       | [זרים .dr]{.potential-difference} | [οι αλλογενεις]{.potential-difference} |
| וכל                                                                                 |                                   | και παντες                             |
| עשה                                                                                 |                                   | οι ποιουντες                           |
| רשעה                                                                                |                                   | ανομα                                  |
| קש                                                                                  |                                   | καλαμη                                 |
| ולהט                                                                                |                                   | και αναψει                             |
| אתם                                                                                 |                                   | αυτους                                 |
| היום                                                                                |                                   | η ημερα                                |
| הבא                                                                                 |                                   | η ερχομενη                             |
| אמר                                                                                 |                                   | λεγει                                  |
| יהוה                                                                                |                                   | κυριος                                 |
| צבאות                                                                               |                                   | παντοκρατωρ                            |
| אשר                                                                                 |                                   | και                                    |
| לא                                                                                  |                                   | ου μη                                  |
| יעזב •^[Change from active to passive form in verbs.]                               |                                   | υπολειφθη                              |
| להם                                                                                 |                                   | εξ αυτων                               |
| שרש                                                                                 |                                   | ριζα                                   |
| וענף                                                                                |                                   | ουδε κλημα                             |
: Malachi chapter 3, verse 19 { .hover tbl-colwidths="[35,30,35]"}

### Verse 20

| Masoretic text   | Septuagint             |
|:-----------------|:-----------------------|
| וזרחה            | και ανατελει           |
| לכם              | υμιν                   |
| יראי             | τοις φοβουμενοις       |
| שמי              | το ονομα μου           |
| שמש              | ηλιος                  |
| צדקה             | δικαιοσυνης            |
| ומרפא            | και ιασις              |
| בכנפיה           | εν ταις πτερυξιν αυτου |
| ויצאתם           | και εξελευσεσθε        |
| ופשתם            | και σκιρτησετε         |
| כעגלי            | ως μοσχαρια            |
| מרבק             | εκ δεσμων ανειμενα     |
: Malachi chapter 3, verse 20 { .hover tbl-colwidths="[50,50]"}

### Verse 21

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| ועסותם           | και καταπατησετε |
| רשעים            | ανομους          |
| כי               | διοτι            |
| יהיו             | εσονται          |
| אפר              | σποδος           |
| תחת              | υποκατω          |
| כפות רגליכם      | των ποδων υμων   |
| ביום             | εν τη ημερα      |
| אשר              | η                |
| אני              | εγω              |
| עשה              | ποιω             |
| אמר              | λεγει            |
| יהוה             | κυριος           |
| צבאות            | παντοκρατωρ      |
: Malachi chapter 3, verse 21 { .hover tbl-colwidths="[50,50]"}

### Verse 22

| Masoretic text   | Septuagint          |
|:-----------------|:--------------------|
| זכרו             | μνησθητε [24]       |
| תורת             | νομου [24]          |
| משה              | μωυση [24]          |
| עבדי             | του δουλου μου [24] |
| אשר              | καθοτι [24]         |
| צויתי            | ενετειλαμην [24]    |
| אותו             | αυτω [24]           |
| בחרב             | εν χωρηβ [24]       |
| על               | προς [24]           |
| כל               | παντα [24]          |
| ישראל            | τον ισραηλ [24]     |
| חקים             | προσταγματα [24]    |
| ומשפטים          | και δικαιωματα [24] |
: Malachi chapter 3, verse 22 { .hover tbl-colwidths="[50,50]"}

### Verse 23

| Masoretic text                          | Septuagint        |
|:----------------------------------------|:------------------|
| הנה                                     | και ιδου [22]     |
| אנכי                                    | εγω [22]          |
| שלח                                     | αποστελλω [22]    |
| לכם                                     | υμιν [22]         |
| את אליה                                 | ηλιαν [22]        |
| הנביא                                   | τον θεσβιτην [22] |
| לפני                                    | πριν [22]         |
| בוא                                     | ελθειν [22]       |
| יום                                     | ημεραν [22]       |
| יהוה                                    | κυριου [22]       |
| הגדול                                   | την μεγαλην [22]  |
| והנורא •^[Etymological exegesis.] ונראה | και επιφανη [22]  |
: Malachi chapter 3, verse 23 { .hover tbl-colwidths="[50,50]"}

### Verse 24

| Masoretic text   | Septuagint             |
|:-----------------|:-----------------------|
| והשיב            | ος αποκαταστησει [23]  |
| לב               | καρδιαν [23]           |
| אבות             | πατρος [23]            |
| על               | προς [23]              |
| בנים             | υιον [23]              |
| ולב              | και καρδιαν [23]       |
| בנים             | ανθρωπου [23]          |
| על               | προς [23]              |
| אבותם            | τον πλησιον αυτου [23] |
| פן               | μη [23]                |
| אבוא             | ελθω [23]              |
| והכיתי           | και παταξω [23]        |
| את הארץ          | την γην [23]           |
| חרם              | αρδην [23]             |
: Malachi chapter 3, verse 24 { .hover tbl-colwidths="[50,50]"}

