# Nahum

The tables below show the Hebrew and Greek texts aligned vertically. When a Hebrew verse number does not match the Greek counterpart, the editors added a note with the corresponding verse number between square brackets.

## Chapter 1

### Verse 1

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| משא              | λημμα         |
| נינוה            | νινευη        |
| ספר              | βιβλιον       |
| חזון             | ορασεως       |
| נחום             | ναουμ         |
| האלקשי           | του ελκεσαιου |
: Nahum chapter 1, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint             |
|:-----------------|:-----------------------|
| אל               | θεος                   |
| קנוא             | ζηλωτης                |
| ונקם             | και εκδικων            |
| יהוה             | κυριος                 |
| נקם              | εκδικων                |
| יהוה             | κυριος                 |
| ובעל חמה         | μετα θυμου             |
| נקם              | εκδικων                |
| יהוה             | κυριος                 |
| לצריו            | τους υπεναντιους αυτου |
| ונוטר            | και εξαιρων            |
| הוא              | αυτος                  |
| לאיביו           | τους εχθρους αυτου     |
: Nahum chapter 1, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                       | Septuagint       |
|:-------------------------------------|:-----------------|
| יהוה                                 | κυριος           |
| ארך אפים                             | μακροθυμος       |
| *וגדול **וגדל                        | και μεγαλη       |
| כח                                   | η ισχυς αυτου    |
| ונקה                                 | και αθωων        |
| לא                                   | ουκ              |
| ינקה                                 | αθωωσει          |
| יהוה                                 | κυριος           |
| בסופה •^[Etymological exegesis.] סוף | εν συντελεια     |
| ובשערה                               | και εν συσσεισμω |
| דרכו                                 | η οδος αυτου     |
| וענן                                 | και νεφελαι      |
| אבק                                  | κονιορτος        |
| רגליו                                | ποδων αυτου      |
: Nahum chapter 1, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| גוער             | απειλων            |
| בים              | θαλασση            |
| ויבשהו           | και ξηραινων αυτην |
| וכל              | και παντας         |
| הנהרות           | τους ποταμους      |
| החריב            | εξερημων           |
| אמלל             | ωλιγωθη            |
| בשן              | η βασανιτις        |
| וכרמל            | και ο καρμηλος     |
| ופרח             | και τα εξανθουντα  |
| לבנון            | του λιβανου        |
| אמלל             | εξελιπεν           |
: Nahum chapter 1, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                          | Septuagint         |
|:----------------------------------------|:-------------------|
| הרים                                    | τα ορη             |
| רעשו                                    | εσεισθησαν         |
| ממנו                                    | απ' αυτου          |
| והגבעות                                 | και οι βουνοι      |
| התמגגו                                  | εσαλευθησαν        |
| ותשא •^[Etymological exegesis.] שאה =vs | και ανεσταλη       |
| הארץ                                    | η γη               |
| מפניו                                   | απο προσωπου αυτου |
| ותבל                                    | η συμπασα          |
| וכל                                     | και παντες         |
| ישבי                                    | οι κατοικουντες    |
| בה                                      | εν αυτη            |
: Nahum chapter 1, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text               | Tov's retroversion               | Septuagint                     |
|:-----------------------------|:---------------------------------|:-------------------------------|
| לפני                         |                                  | απο προσωπου                   |
| זעמו                         |                                  | οργης αυτου                    |
| מי                           |                                  | τις                            |
| יעמוד                        |                                  | υποστησεται                    |
| ומי                          |                                  | και τις                        |
| יקום                         |                                  | αντιστησεται                   |
| בחרון                        |                                  | εν οργη                        |
| אפו                          |                                  | θυμου αυτου                    |
| חמתו                         |                                  | ο θυμος αυτου                  |
| נתכה                         |                                  | τηκει                          |
| [כאש]{.potential-difference} | [ראש .kr]{.potential-difference} | [αρχας]{.potential-difference} |
| והצרים                       |                                  | και αι πετραι                  |
| נתצו                         |                                  | διεθρυβησαν                    |
| ממנו                         |                                  | απ' αυτου                      |
: Nahum chapter 1, verse 6 { .hover tbl-colwidths="[35,30,35]"}

### Verse 7

| Masoretic text                 | Tov's retroversion                                                                                               | Septuagint                                      |
|:-------------------------------|:-----------------------------------------------------------------------------------------------------------------|:------------------------------------------------|
| טוב                            |                                                                                                                  | χρηστος                                         |
| יהוה                           |                                                                                                                  | κυριος                                          |
| [למעוז]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [τοις υπομενουσιν αυτον]{.potential-difference} |
| ביום                           |                                                                                                                  | εν ημερα                                        |
| צרה                            |                                                                                                                  | θλιψεως                                         |
| וידע                           |                                                                                                                  | και γινωσκων                                    |
| חסי                            |                                                                                                                  | τους ευλαβουμενους                              |
| בו                             |                                                                                                                  | αυτον                                           |
: Nahum chapter 1, verse 7 { .hover tbl-colwidths="[35,30,35]"}

### Verse 8

| Masoretic text                       | Septuagint             |
|:-------------------------------------|:-----------------------|
| ובשטף                                | και εν κατακλυσμω      |
| עבר •^[Etymological exegesis.]       | πορειας                |
| כלה                                  | συντελειαν             |
| יעשה                                 | ποιησεται              |
| מקומה •^[Etymological exegesis.] קום | τους επεγειρομενους    |
| ואיביו                               | και τους εχθρους αυτου |
| ירדף                                 | διωξεται               |
| חשך                                  | σκοτος                 |
: Nahum chapter 1, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                                               | Septuagint                           |
|:-----------------------------------------------------------------------------|:-------------------------------------|
| מה                                                                           | τι                                   |
| תחשבון                                                                       | λογιζεσθε                            |
| אל                                                                           | επι                                  |
| יהוה                                                                         | τον κυριον                           |
| כלה                                                                          | συντελειαν                           |
| הוא                                                                          | αυτος                                |
| עשה                                                                          | ποιησεται                            |
| לא                                                                           | ουκ                                  |
| תקום •^[Etymological exegesis.] נקם                                          | εκδικησει                            |
| פעמים                                                                        | δις                                  |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [επι το αυτο]{.potential-difference} |
| צרה •^[Addition of preposition or particle.]                                 | εν θλιψει                            |
: Nahum chapter 1, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                        | Tov's retroversion                                                                                                                                    | Septuagint                              |
|:------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------|
| כי                                                    |                                                                                                                                                       | οτι                                     |
| עד                                                    |                                                                                                                                                       | εως                                     |
| [סירים]{.potential-difference}                        | [יסודם •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (interchange of R/D, etc.)] .y-]{.potential-difference} | [θεμελιου αυτων]{.potential-difference} |
| סבכים                                                 |                                                                                                                                                       | χερσωθησεται                            |
| וכסבאם •^[Etymological exegesis.] סיר                 |                                                                                                                                                       | και ως σμιλαξ                           |
| [סבואים]{.potential-difference}                       | [סבוכים .אk]{.potential-difference}                                                                                                                   | [περιπλεκομενη]{.potential-difference}  |
| אכלו •^[Change from active to passive form in verbs.] |                                                                                                                                                       | βρωθησεται                              |
| כקש                                                   |                                                                                                                                                       | και ως καλαμη                           |
| יבש                                                   |                                                                                                                                                       | ξηρασιας                                |
| מלא                                                   |                                                                                                                                                       | μεστη                                   |
: Nahum chapter 1, verse 10 { .hover tbl-colwidths="[35,30,35]"}

### Verse 11

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| ממך              | εκ σου       |
| יצא              | εξελευσεται  |
| חשב              | λογισμος     |
| על               | κατα         |
| יהוה             | του κυριου   |
| רעה              | πονηρα       |
| יעץ              | λογιζομενος  |
| בליעל            | εναντια      |
: Nahum chapter 1, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                    | Tov's retroversion                                                                                    | Septuagint                                                                             |
|:----------------------------------|:------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| כה                                |                                                                                                       | ταδε                                                                                   |
| אמר                               |                                                                                                       | λεγει                                                                                  |
| יהוה                              |                                                                                                       | κυριος                                                                                 |
| [אם שלמים]{.potential-difference} | [משל מים •^[Different word-division reflected in the parent text of the LXX.]]{.potential-difference} | [καταρχων υδατων]{.potential-difference}                                               |
| [וכן]{.potential-difference}      |                                                                                                       | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| רבים                              |                                                                                                       | πολλων                                                                                 |
| וכן                               |                                                                                                       | και ουτως                                                                              |
| נגזו                              |                                                                                                       | διασταλησονται                                                                         |
| [ועבר]{.potential-difference}     |                                                                                                       | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| וענתך •^[Etymological exegesis.]  |                                                                                                       | και η ακοη σου                                                                         |
| לא                                |                                                                                                       | ουκ                                                                                    |
| אענך •^[Etymological exegesis.]   |                                                                                                       | ενακουσθησεται                                                                         |
| עוד                               |                                                                                                       | ετι                                                                                    |
: Nahum chapter 1, verse 12 { .hover tbl-colwidths="[35,30,35]"}

### Verse 13

| Masoretic text   | Septuagint           |
|:-----------------|:---------------------|
| ועתה             | και νυν              |
| אשבר             | συντριψω             |
| מטהו             | την ραβδον αυτου     |
| מעליך            | απο σου              |
| ומוסרתיך         | και τους δεσμους σου |
| אנתק             | διαρρηξω             |
: Nahum chapter 1, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text   | Septuagint          |
|:-----------------|:--------------------|
| וצוה             | και εντελειται      |
| עליך             | υπερ σου            |
| יהוה             | κυριος              |
| לא               | ου                  |
| יזרע             | σπαρησεται          |
| משמך             | εκ του ονοματος σου |
| עוד              | ετι                 |
| מבית             | εξ οικου            |
| אלהיך            | θεου σου            |
| אכרית            | εξολεθρευσω         |
| פסל              | τα γλυπτα           |
| ומסכה            | και χωνευτα         |
| אשים             | θησομαι             |
| קברך             | ταφην σου           |
| כי               | οτι                 |
| קלות             | ταχεις              |
: Nahum chapter 1, verse 14 { .hover tbl-colwidths="[50,50]"}

## Chapter 2

### Verse 1

| Masoretic text                                                                   | Septuagint                                                                                                                 |
|:---------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------|
| הנה                                                                              | ιδου                                                                                                                       |
| על                                                                               | επι                                                                                                                        |
| ההרים                                                                            | τα ορη                                                                                                                     |
| רגלי                                                                             | οι ποδες                                                                                                                   |
| מבשר                                                                             | ευαγγελιζομενου                                                                                                            |
| משמיע                                                                            | και απαγγελλοντος                                                                                                          |
| שלום                                                                             | ειρηνην                                                                                                                    |
| חגי                                                                              | εορταζε                                                                                                                    |
| יהודה                                                                            | ιουδα                                                                                                                      |
| חגיך                                                                             | τας εορτας σου                                                                                                             |
| שלמי                                                                             | αποδος                                                                                                                     |
| נדריך                                                                            | τας ευχας σου                                                                                                              |
| כי                                                                               | διοτι                                                                                                                      |
| לא                                                                               | ου μη                                                                                                                      |
| יוסיף                                                                            | προσθησωσιν                                                                                                                |
| עוד                                                                              | ετι                                                                                                                        |
| *לעבור **לעבר                                                                    | του διελθειν                                                                                                               |
| בך                                                                               | δια σου                                                                                                                    |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εις                                                                                                                        |
| בליעל •^[Etymological exegesis.] בלה                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις παλαιωσιν |
| כלה •^[Difference in vocalization (reading).] •^[Etymological exegesis.]         | συντετελεσται                                                                                                              |
| נכרת                                                                             | εξηρται                                                                                                                    |
: Nahum chapter 2, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                 | Tov's retroversion                | Septuagint                            |
|:-----------------------------------------------|:----------------------------------|:--------------------------------------|
| עלה                                            |                                   | ανεβη                                 |
| [מפיץ]{.potential-difference}                  | [מפיח .cx]{.potential-difference} | [εμφυσων]{.potential-difference}      |
| על                                             |                                   | εις                                   |
| פניך                                           |                                   | προσωπον σου                          |
| [נצור]{.potential-difference}                  | [נוצר]{.potential-difference}     | [εξαιρουμενος]{.potential-difference} |
| מצרה •^[Difference in vocalization (reading).] |                                   | εκ θλιψεως                            |
| צפה                                            |                                   | σκοπευσον                             |
| דרך                                            |                                   | οδον                                  |
| חזק                                            |                                   | κρατησον                              |
| מתנים                                          |                                   | οσφυος                                |
| אמץ                                            |                                   | ανδρισαι                              |
| כח                                             |                                   | τη ισχυι                              |
| מאד                                            |                                   | σφοδρα                                |
: Nahum chapter 2, verse 2 { .hover tbl-colwidths="[35,30,35]"}

### Verse 3

| Masoretic text                 | Tov's retroversion             | Septuagint                                 |
|:-------------------------------|:-------------------------------|:-------------------------------------------|
| כי                             |                                | διοτι                                      |
| שב                             |                                | απεστρεψεν                                 |
| יהוה                           |                                | κυριος                                     |
| את גאון                        |                                | την υβριν                                  |
| יעקב                           |                                | ιακωβ                                      |
| כגאון                          |                                | καθως υβριν                                |
| ישראל                          |                                | του ισραηλ                                 |
| כי                             |                                | διοτι                                      |
| [בקקום]{.potential-difference} | [בקקים]{.potential-difference} | [εκτινασσοντες]{.potential-difference}     |
| [בקקים]{.potential-difference} | [בקקום]{.potential-difference} | [εξετιναξαν αυτους]{.potential-difference} |
| וזמריהם                        |                                | και τα κληματα αυτων                       |
| שחתו                           |                                | διεφθειραν                                 |
: Nahum chapter 2, verse 3 { .hover tbl-colwidths="[35,30,35]"}

### Verse 4

| Masoretic text                                                                    | Tov's retroversion                                                      | Septuagint                             |
|:----------------------------------------------------------------------------------|:------------------------------------------------------------------------|:---------------------------------------|
| מגן                                                                               |                                                                         | οπλα                                   |
| גבריהו                                                                            |                                                                         | δυναστειας αυτων                       |
| [מאדם]{.potential-difference}                                                     | [מאדם •^[Difference in vocalization (reading).]]{.potential-difference} | [εξ ανθρωπων]{.potential-difference}   |
| אנשי                                                                              |                                                                         | ανδρας                                 |
| חיל                                                                               |                                                                         | δυνατους                               |
| מתלעים •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] עלל |                                                                         | εμπαιζοντας                            |
| באש                                                                               |                                                                         | εν πυρι                                |
| פלדות                                                                             |                                                                         | αι ηνιαι                               |
| הרכב                                                                              |                                                                         | των αρματων αυτων                      |
| ביום                                                                              |                                                                         | εν ημερα                               |
| הכינו                                                                             |                                                                         | ετοιμασιας αυτου                       |
| [והברשים]{.potential-difference}                                                  | [והפרשים .bp]{.potential-difference}                                    | [και οι ιππεις]{.potential-difference} |
| הרעלו                                                                             |                                                                         | θορυβηθησονται                         |
: Nahum chapter 2, verse 4 { .hover tbl-colwidths="[35,30,35]"}

### Verse 5

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| בחוצות           | εν ταις οδοις      |
| יתהוללו          | και συγχυθησονται  |
| הרכב             | τα αρματα          |
| ישתקשקון         | και συμπλακησονται |
| ברחבות           | εν ταις πλατειαις  |
| מראיהן           | η ορασις αυτων     |
| כלפידם           | ως λαμπαδες πυρος  |
| כברקים           | και ως αστραπαι    |
| ירוצצו           | διατρεχουσαι       |
: Nahum chapter 2, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text                                                               | Septuagint                             |
|:-----------------------------------------------------------------------------|:---------------------------------------|
| יזכר                                                                         | και μνησθησονται                       |
| אדיריו                                                                       | οι μεγιστανες αυτων                    |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [και φευξονται]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [ημερας]{.potential-difference}        |
| יכשלו                                                                        | και ασθενησουσιν                       |
| *בהלכותם **בהליכתם                                                           | εν τη πορεια αυτων                     |
| ימהרו                                                                        | και σπευσουσιν                         |
| חומתה                                                                        | επι τα τειχη                           |
| והכן                                                                         | και ετοιμασουσιν                       |
| הסכך                                                                         | τας προφυλακας αυτων                   |
: Nahum chapter 2, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| שערי             | πυλαι           |
| הנהרות           | των ποταμων     |
| נפתחו            | διηνοιχθησαν    |
| וההיכל           | και τα βασιλεια |
| נמוג             | διεπεσεν        |
: Nahum chapter 2, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                | Tov's retroversion                | Septuagint                                                                                   |
|:------------------------------|:----------------------------------|:---------------------------------------------------------------------------------------------|
| [והצב]{.potential-difference} | [ומצב .hm]{.potential-difference} | [και η υποστασις]{.potential-difference}                                                     |
| גלתה                          |                                   | απεκαλυφθη                                                                                   |
| העלתה                         |                                   | και αυτη ανεβαινεν                                                                           |
| ואמהתיה                       |                                   | και αι δουλαι αυτης                                                                          |
| מנהגות                        |                                   | ηγοντο                                                                                       |
| [כקול]{.potential-difference} |                                   | [καθως •^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| יונים                         |                                   | περιστεραι                                                                                   |
| מתפפת                         |                                   | φθεγγομεναι                                                                                  |
| על                            |                                   | εν                                                                                           |
| לבבהן                         |                                   | καρδιαις αυτων                                                                               |
: Nahum chapter 2, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text                                                               | Tov's retroversion                                                                                     | Septuagint                                                                                                                                 |
|:-----------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------|
| ונינוה                                                                       |                                                                                                        | και νινευη                                                                                                                                 |
| כברכת                                                                        |                                                                                                        | ως κολυμβηθρα                                                                                                                              |
| מים                                                                          |                                                                                                        | υδατος                                                                                                                                     |
| [מימי היא]{.potential-difference}                                            | [מימיה •^[Two words of MT joined into one word in the parent text of the LXX.]]{.potential-difference} | [τα υδατα αυτης]{.potential-difference}                                                                                                    |
| והמה                                                                         |                                                                                                        | και αυτοι                                                                                                                                  |
| נסים                                                                         |                                                                                                        | φευγοντες                                                                                                                                  |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                                                                                        | [ουκ]{.potential-difference}                                                                                                               |
| [עמדו עמדו]{.potential-difference}                                           |                                                                                                        | [εστησαν •^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} |
| ואין                                                                         |                                                                                                        | και ουκ ην                                                                                                                                 |
| מפנה                                                                         |                                                                                                        | ο επιβλεπων                                                                                                                                |
: Nahum chapter 2, verse 9 { .hover tbl-colwidths="[35,30,35]"}

### Verse 10

| Masoretic text                                | Septuagint         |
|:----------------------------------------------|:-------------------|
| בזו •^[Difference in vocalization (reading).] | διηρπαζον          |
| כסף                                           | το αργυριον        |
| בזו •^[Difference in vocalization (reading).] | διηρπαζον          |
| זהב                                           | το χρυσιον         |
| ואין                                          | και ουκ ην         |
| קצה                                           | περας              |
| לתכונה                                        | του κοσμου αυτης   |
| כבד                                           | βεβαρυνται         |
| מכל                                           | υπερ παντα         |
| כלי                                           | τα σκευη           |
| חמדה                                          | τα επιθυμητα αυτης |
: Nahum chapter 2, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                        | Tov's retroversion            | Septuagint                      |
|:--------------------------------------|:------------------------------|:--------------------------------|
| בוקה •^[Etymological exegesis.] בקק   |                               | εκτιναγμος                      |
| ומבוקה •^[Etymological exegesis.] בקק |                               | και ανατιναγμος                 |
| ומבלקה                                |                               | και εκβρασμος                   |
| ולב                                   |                               | και καρδιας                     |
| נמס                                   |                               | θραυσμος                        |
| ופק                                   |                               | και υπολυσις                    |
| ברכים                                 |                               | γονατων                         |
| וחלחלה                                |                               | και ωδινες                      |
| בכל                                   |                               | επι πασαν                       |
| מתנים                                 |                               | οσφυν                           |
| ופני                                  |                               | και το προσωπον                 |
| כלם                                   |                               | παντων                          |
| קבצו                                  |                               | ως προσκαυμα                    |
| [פארור]{.potential-difference}        | [פרור]{.potential-difference} | [χυτρας]{.potential-difference} |
: Nahum chapter 2, verse 11 { .hover tbl-colwidths="[35,30,35]"}

### Verse 12

| Masoretic text                     | Tov's retroversion                | Septuagint                             |
|:-----------------------------------|:----------------------------------|:---------------------------------------|
| איה                                |                                   | που εστιν                              |
| מעון                               |                                   | το κατοικητηριον                       |
| אריות                              |                                   | των λεοντων                            |
| ומרעה                              |                                   | και η νομη                             |
| הוא •^[Etymological exegesis.] היה |                                   | η ουσα                                 |
| לכפרים                             |                                   | τοις σκυμνοις                          |
| אשר                                |                                   | ου                                     |
| הלך                                |                                   | επορευθη                               |
| אריה                               |                                   | λεων                                   |
| [לביא]{.potential-difference}      | [לבוא .yw]{.potential-difference} | [του εισελθειν]{.potential-difference} |
| שם                                 |                                   | εκει                                   |
| גור                                |                                   | σκυμνος                                |
| אריה                               |                                   | λεοντος                                |
| ואין                               |                                   | και ουκ ην                             |
| מחריד                              |                                   | ο εκφοβων                              |
: Nahum chapter 2, verse 12 { .hover tbl-colwidths="[35,30,35]"}

### Verse 13

| Masoretic text   | Septuagint                 |
|:-----------------|:---------------------------|
| אריה             | λεων                       |
| טרף              | ηρπασεν                    |
| בדי              | τα ικανα                   |
| גרותיו           | τοις σκυμνοις αυτου        |
| ומחנק            | και απεπνιξεν              |
| ללבאתיו          | τοις λεουσιν αυτου         |
| וימלא            | και επλησεν                |
| טרף              | θηρας                      |
| חריו             | νοσσιαν αυτου              |
| ומענתיו          | και το κατοικητηριον αυτου |
| טרפה             | αρπαγης                    |
: Nahum chapter 2, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                                          | Tov's retroversion                   | Septuagint                                                                             |
|:----------------------------------------------------------------------------------------|:-------------------------------------|:---------------------------------------------------------------------------------------|
| הנני                                                                                    |                                      | ιδου εγω                                                                               |
| אליך                                                                                    |                                      | επι σε                                                                                 |
| נאם                                                                                     |                                      | λεγει                                                                                  |
| יהוה                                                                                    |                                      | κυριος                                                                                 |
| צבאות                                                                                   |                                      | παντοκρατωρ                                                                            |
| והבערתי                                                                                 |                                      | και εκκαυσω                                                                            |
| בעשן                                                                                    |                                      | εν καπνω                                                                               |
| רכבה •^[Etymological exegesis.] רב                                                      |                                      | πληθος σου                                                                             |
| וכפיריך                                                                                 |                                      | και τους λεοντας σου                                                                   |
| תאכל                                                                                    |                                      | καταφαγεται                                                                            |
| חרב                                                                                     |                                      | ρομφαια                                                                                |
| והכרתי                                                                                  |                                      | και εξολεθρευσω                                                                        |
| מארץ                                                                                    |                                      | εκ της γης                                                                             |
| טרפך                                                                                    |                                      | την θηραν σου                                                                          |
| ולא                                                                                     |                                      | και ου μη                                                                              |
| ישמע                                                                                    |                                      | ακουσθη                                                                                |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] לא עוד |                                      | ουκετι                                                                                 |
| [קול]{.potential-difference}                                                            |                                      | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [מלאככה]{.potential-difference}                                                         | [מלאכתכה .kt]{.potential-difference} | [τα εργα σου]{.potential-difference}                                                   |
: Nahum chapter 2, verse 14 { .hover tbl-colwidths="[35,30,35]"}

## Chapter 3

### Verse 1

| Masoretic text                  | Septuagint    |
|:--------------------------------|:--------------|
| הוי                             | ω             |
| עיר                             | πολις         |
| דמים                            | αιματων       |
| כלה                             | ολη           |
| כחש                             | ψευδης        |
| פרק                             | αδικιας       |
| מלאה                            | πληρης        |
| לא                              | ου            |
| ימיש •^[Etymological exegesis.] | ψηλαφηθησεται |
| טרף                             | θηρα          |
: Nahum chapter 3, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| קול              | φωνη          |
| שוט              | μαστιγων      |
| וקול             | και φωνη      |
| רעש              | σεισμου       |
| אופן             | τροχων        |
| וסוס             | και ιππου     |
| דהר              | διωκοντος     |
| ומרכבה           | και αρματος   |
| מרקדה            | αναβρασσοντος |
: Nahum chapter 3, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                                 | Septuagint            |
|:-----------------------------------------------|:----------------------|
| פרש                                            | και ιππεως            |
| מעלה                                           | αναβαινοντος          |
| ולהב                                           | και στιλβουσης        |
| חרב                                            | ρομφαιας              |
| וברק                                           | και εξαστραπτοντων    |
| חנית                                           | οπλων                 |
| ורב                                            | και πληθους           |
| חלל                                            | τραυματιων            |
| וכבד                                           | και βαρειας           |
| פגר                                            | πτωσεως               |
| ואין                                           | και ουκ ην            |
| קצה                                            | περας                 |
| לגויה •^[Etymological exegesis.] גוי           | τοις εθνεσιν αυτης    |
| *יכשלו **וכשלו •^[Agreement of LXX with qere.] | και ασθενησουσιν      |
| בגויתם                                         | εν τοις σωμασιν αυτων |
: Nahum chapter 3, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint              |
|:-----------------|:------------------------|
| מרב              | απο πληθους             |
| זנוני            | πορνειας                |
| זונה             | πορνη                   |
| טובת             | καλη                    |
| חן               | και επιχαρης            |
| בעלת             | ηγουμενη                |
| כשפים            | φαρμακων                |
| המכרת            | η πωλουσα               |
| גוים             | εθνη                    |
| בזנוניה          | εν τη πορνεια αυτης     |
| ומשפחות          | και φυλας               |
| בכשפיה           | εν τοις φαρμακοις αυτης |
: Nahum chapter 3, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                               | Septuagint                      |
|:-----------------------------------------------------------------------------|:--------------------------------|
| הנני                                                                         | ιδου εγω                        |
| אליך                                                                         | επι σε                          |
| נאם                                                                          | λεγει                           |
| יהוה                                                                         | κυριος                          |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [ο θεος]{.potential-difference} |
| צבאות                                                                        | ο παντοκρατωρ                   |
| וגליתי                                                                       | και αποκαλυψω                   |
| שוליך                                                                        | τα οπισω σου                    |
| על                                                                           | επι                             |
| פניך                                                                         | το προσωπον σου                 |
| והראיתי                                                                      | και δειξω                       |
| גוים                                                                         | εθνεσιν                         |
| מערך                                                                         | την αισχυνην σου                |
| וממלכות                                                                      | και βασιλειαις                  |
| קלונך                                                                        | την ατιμιαν σου                 |
: Nahum chapter 3, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text   | Septuagint              |
|:-----------------|:------------------------|
| והשלכתי          | και επιρριψω            |
| עליך             | επι σε                  |
| שקצים            | βδελυγμον               |
| ונבלתיך          | κατα τας ακαθαρσιας σου |
| ושמתיך           | και θησομαι σε          |
| כראי             | εις παραδειγμα          |
: Nahum chapter 3, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                  | Tov's retroversion                                                            | Septuagint                            |
|:--------------------------------|:------------------------------------------------------------------------------|:--------------------------------------|
| והיה                            |                                                                               | και εσται                             |
| כל                              |                                                                               | πας                                   |
| ראיך                            |                                                                               | ο ορων σε                             |
| [ידוד]{.potential-difference}   | [•^[Questionable notation, equivalent, etc.] @ירד .dr]{.potential-difference} | [αποπηδησεται]{.potential-difference} |
| ממך                             |                                                                               | απο σου                               |
| ואמר                            |                                                                               | και ερει                              |
| שדדה                            |                                                                               | δειλαια                               |
| נינוה                           |                                                                               | νινευη                                |
| מי                              |                                                                               | τις                                   |
| ינוד                            |                                                                               | στεναξει                              |
| לה                              |                                                                               | αυτην                                 |
| מאין                            |                                                                               | ποθεν                                 |
| אבקש                            |                                                                               | ζητησω                                |
| [מנחמים]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] נחמים]{.potential-difference}    | [παρακλησιν]{.potential-difference}   |
| לך                              |                                                                               | αυτη                                  |
: Nahum chapter 3, verse 7 { .hover tbl-colwidths="[35,30,35]"}

### Verse 8

| Masoretic text                                                                   | Septuagint                                                                                                                                                                        |
|:---------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | ετοιμασαι                                                                                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | μεριδα                                                                                                                                                                            |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | αρμοσαι                                                                                                                                                                           |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [χορδην]{.potential-difference}                                                                                                                                                   |
| התיטבי                                                                           | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ετοιμασαι •^[Reference to doublet (occurring between the two elements of the doublet.] ετοιμασαι |
| מנא •^[Etymological exegesis.] מנה .אh                                           | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] μεριδα •^[Reference to doublet (occurring between the two elements of the doublet.] μεριδα       |
| אמון                                                                             | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] αρμοσαι •^[Reference to doublet (occurring between the two elements of the doublet.] αμων        |
| הישבה                                                                            | η κατοικουσα                                                                                                                                                                      |
| ביארים                                                                           | εν ποταμοις                                                                                                                                                                       |
| מים                                                                              | υδωρ                                                                                                                                                                              |
| סביב                                                                             | κυκλω                                                                                                                                                                             |
| לה                                                                               | αυτης                                                                                                                                                                             |
| אשר                                                                              | ης                                                                                                                                                                                |
| חיל                                                                              | η αρχη                                                                                                                                                                            |
| ים                                                                               | θαλασσα                                                                                                                                                                           |
| מים •^[Etymological exegesis.] מים •^[Difference in vocalization (reading).]     | και υδωρ                                                                                                                                                                          |
| חומתה                                                                            | τα τειχη αυτης                                                                                                                                                                    |
: Nahum chapter 3, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                                                     | Tov's retroversion                                                      | Septuagint                             |
|:-----------------------------------------------------------------------------------|:------------------------------------------------------------------------|:---------------------------------------|
| כוש                                                                                |                                                                         | και αιθιοπια                           |
| [עצמה]{.potential-difference}                                                      | [עצמה •^[Difference in vocalization (reading).]]{.potential-difference} | [η ισχυς αυτης]{.potential-difference} |
| ומצרים                                                                             |                                                                         | και αιγυπτος                           |
| ואין                                                                               |                                                                         | και ουκ εστιν                          |
| קצה                                                                                |                                                                         | περας                                  |
| פוט •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] פלט .wl |                                                                         | της φυγης                              |
| ולובים                                                                             |                                                                         | και λιβυες                             |
| היו                                                                                |                                                                         | εγενοντο                               |
| בעזרתך                                                                             |                                                                         | βοηθοι αυτης                           |
: Nahum chapter 3, verse 9 { .hover tbl-colwidths="[35,30,35]"}

### Verse 10

| Masoretic text                                                               | Septuagint                     |
|:-----------------------------------------------------------------------------|:-------------------------------|
| גם                                                                           | και                            |
| היא                                                                          | αυτη                           |
| לגלה                                                                         | εις μετοικεσιαν                |
| הלכה                                                                         | πορευσεται                     |
| בשבי                                                                         | αιχμαλωτος                     |
| גם                                                                           | και                            |
| עלליה                                                                        | τα νηπια αυτης                 |
| ירטשו                                                                        | εδαφιουσιν                     |
| בראש                                                                         | επ' αρχας                      |
| כל                                                                           | πασων                          |
| חוצות                                                                        | των οδων αυτης                 |
| ועל                                                                          | και επι                        |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [παντα]{.potential-difference} |
| נכבדיה                                                                       | τα ενδοξα αυτης                |
| ידו                                                                          | βαλουσιν                       |
| גורל                                                                         | κληρους                        |
| וכל                                                                          | και παντες                     |
| גדוליה                                                                       | οι μεγιστανες αυτης            |
| רתקו                                                                         | δεθησονται                     |
| בזקים                                                                        | χειροπεδαις                    |
: Nahum chapter 3, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                                                               | Septuagint                      |
|:-----------------------------------------------------------------------------|:--------------------------------|
| גם                                                                           | και                             |
| את                                                                           | συ                              |
| תשכרי                                                                        | μεθυσθηση                       |
| תהי                                                                          | και εση                         |
| נעלמה                                                                        | υπερεωραμενη                    |
| גם                                                                           | και                             |
| את                                                                           | συ                              |
| תבקשי                                                                        | ζητησεις                        |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [σεαυτη]{.potential-difference} |
| מעוז                                                                         | στασιν                          |
| מאויב                                                                        | εξ εχθρων                       |
: Nahum chapter 3, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                                                                   | Septuagint       |
|:---------------------------------------------------------------------------------|:-----------------|
| כל                                                                               | παντα            |
| מבצריך                                                                           | τα οχυρωματα σου |
| תאנים                                                                            | συκαι            |
| עם                                                                               | {..εχουσαι}      |
| בכורים                                                                           | σκοπους          |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εχουσαι          |
| אם                                                                               | εαν              |
| ינועו                                                                            | σαλευθωσιν       |
| ונפלו                                                                            | και πεσουνται    |
| על                                                                               | εις              |
| פי                                                                               | στομα            |
| אוכל                                                                             | εσθοντος         |
: Nahum chapter 3, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                                                   | Septuagint                                                                                                               |
|:---------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------|
| הנה                                                                              | ιδου                                                                                                                     |
| עמך                                                                              | ο λαος σου                                                                                                               |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | ως                                                                                                                       |
| נשים                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] ως γυναικες |
| בקרבך                                                                            | εν σοι                                                                                                                   |
| לאיביך                                                                           | τοις εχθροις σου                                                                                                         |
| פתוח {!}p                                                                        | ανοιγομεναι                                                                                                              |
| נפתחו {!}p                                                                       | ανοιχθησονται                                                                                                            |
| שערי                                                                             | πυλαι                                                                                                                    |
| ארצך                                                                             | της γης σου                                                                                                              |
| אכלה                                                                             | και καταφαγεται                                                                                                          |
| אש                                                                               | πυρ                                                                                                                      |
| בריחיך                                                                           | τους μοχλους σου                                                                                                         |
: Nahum chapter 3, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                | Tov's retroversion                                                                                  | Septuagint                            |
|:------------------------------|:----------------------------------------------------------------------------------------------------|:--------------------------------------|
| מי                            |                                                                                                     | υδωρ                                  |
| מצור                          |                                                                                                     | περιοχης                              |
| שאבי                          |                                                                                                     | επισπασαι                             |
| לך                            |                                                                                                     | σεαυτη                                |
| חזקי                          |                                                                                                     | και κατακρατησον                      |
| מבצריך                        |                                                                                                     | των οχυρωματων σου                    |
| באי                           |                                                                                                     | εμβηθι                                |
| בטיט                          |                                                                                                     | εις πηλον                             |
| ורמסי                         |                                                                                                     | και συμπατηθητι                       |
| בחמר                          |                                                                                                     | εν αχυροις                            |
| החזיקי                        |                                                                                                     | κατακρατησον                          |
| [מלבן]{.potential-difference} | [מלבנה •^[Difference in vocalization (reading).] •^[Etymological exegesis.]]{.potential-difference} | [υπερ πλινθον]{.potential-difference} |
: Nahum chapter 3, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text                 | Septuagint                                                                             |
|:-------------------------------|:---------------------------------------------------------------------------------------|
| שם                             | εκει                                                                                   |
| תאכלך                          | καταφαγεται σε                                                                         |
| אש                             | πυρ                                                                                    |
| תכריתך                         | εξολεθρευσει σε                                                                        |
| חרב                            | ρομφαια                                                                                |
| תאכלך                          | καταφαγεται σε                                                                         |
| כילק                           | ως ακρις                                                                               |
| [התכבד]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [כילק]{.potential-difference}  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| התכבדי                         | και βαρυνθηση                                                                          |
| כארבה                          | ως βρουχος                                                                             |
: Nahum chapter 3, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text   | Septuagint                                                                                               |
|:-----------------|:---------------------------------------------------------------------------------------------------------|
| הרבית            | επληθυνας                                                                                                |
| רכליך            | τας εμποριας σου                                                                                         |
| מכוכבי           | υπερ τα αστρα                                                                                            |
| השמים            | του ουρανου                                                                                              |
| ילק              | βρουχος                                                                                                  |
| פשט              | ωρμησεν                                                                                                  |
| ויעף             | και εξεπετασθη •^[Reference to doublet (occurring between the two elements of the doublet.] εξηλατο [17] |
: Nahum chapter 3, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text                    | Tov's retroversion               | Septuagint                                                                                                                                  |
|:----------------------------------|:---------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------|
| [מנזריך]{.potential-difference}   |                                  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}                                                      |
| כארבה                             |                                  | ως αττελεβος                                                                                                                                |
| וטפסריך                           |                                  | ο συμμικτος σου                                                                                                                             |
| [כגוב גבי]{.potential-difference} |                                  | [ως ακρις •^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} |
| החונים                            |                                  | επιβεβηκυια                                                                                                                                 |
| בגדרות                            |                                  | επι φραγμον                                                                                                                                 |
| ביום                              |                                  | εν ημεραις                                                                                                                                  |
| [קרה]{.potential-difference}      | [קרח .hx]{.potential-difference} | [παγους]{.potential-difference}                                                                                                             |
| שמש                               |                                  | ο ηλιος                                                                                                                                     |
| זרחה                              |                                  | ανετειλεν                                                                                                                                   |
| ונודד                             |                                  | και αφηλατο                                                                                                                                 |
| ולא                               |                                  | και ουκ                                                                                                                                     |
| נודע                              |                                  | εγνω                                                                                                                                        |
| מקומו                             |                                  | τον τοπον αυτης                                                                                                                             |
| [אים]{.potential-difference}      | [אוי להם]{.potential-difference} | [ουαι αυτοις]{.potential-difference}                                                                                                        |
: Nahum chapter 3, verse 17 { .hover tbl-colwidths="[35,30,35]"}

### Verse 18

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| נמו              | ενυσταξαν         |
| רעיך             | οι ποιμενες σου   |
| מלך              | βασιλευς          |
| אשור             | ασσυριος          |
| ישכנו            | εκοιμισεν         |
| אדיריך           | τους δυναστας σου |
| נפשו             | απηρεν            |
| עמך              | ο λαος σου        |
| על               | επι               |
| ההרים            | τα ορη            |
| ואין             | και ουκ ην        |
| מקבץ             | ο εκδεχομενος     |
: Nahum chapter 3, verse 18 { .hover tbl-colwidths="[50,50]"}

### Verse 19

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| אין              | ουκ εστιν        |
| כהה              | ιασις            |
| לשברך            | τη συντριβη σου  |
| נחלה             | εφλεγμανεν       |
| מכתך             | η πληγη σου      |
| כל               | παντες           |
| שמעי             | οι ακουοντες     |
| שמעך             | την αγγελιαν σου |
| תקעו             | κροτησουσιν      |
| כף               | χειρας           |
| עליך             | επι σε           |
| כי               | διοτι            |
| על מי            | επι τινα         |
| לא               | ουκ              |
| עברה             | επηλθεν          |
| רעתך             | η κακια σου      |
| תמיד             | δια παντος       |
: Nahum chapter 3, verse 19 { .hover tbl-colwidths="[50,50]"}

