# Obadiah

The tables below show the Hebrew and Greek texts aligned vertically. When a Hebrew verse number does not match the Greek counterpart, the editors added a note with the corresponding verse number between square brackets.

## Chapter 1

### Verse 1

| Masoretic text                                                                                 | Septuagint               |
|:-----------------------------------------------------------------------------------------------|:-------------------------|
| חזון                                                                                           | ορασις                   |
| עבדיה                                                                                          | αβδιου                   |
| כה                                                                                             | ταδε                     |
| אמר                                                                                            | λεγει                    |
| אדני                                                                                           | κυριος                   |
| יהוה                                                                                           | ο θεος                   |
| לאדום                                                                                          | τη ιδουμαια              |
| שמועה                                                                                          | ακοην                    |
| שמענו                                                                                          | ηκουσα                   |
| מאת                                                                                            | παρα                     |
| יהוה                                                                                           | κυριου                   |
| וציר •^[Etymological exegesis.] צור .yw                                                        | και περιοχην {cπεριοχον} |
| בגוים                                                                                          | εις τα εθνη              |
| שלח •^[Change from passive to active form in verbs.] •^[Difference in vocalization (reading).] | εξαπεστειλεν             |
| קומו                                                                                           | αναστητε                 |
| ונקומה                                                                                         | και εξαναστωμεν          |
| עליה                                                                                           | επ' αυτην                |
| למלחמה                                                                                         | εις πολεμον              |
: Obadiah chapter 1, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| הנה              | ιδου            |
| קטן              | ολιγοστον       |
| נתתיך            | δεδωκα σε       |
| בגוים            | εν τοις εθνεσιν |
| בזוי             | ητιμωμενος      |
| אתה              | συ ει           |
| מאד              | σφοδρα          |
: Obadiah chapter 1, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                                                                   | Tov's retroversion                | Septuagint                                                                                                               |
|:---------------------------------------------------------------------------------|:----------------------------------|:-------------------------------------------------------------------------------------------------------------------------|
| זדון                                                                             |                                   | υπερηφανια                                                                                                               |
| לבך                                                                              |                                   | της καρδιας σου                                                                                                          |
| השיאך •^[Etymological exegesis.] נשא =vs                                         |                                   | επηρεν σε                                                                                                                |
| שכני                                                                             |                                   | κατασκηνουντα                                                                                                            |
| בחגוי                                                                            |                                   | εν ταις οπαις                                                                                                            |
| סלע                                                                              |                                   | των πετρων                                                                                                               |
| [מרום]{.potential-difference}                                                    | [מרים .wy]{.potential-difference} | [υψων]{.potential-difference}                                                                                            |
| שבתו                                                                             |                                   | κατοικιαν αυτου                                                                                                          |
| אמר                                                                              |                                   | λεγων                                                                                                                    |
| בלבו                                                                             |                                   | εν καρδια αυτου                                                                                                          |
| מי                                                                               |                                   | τις                                                                                                                      |
| יורדני                                                                           |                                   | με καταξει                                                                                                               |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                   | επι                                                                                                                      |
| ארץ                                                                              |                                   | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] επι την γην |
: Obadiah chapter 1, verse 3 { .hover tbl-colwidths="[35,30,35]"}

### Verse 4

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| אם               | εαν          |
| תגביה            | μετεωρισθης  |
| כנשר             | ως αετος     |
| ואם              | και εαν      |
| בין              | ανα μεσον    |
| כוכבים           | των αστρων   |
| שים              | θης          |
| קנך              | νοσσιαν σου  |
| משם              | εκειθεν      |
| אורידך           | καταξω σε    |
| נאם              | λεγει        |
| יהוה             | κυριος       |
: Obadiah chapter 1, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                  | Tov's retroversion                  | Septuagint                         |
|:--------------------------------|:------------------------------------|:-----------------------------------|
| אם                              |                                     | ει                                 |
| גנבים                           |                                     | κλεπται                            |
| באו                             |                                     | εισηλθον                           |
| לך                              |                                     | προς σε                            |
| אם                              |                                     | η                                  |
| שודדי                           |                                     | λησται                             |
| לילה                            |                                     | νυκτος                             |
| איך                             |                                     | που αν                             |
| [נדמיתה]{.potential-difference} | [נרמיתה .dr]{.potential-difference} | [απερριφης]{.potential-difference} |
| הלוא                            |                                     | ουκ αν                             |
| יגנבו                           |                                     | εκλεψαν                            |
| דים                             |                                     | τα ικανα εαυτοις                   |
| אם                              |                                     | και ει                             |
| בצרים                           |                                     | τρυγηται                           |
| באו                             |                                     | εισηλθον                           |
| לך                              |                                     | προς σε                            |
| הלוא                            |                                     | ουκ αν                             |
| ישאירו                          |                                     | υπελιποντο                         |
| עללות                           |                                     | επιφυλλιδα                         |
: Obadiah chapter 1, verse 5 { .hover tbl-colwidths="[35,30,35]"}

### Verse 6

| Masoretic text   | Septuagint          |
|:-----------------|:--------------------|
| איך              | πως                 |
| נחפשו            | εξηρευνηθη          |
| עשו              | ησαυ                |
| נבעו             | και κατελημφθη      |
| מצפניו           | αυτου τα κεκρυμμενα |
: Obadiah chapter 1, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                                                                                                                                             | Septuagint                                                                             |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| עד                                                                                                                                                         | εως                                                                                    |
| הגבול                                                                                                                                                      | των οριων σου                                                                          |
| שלחוך                                                                                                                                                      | εξαπεστειλαν σε                                                                        |
| כל                                                                                                                                                         | παντες                                                                                 |
| אנשי                                                                                                                                                       | οι ανδρες                                                                              |
| בריתך                                                                                                                                                      | της διαθηκης σου                                                                       |
| השיאוך                                                                                                                                                     | αντεστησαν σοι                                                                         |
| יכלו                                                                                                                                                       | ηδυνασθησαν                                                                            |
| לך                                                                                                                                                         | προς σε                                                                                |
| אנשי                                                                                                                                                       | ανδρες                                                                                 |
| שלמך                                                                                                                                                       | ειρηνικοι σου                                                                          |
| [לחמך]{.potential-difference}                                                                                                                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ישימו                                                                                                                                                      | εθηκαν                                                                                 |
| מזור •^[Etymological exegesis.] צוד •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (interchange of R/D, etc.)] .zc | ενεδρα                                                                                 |
| תחתיך                                                                                                                                                      | υποκατω σου                                                                            |
| אין                                                                                                                                                        | ουκ εστιν                                                                              |
| תבונה                                                                                                                                                      | συνεσις                                                                                |
| בו                                                                                                                                                         | αυτοις                                                                                 |
: Obadiah chapter 1, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                                                   | Septuagint                                                                             |
|:---------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| [הלוא]{.potential-difference}                                                    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| ביום                                                                             | εν {...τη ημερα}                                                                       |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εκεινη                                                                                 |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | τη ημερα                                                                               |
| ההוא                                                                             | {..εκεινη}                                                                             |
| נאם                                                                              | λεγει                                                                                  |
| יהוה                                                                             | κυριος                                                                                 |
| והאבדתי                                                                          | απολω                                                                                  |
| חכמים                                                                            | σοφους                                                                                 |
| מאדום                                                                            | εκ της ιδουμαιας                                                                       |
| ותבונה                                                                           | και συνεσιν                                                                            |
| מהר                                                                              | εξ ορους                                                                               |
| עשו                                                                              | ησαυ                                                                                   |
: Obadiah chapter 1, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                                                   | Septuagint                                                                                                                                                                                                 |
|:---------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| וחתו                                                                             | και πτοηθησονται                                                                                                                                                                                           |
| גבוריך                                                                           | οι μαχηται σου                                                                                                                                                                                             |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | οι                                                                                                                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εκ                                                                                                                                                                                                         |
| תימן                                                                             | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] οι •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εκ θαιμαν |
| למען                                                                             | οπως                                                                                                                                                                                                       |
| יכרת                                                                             | εξαρθη                                                                                                                                                                                                     |
| איש                                                                              | ανθρωπος                                                                                                                                                                                                   |
| מהר                                                                              | εξ ορους                                                                                                                                                                                                   |
| עשו                                                                              | ησαυ                                                                                                                                                                                                       |
| מקטל                                                                             | δια την σφαγην [10]                                                                                                                                                                                        |
: Obadiah chapter 1, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                                                   | Septuagint                                                                                                                                                                                                            |
|:---------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| מחמס                                                                             | και την ασεβειαν                                                                                                                                                                                                      |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | την                                                                                                                                                                                                                   |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εις                                                                                                                                                                                                                   |
| אחיך                                                                             | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] την •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις τον αδελφον σου |
| יעקב                                                                             | ιακωβ                                                                                                                                                                                                                 |
| תכסך                                                                             | και καλυψει σε                                                                                                                                                                                                        |
| בושה                                                                             | αισχυνη                                                                                                                                                                                                               |
| ונכרת                                                                            | και εξαρθηση                                                                                                                                                                                                          |
| לעולם                                                                            | εις τον αιωνα                                                                                                                                                                                                         |
: Obadiah chapter 1, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                                                                   | Septuagint                                                                                                                   |
|:---------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------|
| ביום                                                                             | αφ' ης ημερας                                                                                                                |
| עמדך                                                                             | αντεστης                                                                                                                     |
| מנגד                                                                             | εξ εναντιας                                                                                                                  |
| ביום                                                                             | εν ημερα                                                                                                                     |
| שבות                                                                             | αιχμαλωτευοντων                                                                                                              |
| זרים                                                                             | αλλογενων                                                                                                                    |
| חילו                                                                             | δυναμιν αυτου                                                                                                                |
| ונכרים                                                                           | και αλλοτριοι                                                                                                                |
| באו                                                                              | εισηλθον                                                                                                                     |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εις                                                                                                                          |
| *שערו **שעריו                                                                    | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις πυλας αυτου |
| ועל                                                                              | και επι                                                                                                                      |
| ירושלם                                                                           | ιερουσαλημ                                                                                                                   |
| ידו                                                                              | εβαλον                                                                                                                       |
| גורל                                                                             | κληρους                                                                                                                      |
| גם                                                                               | και                                                                                                                          |
| אתה                                                                              | συ ης                                                                                                                        |
| כאחד                                                                             | ως εις                                                                                                                       |
| מהם                                                                              | εξ αυτων                                                                                                                     |
: Obadiah chapter 1, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                  | Septuagint       |
|:--------------------------------|:-----------------|
| ואל                             | και μη           |
| תרא                             | επιδης           |
| ביום                            | ημεραν           |
| אחיך                            | αδελφου σου      |
| ביום                            | εν ημερα         |
| נכרו •^[Etymological exegesis.] | αλλοτριων        |
| ואל                             | και μη           |
| תשמח                            | επιχαρης         |
| לבני                            | επι τους υιους   |
| יהודה                           | ιουδα            |
| ביום                            | εν ημερα         |
| אבדם                            | απωλειας αυτων   |
| ואל                             | και μη           |
| תגדל פיך                        | μεγαλορρημονησης |
| ביום                            | εν ημερα         |
| צרה                             | θλιψεως          |
: Obadiah chapter 1, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                 | Tov's retroversion                                                                                                                                                                                                                                                                                  | Septuagint                                   |
|:-------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------|
| אל                             |                                                                                                                                                                                                                                                                                                     | μηδε                                         |
| תבוא                           |                                                                                                                                                                                                                                                                                                     | εισελθης                                     |
| בשער                           |                                                                                                                                                                                                                                                                                                     | εις πυλας                                    |
| עמי                            |                                                                                                                                                                                                                                                                                                     | λαων                                         |
| ביום                           |                                                                                                                                                                                                                                                                                                     | εν ημερα                                     |
| [אידם]{.potential-difference}  | [•^[Questionable notation, equivalent, etc.] אונם .yw]{.potential-difference}                                                                                                                                                                                                                       | [πονων αυτων]{.potential-difference}         |
| אל                             |                                                                                                                                                                                                                                                                                                     | μηδε                                         |
| תרא                            |                                                                                                                                                                                                                                                                                                     | επιδης                                       |
| גם                             |                                                                                                                                                                                                                                                                                                     | και                                          |
| אתה                            |                                                                                                                                                                                                                                                                                                     | συ                                           |
| [ברעתו]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] בעדתו •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (interchange of R/D, etc.)] •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (metathesis.)]]{.potential-difference} | [την συναγωγην αυτων]{.potential-difference} |
| ביום                           |                                                                                                                                                                                                                                                                                                     | εν ημερα                                     |
| אידו                           |                                                                                                                                                                                                                                                                                                     | ολεθρου αυτων                                |
| ואל                            |                                                                                                                                                                                                                                                                                                     | μηδε                                         |
| תשלחנה                         |                                                                                                                                                                                                                                                                                                     | συνεπιθη                                     |
| בחילו                          |                                                                                                                                                                                                                                                                                                     | επι την δυναμιν αυτων                        |
| ביום                           |                                                                                                                                                                                                                                                                                                     | εν ημερα                                     |
| אידו                           |                                                                                                                                                                                                                                                                                                     | απωλειας αυτων                               |
: Obadiah chapter 1, verse 13 { .hover tbl-colwidths="[35,30,35]"}

### Verse 14

| Masoretic text   | Septuagint               |
|:-----------------|:-------------------------|
| ואל              | μηδε                     |
| תעמד             | επιστης                  |
| על               | επι                      |
| הפרק             | τας διεκβολας αυτων      |
| להכרית           | του εξολεθρευσαι         |
| את פליטיו        | τους ανασωζομενους αυτων |
| ואל              | μηδε                     |
| תסגר             | συγκλεισης               |
| שרידיו           | τους φευγοντας εξ αυτων  |
| ביום             | εν ημερα                 |
| צרה              | θλιψεως                  |
: Obadiah chapter 1, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text                                                               | Septuagint                     |
|:-----------------------------------------------------------------------------|:-------------------------------|
| כי                                                                           | διοτι                          |
| קרוב                                                                         | εγγυς                          |
| יום                                                                          | ημερα                          |
| יהוה                                                                         | κυριου                         |
| על                                                                           | επι                            |
| כל                                                                           | παντα                          |
| הגוים                                                                        | τα εθνη                        |
| כאשר                                                                         | ον τροπον                      |
| עשית                                                                         | εποιησας                       |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [ουτως]{.potential-difference} |
| יעשה                                                                         | εσται                          |
| לך                                                                           | σοι                            |
| גמלך                                                                         | το ανταποδομα σου              |
| ישוב                                                                         | ανταποδοθησεται                |
| בראשך                                                                        | εις κεφαλην σου                |
: Obadiah chapter 1, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text                | Tov's retroversion           | Septuagint                     |
|:------------------------------|:-----------------------------|:-------------------------------|
| כי                            |                              | διοτι                          |
| כאשר                          |                              | ον τροπον                      |
| שתיתם                         |                              | επιες                          |
| על                            |                              | επι                            |
| הר                            |                              | το ορος                        |
| קדשי                          |                              | το αγιον μου                   |
| ישתו                          |                              | πιονται                        |
| כל                            |                              | παντα                          |
| הגוים                         |                              | τα εθνη                        |
| [תמיד]{.potential-difference} | [תמד]{.potential-difference} | [οινον]{.potential-difference} |
| ושתו                          |                              | πιονται                        |
| ולעו                          |                              | και καταβησονται               |
| והיו                          |                              | και εσονται                    |
| כלוא                          |                              | καθως ουχ                      |
| היו                           |                              | υπαρχοντες                     |
: Obadiah chapter 1, verse 16 { .hover tbl-colwidths="[35,30,35]"}

### Verse 17

| Masoretic text   | Septuagint                      |
|:-----------------|:--------------------------------|
| ובהר             | εν δε τω ορει                   |
| ציון             | σιων                            |
| תהיה             | εσται                           |
| פליטה            | η σωτηρια                       |
| והיה             | και εσται                       |
| קדש              | αγιον                           |
| וירשו            | και κατακληρονομησουσιν         |
| בית              | ο οικος                         |
| יעקב             | ιακωβ                           |
| את מורשיהם       | τους κατακληρονομησαντας αυτους |
: Obadiah chapter 1, verse 17 { .hover tbl-colwidths="[50,50]"}

### Verse 18

| Masoretic text   | Septuagint              |
|:-----------------|:------------------------|
| והיה             | και εσται               |
| בית              | ο οικος                 |
| יעקב             | ιακωβ                   |
| אש               | πυρ                     |
| ובית             | ο δε οικος              |
| יוסף             | ιωσηφ                   |
| להבה             | φλοξ                    |
| ובית             | ο δε οικος              |
| עשו              | ησαυ                    |
| לקש              | εις καλαμην             |
| ודלקו            | και εκκαυθησονται       |
| בהם              | εις αυτους              |
| ואכלום           | και καταφαγονται αυτους |
| ולא              | και ουκ                 |
| יהיה             | εσται                   |
| שריד             | πυροφορος               |
| לבית             | εν τω οικω              |
| עשו              | ησαυ                    |
| כי               | διοτι                   |
| יהוה             | κυριος                  |
| דבר              | ελαλησεν                |
: Obadiah chapter 1, verse 18 { .hover tbl-colwidths="[50,50]"}

### Verse 19

| Masoretic text                  | Tov's retroversion             | Septuagint                                          |
|:--------------------------------|:-------------------------------|:----------------------------------------------------|
| וירשו                           |                                | και κατακληρονομησουσιν                             |
| הנגב                            |                                | οι εν ναγεβ                                         |
| את הר                           |                                | το ορος                                             |
| עשו                             |                                | το ησαυ                                             |
| והשפלה                          |                                | και οι εν τη σεφηλα •^[Transliterated Hebrew word.] |
| את פלשתים                       |                                | τους αλλοφυλους                                     |
| וירשו                           |                                | και κατακληρονομησουσιν                             |
| [את שדה]{.potential-difference} | [את הר]{.potential-difference} | [το ορος]{.potential-difference}                    |
| אפרים                           |                                | εφραιμ                                              |
| ואת שדה                         |                                | και το πεδιον                                       |
| שמרון                           |                                | σαμαρειας                                           |
| ובנימן                          |                                | και βενιαμιν                                        |
| את הגלעד                        |                                | και την γαλααδιτιν                                  |
: Obadiah chapter 1, verse 19 { .hover tbl-colwidths="[35,30,35]"}

### Verse 20

| Masoretic text                                                                         | Tov's retroversion           | Septuagint                  |
|:---------------------------------------------------------------------------------------|:-----------------------------|:----------------------------|
| וגלת                                                                                   |                              | και της μετοικεσιας         |
| החל •^[Etymological exegesis.] חלל                                                     |                              | η αρχη                      |
| הזה                                                                                    |                              | αυτη                        |
| לבני                                                                                   |                              | τοις υιοις                  |
| ישראל                                                                                  |                              | ισραηλ                      |
| [אשר]{.potential-difference}                                                           | [ארץ]{.potential-difference} | [γη]{.potential-difference} |
| כנענים                                                                                 |                              | των χαναναιων               |
| עד                                                                                     |                              | εως                         |
| צרפת                                                                                   |                              | σαρεπτων                    |
| וגלת                                                                                   |                              | και η μετοικεσια            |
| ירושלם                                                                                 |                              | ιερουσαλημ                  |
| אשר •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ב |                              | εως                         |
| בספרד                                                                                  |                              | εφραθα                      |
| ירשו                                                                                   |                              | και κληρονομησουσιν         |
| את ערי                                                                                 |                              | τας πολεις                  |
| הנגב                                                                                   |                              | του ναγεβ                   |
: Obadiah chapter 1, verse 20 { .hover tbl-colwidths="[35,30,35]"}

### Verse 21

| Masoretic text                                         | Septuagint        |
|:-------------------------------------------------------|:------------------|
| ועלו                                                   | και αναβησονται   |
| משעים •^[Change from active to passive form in verbs.] | ανδρες σεσωσμενοι |
| בהר                                                    | εξ ορους          |
| ציון                                                   | σιων              |
| לשפט                                                   | του εκδικησαι     |
| את הר                                                  | το ορος           |
| עשו                                                    | ησαυ              |
| והיתה                                                  | και εσται         |
| ליהוה                                                  | τω κυριω          |
| המלוכה                                                 | η βασιλεια        |
: Obadiah chapter 1, verse 21 { .hover tbl-colwidths="[50,50]"}

