# Song of Songs

The tables below show the Hebrew and Greek texts aligned vertically. When a Hebrew verse number does not match the Greek counterpart, the editors added a note with the corresponding verse number between square brackets.

## Chapter 1

### Verse 1

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| שיר              | ασμα         |
| השירים           | ασματων      |
| אשר              | ο εστιν      |
| לשלמה            | τω σαλωμων   |
: Song of Songs chapter 1, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                 | Septuagint     |
|:-----------------------------------------------|:---------------|
| ישקני                                          | φιλησατω με    |
| מנשיקות                                        | απο φιληματων  |
| פיהו                                           | στοματος αυτου |
| כי                                             | οτι            |
| טובים                                          | αγαθοι         |
| דדיך •^[Difference in vocalization (reading).] | μαστοι σου     |
| מיין                                           | υπερ οινον     |
: Song of Songs chapter 1, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                                                                              | Septuagint                                                                                                       |
|:--------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------|
| לריח •^[Difference in preposition or particle.]                                             | και οσμη                                                                                                         |
| שמניך                                                                                       | μυρων σου                                                                                                        |
| טובים                                                                                       | •^[Distributive rendering, occurring once in the translation but referring to more than one Hebrew word.] αγαθοι |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;מכל <4.10>]{.potential-difference}   | [υπερ παντα]{.potential-difference}                                                                              |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;בשמים <4.10>]{.potential-difference} | [τα αρωματα]{.potential-difference}                                                                              |
| שמן <q6>                                                                                    | μυρον                                                                                                            |
| תורק <q6 •^[Questionable notation, equivalent, etc.] >                                      | εκκενωθεν                                                                                                        |
| שמך                                                                                         | ονομα σου                                                                                                        |
| על כן                                                                                       | δια τουτο                                                                                                        |
| עלמות                                                                                       | νεανιδες                                                                                                         |
| אהבוך                                                                                       | ηγαπησαν σε                                                                                                      |
: Song of Songs chapter 1, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text                                                                             | Septuagint                                                                                                                         |
|:-------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------|
| משכני                                                                                      | ειλκυσαν σε                                                                                                                        |
| אחריך                                                                                      | οπισω σου                                                                                                                          |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;לריח <1.3>]{.potential-difference}  | [εις οσμην]{.potential-difference}                                                                                                 |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;שמניך <1.3>]{.potential-difference} | [μυρων σου]{.potential-difference}                                                                                                 |
| נרוצה                                                                                      | δραμουμεν                                                                                                                          |
| הביאני                                                                                     | εισηνεγκεν με                                                                                                                      |
| המלך                                                                                       | ο βασιλευς                                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]           | εις                                                                                                                                |
| חדריו                                                                                      | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις το ταμιειον αυτου |
| נגילה                                                                                      | αγαλλιασωμεθα                                                                                                                      |
| ונשמחה                                                                                     | και ευφρανθωμεν                                                                                                                    |
| בך                                                                                         | εν σοι                                                                                                                             |
| נזכירה                                                                                     | αγαπησομεν                                                                                                                         |
| דדיך •^[Difference in vocalization (reading).]                                             | μαστους σου                                                                                                                        |
| מיין                                                                                       | υπερ οινον                                                                                                                         |
| מישרים                                                                                     | ευθυτης                                                                                                                            |
| אהבוך                                                                                      | ηγαπησεν σε                                                                                                                        |
: Song of Songs chapter 1, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| שחורה            | μελαινα      |
| אני              | ειμι         |
| ונאוה            | και καλη     |
| בנות             | θυγατερες    |
| ירושלם           | ιερουσαλημ   |
| כאהלי            | ως σκηνωματα |
| קדר              | κηδαρ        |
| כיריעות          | ως δερρεις   |
| שלמה             | σαλωμων      |
: Song of Songs chapter 1, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text                                                                         | Septuagint                                                                                     |
|:---------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------|
| אל                                                                                     | μη                                                                                             |
| תראוני                                                                                 | βλεψητε με                                                                                     |
| שאני                                                                                   | οτι εγω ειμι                                                                                   |
| שחרחרת                                                                                 | μεμελανωμενη                                                                                   |
| ששזפתני                                                                                | οτι παρεβλεψεν με                                                                              |
| השמש                                                                                   | ο ηλιος                                                                                        |
| בני                                                                                    | υιοι                                                                                           |
| אמי                                                                                    | μητρος μου                                                                                     |
| נחרו                                                                                   | εμαχεσαντο                                                                                     |
| בי                                                                                     | εν εμοι                                                                                        |
| שמני                                                                                   | εθεντο με                                                                                      |
| נטרה                                                                                   | φυλακισσαν                                                                                     |
| את הכרמים •^[Difference in preposition or particle.]                                   | εν αμπελωσιν                                                                                   |
| כרמי                                                                                   | αμπελωνα •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] εμον |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] י שלי | εμον                                                                                           |
| לא                                                                                     | ουκ                                                                                            |
| נטרתי                                                                                  | εφυλαξα                                                                                        |
: Song of Songs chapter 1, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| הגידה            | απαγγειλον       |
| לי               | μοι              |
| שאהבה            | ον ηγαπησεν      |
| נפשי             | η ψυχη μου       |
| איכה             | που              |
| תרעה             | ποιμαινεις       |
| איכה             | που              |
| תרביץ            | κοιταζεις        |
| בצהרים           | εν μεσημβρια     |
| שלמה             | μηποτε           |
| אהיה             | γενωμαι          |
| כעטיה            | ως περιβαλλομενη |
| על               | επ'              |
| עדרי             | αγελαις          |
| חבריך            | εταιρων σου      |
: Song of Songs chapter 1, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| אם               | εαν             |
| לא               | μη              |
| תדעי             | γνως            |
| לך               | σεαυτην         |
| היפה             | η καλη          |
| בנשים            | εν γυναιξιν     |
| צאי              | εξελθε          |
| לך               | συ              |
| בעקבי            | εν πτερναις     |
| הצאן             | των ποιμνιων    |
| ורעי             | και ποιμαινε    |
| את גדיתיך        | τας εριφους σου |
| על               | επι             |
| משכנות           | σκηνωμασιν      |
| הרעים            | των ποιμενων    |
: Song of Songs chapter 1, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| לססתי            | τη ιππω μου   |
| ברכבי            | εν αρμασιν    |
| פרעה             | φαραω         |
| דמיתיך           | ωμοιωσα σε    |
| רעיתי            | η πλησιον μου |
: Song of Songs chapter 1, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                                                     | Tov's retroversion          | Septuagint                  |
|:-----------------------------------------------------------------------------------|:----------------------------|:----------------------------|
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}       | [מה]{.potential-difference} | [τι]{.potential-difference} |
| נאוו                                                                               |                             | ωραιωθησαν                  |
| לחייך                                                                              |                             | σιαγονες σου                |
| בתרים •^[Difference in preposition or particle.] •^[Etymological exegesis.] <2.12> |                             | ως τρυγονες                 |
| צוארך                                                                              |                             | τραχηλος σου                |
| בחרוזים •^[Difference in preposition or particle.]                                 |                             | ως ορμισκοι                 |
: Song of Songs chapter 1, verse 10 { .hover tbl-colwidths="[35,30,35]"}

### Verse 11

| Masoretic text        | Septuagint   |
|:----------------------|:-------------|
| תורי =;תוארי <jj8.18> | ομοιωματα    |
| זהב                   | χρυσιου      |
| נעשה                  | ποιησομεν    |
| לך                    | σοι          |
| עם                    | μετα         |
| נקדות                 | στιγματων    |
| הכסף                  | του αργυριου |
: Song of Songs chapter 1, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| עד               | εως                |
| שהמלך            | ου ο βασιλευς      |
| במסבו            | εν ανακλισει αυτου |
| נרדי             | ναρδος μου         |
| נתן              | εδωκεν             |
| ריחו             | οσμην αυτου        |
: Song of Songs chapter 1, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| צרור             | αποδεσμος      |
| המר              | της στακτης    |
| דודי             | αδελφιδος μου  |
| לי               | εμοι           |
| בין              | ανα μεσον      |
| שדי              | των μαστων μου |
| ילין             | αυλισθησεται   |
: Song of Songs chapter 1, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| אשכל             | βοτρυς        |
| הכפר             | της κυπρου    |
| דודי             | αδελφιδος μου |
| לי               | εμοι          |
| בכרמי            | εν αμπελωσιν  |
| עין גדי          | εγγαδδι       |
: Song of Songs chapter 1, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| הנך              | ιδου ει       |
| יפה              | καλη          |
| רעיתי            | η πλησιον μου |
| הנך              | ιδου ει       |
| יפה              | καλη          |
| עיניך            | οφθαλμοι σου  |
| יונים            | περιστεραι    |
: Song of Songs chapter 1, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text                                | Septuagint      |
|:----------------------------------------------|:----------------|
| הנך                                           | ιδου ει         |
| יפה                                           | καλος           |
| דודי                                          | ο αδελφιδος μου |
| אף                                            | και γε          |
| נעים                                          | ωραιος          |
| אף •^[Difference in preposition or particle.] | προς            |
| ערשנו                                         | κλινη ημων      |
| רעננה                                         | συσκιος         |
: Song of Songs chapter 1, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| קרות             | δοκοι          |
| בתינו            | οικων ημων     |
| ארזים            | κεδροι         |
| *רחיטנו **רהיטנו | φατνωματα ημων |
| ברותים           | κυπαρισσοι     |
: Song of Songs chapter 1, verse 17 { .hover tbl-colwidths="[50,50]"}

## Chapter 2

### Verse 1

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| אני              | εγω          |
| חבצלת            | ανθος        |
| השרון            | του πεδιου   |
| שושנת            | κρινον       |
| העמקים           | των κοιλαδων |
: Song of Songs chapter 2, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| כשושנה           | ως κρινον     |
| בין              | εν μεσω       |
| החוחים           | ακανθων       |
| כן               | ουτως         |
| רעיתי            | η πλησιον μου |
| בין              | ανα μεσον     |
| הבנות            | των θυγατερων |
: Song of Songs chapter 2, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| כתפוח            | ως μηλον         |
| בעצי             | εν τοις ξυλοις   |
| היער             | του δρυμου       |
| כן               | ουτως            |
| דודי             | αδελφιδος μου    |
| בין              | ανα μεσον        |
| הבנים            | των υιων         |
| בצלו             | εν τη σκια αυτου |
| חמדתי            | επεθυμησα        |
| וישבתי           | και εκαθισα      |
| ופריו            | και καρπος αυτου |
| מתוק             | γλυκυς           |
| לחכי             | εν λαρυγγι μου   |
: Song of Songs chapter 2, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text                                                             | Septuagint    |
|:---------------------------------------------------------------------------|:--------------|
| הביאני •^[Difference in vocalization (reading).]                           | εισαγαγετε με |
| אל                                                                         | εις           |
| בית                                                                        | οικον         |
| היין                                                                       | του οινου     |
| ודגלו •^[Difference in vocalization (reading).] •^[Etymological exegesis.] | ταξατε        |
| עלי                                                                        | επ' εμε       |
| אהבה                                                                       | αγαπην        |
: Song of Songs chapter 2, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                                  | Septuagint    |
|:--------------------------------------------------------------------------------|:--------------|
| סמכוני                                                                          | στηρισατε με  |
| באשישות                                                                         | εν αμοραις    |
| רפדוני                                                                          | στοιβασατε με |
| בתפוחים                                                                         | εν μηλοις     |
| כי                                                                              | οτι           |
| חולת •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] חלל | τετρωμενη     |
| אהבה                                                                            | αγαπης        |
| אני                                                                             | εγω           |
: Song of Songs chapter 2, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| שמאלו            | ευωνυμος αυτου    |
| תחת              | υπο               |
| לראשי            | την κεφαλην μου   |
| וימינו           | και η δεξια αυτου |
| תחבקני           | περιλημψεται με   |
: Song of Songs chapter 2, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                    | Septuagint                                                                                                        |
|:----------------------------------|:------------------------------------------------------------------------------------------------------------------|
| השבעתי                            | ωρκισα                                                                                                            |
| אתכם                              | υμας                                                                                                              |
| בנות                              | θυγατερες                                                                                                         |
| ירושלם                            | ιερουσαλημ                                                                                                        |
| בצבאות •^[Etymological exegesis.] | εν ταις δυναμεσιν                                                                                                 |
| או                                | και                                                                                                               |
| באילות •^[Etymological exegesis.] | εν ταις ισχυσεσιν                                                                                                 |
| השדה                              | του αγρου                                                                                                         |
| אם                                | εαν                                                                                                               |
| תעירו                             | εγειρητε                                                                                                          |
| ואם                               | και •^[Distributive rendering, occurring once in the translation but referring to more than one Hebrew word.] εαν |
| תעוררו                            | εξεγειρητε                                                                                                        |
| את האהבה                          | την αγαπην                                                                                                        |
| עד                                | εως                                                                                                               |
| שתחפץ                             | ου θεληση                                                                                                         |
: Song of Songs chapter 2, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| קול              | φωνη          |
| דודי             | αδελφιδου μου |
| הנה              | ιδου          |
| זה               | ουτος         |
| בא               | ηκει          |
| מדלג             | πηδων         |
| על               | επι           |
| ההרים            | τα ορη        |
| מקפץ             | διαλλομενος   |
| על               | επι           |
| הגבעות           | τους βουνους  |
: Song of Songs chapter 2, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                                                                                                              | Septuagint                      |
|:--------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------|
| דומה                                                                                                                                        | ομοιος εστιν                    |
| דודי                                                                                                                                        | αδελφιδος μου                   |
| לצבי                                                                                                                                        | τη δορκαδι                      |
| או                                                                                                                                          | η                               |
| לעפר                                                                                                                                        | νεβρω                           |
| האילים                                                                                                                                      | ελαφων                          |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;על <2.17>]{.potential-difference}                                                    | [επι]{.potential-difference}    |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;הרי <2.17>]{.potential-difference}                                                   | [τα ορη]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;בתר <2.17> •^[Introducing reconstructed proper noun.] בית אל]{.potential-difference} | [βαιθηλ]{.potential-difference} |
| הנה                                                                                                                                         | ιδου                            |
| זה                                                                                                                                          | ουτος                           |
| עומד                                                                                                                                        | εστηκεν                         |
| אחר                                                                                                                                         | οπισω                           |
| כתלנו                                                                                                                                       | του τοιχου ημων                 |
| משגיח                                                                                                                                       | παρακυπτων                      |
| מן                                                                                                                                          | δια                             |
| החלנות                                                                                                                                      | των θυριδων                     |
| מציץ                                                                                                                                        | εκκυπτων                        |
| מן                                                                                                                                          | δια                             |
| החרכים                                                                                                                                      | των δικτυων                     |
: Song of Songs chapter 2, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                                                              | Septuagint                                                                                                                         |
|:--------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------|
| ענה                                                                                         | αποκρινεται                                                                                                                        |
| דודי                                                                                        | αδελφιδος μου                                                                                                                      |
| ואמר                                                                                        | και λεγει                                                                                                                          |
| לי                                                                                          | μοι                                                                                                                                |
| קומי                                                                                        | αναστα                                                                                                                             |
| לך {... •^[Questionable notation, equivalent, etc.] ולכי לכ}                                | ελθε                                                                                                                               |
| רעיתי                                                                                       | η πλησιον μου                                                                                                                      |
| יפתי                                                                                        | καλη μου                                                                                                                           |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;יונתי <2.14>]{.potential-difference} | [περιστερα μου]{.potential-difference}                                                                                             |
| [ולכי]{.potential-difference}                                                               | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} |
| [לך]{.potential-difference}                                                                 | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} |
: Song of Songs chapter 2, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| כי               | οτι          |
| הנה              | ιδου         |
| *הסתו **הסתיו    | ο χειμων     |
| עבר              | παρηλθεν     |
| הגשם             | ο υετος      |
| חלף              | απηλθεν      |
| הלך              | επορευθη     |
| לו               | εαυτω        |
: Song of Songs chapter 2, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                   | Septuagint    |
|:---------------------------------|:--------------|
| הנצנים                           | τα ανθη       |
| נראו                             | ωφθη          |
| בארץ                             | εν τη γη      |
| עת                               | καιρος        |
| הזמיר •^[Etymological exegesis.] | της τομης     |
| הגיע                             | εφθακεν       |
| וקול                             | φωνη          |
| התור                             | του τρυγονος  |
| נשמע                             | ηκουσθη       |
| בארצנו                           | εν τη γη ημων |
: Song of Songs chapter 2, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                                               | Tov's retroversion                    | Septuagint                             |
|:-----------------------------------------------------------------------------|:--------------------------------------|:---------------------------------------|
| התאנה                                                                        |                                       | η συκη                                 |
| חנטה                                                                         |                                       | εξηνεγκεν                              |
| פגיה                                                                         |                                       | ολυνθους αυτης                         |
| והגפנים                                                                      |                                       | αι αμπελοι                             |
| סמדר                                                                         |                                       | κυπριζουσιν                            |
| נתנו                                                                         |                                       | εδωκαν                                 |
| ריח                                                                          |                                       | οσμην                                  |
| קומי                                                                         |                                       | αναστα                                 |
| *לכי **לך •^[Agreement of LXX with ketib.]                                   |                                       | ελθε                                   |
| רעיתי                                                                        |                                       | η πλησιον μου                          |
| יפתי                                                                         |                                       | καλη μου                               |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [יונתי <2.14>]{.potential-difference} | [περιστερα μου]{.potential-difference} |
| ולכי                                                                         |                                       | και ελθε [14]                          |
| לך                                                                           |                                       | συ [14]                                |
: Song of Songs chapter 2, verse 13 { .hover tbl-colwidths="[35,30,35]"}

### Verse 14

| Masoretic text                  | Tov's retroversion                                                                                               | Septuagint                                  |
|:--------------------------------|:-----------------------------------------------------------------------------------------------------------------|:--------------------------------------------|
| יונתי                           |                                                                                                                  | περιστερα μου                               |
| בחגוי                           |                                                                                                                  | εν σκεπη                                    |
| הסלע                            |                                                                                                                  | της πετρας                                  |
| [בסתר]{.potential-difference}   | [•^[Questionable notation, equivalent, etc.] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [εχομενα]{.potential-difference}            |
| [המדרגה]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [του προτειχισματος]{.potential-difference} |
| הראיני                          |                                                                                                                  | δειξον μοι                                  |
| את מראיך                        |                                                                                                                  | την οψιν σου                                |
| השמיעיני                        |                                                                                                                  | και ακουτισον με                            |
| את קולך                         |                                                                                                                  | την φωνην σου                               |
| כי                              |                                                                                                                  | οτι                                         |
| קולך                            |                                                                                                                  | η φωνη σου                                  |
| ערב                             |                                                                                                                  | ηδεια                                       |
| ומראיך                          |                                                                                                                  | και η οψις σου                              |
| נאוה                            |                                                                                                                  | ωραια                                       |
: Song of Songs chapter 2, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text                         | Septuagint                                                                                                                                  |
|:---------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------|
| אחזו                                   | πιασατε                                                                                                                                     |
| לנו                                    | ημιν                                                                                                                                        |
| [שועלים שועלים]{.potential-difference} | [αλωπεκας •^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} |
| קטנים                                  | μικρους                                                                                                                                     |
| מחבלים                                 | αφανιζοντας                                                                                                                                 |
| כרמים                                  | αμπελωνας                                                                                                                                   |
| וכרמינו                                | και αι αμπελοι ημων                                                                                                                         |
| סמדר                                   | κυπριζουσιν                                                                                                                                 |
: Song of Songs chapter 2, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| דודי             | αδελφιδος μου   |
| לי               | εμοι            |
| ואני             | καγω            |
| לו               | αυτω            |
| הרעה             | ο ποιμαινων     |
| בשושנים          | εν τοις κρινοις |
: Song of Songs chapter 2, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text                                                                | Septuagint    |
|:------------------------------------------------------------------------------|:--------------|
| עד                                                                            | εως           |
| שיפוח                                                                         | ου διαπνευση  |
| היום                                                                          | η ημερα       |
| ונסו •^[Change from active to passive form in verbs.]                         | και κινηθωσιν |
| הצללים                                                                        | αι σκιαι      |
| סב •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] שוב | αποστρεψον    |
| דמה                                                                           | ομοιωθητι     |
| לך                                                                            | συ            |
| דודי                                                                          | αδελφιδε μου  |
| לצבי                                                                          | τω δορκωνι    |
| או                                                                            | η             |
| לעפר                                                                          | νεβρω         |
| האילים                                                                        | ελαφων        |
| על                                                                            | επι           |
| הרי                                                                           | ορη           |
| בתר                                                                           | κοιλωματων    |
: Song of Songs chapter 2, verse 17 { .hover tbl-colwidths="[50,50]"}

## Chapter 3

### Verse 1

| Masoretic text                                                                              | Septuagint                             |
|:--------------------------------------------------------------------------------------------|:---------------------------------------|
| על                                                                                          | επι                                    |
| משכבי                                                                                       | κοιτην μου                             |
| בלילות                                                                                      | εν νυξιν                               |
| בקשתי                                                                                       | εζητησα                                |
| את שאהבה                                                                                    | ον ηγαπησεν                            |
| נפשי                                                                                        | η ψυχη μου                             |
| בקשתיו                                                                                      | εζητησα αυτον                          |
| ולא                                                                                         | και ουχ                                |
| מצאתיו                                                                                      | ευρον αυτον                            |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;קראתיו <5.6>]{.potential-difference} | [εκαλεσα αυτον]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;ולא <5.6>]{.potential-difference}    | [και ουχ]{.potential-difference}       |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;ענני <5.6>]{.potential-difference}   | [υπηκουσεν μου]{.potential-difference} |
: Song of Songs chapter 3, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint            |
|:-----------------|:----------------------|
| אקומה            | αναστησομαι           |
| נא               | δη                    |
| ואסובבה          | και κυκλωσω           |
| בעיר             | εν τη πολει           |
| בשוקים           | εν ταις αγοραις       |
| וברחבות          | και εν ταις πλατειαις |
| אבקשה            | και ζητησω            |
| את שאהבה         | ον ηγαπησεν           |
| נפשי             | η ψυχη μου            |
| בקשתיו           | εζητησα αυτον         |
| ולא              | και ουχ               |
| מצאתיו           | ευρον αυτον           |
: Song of Songs chapter 3, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                                                               | Septuagint                  |
|:-----------------------------------------------------------------------------|:----------------------------|
| מצאוני                                                                       | ευροσαν με                  |
| השמרים                                                                       | οι τηρουντες                |
| הסבבים                                                                       | οι κυκλουντες               |
| בעיר                                                                         | εν τη πολει                 |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [μη]{.potential-difference} |
| את שאהבה                                                                     | ον ηγαπησεν                 |
| נפשי                                                                         | η ψυχη μου                  |
| ראיתם                                                                        | ειδετε                      |
: Song of Songs chapter 3, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| כמעט             | ως μικρον          |
| שעברתי           | οτε παρηλθον       |
| מהם              | απ' αυτων          |
| עד               | εως                |
| שמצאתי           | ου ευρον           |
| את שאהבה         | ον ηγαπησεν        |
| נפשי             | η ψυχη μου         |
| אחזתיו           | εκρατησα αυτον     |
| ולא              | και ουκ            |
| ארפנו            | αφησω αυτον        |
| עד               | εως                |
| שהביאתיו         | ου εισηγαγον αυτον |
| אל               | εις                |
| בית              | οικον              |
| אמי              | μητρος μου         |
| ואל              | και εις            |
| חדר              | ταμιειον           |
| הורתי            | της συλλαβουσης με |
: Song of Songs chapter 3, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                                        | Septuagint                                                                                                        |
|:--------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------|
| השבעתי                                                                                | ωρκισα                                                                                                            |
| אתכם                                                                                  | υμας                                                                                                              |
| בנות                                                                                  | θυγατερες                                                                                                         |
| ירושלם                                                                                | ιερουσαλημ                                                                                                        |
| בצבאות •^[Etymological exegesis.]                                                     | εν ταις δυναμεσιν                                                                                                 |
| או                                                                                    | και                                                                                                               |
| באילות •^[Etymological exegesis.]                                                     | εν ταις ισχυσεσιν                                                                                                 |
| השדה                                                                                  | του αγρου                                                                                                         |
| אם                                                                                    | εαν                                                                                                               |
| תעירו                                                                                 | εγειρητε                                                                                                          |
| ואם                                                                                   | και •^[Distributive rendering, occurring once in the translation but referring to more than one Hebrew word.] εαν |
| תעוררו                                                                                | εξεγειρητε                                                                                                        |
| את האהבה                                                                              | την αγαπην                                                                                                        |
| עד •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ש | εως αν                                                                                                            |
| שתחפץ                                                                                 | θεληση                                                                                                            |
: Song of Songs chapter 3, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| מי               | τις           |
| זאת              | αυτη          |
| עלה              | η αναβαινουσα |
| מן               | απο           |
| המדבר            | της ερημου    |
| כתימרות          | ως στελεχη    |
| עשן              | καπνου        |
| מקטרת            | τεθυμιαμενη   |
| מור              | σμυρναν       |
| ולבונה           | και λιβανον   |
| מכל              | απο παντων    |
| אבקת             | κονιορτων     |
| רוכל             | μυρεψου       |
: Song of Songs chapter 3, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| הנה              | ιδου         |
| מטתו             | η κλινη      |
| שלשלמה           | του σαλωμων  |
| ששים             | εξηκοντα     |
| גברים            | δυνατοι      |
| סביב             | κυκλω        |
| לה               | αυτης        |
| מגברי            | απο δυνατων  |
| ישראל            | ισραηλ       |
: Song of Songs chapter 3, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                        | Septuagint    |
|:------------------------------------------------------|:--------------|
| כלם                                                   | παντες        |
| אחזי •^[Change from passive to active form in verbs.] | κατεχοντες    |
| חרב                                                   | ρομφαιαν      |
| מלמדי                                                 | δεδιδαγμενοι  |
| מלחמה                                                 | πολεμον       |
| איש                                                   | ανηρ          |
| חרבו                                                  | ρομφαια αυτου |
| על                                                    | επι           |
| ירכו                                                  | μηρον αυτου   |
| מפחד                                                  | απο θαμβους   |
| בלילות                                                | εν νυξιν      |
: Song of Songs chapter 3, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| אפריון           | φορειον      |
| עשה              | εποιησεν     |
| לו               | εαυτω        |
| המלך             | ο βασιλευς   |
| שלמה             | σαλωμων      |
| מעצי             | απο ξυλων    |
| הלבנון           | του λιβανου  |
: Song of Songs chapter 3, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                | Tov's retroversion                                                              | Septuagint                           |
|:------------------------------|:--------------------------------------------------------------------------------|:-------------------------------------|
| עמודיו                        |                                                                                 | στυλους αυτου                        |
| עשה                           |                                                                                 | εποιησεν                             |
| כסף                           |                                                                                 | αργυριον                             |
| רפידתו                        |                                                                                 | και ανακλιτον αυτου                  |
| זהב                           |                                                                                 | χρυσεον                              |
| מרכבו                         |                                                                                 | επιβασις αυτου                       |
| ארגמן                         |                                                                                 | πορφυρα                              |
| תוכו                          |                                                                                 | εντος αυτου                          |
| [רצוף]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] רצוף אבנים]{.potential-difference} | [λιθοστρωτον]{.potential-difference} |
| אהבה                          |                                                                                 | αγαπην                               |
| מבנות                         |                                                                                 | απο θυγατερων                        |
| ירושלם                        |                                                                                 | ιερουσαλημ                           |
: Song of Songs chapter 3, verse 10 { .hover tbl-colwidths="[35,30,35]"}

### Verse 11

| Masoretic text                | Septuagint                                                                             |
|:------------------------------|:---------------------------------------------------------------------------------------|
| צאינה                         | εξελθατε                                                                               |
| וראינה                        | και ιδετε                                                                              |
| [בנות]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [ציון]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| במלך                          | εν τω βασιλει                                                                          |
| שלמה                          | σαλωμων                                                                                |
| בעטרה                         | εν τω στεφανω                                                                          |
| שעטרה                         | ω εστεφανωσεν                                                                          |
| לו                            | αυτον                                                                                  |
| אמו                           | η μητηρ αυτου                                                                          |
| ביום                          | εν ημερα                                                                               |
| חתנתו                         | νυμφευσεως αυτου                                                                       |
| וביום                         | και εν ημερα                                                                           |
| שמחת                          | ευφροσυνης                                                                             |
| לבו                           | καρδιας αυτου                                                                          |
: Song of Songs chapter 3, verse 11 { .hover tbl-colwidths="[50,50]"}

## Chapter 4

### Verse 1

| Masoretic text                                                                                                                    | Septuagint        |
|:----------------------------------------------------------------------------------------------------------------------------------|:------------------|
| הנך                                                                                                                               | ιδου ει           |
| יפה                                                                                                                               | καλη              |
| רעיתי                                                                                                                             | η πλησιον μου     |
| הנך                                                                                                                               | ιδου ει           |
| יפה                                                                                                                               | καλη              |
| עיניך                                                                                                                             | οφθαλμοι σου      |
| יונים                                                                                                                             | περιστεραι        |
| מבעד                                                                                                                              | εκτος             |
| לצמתך •^[Etymological exegesis.]                                                                                                  | της σιωπησεως σου |
| שערך                                                                                                                              | τριχωμα σου       |
| כעדר                                                                                                                              | ως αγελαι         |
| העזים                                                                                                                             | των αιγων         |
| שגלשו •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] גלה •^[Change from active to passive form in verbs.] | αι απεκαλυφθησαν  |
| מהר =;מן ה •^[Possible abbreviation.] <6.5>                                                                                       | απο του           |
| גלעד                                                                                                                              | γαλααδ            |
: Song of Songs chapter 4, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| שניך             | οδοντες σου    |
| כעדר             | ως αγελαι      |
| הקצובות          | των κεκαρμενων |
| שעלו             | αι ανεβησαν    |
| מן               | απο            |
| הרחצה            | του λουτρου    |
| שכלם             | αι πασαι       |
| מתאימות          | διδυμευουσαι   |
| ושכלה            | και ατεκνουσα  |
| אין              | ουκ εστιν      |
| בהם              | εν αυταις      |
: Song of Songs chapter 4, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                   | Tov's retroversion                                                                                               | Septuagint                         |
|:---------------------------------|:-----------------------------------------------------------------------------------------------------------------|:-----------------------------------|
| כחוט                             |                                                                                                                  | ως σπαρτιον                        |
| השני                             |                                                                                                                  | το κοκκινον                        |
| שפתתיך                           |                                                                                                                  | χειλη σου                          |
| ומדבריך                          |                                                                                                                  | και η λαλια σου                    |
| נאוה                             |                                                                                                                  | ωραια                              |
| כפלח                             |                                                                                                                  | ως λεπυρον                         |
| הרמון                            |                                                                                                                  | της ροας                           |
| [רקתך]{.potential-difference}    | [•^[Questionable notation, equivalent, etc.] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [μηλον σου]{.potential-difference} |
| מבעד                             |                                                                                                                  | εκτος                              |
| לצמתך •^[Etymological exegesis.] |                                                                                                                  | της σιωπησεως σου                  |
: Song of Songs chapter 4, verse 3 { .hover tbl-colwidths="[35,30,35]"}

### Verse 4

| Masoretic text                                                               | Septuagint                                  |
|:-----------------------------------------------------------------------------|:--------------------------------------------|
| כמגדל                                                                        | ως πυργος                                   |
| דויד                                                                         | δαυιδ                                       |
| צוארך                                                                        | τραχηλος σου                                |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [ο]{.potential-difference}                  |
| בנוי                                                                         | ωκοδομημενος                                |
| לתלפיות                                                                      | εις θαλπιωθ •^[Transliterated Hebrew word.] |
| אלף                                                                          | χιλιοι                                      |
| המגן                                                                         | θυρεοι                                      |
| תלוי                                                                         | κρεμανται                                   |
| עליו                                                                         | επ' αυτον                                   |
| כל                                                                           | πασαι                                       |
| שלטי                                                                         | βολιδες                                     |
| הגבורים                                                                      | των δυνατων                                 |
: Song of Songs chapter 4, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| שני              | δυο          |
| שדיך             | μαστοι σου   |
| כשני             | ως δυο       |
| עפרים            | νεβροι       |
| תאומי            | διδυμοι      |
| צביה             | δορκαδος     |
| הרועים           | οι νεμομενοι |
| בשושנים          | εν κρινοις   |
: Song of Songs chapter 4, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text                                        | Septuagint    |
|:------------------------------------------------------|:--------------|
| עד                                                    | εως           |
| שיפוח                                                 | ου διαπνευση  |
| היום                                                  | η ημερα       |
| ונסו •^[Change from active to passive form in verbs.] | και κινηθωσιν |
| הצללים                                                | αι σκιαι      |
| אלך                                                   | πορευσομαι    |
| לי                                                    | εμαυτω        |
| אל                                                    | προς          |
| הר                                                    | το ορος       |
| המור                                                  | της σμυρνης   |
| ואל                                                   | και προς      |
| גבעת                                                  | τον βουνον    |
| הלבונה                                                | του λιβανου   |
: Song of Songs chapter 4, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                                                                   | Septuagint                                                                              |
|:---------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------|
| כלך                                                                              | ολη •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ει |
| יפה                                                                              | καλη                                                                                    |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | ει                                                                                      |
| רעיתי                                                                            | η πλησιον μου                                                                           |
| ומום                                                                             | και μωμος                                                                               |
| אין                                                                              | ουκ εστιν                                                                               |
| בך                                                                               | εν σοι                                                                                  |
: Song of Songs chapter 4, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                                                             | Tov's retroversion                                                     | Septuagint                     |
|:-------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------|:-------------------------------|
| [אתי]{.potential-difference}                                                               | [אתי •^[Difference in vocalization (reading).]]{.potential-difference} | [δευρο]{.potential-difference} |
| מלבנון                                                                                     |                                                                        | απο λιβανου                    |
| כלה                                                                                        |                                                                        | νυμφη                          |
| [אתי]{.potential-difference}                                                               | [אתי •^[Difference in vocalization (reading).]]{.potential-difference} | [δευρο]{.potential-difference} |
| מלבנון                                                                                     |                                                                        | απο λιβανου                    |
| תבואי                                                                                      |                                                                        | ελευση                         |
| תשורי                                                                                      |                                                                        | και διελευση                   |
| מראש                                                                                       |                                                                        | απο αρχης                      |
| אמנה •^[Difference in vocalization (reading).] •^[Questionable notation, equivalent, etc.] |                                                                        | πιστεως                        |
| מראש                                                                                       |                                                                        | απο κεφαλης                    |
| שניר                                                                                       |                                                                        | σανιρ                          |
| וחרמון                                                                                     |                                                                        | και ερμων                      |
| ממענות                                                                                     |                                                                        | απο μανδρων                    |
| אריות                                                                                      |                                                                        | λεοντων                        |
| מהררי                                                                                      |                                                                        | απο ορεων                      |
| נמרים                                                                                      |                                                                        | παρδαλεων                      |
: Song of Songs chapter 4, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| לבבתני           | εκαρδιωσας ημας  |
| אחתי             | αδελφη μου       |
| כלה              | νυμφη            |
| לבבתיני          | εκαρδιωσας ημας  |
| *באחד **באחת     | ενι              |
| מעיניך           | απο οφθαλμων σου |
| באחד             | εν μια           |
| ענק              | ενθεματι         |
| מצורניך          | τραχηλων σου     |
: Song of Songs chapter 4, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                 | Septuagint   |
|:-----------------------------------------------|:-------------|
| מה                                             | τι           |
| יפו                                            | εκαλλιωθησαν |
| דדיך •^[Difference in vocalization (reading).] | μαστοι σου   |
| אחתי                                           | αδελφη μου   |
| כלה                                            | νυμφη        |
| מה                                             | τι           |
| טבו                                            | εκαλλιωθησαν |
| דדיך •^[Difference in vocalization (reading).] | μαστοι σου   |
| מיין                                           | απο οινου    |
| וריח                                           | και οσμη     |
| שמניך =;שלמתיך <4.11>                          | ιματιων σου  |
| מכל                                            | υπερ παντα   |
| בשמים                                          | τα αρωματα   |
: Song of Songs chapter 4, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| נפת              | κηριον          |
| תטפנה            | αποσταζουσιν    |
| שפתותיך          | χειλη σου       |
| כלה              | νυμφη           |
| דבש              | μελι            |
| וחלב             | και γαλα        |
| תחת              | υπο             |
| לשונך            | την γλωσσαν σου |
| וריח             | και οσμη        |
| שלמתיך           | ιματιων σου     |
| כריח             | ως οσμη         |
| לבנון            | λιβανου         |
: Song of Songs chapter 4, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text              | Tov's retroversion                                                      | Septuagint                     |
|:----------------------------|:------------------------------------------------------------------------|:-------------------------------|
| גן                          |                                                                         | κηπος                          |
| נעול                        |                                                                         | κεκλεισμενος                   |
| אחתי                        |                                                                         | αδελφη μου                     |
| כלה                         |                                                                         | νυμφη                          |
| [גל]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] גן]{.potential-difference} | [κηπος]{.potential-difference} |
| נעול                        |                                                                         | κεκλεισμενος                   |
| מעין                        |                                                                         | πηγη                           |
| חתום                        |                                                                         | εσφραγισμενη                   |
: Song of Songs chapter 4, verse 12 { .hover tbl-colwidths="[35,30,35]"}

### Verse 13

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| שלחיך            | αποστολαι σου |
| פרדס             | παραδεισος    |
| רמונים           | ροων          |
| עם               | μετα          |
| פרי              | καρπου        |
| מגדים            | ακροδρυων     |
| כפרים            | κυπροι        |
| עם               | μετα          |
| נרדים            | ναρδων        |
: Song of Songs chapter 4, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text   | Septuagint                           |
|:-----------------|:-------------------------------------|
| נרד              | ναρδος                               |
| וכרכם            | και κροκος                           |
| קנה              | καλαμος                              |
| וקנמון           | και κινναμωμον                       |
| עם               | μετα                                 |
| כל               | παντων                               |
| עצי              | ξυλων                                |
| לבונה            | του λιβανου                          |
| מר               | σμυρνα                               |
| ואהלות           | αλωθ •^[Transliterated Hebrew word.] |
| עם               | μετα                                 |
| כל               | παντων                               |
| ראשי             | πρωτων                               |
| בשמים            | μυρων                                |
: Song of Songs chapter 4, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| מעין             | πηγη           |
| גנים             | κηπων          |
| באר              | φρεαρ          |
| מים              | υδατος         |
| חיים             | ζωντος         |
| ונזלים           | και ροιζουντος |
| מן               | απο            |
| לבנון            | του λιβανου    |
: Song of Songs chapter 4, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| עורי             | εξεγερθητι      |
| צפון             | βορρα           |
| ובואי            | και ερχου       |
| תימן             | νοτε            |
| הפיחי            | διαπνευσον      |
| גני              | κηπον μου       |
| יזלו             | και ρευσατωσαν  |
| בשמיו            | αρωματα μου     |
| יבא              | καταβητω        |
| דודי             | αδελφιδος μου   |
| לגנו             | εις κηπον αυτου |
| ויאכל            | και φαγετω      |
| פרי              | καρπον          |
| מגדיו            | ακροδρυων αυτου |
: Song of Songs chapter 4, verse 16 { .hover tbl-colwidths="[50,50]"}

## Chapter 5

### Verse 1

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| באתי             | εισηλθον      |
| לגני             | εις κηπον μου |
| אחתי             | αδελφη μου    |
| כלה              | νυμφη         |
| אריתי            | ετρυγησα      |
| מורי             | σμυρναν μου   |
| עם               | μετα          |
| בשמי             | αρωματων μου  |
| אכלתי            | εφαγον        |
| יערי             | αρτον μου     |
| עם               | μετα          |
| דבשי             | μελιτος μου   |
| שתיתי            | επιον         |
| ייני             | οινον μου     |
| עם               | μετα          |
| חלבי             | γαλακτος μου  |
| אכלו             | φαγετε        |
| רעים             | πλησιοι       |
| שתו              | και πιετε     |
| ושכרו            | και μεθυσθητε |
| דודים            | αδελφοι       |
: Song of Songs chapter 5, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                                               | Septuagint                         |
|:-----------------------------------------------------------------------------|:-----------------------------------|
| אני                                                                          | εγω                                |
| ישנה                                                                         | καθευδω                            |
| ולבי                                                                         | και η καρδια μου                   |
| ער                                                                           | αγρυπνει                           |
| קול                                                                          | φωνη                               |
| דודי                                                                         | αδελφιδου μου                      |
| דופק                                                                         | κρουει                             |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [επι]{.potential-difference}       |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [την θυραν]{.potential-difference} |
| פתחי                                                                         | ανοιξον                            |
| לי                                                                           | μοι                                |
| אחתי                                                                         | αδελφη μου                         |
| רעיתי                                                                        | η πλησιον μου                      |
| יונתי                                                                        | περιστερα μου                      |
| תמתי                                                                         | τελεια μου                         |
| שראשי                                                                        | οτι η κεφαλη μου                   |
| נמלא                                                                         | επλησθη                            |
| טל                                                                           | δροσου                             |
| קוצותי                                                                       | και οι βοστρυχοι μου               |
| רסיסי                                                                        | ψεκαδων                            |
| לילה                                                                         | νυκτος                             |
: Song of Songs chapter 5, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| פשטתי            | εξεδυσαμην      |
| את כתנתי         | τον χιτωνα μου  |
| איככה            | πως             |
| אלבשנה           | ενδυσωμαι αυτον |
| רחצתי            | ενιψαμην        |
| את רגלי          | τους ποδας μου  |
| איככה            | πως             |
| אטנפם            | μολυνω αυτους   |
: Song of Songs chapter 5, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| דודי             | αδελφιδος μου    |
| שלח              | απεστειλεν       |
| ידו              | χειρα αυτου      |
| מן               | απο              |
| החר              | της οπης         |
| ומעי             | και η κοιλια μου |
| המו              | εθροηθη          |
| עליו             | επ' αυτον        |
: Song of Songs chapter 5, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                 | Septuagint      |
|:-------------------------------|:----------------|
| קמתי                           | ανεστην         |
| אני                            | εγω             |
| לפתח                           | ανοιξαι         |
| לדודי                          | τω αδελφιδω μου |
| וידי                           | χειρες μου      |
| נטפו                           | εσταξαν         |
| מור                            | σμυρναν         |
| ואצבעתי                        | δακτυλοι μου    |
| מור                            | σμυρναν         |
| עבר •^[Etymological exegesis.] | πληρη           |
| על                             | επι             |
| כפות                           | χειρας          |
| המנעול                         | του κλειθρου    |
: Song of Songs chapter 5, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text                                            | Septuagint                                                                                                                         |
|:----------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------|
| פתחתי                                                     | ηνοιξα                                                                                                                             |
| אני                                                       | εγω                                                                                                                                |
| לדודי                                                     | τω αδελφιδω μου                                                                                                                    |
| ודודי                                                     | αδελφιδος μου                                                                                                                      |
| [חמק]{.potential-difference}                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} |
| {... •^[Questionable notation, equivalent, etc.] חמק} עבר | παρηλθεν                                                                                                                           |
| נפשי                                                      | ψυχη μου                                                                                                                           |
| יצאה                                                      | εξηλθεν                                                                                                                            |
| בדברו                                                     | εν λογω αυτου                                                                                                                      |
| בקשתיהו                                                   | εζητησα αυτον                                                                                                                      |
| ולא                                                       | και ουχ                                                                                                                            |
| מצאתיהו                                                   | ευρον αυτον                                                                                                                        |
| קראתיו                                                    | εκαλεσα αυτον                                                                                                                      |
| ולא                                                       | και ουχ                                                                                                                            |
| ענני                                                      | υπηκουσεν μου                                                                                                                      |
: Song of Songs chapter 5, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| מצאני            | ευροσαν με       |
| השמרים           | οι φυλακες       |
| הסבבים           | οι κυκλουντες    |
| בעיר             | εν τη πολει      |
| הכוני            | επαταξαν με      |
| פצעוני           | ετραυματισαν με  |
| נשאו             | ηραν             |
| את רדידי         | το θεριστρον μου |
| מעלי             | απ' εμου         |
| שמרי             | φυλακες          |
| החמות            | των τειχεων      |
: Song of Songs chapter 5, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                                                                 | Septuagint                                     |
|:-----------------------------------------------------------------------------------------------|:-----------------------------------------------|
| השבעתי                                                                                         | ωρκισα                                         |
| אתכם                                                                                           | υμας                                           |
| בנות                                                                                           | θυγατερες                                      |
| ירושלם                                                                                         | ιερουσαλημ                                     |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;בצבאות <2.7>]{.potential-difference}    | [εν ταις δυναμεσιν]{.potential-difference}     |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;או באילות <2.7>]{.potential-difference} | [και εν ταις ισχυσεσιν]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;השדה <2.7>]{.potential-difference}      | [του αγρου]{.potential-difference}             |
| אם                                                                                             | εαν                                            |
| תמצאו                                                                                          | ευρητε                                         |
| את דודי                                                                                        | τον αδελφιδον μου                              |
| מה                                                                                             | τι                                             |
| תגידו                                                                                          | απαγγειλητε                                    |
| לו                                                                                             | αυτω                                           |
| שחולת •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] חלל               | οτι τετρωμενη                                  |
| אהבה                                                                                           | αγαπης                                         |
| אני                                                                                            | ειμι εγω                                       |
: Song of Songs chapter 5, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| מה               | τι            |
| דודך             | αδελφιδος σου |
| מדוד             | απο αδελφιδου |
| היפה             | η καλη        |
| בנשים            | εν γυναιξιν   |
| מה               | τι            |
| דודך             | αδελφιδος σου |
| מדוד             | απο αδελφιδου |
| שככה             | οτι ουτως     |
| השבעתנו          | ωρκισας ημας  |
: Song of Songs chapter 5, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| דודי             | αδελφιδος μου  |
| צח               | λευκος         |
| ואדום            | και πυρρος     |
| דגול             | εκλελοχισμενος |
| מרבבה            | απο μυριαδων   |
: Song of Songs chapter 5, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text   | Septuagint                              |
|:-----------------|:----------------------------------------|
| ראשו             | κεφαλη αυτου                            |
| כתם              | χρυσιον                                 |
| פז               | και φαζ •^[Transliterated Hebrew word.] |
| קוצותיו          | βοστρυχοι αυτου                         |
| תלתלים           | ελαται                                  |
| שחרות            | μελανες                                 |
| כעורב            | ως κοραξ                                |
: Song of Songs chapter 5, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                                                                                                           | Septuagint                                                         |
|:-------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------|
| עיניו                                                                                                                    | οφθαλμοι αυτου                                                     |
| כיונים                                                                                                                   | ως περιστεραι                                                      |
| על                                                                                                                       | επι                                                                |
| אפיקי                                                                                                                    | πληρωματα                                                          |
| מים                                                                                                                      | υδατων                                                             |
| רחצות                                                                                                                    | λελουσμεναι                                                        |
| בחלב                                                                                                                     | εν γαλακτι                                                         |
| ישבות                                                                                                                    | καθημεναι                                                          |
| על                                                                                                                       | επι                                                                |
| מלאת                                                                                                                     | πληρωματα {... •^[Questionable notation, equivalent, etc.] υδατων} |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [υδατων]{.potential-difference}                                    |
: Song of Songs chapter 5, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                   | Septuagint     |
|:-------------------------------------------------|:---------------|
| לחיו                                             | σιαγονες αυτου |
| כערוגת                                           | ως φιαλαι      |
| הבשם                                             | του αρωματος   |
| מגדלות •^[Difference in vocalization (reading).] | φυουσαι        |
| מרקחים                                           | μυρεψικα       |
| שפתותיו                                          | χειλη αυτου    |
| שושנים                                           | κρινα          |
| נטפות                                            | σταζοντα       |
| מור                                              | σμυρναν        |
| עבר •^[Etymological exegesis.]                   | πληρη          |
: Song of Songs chapter 5, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                 | Tov's retroversion                                                                                                                                  | Septuagint                                                        |
|:-------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------|
| ידיו                           |                                                                                                                                                     | χειρες αυτου                                                      |
| גלילי                          |                                                                                                                                                     | τορευται                                                          |
| זהב                            |                                                                                                                                                     | χρυσαι                                                            |
| ממלאים                         |                                                                                                                                                     | πεπληρωμεναι                                                      |
| בתרשיש                         |                                                                                                                                                     | θαρσις •^[Transliterated Hebrew word.]                            |
| מעיו                           |                                                                                                                                                     | κοιλια αυτου                                                      |
| עשת                            |                                                                                                                                                     | πυξιον                                                            |
| שן                             |                                                                                                                                                     | ελεφαντινον                                                       |
| [מעלפת]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] מעל פת •^[Two words of MT joined into one word in the parent text of the LXX.]]{.potential-difference} | [επι λιθου]{.potential-difference}                                |
| ספירים                         |                                                                                                                                                     | {... •^[Questionable notation, equivalent, etc.] λιθου} σαπφειρου |
: Song of Songs chapter 5, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| שוקיו            | κνημαι αυτου   |
| עמודי            | στυλοι         |
| שש               | μαρμαρινοι     |
| מיסדים           | τεθεμελιωμενοι |
| על               | επι            |
| אדני             | βασεις         |
| פז               | χρυσας         |
| מראהו            | ειδος αυτου    |
| כלבנון           | ως λιβανος     |
| בחור             | εκλεκτος       |
| כארזים           | ως κεδροι      |
: Song of Songs chapter 5, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| חכו              | φαρυγξ αυτου  |
| ממתקים           | γλυκασμοι     |
| וכלו             | και ολος      |
| מחמדים           | επιθυμια      |
| זה               | ουτος         |
| דודי             | αδελφιδος μου |
| וזה              | και ουτος     |
| רעי              | πλησιον μου   |
| בנות             | θυγατερες     |
| ירושלם           | ιερουσαλημ    |
: Song of Songs chapter 5, verse 16 { .hover tbl-colwidths="[50,50]"}

## Chapter 6

### Verse 1

| Masoretic text   | Septuagint          |
|:-----------------|:--------------------|
| אנה              | που                 |
| הלך              | απηλθεν             |
| דודך             | ο αδελφιδος σου     |
| היפה             | η καλη              |
| בנשים            | εν γυναιξιν         |
| אנה              | που                 |
| פנה              | απεβλεψεν           |
| דודך             | ο αδελφιδος σου     |
| ונבקשנו          | και ζητησομεν αυτον |
| עמך              | μετα σου            |
: Song of Songs chapter 6, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| דודי             | αδελφιδος μου   |
| ירד              | κατεβη          |
| לגנו             | εις κηπον αυτου |
| לערוגות          | εις φιαλας      |
| הבשם             | του αρωματος    |
| לרעות            | ποιμαινειν      |
| בגנים            | εν κηποις       |
| וללקט            | και συλλεγειν   |
| שושנים           | κρινα           |
: Song of Songs chapter 6, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| אני              | εγω               |
| לדודי            | τω αδελφιδω μου   |
| ודודי            | και αδελφιδος μου |
| לי               | εμοι              |
| הרעה             | ο ποιμαινων       |
| בשושנים          | εν τοις κρινοις   |
: Song of Songs chapter 6, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text                                 | Septuagint    |
|:-----------------------------------------------|:--------------|
| יפה                                            | καλη          |
| את                                             | ει            |
| רעיתי                                          | η πλησιον μου |
| כתרצה                                          | ως ευδοκια    |
| נאוה                                           | ωραια         |
| כירושלם                                        | ως ιερουσαλημ |
| אימה •^[Difference in vocalization (reading).] | θαμβος        |
| כנדגלות •^[Etymological exegesis.]             | ως τεταγμεναι |
: Song of Songs chapter 6, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                                   | Septuagint     |
|:---------------------------------------------------------------------------------|:---------------|
| הסבי                                                                             | αποστρεψον     |
| עיניך                                                                            | οφθαλμους σου  |
| מנגדי                                                                            | απεναντιον μου |
| שהם                                                                              | οτι αυτοι      |
| הרהיבני                                                                          | ανεπτερωσαν με |
| שערך                                                                             | τριχωμα σου    |
| כעדר                                                                             | ως αγελαι      |
| העזים                                                                            | των αιγων      |
| שגלשו •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] גלה | αι ανεφανησαν  |
| מן                                                                               | απο            |
| הגלעד                                                                            | του γαλααδ     |
: Song of Songs chapter 6, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text         | Septuagint     |
|:-----------------------|:---------------|
| שניך                   | οδοντες σου    |
| כעדר                   | ως αγελαι      |
| הרחלים =;הקצובות <4.2> | των κεκαρμενων |
| שעלו                   | αι ανεβησαν    |
| מן                     | απο            |
| הרחצה                  | του λουτρου    |
| שכלם                   | αι πασαι       |
| מתאימות                | διδυμευουσαι   |
| ושכלה                  | και ατεκνουσα  |
| אין                    | ουκ εστιν      |
| בהם                    | εν αυταις      |
: Song of Songs chapter 6, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text                                                                                                                             | Septuagint                               |
|:-------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------|
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;כחוט <4.3>]{.potential-difference}    | [ως σπαρτιον]{.potential-difference}     |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;השני <4.3>]{.potential-difference}    | [το κοκκινον]{.potential-difference}     |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;שפתתיך <4.3>]{.potential-difference}  | [χειλη σου]{.potential-difference}       |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;ומדבריך <4.3>]{.potential-difference} | [και η λαλια σου]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;נאוה <4.3>]{.potential-difference}    | [ωραια]{.potential-difference}           |
| כפלח                                                                                                                                       | ως λεπυρον                               |
| הרמון                                                                                                                                      | της ροας                                 |
| רקתך                                                                                                                                       | μηλον σου                                |
| מבעד                                                                                                                                       | εκτος                                    |
| לצמתך •^[Etymological exegesis.]                                                                                                           | της σιωπησεως σου                        |
: Song of Songs chapter 6, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text                                                               | Septuagint                  |
|:-----------------------------------------------------------------------------|:----------------------------|
| ששים                                                                         | εξηκοντα                    |
| המה                                                                          | εισιν                       |
| מלכות                                                                        | βασιλισσαι                  |
| ושמנים                                                                       | και ογδοηκοντα              |
| פילגשים                                                                      | παλλακαι                    |
| ועלמות                                                                       | και νεανιδες                |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [ων]{.potential-difference} |
| אין                                                                          | ουκ εστιν                   |
| מספר                                                                         | αριθμος                     |
: Song of Songs chapter 6, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text   | Septuagint            |
|:-----------------|:----------------------|
| אחת              | μια                   |
| היא              | εστιν                 |
| יונתי            | περιστερα μου         |
| תמתי             | τελεια μου            |
| אחת              | μια                   |
| היא              | εστιν                 |
| לאמה             | τη μητρι αυτης        |
| ברה              | εκλεκτη               |
| היא              | εστιν                 |
| ליולדתה          | τη τεκουση αυτης      |
| ראוה             | ειδοσαν αυτην         |
| בנות             | θυγατερες             |
| ויאשרוה          | και μακαριουσιν αυτην |
| מלכות            | βασιλισσαι            |
| ופילגשים         | και παλλακαι          |
| ויהללוה          | και αινεσουσιν αυτην  |
: Song of Songs chapter 6, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                     | Septuagint    |
|:-----------------------------------|:--------------|
| מי                                 | τις           |
| זאת                                | αυτη          |
| הנשקפה                             | η εκκυπτουσα  |
| כמו                                | ωσει          |
| שחר                                | ορθρος        |
| יפה                                | καλη          |
| כלבנה                              | ως σεληνη     |
| ברה                                | εκλεκτη       |
| כחמה                               | ως ο ηλιος    |
| אימה                               | θαμβος        |
| כנדגלות •^[Etymological exegesis.] | ως τεταγμεναι |
: Song of Songs chapter 6, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                                                                                                                         | Septuagint                                |
|:---------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------|
| אל                                                                                                                                     | εις                                       |
| גנת                                                                                                                                    | κηπον                                     |
| אגוז                                                                                                                                   | καρυας                                    |
| ירדתי                                                                                                                                  | κατεβην                                   |
| לראות                                                                                                                                  | ιδειν                                     |
| באבי                                                                                                                                   | εν γενημασιν                              |
| הנחל                                                                                                                                   | του χειμαρρου                             |
| לראות                                                                                                                                  | ιδειν                                     |
| הפרחה                                                                                                                                  | ει ηνθησεν                                |
| הגפן                                                                                                                                   | η αμπελος                                 |
| הנצו                                                                                                                                   | εξηνθησαν                                 |
| הרמנים                                                                                                                                 | αι ροαι                                   |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;שם <7.13>]{.potential-difference}                                               | [εκει]{.potential-difference}             |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;אתן <7.13>]{.potential-difference}                                              | [δωσω]{.potential-difference}             |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;את דדי •^[Difference in vocalization (reading).] <7.13>]{.potential-difference} | [τους μαστους μου]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;לך <7.13>]{.potential-difference}                                               | [σοι]{.potential-difference}              |
: Song of Songs chapter 6, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                                                                                                                                                                                                           | Septuagint                                                 |
|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------|
| לא                                                                                                                                                                                                                       | ουκ                                                        |
| ידעתי                                                                                                                                                                                                                    | εγνω                                                       |
| נפשי                                                                                                                                                                                                                     | η ψυχη μου                                                 |
| שמתני                                                                                                                                                                                                                    | εθετο με                                                   |
| מרכבות                                                                                                                                                                                                                   | αρματα                                                     |
| עמי נדיב •^[Difference in vocalization (reading).] •^[Two words of MT joined into one word in the parent text of the LXX.] •^[Introducing reconstructed proper noun.] •^[Questionable notation, equivalent, etc.] עמינדב | αμιναδαβ •^[Transliterated Hebrew word.] <7.2,es2.15,9.29> |
: Song of Songs chapter 6, verse 12 { .hover tbl-colwidths="[50,50]"}

## Chapter 7

### Verse 1

| Masoretic text                                                                                                           | Tov's retroversion              | Septuagint                          |
|:-------------------------------------------------------------------------------------------------------------------------|:--------------------------------|:------------------------------------|
| שובי                                                                                                                     |                                 | επιστρεφε                           |
| שובי                                                                                                                     |                                 | επιστρεφε                           |
| השולמית                                                                                                                  |                                 | η σουλαμιτις                        |
| שובי                                                                                                                     |                                 | επιστρεφε                           |
| שובי                                                                                                                     |                                 | επιστρεφε                           |
| ונחזה                                                                                                                    |                                 | και οψομεθα                         |
| בך                                                                                                                       |                                 | εν σοι                              |
| מה                                                                                                                       |                                 | τι                                  |
| תחזו                                                                                                                     |                                 | οψεσθε                              |
| בשולמית                                                                                                                  |                                 | εν τη σουλαμιτιδι                   |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [היוצאת]{.potential-difference} | [η ερχομενη]{.potential-difference} |
| כמחלת •^[Difference in vocalization (reading).]                                                                          |                                 | ως χοροι                            |
| המחנים •^[Difference in vocalization (reading).]                                                                         |                                 | των παρεμβολων                      |
: Song of Songs chapter 7, verse 1 { .hover tbl-colwidths="[35,30,35]"}

### Verse 2

| Masoretic text                | Tov's retroversion               | Septuagint                                                     |
|:------------------------------|:---------------------------------|:---------------------------------------------------------------|
| מה                            |                                  | τι                                                             |
| יפו                           |                                  | ωραιωθησαν                                                     |
| פעמיך                         |                                  | διαβηματα σου                                                  |
| בנעלים                        |                                  | εν υποδημασιν                                                  |
| בת                            |                                  | θυγατερ                                                        |
| [נדיב]{.potential-difference} | [נדב .y-]{.potential-difference} | [ναδαβ •^[Transliterated Hebrew word.]]{.potential-difference} |
| חמוקי                         |                                  | ρυθμοι                                                         |
| ירכיך                         |                                  | μηρων σου                                                      |
| כמו                           |                                  | ομοιοι                                                         |
| חלאים                         |                                  | ορμισκοις                                                      |
| מעשה                          |                                  | εργω                                                           |
| ידי                           |                                  | χειρων                                                         |
| אמן                           |                                  | τεχνιτου                                                       |
: Song of Songs chapter 7, verse 2 { .hover tbl-colwidths="[35,30,35]"}

### Verse 3

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| שררך             | ομφαλος σου  |
| אגן              | κρατηρ       |
| הסהר             | τορευτος     |
| אל               | μη           |
| יחסר             | υστερουμενος |
| המזג             | κραμα        |
| בטנך             | κοιλια σου   |
| ערמת             | θιμωνια      |
| חטים             | σιτου        |
| סוגה             | πεφραγμενη   |
| בשושנים          | εν κρινοις   |
: Song of Songs chapter 7, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| שני              | δυο          |
| שדיך             | μαστοι σου   |
| כשני             | ως δυο       |
| עפרים            | νεβροι       |
| תאמי             | διδυμοι      |
| צביה             | δορκαδος     |
: Song of Songs chapter 7, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                 | Septuagint   |
|:-----------------------------------------------|:-------------|
| צוארך                                          | τραχηλος σου |
| כמגדל                                          | ως πυργος    |
| השן                                            | ελεφαντινος  |
| עיניך                                          | οφθαλμοι σου |
| ברכות •^[Addition of preposition or particle.] | ως λιμναι    |
| בחשבון                                         | εν εσεβων    |
| על •^[Difference in preposition or particle.]  | εν           |
| שער                                            | πυλαις       |
| בת                                             | θυγατρος     |
| רבים                                           | πολλων       |
| אפך                                            | μυκτηρ σου   |
| כמגדל                                          | ως πυργος    |
| הלבנון                                         | του λιβανου  |
| צופה                                           | σκοπευων     |
| פני                                            | προσωπον     |
| דמשק                                           | δαμασκου     |
: Song of Songs chapter 7, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text                         | Septuagint     |
|:---------------------------------------|:---------------|
| ראשך                                   | κεφαλη σου     |
| עליך                                   | επι σε         |
| ככרמל                                  | ως καρμηλος    |
| ודלת                                   | και πλοκιον    |
| ראשך                                   | κεφαλης σου    |
| כארגמן                                 | ως πορφυρα     |
| מלך                                    | βασιλευς       |
| אסור                                   | δεδεμενος      |
| ברהטים •^[Etymological exegesis.] רהטa | εν παραδρομαις |
: Song of Songs chapter 7, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| מה               | τι           |
| יפית             | ωραιωθης     |
| ומה              | και τι       |
| נעמת             | ηδυνθης      |
| אהבה             | αγαπη        |
| בתענוגים         | εν τρυφαις   |
: Song of Songs chapter 7, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| זאת              | τουτο             |
| קומתך            | μεγεθος σου       |
| דמתה             | ωμοιωθη           |
| לתמר             | τω φοινικι        |
| ושדיך            | και οι μαστοι σου |
| לאשכלות          | τοις βοτρυσιν     |
: Song of Songs chapter 7, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                 | Septuagint      |
|:-----------------------------------------------|:----------------|
| אמרתי                                          | ειπα            |
| אעלה                                           | αναβησομαι      |
| בתמר •^[Difference in vocalization (reading).] | εν τω φοινικι   |
| אחזה                                           | κρατησω         |
| בסנסניו •^[Etymological exegesis.]             | των υψεων αυτου |
| ויהיו                                          | και εσονται     |
| נא                                             | δη              |
| שדיך                                           | μαστοι σου      |
| כאשכלות                                        | ως βοτρυες      |
| הגפן                                           | της αμπελου     |
| וריח                                           | και οσμη        |
| אפך                                            | ρινος σου       |
| כתפוחים                                        | ως μηλα         |
: Song of Songs chapter 7, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                 | Tov's retroversion                 | Septuagint                           |
|:-----------------------------------------------|:-----------------------------------|:-------------------------------------|
| וחכך                                           |                                    | και λαρυγξ σου                       |
| כיין                                           |                                    | ως οινος                             |
| הטוב                                           |                                    | ο αγαθος                             |
| הולך                                           |                                    | πορευομενος                          |
| לדודי                                          |                                    | τω αδελφιδω μου                      |
| למישרים                                        |                                    | εις ευθυθητα                         |
| דובב                                           |                                    | ικανουμενος                          |
| שפתי •^[Difference in vocalization (reading).] |                                    | χειλεσιν μου                         |
| [ישנים]{.potential-difference}                 | [ושנים .yw]{.potential-difference} | [και οδουσιν]{.potential-difference} |
: Song of Songs chapter 7, verse 10 { .hover tbl-colwidths="[35,30,35]"}

### Verse 11

| Masoretic text                  | Tov's retroversion                                                              | Septuagint                                          |
|:--------------------------------|:--------------------------------------------------------------------------------|:----------------------------------------------------|
| אני                             |                                                                                 | εγω                                                 |
| לדודי                           |                                                                                 | τω αδελφιδω μου                                     |
| ועלי                            |                                                                                 | και επ' εμε                                         |
| [תשוקתו]{.potential-difference} | [•^[Questionable notation, equivalent, etc.] תשובתו .qb]{.potential-difference} | [η επιστροφη αυτου <ge3.16>]{.potential-difference} |
: Song of Songs chapter 7, verse 11 { .hover tbl-colwidths="[35,30,35]"}

### Verse 12

| Masoretic text                                                                   | Septuagint                                                                                                             |
|:---------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------|
| לכה                                                                              | ελθε                                                                                                                   |
| דודי                                                                             | αδελφιδε μου                                                                                                           |
| נצא                                                                              | εξελθωμεν                                                                                                              |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εις                                                                                                                    |
| השדה                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εις αγρον |
| נלינה                                                                            | αυλισθωμεν                                                                                                             |
| בכפרים                                                                           | εν κωμαις                                                                                                              |
: Song of Songs chapter 7, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                   | Septuagint       |
|:-------------------------------------------------|:-----------------|
| נשכימה                                           | ορθρισωμεν       |
| לכרמים                                           | εις αμπελωνας    |
| נראה                                             | ιδωμεν           |
| אם                                               | ει               |
| פרחה                                             | ηνθησεν          |
| הגפן                                             | η αμπελος        |
| פתח                                              | ηνθησεν          |
| הסמדר                                            | ο κυπρισμος      |
| הנצו                                             | ηνθησαν          |
| הרמונים                                          | αι ροαι          |
| שם                                               | εκει             |
| אתן                                              | δωσω             |
| את דדי •^[Difference in vocalization (reading).] | τους μαστους μου |
| לך                                               | σοι              |
: Song of Songs chapter 7, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| הדודאים          | οι μανδραγοραι |
| נתנו             | εδωκαν         |
| ריח              | οσμην          |
| ועל              | και επι        |
| פתחינו           | θυραις ημων    |
| כל               | παντα          |
| מגדים            | ακροδρυα       |
| חדשים            | νεα            |
| גם               | προς           |
| ישנים            | παλαια         |
| דודי             | αδελφιδε μου   |
| צפנתי            | ετηρησα        |
| לך               | σοι            |
: Song of Songs chapter 7, verse 14 { .hover tbl-colwidths="[50,50]"}

## Chapter 8

### Verse 1

| Masoretic text                                 | Septuagint     |
|:-----------------------------------------------|:---------------|
| מי                                             | τις            |
| יתנך                                           | δωη σε         |
| כאח •^[Difference in preposition or particle.] | αδελφιδον      |
| לי                                             | μου            |
| יונק                                           | θηλαζοντα      |
| שדי                                            | μαστους        |
| אמי                                            | μητρος μου     |
| אמצאך                                          | ευρουσα σε     |
| בחוץ                                           | εξω            |
| אשקך                                           | φιλησω σε      |
| גם                                             | και γε         |
| לא                                             | ουκ            |
| יבוזו                                          | εξουδενωσουσιν |
| לי                                             | μοι            |
: Song of Songs chapter 8, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                                                                  | Septuagint                                                                                 |
|:------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------|
| אנהגך                                                                                           | παραλημψομαι σε                                                                            |
| אביאך                                                                                           | εισαξω σε                                                                                  |
| אל                                                                                              | εις                                                                                        |
| בית                                                                                             | οικον                                                                                      |
| אמי                                                                                             | μητρος μου                                                                                 |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;{x}ואל חדר <3.4>]{.potential-difference} | [και εις ταμιειον]{.potential-difference}                                                  |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;{x}הורתי <3.4>]{.potential-difference}   | [της συλλαβουσης με]{.potential-difference}                                                |
| [תלמדני]{.potential-difference}                                                                 | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).] {x}]{.potential-difference} |
| אשקך                                                                                            | ποτιω σε                                                                                   |
| מיין •^[Difference in vocalization (reading).]                                                  | απο οινου                                                                                  |
| הרקח                                                                                            | του μυρεψικου                                                                              |
| מעסיס                                                                                           | απο ναματος                                                                                |
| רמני •^[Difference in vocalization (reading).]                                                  | ροων μου                                                                                   |
: Song of Songs chapter 8, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| שמאלו            | ευωνυμος αυτου    |
| תחת              | υπο               |
| ראשי             | την κεφαλην μου   |
| וימינו           | και η δεξια αυτου |
| תחבקני           | περιλημψεται με   |
: Song of Songs chapter 8, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text                                                                                                                                                       | Septuagint                                                                              |
|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------|
| השבעתי                                                                                                                                                               | ωρκισα                                                                                  |
| אתכם                                                                                                                                                                 | υμας                                                                                    |
| בנות                                                                                                                                                                 | θυγατερες                                                                               |
| ירושלם                                                                                                                                                               | ιερουσαλημ                                                                              |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;בצבאות •^[Etymological exegesis.] <2.7>]{.potential-difference} | [εν ταις δυναμεσιν]{.potential-difference}                                              |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;או <2.7>]{.potential-difference}                                | [και]{.potential-difference}                                                            |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;באילות •^[Etymological exegesis.] <2.7>]{.potential-difference} | [εν ταις ισχυσεσιν]{.potential-difference}                                              |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Long minus or plus (at least four lines).] =;השדה <2.7>]{.potential-difference}                              | [του αγρου]{.potential-difference}                                                      |
| מה                                                                                                                                                                   | τι                                                                                      |
| תעירו                                                                                                                                                                | εγειρητε                                                                                |
| ומה                                                                                                                                                                  | και τι                                                                                  |
| תעררו                                                                                                                                                                | εξεγειρητε                                                                              |
| את האהבה                                                                                                                                                             | την αγαπην                                                                              |
| עד •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ש                                                                                | εως αν                                                                                  |
| שתחפץ                                                                                                                                                                | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] θεληση |
: Song of Songs chapter 8, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                                          | Septuagint                                                                             |
|:----------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| מי                                                                                      | τις                                                                                    |
| זאת                                                                                     | αυτη                                                                                   |
| עלה                                                                                     | η αναβαινουσα                                                                          |
| [מן]{.potential-difference}                                                             | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| המדבר •^[Etymological exegesis.] •^[Questionable notation, equivalent, etc.] ברר,מבהירה | λελευκανθισμενη                                                                        |
| מתרפקת                                                                                  | επιστηριζομενη                                                                         |
| על                                                                                      | επι                                                                                    |
| דודה                                                                                    | τον αδελφιδον αυτης                                                                    |
| תחת                                                                                     | υπο                                                                                    |
| התפוח                                                                                   | μηλον                                                                                  |
| עוררתיך                                                                                 | εξηγειρα σε                                                                            |
| שמה                                                                                     | εκει                                                                                   |
| חבלתך                                                                                   | ωδινησεν σε                                                                            |
| אמך                                                                                     | η μητηρ σου                                                                            |
| שמה                                                                                     | εκει                                                                                   |
| חבלה •^[Notation in Hebrew column of elements repeated in the translation.] ך           | ωδινησεν σε                                                                            |
| ילדתך •^[Difference in vocalization (reading).]                                         | η τεκουσα σου                                                                          |
: Song of Songs chapter 8, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text                   | Tov's retroversion                                                        | Septuagint                            |
|:---------------------------------|:--------------------------------------------------------------------------|:--------------------------------------|
| שימני                            |                                                                           | θες με                                |
| כחותם                            |                                                                           | ως σφραγιδα                           |
| על                               |                                                                           | επι                                   |
| לבך                              |                                                                           | την καρδιαν σου                       |
| כחותם                            |                                                                           | ως σφραγιδα                           |
| על                               |                                                                           | επι                                   |
| זרועך                            |                                                                           | τον βραχιονα σου                      |
| כי                               |                                                                           | οτι                                   |
| עזה                              |                                                                           | κραταια                               |
| כמות                             |                                                                           | ως θανατος                            |
| אהבה                             |                                                                           | αγαπη                                 |
| קשה                              |                                                                           | σκληρος                               |
| כשאול                            |                                                                           | ως αδης                               |
| קנאה                             |                                                                           | ζηλος                                 |
| רשפיה                            |                                                                           | περιπτερα αυτης                       |
| רשפי                             |                                                                           | περιπτερα                             |
| אש                               |                                                                           | πυρος                                 |
| [שלהבתיה]{.potential-difference} | [להבתיה •^[Difference in vocalization (reading).]]{.potential-difference} | [φλογες αυτης]{.potential-difference} |
: Song of Songs chapter 8, verse 6 { .hover tbl-colwidths="[35,30,35]"}

### Verse 7

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| מים              | υδωρ               |
| רבים             | πολυ               |
| לא               | ου                 |
| יוכלו            | δυνησεται          |
| לכבות            | σβεσαι             |
| את האהבה         | την αγαπην         |
| ונהרות           | και ποταμοι        |
| לא               | ου                 |
| ישטפוה           | συγκλυσουσιν αυτην |
| אם               | εαν                |
| יתן              | δω                 |
| איש              | ανηρ               |
| את כל            | τον παντα          |
| הון ביתו         | βιον αυτου         |
| באהבה            | εν τη αγαπη        |
| בוז {!}nd        | εξουδενωσει        |
| יבוזו {!}nd      | εξουδενωσουσιν     |
| לו               | αυτον              |
: Song of Songs chapter 8, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text   | Septuagint     |
|:-----------------|:---------------|
| אחות             | αδελφη         |
| לנו              | ημιν           |
| קטנה             | μικρα          |
| ושדים            | και μαστους    |
| אין לה           | ουκ εχει       |
| מה               | τι             |
| נעשה             | ποιησωμεν      |
| לאחתנו           | τη αδελφη ημων |
| ביום             | εν ημερα       |
| שידבר            | η εαν λαληθη   |
| בה               | εν αυτη        |
: Song of Songs chapter 8, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                 | Septuagint    |
|:-----------------------------------------------|:--------------|
| אם                                             | ει            |
| חומה                                           | τειχος        |
| היא                                            | εστιν         |
| נבנה                                           | οικοδομησωμεν |
| עליה                                           | επ' αυτην     |
| טירת •^[Difference in vocalization (reading).] | επαλξεις      |
| כסף                                            | αργυρας       |
| ואם                                            | και ει        |
| דלת                                            | θυρα          |
| היא                                            | εστιν         |
| נצור                                           | διαγραψωμεν   |
| עליה                                           | επ' αυτην     |
| לוח                                            | σανιδα        |
| ארז                                            | κεδρινην      |
: Song of Songs chapter 8, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text              | Septuagint                                                                             |
|:----------------------------|:---------------------------------------------------------------------------------------|
| אני                         | εγω                                                                                    |
| חומה                        | τειχος                                                                                 |
| ושדי                        | και μαστοι μου                                                                         |
| כמגדלות                     | ως πυργοι                                                                              |
| [אז]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| הייתי                       | εγω ημην                                                                               |
| בעיניו                      | εν οφθαλμοις αυτου                                                                     |
| כמוצאת                      | ως ευρισκουσα                                                                          |
| שלום                        | ειρηνην                                                                                |
: Song of Songs chapter 8, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                                                                    | Septuagint         |
|:----------------------------------------------------------------------------------|:-------------------|
| כרם                                                                               | αμπελων            |
| היה                                                                               | εγενηθη            |
| לשלמה                                                                             | τω σαλωμων         |
| בבעל המון •^[Two words of MT joined into one word in the parent text of the LXX.] | εν βεελαμων        |
| נתן                                                                               | εδωκεν             |
| את הכרם                                                                           | τον αμπελωνα αυτου |
| לנטרים                                                                            | τοις τηρουσιν      |
| איש                                                                               | ανηρ               |
| יבא                                                                               | οισει              |
| בפריו                                                                             | εν καρπω αυτου     |
| אלף                                                                               | χιλιους            |
| כסף                                                                               | αργυριου           |
: Song of Songs chapter 8, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| כרמי             | αμπελων μου      |
| שלי              | εμος             |
| לפני             | ενωπιον μου      |
| האלף             | οι χιλιοι        |
| לך               | σοι              |
| שלמה             | σαλωμων          |
| ומאתים           | και οι διακοσιοι |
| לנטרים           | τοις τηρουσι     |
| את פריו          | τον καρπον αυτου |
: Song of Songs chapter 8, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                  | Tov's retroversion             | Septuagint                           |
|:--------------------------------|:-------------------------------|:-------------------------------------|
| [היושבת]{.potential-difference} | [היושב]{.potential-difference} | [ο καθημενος]{.potential-difference} |
| בגנים                           |                                | εν κηποις                            |
| חברים                           |                                | εταιροι                              |
| מקשיבים                         |                                | προσεχοντες                          |
| לקולך                           |                                | τη φωνη σου                          |
| השמיעיני                        |                                | ακουτισον με                         |
: Song of Songs chapter 8, verse 13 { .hover tbl-colwidths="[35,30,35]"}

### Verse 14

| Masoretic text              | Septuagint                                                                             |
|:----------------------------|:---------------------------------------------------------------------------------------|
| ברח                         | φυγε                                                                                   |
| דודי                        | αδελφιδε μου                                                                           |
| ודמה                        | και ομοιωθητι                                                                          |
| [לך]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| לצבי                        | τη δορκαδι                                                                             |
| או                          | η                                                                                      |
| לעפר                        | τω νεβρω                                                                               |
| האילים                      | των ελαφων                                                                             |
| על                          | επι                                                                                    |
| הרי                         | ορη                                                                                    |
| בשמים                       | αρωματων                                                                               |
: Song of Songs chapter 8, verse 14 { .hover tbl-colwidths="[50,50]"}

