# Zephaniah

The tables below show the Hebrew and Greek texts aligned vertically. When a Hebrew verse number does not match the Greek counterpart, the editors added a note with the corresponding verse number between square brackets.

## Chapter 1

### Verse 1

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| דבר              | λογος        |
| יהוה             | κυριου       |
| אשר              | ος           |
| היה              | εγενηθη      |
| אל               | προς         |
| צפניה            | σοφονιαν     |
| בן               | τον του      |
| כושי             | χουσι        |
| בן               | υιον         |
| גדליה            | γοδολιου     |
| בן               | του          |
| אמריה            | αμαριου      |
| בן               | του          |
| חזקיה            | εζεκιου      |
| בימי             | εν ημεραις   |
| יאשיהו           | ιωσιου       |
| בן               | υιου         |
| אמון             | αμων         |
| מלך              | βασιλεως     |
| יהודה            | ιουδα        |
: Zephaniah chapter 1, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| אסף {!}nd        | εκλειψει     |
| אסף {!}nd        | εκλιπετω     |
| כל               | παντα        |
| מעל פני          | απο προσωπου |
| האדמה            | της γης      |
| נאם              | λεγει        |
| יהוה             | κυριος       |
: Zephaniah chapter 1, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                     | Septuagint                                                                             |
|:-----------------------------------|:---------------------------------------------------------------------------------------|
| אסף                                | εκλιπετω                                                                               |
| אדם                                | ανθρωπος                                                                               |
| ובהמה                              | και κτηνη                                                                              |
| אסף                                | εκλιπετω                                                                               |
| עוף                                | τα πετεινα                                                                             |
| השמים                              | του ουρανου                                                                            |
| ודגי                               | και οι ιχθυες                                                                          |
| הים                                | της θαλασσης                                                                           |
| [והמכשלות]{.potential-difference}  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [את הרשעים]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| והכרתי                             | και εξαρω                                                                              |
| את האדם                            | τους ανθρωπους                                                                         |
| מעל פני                            | απο προσωπου                                                                           |
| האדמה                              | της γης                                                                                |
| נאם                                | λεγει                                                                                  |
| יהוה                               | κυριος                                                                                 |
: Zephaniah chapter 1, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text              | Septuagint                                                                             |
|:----------------------------|:---------------------------------------------------------------------------------------|
| ונטיתי                      | και εκτενω                                                                             |
| ידי                         | την χειρα μου                                                                          |
| על                          | επι                                                                                    |
| יהודה                       | ιουδαν                                                                                 |
| ועל                         | και επι                                                                                |
| כל                          | παντας                                                                                 |
| יושבי                       | τους κατοικουντας                                                                      |
| ירושלם                      | ιερουσαλημ                                                                             |
| והכרתי                      | και εξαρω                                                                              |
| מן                          | εκ                                                                                     |
| המקום                       | του τοπου                                                                              |
| הזה                         | τουτου                                                                                 |
| את שאר =;את שם              | τα ονοματα                                                                             |
| הבעל                        | της βααλ                                                                               |
| את שם                       | και τα ονοματα                                                                         |
| הכמרים                      | {... •^[Questionable notation, equivalent, etc.] των ιερεων}                           |
| [עם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| הכהנים                      | των ιερεων                                                                             |
: Zephaniah chapter 1, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                        | Septuagint                                                                                 |
|:--------------------------------------|:-------------------------------------------------------------------------------------------|
| ואת המשתחוים                          | και τους προσκυνουντας                                                                     |
| על                                    | επι                                                                                        |
| הגגות                                 | τα δωματα                                                                                  |
| לצבא                                  | τη στρατια                                                                                 |
| השמים                                 | του ουρανου                                                                                |
| [ואת המשתחוים]{.potential-difference} | [και •^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| הנשבעים                               | τους ομνυοντας                                                                             |
| ליהוה                                 | κατα του κυριου                                                                            |
| והנשבעים                              | και τους ομνυοντας                                                                         |
| במלכם                                 | κατα του βασιλεως αυτων                                                                    |
: Zephaniah chapter 1, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text   | Septuagint              |
|:-----------------|:------------------------|
| ואת הנסוגים      | και τους εκκλινοντας    |
| מאחרי            | απο                     |
| יהוה             | του κυριου              |
| ואשר             | και τους                |
| לא               | μη                      |
| בקשו             | ζητησαντας              |
| את יהוה          | τον κυριον              |
| ולא              | και τους μη             |
| דרשהו            | αντεχομενους του κυριου |
: Zephaniah chapter 1, verse 6 { .hover tbl-colwidths="[50,50]"}

### Verse 7

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| הס               | ευλαβεισθε         |
| מפני             | απο προσωπου       |
| אדני             | κυριου             |
| יהוה             | του θεου           |
| כי               | διοτι              |
| קרוב             | εγγυς              |
| יום              | η ημερα            |
| יהוה             | του κυριου         |
| כי               | οτι                |
| הכין             | ητοιμακεν          |
| יהוה             | κυριος             |
| זבח              | την θυσιαν αυτου   |
| הקדיש            | ηγιακεν            |
| קראיו            | τους κλητους αυτου |
: Zephaniah chapter 1, verse 7 { .hover tbl-colwidths="[50,50]"}

### Verse 8

| Masoretic text               | Tov's retroversion           | Septuagint                         |
|:-----------------------------|:-----------------------------|:-----------------------------------|
| והיה                         |                              | και εσται                          |
| ביום                         |                              | εν ημερα                           |
| זבח                          |                              | θυσιας                             |
| יהוה                         |                              | κυριου                             |
| ופקדתי                       |                              | και εκδικησω                       |
| על                           |                              | επι                                |
| השרים                        |                              | τους αρχοντας                      |
| ועל                          |                              | και επι                            |
| [בני]{.potential-difference} | [בית]{.potential-difference} | [τον οικον]{.potential-difference} |
| המלך                         |                              | του βασιλεως                       |
| ועל                          |                              | και επι                            |
| כל                           |                              | παντας                             |
| הלבשים                       |                              | τους ενδεδυμενους                  |
| מלבוש                        |                              | ενδυματα                           |
| נכרי                         |                              | αλλοτρια                           |
: Zephaniah chapter 1, verse 8 { .hover tbl-colwidths="[35,30,35]"}

### Verse 9

| Masoretic text                                                                   | Septuagint                      |
|:---------------------------------------------------------------------------------|:--------------------------------|
| ופקדתי                                                                           | και εκδικησω                    |
| על                                                                               | επι                             |
| כל                                                                               | παντας                          |
| הדולג                                                                            | εμφανως                         |
| על                                                                               | επι                             |
| המפתן                                                                            | τα προπυλα                      |
| ביום                                                                             | εν {...τη ημερα}                |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εκεινη                          |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | τη ημερα                        |
| ההוא                                                                             | {..εκεινη}                      |
| הממלאים                                                                          | τους πληρουντας                 |
| בית                                                                              | τον οικον                       |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     | [κυριου]{.potential-difference} |
| אדניהם                                                                           | του θεου αυτων                  |
| חמס                                                                              | ασεβειας                        |
| ומרמה                                                                            | και δολου                       |
: Zephaniah chapter 1, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text                                                                   | Septuagint       |
|:---------------------------------------------------------------------------------|:-----------------|
| והיה                                                                             | και εσται        |
| ביום                                                                             | εν {...τη ημερα} |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | εκεινη           |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | τη ημερα         |
| ההוא                                                                             | {..εκεινη}       |
| נאם                                                                              | λεγει            |
| יהוה                                                                             | κυριος           |
| קול                                                                              | φωνη             |
| צעקה                                                                             | κραυγης          |
| משער                                                                             | απο πυλης        |
| הדגים                                                                            | αποκεντουντων    |
| ויללה                                                                            | και ολολυγμος    |
| מן                                                                               | απο              |
| המשנה                                                                            | της δευτερας     |
| ושבר                                                                             | και συντριμμος   |
| גדול                                                                             | μεγας            |
| מהגבעות                                                                          | απο των βουνων   |
: Zephaniah chapter 1, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| הילילו           | θρηνησατε          |
| ישבי             | οι κατοικουντες    |
| המכתש            | την κατακεκομμενην |
| כי               | οτι                |
| נדמה             | ωμοιωθη            |
| כל               | πας                |
| עם               | ο λαος             |
| כנען             | χανααν             |
| נכרתו            | εξωλεθρευθησαν     |
| כל               | παντες             |
| נטילי            | οι επηρμενοι       |
| כסף              | αργυριω            |
: Zephaniah chapter 1, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text                                                                   | Tov's retroversion            | Septuagint                                |
|:---------------------------------------------------------------------------------|:------------------------------|:------------------------------------------|
| והיה                                                                             |                               | και εσται                                 |
| [בעת]{.potential-difference}                                                     | [ביום]{.potential-difference} | [εν {...τη ημερα}]{.potential-difference} |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                               | εκεινη                                    |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                               | τη ημερα                                  |
| ההיא                                                                             |                               | {..εκεινη                                 |
| אחפש                                                                             |                               | εξερευνησω                                |
| את ירושלם                                                                        |                               | την ιερουσαλημ                            |
| בנרות                                                                            |                               | μετα λυχνου                               |
| ופקדתי                                                                           |                               | και εκδικησω                              |
| על                                                                               |                               | επι                                       |
| האנשים                                                                           |                               | τους ανδρας                               |
| הקפאים                                                                           |                               | τους καταφρονουντας                       |
| על                                                                               |                               | επι                                       |
| שמריהם                                                                           |                               | τα φυλαγματα αυτων                        |
| האמרים                                                                           |                               | οι λεγοντες                               |
| בלבבם                                                                            |                               | εν ταις καρδιαις αυτων                    |
| לא                                                                               |                               | ου μη                                     |
| ייטיב                                                                            |                               | αγαθοποιηση                               |
| יהוה                                                                             |                               | κυριος                                    |
| ולא                                                                              |                               | ουδ' ου μη                                |
| ירע                                                                              |                               | κακωση                                    |
: Zephaniah chapter 1, verse 12 { .hover tbl-colwidths="[35,30,35]"}

### Verse 13

| Masoretic text                                                               | Septuagint                         |
|:-----------------------------------------------------------------------------|:-----------------------------------|
| והיה                                                                         | και εσται                          |
| חילם                                                                         | η δυναμις αυτων                    |
| למשסה                                                                        | εις διαρπαγην                      |
| ובתיהם                                                                       | και οι οικοι αυτων                 |
| לשממה                                                                        | εις αφανισμον                      |
| ובנו                                                                         | και οικοδομησουσιν                 |
| בתים                                                                         | οικιας                             |
| ולא                                                                          | και ου μη                          |
| ישבו                                                                         | κατοικησουσιν                      |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [εν αυταις]{.potential-difference} |
| ונטעו                                                                        | και καταφυτευσουσιν                |
| כרמים                                                                        | αμπελωνας                          |
| ולא                                                                          | και ου μη                          |
| ישתו                                                                         | πιωσιν                             |
| את יינם                                                                      | τον οινον αυτων                    |
: Zephaniah chapter 1, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                               | Tov's retroversion              | Septuagint                        |
|:-----------------------------------------------------------------------------|:--------------------------------|:----------------------------------|
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} |                                 | [οτι]{.potential-difference}      |
| קרוב                                                                         |                                 | εγγυς                             |
| יום                                                                          |                                 | η ημερα                           |
| יהוה                                                                         |                                 | κυριου                            |
| הגדול                                                                        |                                 | η μεγαλη                          |
| קרוב                                                                         |                                 | εγγυς                             |
| ומהר                                                                         |                                 | και ταχεια                        |
| מאד                                                                          |                                 | σφοδρα                            |
| קול                                                                          |                                 | φωνη                              |
| יום                                                                          |                                 | ημερας                            |
| יהוה                                                                         |                                 | κυριου                            |
| מר                                                                           |                                 | πικρα                             |
| צרח                                                                          |                                 | και σκληρα                        |
| [שם]{.potential-difference}                                                  | [שם =vs]{.potential-difference} | [τετακται]{.potential-difference} |
| גבור                                                                         |                                 | δυνατη                            |
: Zephaniah chapter 1, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text   | Septuagint    |
|:-----------------|:--------------|
| יום              | ημερα         |
| עברה             | οργης         |
| היום             | η ημερα       |
| ההוא             | εκεινη        |
| יום              | ημερα         |
| צרה              | θλιψεως       |
| ומצוקה           | και αναγκης   |
| יום              | ημερα         |
| שאה              | αωριας        |
| ומשואה           | και αφανισμου |
| יום              | ημερα         |
| חשך              | σκοτους       |
| ואפלה            | και γνοφου    |
| יום              | ημερα         |
| ענן              | νεφελης       |
| וערפל            | και ομιχλης   |
: Zephaniah chapter 1, verse 15 { .hover tbl-colwidths="[50,50]"}

### Verse 16

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| יום              | ημερα        |
| שופר             | σαλπιγγος    |
| ותרועה           | και κραυγης  |
| על               | επι          |
| הערים            | τας πολεις   |
| הבצרות           | τας οχυρας   |
| ועל              | και επι      |
| הפנות            | τας γωνιας   |
| הגבהות           | τας υψηλας   |
: Zephaniah chapter 1, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text                                        | Septuagint           |
|:------------------------------------------------------|:---------------------|
| והצרתי                                                | και εκθλιψω          |
| לאדם                                                  | τους ανθρωπους       |
| והלכו                                                 | και πορευσονται      |
| כעורים                                                | ως τυφλοι            |
| כי                                                    | οτι                  |
| ליהוה                                                 | τω κυριω             |
| חטאו                                                  | εξημαρτον            |
| ושפך •^[Change from passive to active form in verbs.] | και εκχεει           |
| דמם                                                   | το αιμα αυτων        |
| כעפר                                                  | ως χουν              |
| ולחמם                                                 | και τας σαρκας αυτων |
| כגללים                                                | ως βολβιτα           |
: Zephaniah chapter 1, verse 17 { .hover tbl-colwidths="[50,50]"}

### Verse 18

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| גם               | και               |
| כספם             | το αργυριον αυτων |
| גם               | και               |
| זהבם             | το χρυσιον αυτων  |
| לא               | ου μη             |
| יוכל             | δυνηται           |
| להצילם           | εξελεσθαι αυτους  |
| ביום             | εν ημερα          |
| עברת             | οργης             |
| יהוה             | κυριου            |
| ובאש             | και εν πυρι       |
| קנאתו            | ζηλους αυτου      |
| תאכל             | καταναλωθησεται   |
| כל               | πασα              |
| הארץ             | η γη              |
| כי               | διοτι             |
| כלה              | συντελειαν        |
| אך               | και               |
| נבהלה            | σπουδην           |
| יעשה             | ποιησει           |
| את               | επι               |
| כל               | παντας            |
| ישבי             | τους κατοικουντας |
| הארץ             | την γην           |
: Zephaniah chapter 1, verse 18 { .hover tbl-colwidths="[50,50]"}

## Chapter 2

### Verse 1

| Masoretic text                       | Septuagint    |
|:-------------------------------------|:--------------|
| התקוששו                              | συναχθητε     |
| וקושו •^[Etymological exegesis.] קשר | και συνδεθητε |
| הגוי                                 | το εθνος      |
| לא נכסף                              | το απαιδευτον |
: Zephaniah chapter 2, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                                               | Septuagint                                                                             |
|:-----------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| בטרם                                                                         | προ                                                                                    |
| לדת                                                                          | του γενεσθαι                                                                           |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [υμας]{.potential-difference}                                                          |
| [חק]{.potential-difference}                                                  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| כמץ                                                                          | ως ανθος                                                                               |
| עבר                                                                          | παραπορευομενον                                                                        |
| [יום]{.potential-difference}                                                 | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| בטרם לא                                                                      | προ                                                                                    |
| יבוא                                                                         | του επελθειν                                                                           |
| עליכם                                                                        | εφ' υμας                                                                               |
| חרון אף                                                                      | οργην                                                                                  |
| יהוה                                                                         | κυριου                                                                                 |
| בטרם לא                                                                      | προ                                                                                    |
| יבוא                                                                         | του επελθειν                                                                           |
| עליכם                                                                        | εφ' υμας                                                                               |
| יום                                                                          | ημεραν                                                                                 |
| אף                                                                           | θυμου                                                                                  |
| יהוה                                                                         | κυριου                                                                                 |
: Zephaniah chapter 2, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                                                                   | Tov's retroversion            | Septuagint                                                                             |
|:---------------------------------------------------------------------------------|:------------------------------|:---------------------------------------------------------------------------------------|
| בקשו                                                                             |                               | ζητησατε                                                                               |
| את יהוה                                                                          |                               | τον κυριον                                                                             |
| כל                                                                               |                               | παντες                                                                                 |
| ענוי                                                                             |                               | ταπεινοι                                                                               |
| הארץ                                                                             |                               | γης                                                                                    |
| [אשר]{.potential-difference}                                                     |                               | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| משפטו                                                                            |                               | κριμα                                                                                  |
| פעלו                                                                             |                               | εργαζεσθε                                                                              |
| בקשו                                                                             |                               | και {..ζητησατε}                                                                       |
| צדק                                                                              |                               | δικαιοσυνην                                                                            |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                               | ζητησατε                                                                               |
| [בקשו ענוה]{.potential-difference}                                               | [ענוה]{.potential-difference} | [και αποκρινεσθε αυτα]{.potential-difference}                                          |
| אולי                                                                             |                               | οπως                                                                                   |
| תסתרו                                                                            |                               | σκεπασθητε                                                                             |
| ביום                                                                             |                               | εν ημερα                                                                               |
| אף                                                                               |                               | οργης                                                                                  |
| יהוה                                                                             |                               | κυριου                                                                                 |
: Zephaniah chapter 2, verse 3 { .hover tbl-colwidths="[35,30,35]"}

### Verse 4

| Masoretic text                                                              | Tov's retroversion           | Septuagint                          |
|:----------------------------------------------------------------------------|:-----------------------------|:------------------------------------|
| כי                                                                          |                              | διοτι                               |
| עזה                                                                         |                              | γαζα                                |
| עזובה                                                                       |                              | διηρπασμενη                         |
| תהיה                                                                        |                              | εσται                               |
| ואשקלון                                                                     |                              | και ασκαλων                         |
| •^[Notation in Hebrew column of elements repeated in the translation.] תהיה |                              | εσται                               |
| לשממה                                                                       |                              | εις αφανισμον                       |
| [אשדוד]{.potential-difference}                                              | [.dt]{.potential-difference} | [και αζωτος]{.potential-difference} |
| בצהרים                                                                      |                              | μεσημβριας                          |
| יגרשוה                                                                      |                              | εκριφησεται                         |
| ועקרון                                                                      |                              | και ακκαρων                         |
| תעקר                                                                        |                              | εκριζωθησεται                       |
: Zephaniah chapter 2, verse 4 { .hover tbl-colwidths="[35,30,35]"}

### Verse 5

| Masoretic text                 | Septuagint      |
|:-------------------------------|:----------------|
| הוי                            | ουαι            |
| ישבי                           | οι κατοικουντες |
| חבל •^[Etymological exegesis.] | το σχοινισμα    |
| הים                            | της θαλασσης    |
| גוי                            | παροικοι        |
| כרתים                          | κρητων          |
| דבר                            | λογος           |
| יהוה                           | κυριου          |
| עליכם                          | εφ' υμας        |
| כנען                           | χανααν          |
| ארץ                            | γη              |
| פלשתים                         | αλλοφυλων       |
| והאבדתיך                       | και απολω υμας  |
| מאין                           | εκ              |
| יושב                           | κατοικιας       |
: Zephaniah chapter 2, verse 5 { .hover tbl-colwidths="[50,50]"}

### Verse 6

| Masoretic text               | Tov's retroversion           | Septuagint                                                                             |
|:-----------------------------|:-----------------------------|:---------------------------------------------------------------------------------------|
| והיתה                        |                              | και εσται                                                                              |
| [חבל]{.potential-difference} |                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [הים]{.potential-difference} |                              | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [נות]{.potential-difference} | [כרת]{.potential-difference} | [κρητη]{.potential-difference}                                                         |
| [כרת]{.potential-difference} | [נות]{.potential-difference} | [νομη]{.potential-difference}                                                          |
| רעים                         |                              | ποιμνιων                                                                               |
| וגדרות                       |                              | και μανδρα                                                                             |
| צאן                          |                              | προβατων                                                                               |
: Zephaniah chapter 2, verse 6 { .hover tbl-colwidths="[35,30,35]"}

### Verse 7

| Masoretic text                                                                                                                | Tov's retroversion            | Septuagint                            |
|:------------------------------------------------------------------------------------------------------------------------------|:------------------------------|:--------------------------------------|
| והיה                                                                                                                          |                               | και εσται                             |
| חבל •^[Etymological exegesis.]                                                                                                |                               | το σχοινισμα                          |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                  |                               | [της θαλασσης]{.potential-difference} |
| לשארית                                                                                                                        |                               | τοις καταλοιποις                      |
| בית                                                                                                                           |                               | οικου                                 |
| יהודה                                                                                                                         |                               | ιουδα                                 |
| עליהם                                                                                                                         |                               | επ' αυτους                            |
| ירעון                                                                                                                         |                               | νεμησονται                            |
| בבתי                                                                                                                          |                               | εν τοις οικοις                        |
| אשקלון                                                                                                                        |                               | ασκαλωνος                             |
| בערב                                                                                                                          |                               | δειλης                                |
| ירבצון                                                                                                                        |                               | καταλυσουσιν                          |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                  | [מפני]{.potential-difference} | [απο προσωπου]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                  | [בני]{.potential-difference}  | [υιων]{.potential-difference}         |
| [•^[Element 'added' in the Greek (plus in the LXX).] •^[Introducing reconstructed proper noun.] יהודה]{.potential-difference} |                               | [ιουδα]{.potential-difference}        |
| כי                                                                                                                            |                               | οτι                                   |
| יפקדם                                                                                                                         |                               | επεσκεπται αυτους                     |
| יהוה                                                                                                                          |                               | κυριος                                |
| אלהיהם                                                                                                                        |                               | ο θεος αυτων                          |
| ושב                                                                                                                           |                               | και απεστρεψε                         |
| *שבותם **שביתם                                                                                                                |                               | την αιχμαλωσιαν αυτων                 |
: Zephaniah chapter 2, verse 7 { .hover tbl-colwidths="[35,30,35]"}

### Verse 8

| Masoretic text   | Septuagint       |
|:-----------------|:-----------------|
| שמעתי            | ηκουσα           |
| חרפת             | ονειδισμους      |
| מואב             | μωαβ             |
| וגדופי           | και κονδυλισμους |
| בני              | υιων             |
| עמון             | αμμων            |
| אשר              | εν οις           |
| חרפו             | ωνειδιζον        |
| את עמי           | τον λαον μου     |
| ויגדילו          | και εμεγαλυνοντο |
| על               | επι              |
| גבולם            | τα ορια μου      |
: Zephaniah chapter 2, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                              | Septuagint             |
|:--------------------------------------------|:-----------------------|
| לכן                                         | δια τουτο              |
| חי                                          | ζω                     |
| אני                                         | εγω                    |
| נאם                                         | λεγει                  |
| יהוה                                        | κυριος                 |
| צבאות                                       | των δυναμεων           |
| אלהי                                        | ο θεος                 |
| ישראל                                       | ισραηλ                 |
| כי                                          | διοτι                  |
| מואב                                        | μωαβ                   |
| כסדם                                        | ως σοδομα              |
| תהיה                                        | εσται                  |
| ובני                                        | και οι υιοι            |
| עמון                                        | αμμων                  |
| כעמרה                                       | ως γομορρα             |
| ממשק                                        | και δαμασκος           |
| חרול                                        | εκλελειμμενη           |
| ומכרה                                       | ως θιμωνια             |
| מלח                                         | αλωνος                 |
| ושממה                                       | και ηφανισμενη         |
| עד                                          | εις                    |
| עולם                                        | τον αιωνα              |
| שארית                                       | και οι καταλοιποι      |
| עמי                                         | λαου μου               |
| יבזום                                       | διαρπωνται αυτους      |
| ויתר                                        | και οι καταλοιποι      |
| *גוי **גויי •^[Agreement of LXX with qere.] | εθνους μου             |
| ינחלום                                      | κληρονομησουσιν αυτους |
: Zephaniah chapter 2, verse 9 { .hover tbl-colwidths="[50,50]"}

### Verse 10

| Masoretic text              | Septuagint                                                                             |
|:----------------------------|:---------------------------------------------------------------------------------------|
| זאת                         | αυτη                                                                                   |
| להם                         | αυτοις                                                                                 |
| תחת                         | αντι                                                                                   |
| גאונם                       | της υβρεως αυτων                                                                       |
| כי                          | διοτι                                                                                  |
| חרפו                        | ωνειδισαν                                                                              |
| ויגדלו                      | και εμεγαλυνθησαν                                                                      |
| על                          | επι                                                                                    |
| [עם]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| יהוה                        | τον κυριον                                                                             |
| צבאות                       | τον παντοκρατορα                                                                       |
: Zephaniah chapter 2, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                                                               | Septuagint                         |
|:-----------------------------------------------------------------------------|:-----------------------------------|
| נורא •^[Etymological exegesis.] נראה                                         | επιφανησεται                       |
| יהוה                                                                         | κυριος                             |
| עליהם                                                                        | επ' αυτους                         |
| כי                                                                           | και                                |
| רזה                                                                          | εξολεθρευσει                       |
| את כל                                                                        | παντας                             |
| אלהי                                                                         | τους θεους                         |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [των εθνων]{.potential-difference} |
| הארץ                                                                         | της γης                            |
| וישתחוו                                                                      | και προσκυνησουσιν                 |
| לו                                                                           | αυτω                               |
| איש                                                                          | εκαστος                            |
| ממקומו                                                                       | εκ του τοπου αυτου                 |
| כל                                                                           | πασαι                              |
| איי                                                                          | αι νησοι                           |
| הגוים                                                                        | των εθνων                          |
: Zephaniah chapter 2, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text   | Septuagint   |
|:-----------------|:-------------|
| גם               | και          |
| אתם              | υμεις        |
| כושים            | αιθιοπες     |
| חללי             | τραυματιαι   |
| חרבי             | ρομφαιας μου |
| המה              | εστε         |
: Zephaniah chapter 2, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text   | Septuagint      |
|:-----------------|:----------------|
| ויט              | και εκτενει     |
| ידו              | την χειρα αυτου |
| על               | επι             |
| צפון             | βορραν          |
| ויאבד            | και απολει      |
| את אשור          | τον ασσυριον    |
| וישם             | και θησει       |
| את נינוה         | την νινευη      |
| לשממה            | εις αφανισμον   |
| ציה              | ανυδρον         |
| כמדבר            | ως ερημον       |
: Zephaniah chapter 2, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                               | Tov's retroversion                                                                                               | Septuagint                                 |
|:-----------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------|:-------------------------------------------|
| ורבצו                                                                        |                                                                                                                  | και νεμησονται                             |
| בתוכה                                                                        |                                                                                                                  | εν μεσω αυτης                              |
| עדרים                                                                        |                                                                                                                  | ποιμνια                                    |
| כל                                                                           |                                                                                                                  | και παντα                                  |
| חיתו                                                                         |                                                                                                                  | τα θηρια                                   |
| גוי                                                                          |                                                                                                                  | της γης                                    |
| גם                                                                           |                                                                                                                  | και                                        |
| קאת                                                                          |                                                                                                                  | χαμαιλεοντες                               |
| גם                                                                           |                                                                                                                  | και                                        |
| קפד                                                                          |                                                                                                                  | εχινοι                                     |
| בכפתריה                                                                      |                                                                                                                  | εν τοις φατνωμασιν αυτης                   |
| ילינו                                                                        |                                                                                                                  | κοιτασθησονται                             |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [וחיה]{.potential-difference}                                                                                    | [και θηρια]{.potential-difference}         |
| קול ישורר                                                                    |                                                                                                                  | φωνησει                                    |
| בחלון                                                                        |                                                                                                                  | εν τοις διορυγμασιν αυτης                  |
| [חרב]{.potential-difference}                                                 | [ערב .xע]{.potential-difference}                                                                                 | [κορακες]{.potential-difference}           |
| בסף                                                                          |                                                                                                                  | εν τοις πυλωσιν αυτης                      |
| כי                                                                           |                                                                                                                  | διοτι                                      |
| ארזה                                                                         |                                                                                                                  | κεδρος                                     |
| [ערה]{.potential-difference}                                                 | [•^[Questionable notation, equivalent, etc.] •^[Questionable notation, equivalent, etc.]]{.potential-difference} | [το αναστημα αυτης]{.potential-difference} |
: Zephaniah chapter 2, verse 14 { .hover tbl-colwidths="[35,30,35]"}

### Verse 15

| Masoretic text   | Septuagint             |
|:-----------------|:-----------------------|
| זאת              | αυτη                   |
| העיר             | η πολις                |
| העליזה           | η φαυλιστρια           |
| היושבת           | η κατοικουσα           |
| לבטח             | επ' ελπιδι             |
| האמרה            | η λεγουσα              |
| בלבבה            | εν καρδια αυτης        |
| אני              | εγω ειμι               |
| ואפסי            | και ουκ εστιν μετ' εμε |
| עוד              | ετι                    |
| איך              | πως                    |
| היתה             | εγενηθη                |
| לשמה             | εις αφανισμον          |
| מרבץ             | νομη                   |
| לחיה             | θηριων                 |
| כל               | πας                    |
| עובר             | ο διαπορευομενος       |
| עליה             | δι' αυτης              |
| ישרק             | συριει                 |
| יניע             | και κινησει            |
| ידו              | τας χειρας αυτου       |
: Zephaniah chapter 2, verse 15 { .hover tbl-colwidths="[50,50]"}

## Chapter 3

### Verse 1

| Masoretic text                      | Septuagint         |
|:------------------------------------|:-------------------|
| הוי                                 | ω                  |
| מראה •^[Etymological exegesis.] ראה | η επιφανης         |
| ונגאלה •^[Etymological exegesis.]   | και απολελυτρωμενη |
| העיר                                | η πολις            |
| היונה •^[Etymological exegesis.]    | η περιστερα        |
: Zephaniah chapter 3, verse 1 { .hover tbl-colwidths="[50,50]"}

### Verse 2

| Masoretic text                                                                          | Septuagint     |
|:----------------------------------------------------------------------------------------|:---------------|
| לא                                                                                      | ουκ            |
| שמעה •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ב | εισηκουσεν     |
| בקול                                                                                    | φωνης          |
| לא                                                                                      | ουκ            |
| לקחה                                                                                    | εδεξατο        |
| מוסר                                                                                    | παιδειαν       |
| ביהוה                                                                                   | επι τω κυριω   |
| לא                                                                                      | ουκ            |
| בטחה                                                                                    | επεποιθει      |
| אל                                                                                      | και προς       |
| אלהיה                                                                                   | τον θεον αυτης |
| לא                                                                                      | ουκ            |
| קרבה                                                                                    | ηγγισεν        |
: Zephaniah chapter 3, verse 2 { .hover tbl-colwidths="[50,50]"}

### Verse 3

| Masoretic text                                                                   | Septuagint                                                                                                              |
|:---------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------|
| שריה                                                                             | οι αρχοντες αυτης                                                                                                       |
| בקרבה                                                                            | εν αυτη                                                                                                                 |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | ως                                                                                                                      |
| אריות                                                                            | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] ως λεοντες |
| שאגים                                                                            | ωρυομενοι                                                                                                               |
| שפטיה                                                                            | οι κριται αυτης                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] | ως                                                                                                                      |
| זאבי                                                                             | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] ως λυκοι   |
| ערב •^[Etymological exegesis.]                                                   | της αραβιας                                                                                                             |
| לא                                                                               | ουχ                                                                                                                     |
| גרמו                                                                             | υπελιποντο                                                                                                              |
| לבקר                                                                             | εις το πρωι                                                                                                             |
: Zephaniah chapter 3, verse 3 { .hover tbl-colwidths="[50,50]"}

### Verse 4

| Masoretic text   | Septuagint        |
|:-----------------|:------------------|
| נביאיה           | οι προφηται αυτης |
| פחזים            | πνευματοφοροι     |
| אנשי             | ανδρες            |
| בגדות            | καταφρονηται      |
| כהניה            | οι ιερεις αυτης   |
| חללו             | βεβηλουσιν        |
| קדש              | τα αγια           |
| חמסו             | και ασεβουσιν     |
| תורה             | νομον             |
: Zephaniah chapter 3, verse 4 { .hover tbl-colwidths="[50,50]"}

### Verse 5

| Masoretic text                                                                                                                                           | Tov's retroversion                | Septuagint                                                                                                                                                                                                                                                                                                                                                                                      |
|:---------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| יהוה                                                                                                                                                     |                                   | ο δε κυριος                                                                                                                                                                                                                                                                                                                                                                                     |
| צדיק                                                                                                                                                     |                                   | δικαιος                                                                                                                                                                                                                                                                                                                                                                                         |
| בקרבה                                                                                                                                                    |                                   | εν μεσω αυτης                                                                                                                                                                                                                                                                                                                                                                                   |
| לא                                                                                                                                                       |                                   | και ου μη                                                                                                                                                                                                                                                                                                                                                                                       |
| יעשה                                                                                                                                                     |                                   | ποιηση                                                                                                                                                                                                                                                                                                                                                                                          |
| עולה                                                                                                                                                     |                                   | αδικον                                                                                                                                                                                                                                                                                                                                                                                          |
| בבקר                                                                                                                                                     |                                   | πρωι                                                                                                                                                                                                                                                                                                                                                                                            |
| בבקר                                                                                                                                                     |                                   | πρωι                                                                                                                                                                                                                                                                                                                                                                                            |
| [משפטו]{.potential-difference}                                                                                                                           | [יתן]{.potential-difference}      | [δωσει]{.potential-difference}                                                                                                                                                                                                                                                                                                                                                                  |
| [יתן]{.potential-difference}                                                                                                                             | [משפטו]{.potential-difference}    | [κριμα αυτου]{.potential-difference}                                                                                                                                                                                                                                                                                                                                                            |
| לאור                                                                                                                                                     |                                   | εις φως                                                                                                                                                                                                                                                                                                                                                                                         |
| לא                                                                                                                                                       |                                   | και ουκ                                                                                                                                                                                                                                                                                                                                                                                         |
| נעדר                                                                                                                                                     |                                   | απεκρυβη                                                                                                                                                                                                                                                                                                                                                                                        |
| ולא                                                                                                                                                      |                                   | και ουκ •^[Reference to doublet (occurring between the two elements of the doublet.] {...και ουκ}                                                                                                                                                                                                                                                                                               |
| יודע                                                                                                                                                     |                                   | εγνω                                                                                                                                                                                                                                                                                                                                                                                            |
| [עול]{.potential-difference}                                                                                                                             | [{d}לעולם]{.potential-difference} | [αδικιαν •^[Reference to doublet (occurring between the two elements of the doublet.] {..εις νεικος •^[Reference to doublet (occurring between the two elements of the doublet.] •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.]]{.potential-difference}                               |
| •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.] |                                   | αδικιαν}                                                                                                                                                                                                                                                                                                                                                                                        |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                   | εν                                                                                                                                                                                                                                                                                                                                                                                              |
| [בשת]{.potential-difference}                                                                                                                             | [{d}בשחת]{.potential-difference}  | [•^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] εν απαιτησει •^[Reference to doublet (occurring between the two elements of the doublet.] {...εν •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.]]{.potential-difference} |
| •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.] |                                   | διαφθορα}                                                                                                                                                                                                                                                                                                                                                                                       |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                   | και ουκ                                                                                                                                                                                                                                                                                                                                                                                         |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                   | εις νεικος                                                                                                                                                                                                                                                                                                                                                                                      |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.]                                                                         |                                   | αδικιαν                                                                                                                                                                                                                                                                                                                                                                                         |
: Zephaniah chapter 3, verse 5 { .hover tbl-colwidths="[35,30,35]"}

### Verse 6

| Masoretic text                                                                   | Tov's retroversion            | Septuagint                           |
|:---------------------------------------------------------------------------------|:------------------------------|:-------------------------------------|
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                               | εν διαφθορα [6]                      |
| הכרתי                                                                            |                               | κατεσπασα                            |
| [גוים]{.potential-difference}                                                    | [גאים]{.potential-difference} | [υπερηφανους]{.potential-difference} |
| נשמו                                                                             |                               | ηφανισθησαν                          |
| פנותם                                                                            |                               | γωνιαι αυτων                         |
| החרבתי                                                                           |                               | εξερημωσω                            |
| חוצותם                                                                           |                               | τας οδους αυτων                      |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     |                               | [το παραπαν]{.potential-difference}  |
| מבלי                                                                             |                               | του μη                               |
| עובר                                                                             |                               | διοδευειν                            |
| נצדו                                                                             |                               | εξελιπον                             |
| עריהם                                                                            |                               | αι πολεις αυτων                      |
| מבלי איש                                                                         |                               | παρα το μηδενα υπαρχειν              |
| מאין                                                                             |                               | μηδε                                 |
| יושב                                                                             |                               | κατοικειν                            |
: Zephaniah chapter 3, verse 6 { .hover tbl-colwidths="[35,30,35]"}

### Verse 7

| Masoretic text                     | Tov's retroversion                  | Septuagint                                 |
|:-----------------------------------|:------------------------------------|:-------------------------------------------|
| אמרתי                              |                                     | ειπα                                       |
| אך                                 |                                     | πλην                                       |
| תיראי                              |                                     | φοβεισθε                                   |
| אותי                               |                                     | με                                         |
| תקחי                               |                                     | και δεξασθε                                |
| מוסר                               |                                     | παιδειαν                                   |
| ולא                                |                                     | και ου μη                                  |
| יכרת                               |                                     | εξολεθρευθητε                              |
| [מעונה]{.potential-difference}     | [מעיניה .wy]{.potential-difference} | [εξ οφθαλμων αυτης]{.potential-difference} |
| כל                                 |                                     | παντα                                      |
| אשר                                |                                     | οσα                                        |
| פקדתי                              |                                     | εξεδικησα                                  |
| עליה                               |                                     | επ' αυτην                                  |
| [אכן]{.potential-difference}       | [הכן .אh]{.potential-difference}    | [ετοιμαζου]{.potential-difference}         |
| השכימו                             |                                     | ορθρισον                                   |
| השחיתו                             |                                     | διεφθαρται                                 |
| כל                                 |                                     | πασα                                       |
| עלילותם •^[Etymological exegesis.] |                                     | η επιφυλλις αυτων                          |
: Zephaniah chapter 3, verse 7 { .hover tbl-colwidths="[35,30,35]"}

### Verse 8

| Masoretic text                                | Septuagint                                                                             |
|:----------------------------------------------|:---------------------------------------------------------------------------------------|
| לכן                                           | δια τουτο                                                                              |
| חכו                                           | υπομεινον                                                                              |
| לי                                            | με                                                                                     |
| נאם                                           | λεγει                                                                                  |
| יהוה                                          | κυριος                                                                                 |
| ליום                                          | εις ημεραν                                                                             |
| קומי                                          | αναστασεως μου                                                                         |
| לעד •^[Difference in vocalization (reading).] | εις μαρτυριον                                                                          |
| כי                                            | διοτι                                                                                  |
| משפטי                                         | το κριμα μου                                                                           |
| לאסף                                          | εις συναγωγας                                                                          |
| גוים                                          | εθνων                                                                                  |
| לקבצי                                         | του εισδεξασθαι                                                                        |
| ממלכות                                        | βασιλεις                                                                               |
| לשפך                                          | του εκχεαι                                                                             |
| עליהם                                         | επ' αυτους                                                                             |
| [זעמי]{.potential-difference}                 | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| כל                                            | πασαν                                                                                  |
| חרון                                          | οργην                                                                                  |
| אפי                                           | θυμου μου                                                                              |
| כי                                            | διοτι                                                                                  |
| באש                                           | εν πυρι                                                                                |
| קנאתי                                         | ζηλους μου                                                                             |
| תאכל                                          | καταναλωθησεται                                                                        |
| כל                                            | πασα                                                                                   |
| הארץ                                          | η γη                                                                                   |
: Zephaniah chapter 3, verse 8 { .hover tbl-colwidths="[50,50]"}

### Verse 9

| Masoretic text                                                                   | Tov's retroversion                                                                                                                                | Septuagint                                                                                                             |
|:---------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------|
| כי                                                                               |                                                                                                                                                   | οτι                                                                                                                    |
| אז                                                                               |                                                                                                                                                   | τοτε                                                                                                                   |
| אהפך                                                                             |                                                                                                                                                   | μεταστρεψω                                                                                                             |
| אל                                                                               |                                                                                                                                                   | επι                                                                                                                    |
| עמים                                                                             |                                                                                                                                                   | λαους                                                                                                                  |
| שפה                                                                              |                                                                                                                                                   | γλωσσαν                                                                                                                |
| [ברורה]{.potential-difference}                                                   | [בדורה •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (interchange of R/D, etc.)]]{.potential-difference} | [εις γενεαν αυτης]{.potential-difference}                                                                              |
| לקרא                                                                             |                                                                                                                                                   | του επικαλεισθαι                                                                                                       |
| כלם                                                                              |                                                                                                                                                   | παντας                                                                                                                 |
| בשם                                                                              |                                                                                                                                                   | το ονομα                                                                                                               |
| יהוה                                                                             |                                                                                                                                                   | κυριου                                                                                                                 |
| לעבדו                                                                            |                                                                                                                                                   | του δουλευειν αυτω                                                                                                     |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                                                                                                                                   | υπο                                                                                                                    |
| שכם                                                                              |                                                                                                                                                   | •^[Preposition added in the LXX in accordance with the rules of the Greek language or translational habits.] υπο ζυγον |
| אחד                                                                              |                                                                                                                                                   | ενα                                                                                                                    |
: Zephaniah chapter 3, verse 9 { .hover tbl-colwidths="[35,30,35]"}

### Verse 10

| Masoretic text                   | Septuagint                                                                             |
|:---------------------------------|:---------------------------------------------------------------------------------------|
| מעבר                             | εκ περατων                                                                             |
| לנהרי                            | ποταμων                                                                                |
| כוש                              | αιθιοπιας                                                                              |
| [עתרי]{.potential-difference}    | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [בת פוצי]{.potential-difference} | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| יובלון                           | οισουσιν                                                                               |
| מנחתי                            | θυσιας μοι                                                                             |
: Zephaniah chapter 3, verse 10 { .hover tbl-colwidths="[50,50]"}

### Verse 11

| Masoretic text                                                                           | Septuagint                                                                       |
|:-----------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------|
| ביום                                                                                     | εν τη ημερα                                                                      |
| ההוא                                                                                     | εκεινη                                                                           |
| לא                                                                                       | ου μη                                                                            |
| תבושי                                                                                    | καταισχυνθης                                                                     |
| מכל                                                                                      | εκ παντων                                                                        |
| עלילתיך                                                                                  | των επιτηδευματων σου                                                            |
| אשר                                                                                      | ων                                                                               |
| פשעת                                                                                     | ησεβησας                                                                         |
| בי                                                                                       | εις εμε                                                                          |
| כי                                                                                       | οτι                                                                              |
| אז                                                                                       | τοτε                                                                             |
| אסיר                                                                                     | περιελω                                                                          |
| מקרבך                                                                                    | απο σου                                                                          |
| עליזי                                                                                    | τα φαυλισματα                                                                    |
| גאותך                                                                                    | της υβρεως σου                                                                   |
| ולא •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] עוד | και ουκετι μη                                                                    |
| תוספי                                                                                    | προσθης                                                                          |
| לגבהה                                                                                    | του μεγαλαυχησαι                                                                 |
| עוד                                                                                      | •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |
| בהר                                                                                      | επι το ορος                                                                      |
| קדשי                                                                                     | το αγιον μου                                                                     |
: Zephaniah chapter 3, verse 11 { .hover tbl-colwidths="[50,50]"}

### Verse 12

| Masoretic text   | Septuagint         |
|:-----------------|:-------------------|
| והשארתי          | και υπολειψομαι    |
| בקרבך            | εν σοι             |
| עם               | λαον               |
| עני              | πραυν              |
| ודל              | και ταπεινον       |
| וחסו             | και ευλαβηθησονται |
| בשם              | απο του ονοματος   |
| יהוה             | κυριου             |
: Zephaniah chapter 3, verse 12 { .hover tbl-colwidths="[50,50]"}

### Verse 13

| Masoretic text                                                               | Septuagint                      |
|:-----------------------------------------------------------------------------|:--------------------------------|
| שארית                                                                        | οι καταλοιποι                   |
| ישראל                                                                        | του ισραηλ                      |
| לא                                                                           | και ου                          |
| יעשו                                                                         | ποιησουσιν                      |
| עולה                                                                         | αδικιαν                         |
| ולא                                                                          | και ου                          |
| ידברו                                                                        | λαλησουσιν                      |
| כזב                                                                          | ματαια                          |
| ולא                                                                          | και ου μη                       |
| ימצא                                                                         | ευρεθη                          |
| בפיהם                                                                        | εν τω στοματι αυτων             |
| לשון                                                                         | γλωσσα                          |
| תרמית                                                                        | δολια                           |
| כי                                                                           | διοτι                           |
| המה                                                                          | αυτοι                           |
| ירעו                                                                         | νεμησονται                      |
| ורבצו                                                                        | και κοιτασθησονται              |
| ואין                                                                         | και ουκ εσται                   |
| מחריד                                                                        | ο εκφοβων                       |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference} | [αυτους]{.potential-difference} |
: Zephaniah chapter 3, verse 13 { .hover tbl-colwidths="[50,50]"}

### Verse 14

| Masoretic text                                                                    | Septuagint                       |
|:----------------------------------------------------------------------------------|:---------------------------------|
| רני                                                                               | χαιρε                            |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}      | [σφοδρα]{.potential-difference}  |
| בת                                                                                | θυγατερ                          |
| ציון                                                                              | σιων                             |
| הריעו                                                                             | κηρυσσε                          |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;בת]{.potential-difference} | [θυγατερ]{.potential-difference} |
| ישראל •^[Introducing reconstructed proper noun.] ירושלם                           | ιερουσαλημ                       |
| שמחי                                                                              | ευφραινου                        |
| ועלזי                                                                             | και κατατερπου                   |
| בכל                                                                               | εξ ολης                          |
| לב                                                                                | της καρδιας σου                  |
| בת                                                                                | θυγατερ                          |
| ירושלם                                                                            | ιερουσαλημ                       |
: Zephaniah chapter 3, verse 14 { .hover tbl-colwidths="[50,50]"}

### Verse 15

| Masoretic text                                                                          | Tov's retroversion           | Septuagint                             |
|:----------------------------------------------------------------------------------------|:-----------------------------|:---------------------------------------|
| הסיר                                                                                    |                              | περιειλεν                              |
| יהוה                                                                                    |                              | κυριος                                 |
| משפטיך                                                                                  |                              | τα αδικηματα σου                       |
| [פנה]{.potential-difference}                                                            | [פדה]{.potential-difference} | [λελυτρωται σε]{.potential-difference} |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}            | [מיד]{.potential-difference} | [εκ χειρος]{.potential-difference}     |
| איבך                                                                                    |                              | εχθρων σου                             |
| מלך                                                                                     |                              | βασιλευς                               |
| ישראל                                                                                   |                              | ισραηλ                                 |
| יהוה                                                                                    |                              | κυριος                                 |
| בקרבך                                                                                   |                              | εν μεσω σου                            |
| לא                                                                                      |                              | ουκ                                    |
| תיראי                                                                                   |                              | οψη                                    |
| רע                                                                                      |                              | κακα                                   |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] לא עוד |                              | ουκετι                                 |
: Zephaniah chapter 3, verse 15 { .hover tbl-colwidths="[35,30,35]"}

### Verse 16

| Masoretic text                                                                                  | Septuagint                      |
|:------------------------------------------------------------------------------------------------|:--------------------------------|
| ביום                                                                                            | εν τω καιρω                     |
| ההוא                                                                                            | εκεινω                          |
| יאמר •^[Difference in vocalization (reading).] •^[Change from passive to active form in verbs.] | ερει                            |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                    | [κυριος]{.potential-difference} |
| לירושלם                                                                                         | τη ιερουσαλημ                   |
| אל תיראי                                                                                        | θαρσει                          |
| ציון                                                                                            | σιων                            |
| אל                                                                                              | μη                              |
| ירפו                                                                                            | παρεισθωσαν                     |
| ידיך                                                                                            | αι χειρες σου                   |
: Zephaniah chapter 3, verse 16 { .hover tbl-colwidths="[50,50]"}

### Verse 17

| Masoretic text                                                                                                                                          | Tov's retroversion                                                        | Septuagint                      |
|:--------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------|:--------------------------------|
| יהוה                                                                                                                                                    |                                                                           | κυριος                          |
| אלהיך                                                                                                                                                   |                                                                           | ο θεος σου                      |
| בקרבך                                                                                                                                                   |                                                                           | εν σοι                          |
| גבור                                                                                                                                                    |                                                                           | δυνατος                         |
| יושיע                                                                                                                                                   |                                                                           | σωσει                           |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                                            |                                                                           | [σε]{.potential-difference}     |
| [ישיש]{.potential-difference}                                                                                                                           | [•^[Questionable notation, equivalent, etc.] ישים]{.potential-difference} | [επαξει]{.potential-difference} |
| עליך                                                                                                                                                    |                                                                           | επι σε                          |
| בשמחה                                                                                                                                                   |                                                                           | ευφροσυνην                      |
| יחריש •^[Etymological exegesis.] חדש •^[Interchange of consonants between MT and the presumed Hebrew parent text of the LXX (interchange of R/D, etc.)] |                                                                           | και καινιει                     |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                                            |                                                                           | [σε]{.potential-difference}     |
| באהבתו                                                                                                                                                  |                                                                           | εν τη αγαπησει αυτου            |
| יגיל                                                                                                                                                    |                                                                           | και ευφρανθησεται               |
| עליך                                                                                                                                                    |                                                                           | επι σε                          |
| ברנה                                                                                                                                                    |                                                                           | εν τερψει                       |
: Zephaniah chapter 3, verse 17 { .hover tbl-colwidths="[35,30,35]"}

### Verse 18

| Masoretic text                                                                   | Tov's retroversion               | Septuagint                                                                             |
|:---------------------------------------------------------------------------------|:---------------------------------|:---------------------------------------------------------------------------------------|
| נוגי ממועד                                                                       |                                  | ως εν ημερα εορτης [17]                                                                |
| אספתי                                                                            |                                  | και συναξω                                                                             |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                                  | τους συντετριμμενους                                                                   |
| [ממך]{.potential-difference}                                                     |                                  | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference} |
| [היו]{.potential-difference}                                                     | [הוי .yw]{.potential-difference} | [ουαι]{.potential-difference}                                                          |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}     |                                  | [τις]{.potential-difference}                                                           |
| משאת                                                                             |                                  | ελαβεν                                                                                 |
| עליה                                                                             |                                  | επ' αυτην                                                                              |
| חרפה                                                                             |                                  | ονειδισμον                                                                             |
: Zephaniah chapter 3, verse 18 { .hover tbl-colwidths="[35,30,35]"}

### Verse 19

| Masoretic text                                                                                                                                           | Tov's retroversion             | Septuagint                                                                                                                                                                                                                                                       |
|:---------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| הנני                                                                                                                                                     |                                | ιδου εγω                                                                                                                                                                                                                                                         |
| עשה                                                                                                                                                      |                                | ποιω                                                                                                                                                                                                                                                             |
| [•^[Element 'added' in the Greek (plus in the LXX).]]{.potential-difference}                                                                             |                                | [εν σοι]{.potential-difference}                                                                                                                                                                                                                                  |
| [את כל]{.potential-difference}                                                                                                                           |                                | [•^[Hebrew counterpart lacking in the LXX (minus in the LXX).]]{.potential-difference}                                                                                                                                                                           |
| [מעניך]{.potential-difference}                                                                                                                           | [למענך]{.potential-difference} | [ενεκεν σου]{.potential-difference}                                                                                                                                                                                                                              |
| בעת                                                                                                                                                      |                                | εν τω καιρω                                                                                                                                                                                                                                                      |
| ההיא                                                                                                                                                     |                                | εκεινω                                                                                                                                                                                                                                                           |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;נאם <mi4.6>]{.potential-difference}                                                               |                                | [λεγει]{.potential-difference}                                                                                                                                                                                                                                   |
| [•^[Element 'added' in the Greek (plus in the LXX).] =;יהוה <mi4.6>]{.potential-difference}                                                              |                                | [κυριος]{.potential-difference}                                                                                                                                                                                                                                  |
| והושעתי                                                                                                                                                  |                                | και σωσω                                                                                                                                                                                                                                                         |
| את הצלעה <mi4.6>                                                                                                                                         |                                | την εκπεπιεσμενην •^[Reference to doublet (occurring between the two elements of the doublet.] {...τους •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.] |
| •^[Long line continuing in next one, placed both at the end of the line running over and at the beginning of the following line in the opposite column.] |                                | συντετριμμενουσ} [18]                                                                                                                                                                                                                                            |
| והנדחה                                                                                                                                                   |                                | και την απωσμενην                                                                                                                                                                                                                                                |
| אקבץ                                                                                                                                                     |                                | εισδεξομαι                                                                                                                                                                                                                                                       |
| ושמתים                                                                                                                                                   |                                | και θησομαι αυτους                                                                                                                                                                                                                                               |
| לתהלה                                                                                                                                                    |                                | εις καυχημα                                                                                                                                                                                                                                                      |
| ולשם                                                                                                                                                     |                                | και ονομαστους                                                                                                                                                                                                                                                   |
| בכל                                                                                                                                                      |                                | εν παση                                                                                                                                                                                                                                                          |
| הארץ                                                                                                                                                     |                                | τη γη                                                                                                                                                                                                                                                            |
| בשתם                                                                                                                                                     |                                | και καταισχυνθησονται [20]                                                                                                                                                                                                                                       |
: Zephaniah chapter 3, verse 19 { .hover tbl-colwidths="[35,30,35]"}

### Verse 20

| Masoretic text                                                                   | Tov's retroversion            | Septuagint                                                                                                                  |
|:---------------------------------------------------------------------------------|:------------------------------|:----------------------------------------------------------------------------------------------------------------------------|
| בעת                                                                              |                               | εν τω καιρω                                                                                                                 |
| ההיא                                                                             |                               | εκεινω                                                                                                                      |
| [אביא]{.potential-difference}                                                    | [אטיב]{.potential-difference} | [οταν καλως •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] ποιησω]{.potential-difference} |
| אתכם                                                                             |                               | υμιν                                                                                                                        |
| •^[Equivalent reflected elsewhere in the text, disregarded by indexing program.] |                               | ποιησω                                                                                                                      |
| ובעת                                                                             |                               | και εν τω καιρω                                                                                                             |
| קבצי                                                                             |                               | οταν εισδεξωμαι                                                                                                             |
| אתכם                                                                             |                               | υμας                                                                                                                        |
| כי                                                                               |                               | διοτι                                                                                                                       |
| אתן                                                                              |                               | δωσω                                                                                                                        |
| אתכם                                                                             |                               | υμας                                                                                                                        |
| לשם                                                                              |                               | ονομαστους                                                                                                                  |
| ולתהלה                                                                           |                               | και εις καυχημα                                                                                                             |
| בכל                                                                              |                               | εν πασιν                                                                                                                    |
| עמי                                                                              |                               | τοις λαοις                                                                                                                  |
| הארץ                                                                             |                               | της γης                                                                                                                     |
| בשובי                                                                            |                               | εν τω επιστρεφειν με                                                                                                        |
| את שבותיכם                                                                       |                               | την αιχμαλωσιαν υμων                                                                                                        |
| לעיניכם                                                                          |                               | ενωπιον υμων                                                                                                                |
| אמר                                                                              |                               | λεγει                                                                                                                       |
| יהוה                                                                             |                               | κυριος                                                                                                                      |
: Zephaniah chapter 3, verse 20 { .hover tbl-colwidths="[35,30,35]"}

